objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AcctSeedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Address__c</fullName>
        <label>Site Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_City__c</fullName>
        <description>manually updated and/or auto-populated from EPC site on O&amp;M contracts</description>
        <inlineHelpText>manually updated and/or auto-populated from EPC site on O&amp;M contracts</inlineHelpText>
        <label>Site City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Customer__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Account listed on the Sales Order &quot;Customer&quot; field</inlineHelpText>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <description>For Service Construction Requisitions</description>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contacts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hidden field used by CaseClosureFormController. Is used to select Contacts to send the case closure form to.</description>
        <label>Contacts</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (ccfContacts)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>attachmentIdSelected__c</fullName>
        <description>Hidden field to store Attachment record IDs of those attachments that have been selected so far to be included with the Case Closure Form. Enables the page to retain the selections through the preview of the Case Closure Form.</description>
        <label>attachmentIdSelected</label>
        <length>512</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>otherEmailSelected__c</fullName>
        <description>Hidden field. Other email addresses selected so far as recipients of the case closure form.</description>
        <label>otherEmailSelected</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>userIdEmailSelected__c</fullName>
        <description>Hidden field to store User record IDs of those users that have been selected as email recipients of the case closure form so far.</description>
        <label>userIdEmailSelected</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <businessProcess>Project</businessProcess>
        <description>One-off projects such as due diligence visits, retrofits/rebuilds, DAS replacements</description>
        <label>Project</label>
    </recordTypes>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Service Case</businessProcess>
        <description>used to log all reactive service cases and is default case type for email to case settings</description>
        <label>Reactive</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Component__c.object
<CustomObject>
    <description>part to maintenance case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Component</label>
    <nameField>
        <displayFormat>CMPT-{0}</displayFormat>
        <label>Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>should define the role this contact is playing in their relationship with Borrego.</inlineHelpText>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service Contact</fullName>
                </value>
                <value>
                    <fullName>Host Contact</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Sales Decision-Maker</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Not Yet Identified</fullName>
                </value>
                <value>
                    <fullName>Portal User</fullName>
                </value>
                <value>
                    <fullName>Primary O&amp;M Contact</fullName>
                </value>
                <value>
                    <fullName>Technical Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Technical Contact</fullName>
                </value>
                <value>
                    <fullName>O&amp;M Billing Contact</fullName>
                </value>
                <value>
                    <fullName>O&amp;M Service Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>O&amp;M Performance Report Contact</fullName>
                </value>
                <value>
                    <fullName>O&amp;M Case Closure Report Contact</fullName>
                </value>
                <value>
                    <fullName>Amex Contact</fullName>
                </value>
                <value>
                    <fullName>Waiver Contact</fullName>
                </value>
                <value>
                    <fullName>O&amp;M Purchasing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Brings over notes from the Lead</description>
        <inlineHelpText>Shows any notes from the unconverted Lead. Add new notes about the contact in here.</inlineHelpText>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Address__c</fullName>
        <description>previous:  (Account.ShippingStreet &amp; BR() &amp; Account.ShippingCity &amp; &quot;,&quot; &amp; Account.ShippingState &amp; &quot;,&quot; &amp; Account.ShippingPostalCode &amp; BR() &amp; Account.ShippingCountry )</description>
        <formula>( ASProject__r.Site_Address__c  &amp; BR() &amp; ASProject__r.Site_City__c  &amp; &quot;,&quot; &amp;  ASProject__r.Site_State__c &amp; &quot;,&quot; &amp;  ASProject__r.Site_Zip__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The address of the site. This is pulled through from the related project fields .</inlineHelpText>
        <label>Site Address</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Site_Address__c</fullName>
        <label>Site Address</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related account for the Service Contract.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The case on which the service visit was scheduled.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contacts__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contacts</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>Used for any notes regarding the service visit that you want to appear on the work order form</inlineHelpText>
        <label>Service Visit Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PO #</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Does not match any Construction Requisition related to this Service Visit.</errorMessage>
            <filterItems>
                <field>AcctSeedERP__Sales_Order_Line__c.Service_Visit__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <infoMessage>Enter the name of a Construction Requisition that is related to this Service Visit.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeedERP__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Private_Notes__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box to hide the Notes field from Customer Portal users.</inlineHelpText>
        <label>Private Notes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <inlineHelpText>The date on which the service visit is scheduled to occur/start.</inlineHelpText>
        <label>Visit Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Work_Order_Date_Sent__c</fullName>
        <label>Work Order Date Sent</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Work_Order_Sent_To__c</fullName>
        <label>Work Order Sent To</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>attachmentIdSelected__c</fullName>
        <description>Hidden field to store Attachment record IDs of those attachments that have been selected so far to be included with the Work Order Form. Enables the page to retain the selections through the preview of the Work Order Form.</description>
        <label>attachmentIdSelected</label>
        <length>512</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>otherEmailSelected__c</fullName>
        <description>Hidden field. Other email addresses selected so far as recipients of the work order form. This is a temporary holding field for these email addresses so that when a user returns to the email selection page after previewing the work order form PDF, the email addresses selected so far will reappear.</description>
        <label>otherEmailSelected</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>userIdEmailSelected__c</fullName>
        <description>Hidden field to store User record IDs of those users that have been selected as email recipients of the work order form so far.</description>
        <label>userIdEmailSelected</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>used for all Non-Reactive, Non-PM Service Visits</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WorkOrderFormController.cls
public class WorkOrderFormController {
    
    // Methods to create a Work Order Form pdf from a Service Visit record and send it as an email attachment.
    
    ApexPages.StandardController stdController;
    public String email_subject { get; set; }
    public String email_body { get; set; }
    public SV__c serviceVisit { get; set; }
    public Account svAccount { get; set; }
    public Contact svContact { get; set; }
    public Case svCase { get; set; }
    public AcctSeed__Project__c svProject {get; set;}
    public Boolean showPreview { get; set; }
    public Boolean noEmailRecipients { get; set; }
    public List<SelectOption> allUsers { get; set; }
    public String userEmailAddresses {get; set;}
    public String contactEmailAddresses {get; set;}
    List<User> userList = new List<User>();
    Map<Id, User> userMap = new Map<Id, User>();
    List<Attachment> attList = new List<Attachment>();
    String[] selectedToUsers = new String[]{};
    List<Id> attSelected;
    Boolean workorderTest = false;
    
    private final SV__c sVisit;

    // Create a constructor that populates the Service Visit, Account, Contact, Case, and Attachments
    public WorkOrderFormController(ApexPages.StandardController stdController) {
        this.sVisit = (SV__c)stdController.getRecord(); 
        
        showPreview = false;
        noEmailRecipients = false;
        serviceVisit = new SV__c();
        serviceVisit = [select Id, Name, CreatedBy.Email, Account__c, Visit_Date__c, Notes__c, Case__c, Contacts__c, 
                Work_Order_Date_Sent__c, Work_Order_Sent_To__c, attachmentIdSelected__c, userIdEmailSelected__c, 
                otherEmailSelected__c, PO__c, Private_Notes__c, Project__c 
                from SV__c where Id =: this.sVisit.Id];

        serviceVisit.Contacts__c = null;
        userEmailAddresses = serviceVisit.CreatedBy.Email;
        contactEmailAddresses = null;
        svAccount = new Account();
        List<Contact> conList = new List<Contact>();
        svCase = new Case();
        svContact = new Contact();
        if (serviceVisit.Account__c != null) {
            svAccount = [select Id, Name, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode 
                        from Account where Id =: serviceVisit.Account__c];
            conList = [select Id, Name, AccountId, Contact_Type__c, Phone, Email, MobilePhone 
                        from Contact where AccountId =: serviceVisit.Account__c];
            for (Contact c :conList) {
                if (c.Contact_Type__c != null && c.Contact_Type__c.contains('Service Contact')) {
                    svContact = c;
                }
            }
        }
        
        if (serviceVisit.Case__c != null) {
            svCase = [select Id, CaseNumber, Subject from Case where Id =: serviceVisit.Case__c];
        }
        
        svProject = new AcctSeed__Project__c();
        if (serviceVisit.Project__c != null) {
            svProject = [select Id, Name, Site_Address__c, Site_City__c, Site_State__c, Site_Zip__c 
                    from AcctSeed__Project__c where Id = :serviceVisit.Project__c];
        }
        
        email_subject = 'Borrego Solar Systems Case #: ' + svCase.CaseNumber + ' ' + svCase.Subject;
        email_body = 'Work order for Service Visit #: ' + serviceVisit.Name + ' at Account: ' + svAccount.Name + 
                ' along with other relevant documents (if any) are attached.' +
                '\n\nRegards,\nBorrego Solar Systems, Inc.\n';

        // Build the list of Users that can be selected as email recipients
        allUsers = new List<SelectOption>();
        userList = [select Id, Name, Email from User where isActive=true and UserType='Standard' order by name]; 
        for (User u : userList) {
            allUsers.add(new SelectOption(u.Id, u.Name));
            userMap.put(u.Id, u);
        }
        
        // Get the list of available Attachments that can be selected to be included
        attList = [select Id, Name, Description from Attachment where ParentId = :serviceVisit.Id and IsPrivate = false order by Name asc];
    }
    
    // Set the list of users and other email addresses already selected if there are any.  This would happen 
    // if the user has already selected email addresses and then previewed the work order PDF and then 
    // returned to the email selection page.  Do the same thing for selected Attachments.
    public void initEmailAddresses() {

        contactEmailAddresses = serviceVisit.otherEmailSelected__c;
        if (serviceVisit.userIdEmailSelected__c != null) {
            String userIds = serviceVisit.userIdEmailSelected__c;
            List<String> uIds = new List<String>();
            while(userIds != null && userIds.length() > 0) {
                if (userIds.contains(';')) {
                    uIds.add(userIds.substringBefore(';'));
                    userIds = userIds.removeStart(userIds.substringBefore(';') + ';');
                } else {
                    uIds.add(userIds);
                    userIds = userIds.removeStart(userIds);
                }
            }
            setselectedToUsers(uIds);
            for (String s : uIds) {
                if (userMap.containsKey(s)) {
                    userEmailAddresses += ';' + userMap.get(s).Email;
                }
            }
        }
        
        // Initialize the list of Attachments selected so far
        attSelected = new List<Id>();
        if (serviceVisit.attachmentIdSelected__c != null) {
            String attIds = serviceVisit.attachmentIdSelected__c;
            while(attIds != null && attIds.length() > 0) {
                if (attIds.contains(';')) {
                    attSelected.add(attIds.substringBefore(';'));
                    attIds = attIds.removeStart(attIds.substringBefore(';') + ';');
                } else {
                    attSelected.add(attIds);
                    attIds = attIds.removeStart(attIds);
                }
            }
        }
        
        serviceVisit.userIdEmailSelected__c = null;
        serviceVisit.otherEmailSelected__c = null;
        serviceVisit.attachmentIdSelected__c = null;
        update serviceVisit;
    }
    
    // Selected Users for Email "To"
    public String[] getselectedToUsers() {
        return selectedToUsers;
    }
            
    public void setselectedToUsers(String[] users) {
        selectedToUsers = users;
    }
    
    public List<String> getemailTo() {
        List<String> toList = new List<String>();
        Contact toContact = new Contact();
        
        noEmailRecipients = false;
        //userEmailAddresses = null;
        userEmailAddresses = serviceVisit.CreatedBy.Email;  // Always include createdby email address of Service Visit record
        serviceVisit.userIdEmailSelected__c = '';
        for (Integer i=0; i<selectedToUsers.size(); i++) {
            if (i+1 == selectedToUsers.size()) {
                serviceVisit.userIdEmailSelected__c += selectedToUsers[i];
            } else {
                serviceVisit.userIdEmailSelected__c += selectedToUsers[i] + ';';
            }
            toList.add(userMap.get(selectedToUsers[i]).Email);
            if (userEmailAddresses == null) {
                userEmailAddresses = userMap.get(selectedToUsers[i]).Email;
            } else {
                userEmailAddresses += ';' + userMap.get(selectedToUsers[i]).Email;
            }
        }
        
        if (serviceVisit.Contacts__c != null) {
            toContact = [select Id, Name, Email from Contact where Id =: serviceVisit.Contacts__c];
            toList.add(toContact.Email);
            if (contactEmailAddresses == null || contactEmailAddresses == '') {
                contactEmailAddresses = toContact.Email;
            } else {
                contactEmailAddresses += ';' + toContact.Email;
            }
            serviceVisit.Contacts__c = null;
        }
        
        return toList;
    }
    
    public PageReference selectEmailRecipients() {
        List<String> toList = new List<String>();
        
        toList = getemailTo();
        return null;
    }
    
    // Reformat the selected Construction Requisition (Sales Order Line) and return it
    public String getsolString () {
        String sol = '';
        AcctSeedERP__Sales_Order_Line__c conreq = new AcctSeedERP__Sales_Order_Line__c();
        if (serviceVisit.PO__c != null) {
            conreq = [select Id, Name from AcctSeedERP__Sales_Order_Line__c where Id =: serviceVisit.PO__c];
            sol = 'SOL' + conreq.Name.removeStart('SalesOrderLine-0000');
        }
        return sol;
    }
    
    public workOrderWrapper getWorkOrderInfo() {
        workOrderWrapper woWrapper = new workOrderWrapper(serviceVisit, svAccount, svContact, svCase, svProject);
        return woWrapper;
    }
    
    public class workOrderWrapper {
        public SV__c woSV {get; set;}
        public String woSVNotes {get; set;}
        public Account woAcc {get; set;}
        public Contact woCon {get; set;}
        public Case woCase {get; set;}
        public AcctSeed__Project__c woProj {get; set;}
        public workOrderWrapper(SV__c sv, Account acc, Contact cn, Case cs, AcctSeed__Project__c pr) {
            woSV = sv;
            woAcc = acc;
            woCon = cn;
            woCase = cs;
            woProj = pr;
            woSVNotes = Utilities.limitWordLength(sv.Notes__c, 50);
        }
    }
    
    // Preview the work order pdf
    public PageReference previewWorkOrder() {
        showPreview = true;
        serviceVisit.otherEmailSelected__c = contactEmailAddresses;
        update serviceVisit;  // save information so that it will reappear upon return from preview
        return null;
    }
    
    // Get the list of available attachments to choose from
    List<attSelectWrapper> availableAtt = new List<attSelectWrapper>();
    List<attSelectWrapper> selectedAtt = new List<attSelectWrapper>();
    
    public List<attSelectWrapper> getAttachments() {
        
        // If the list of attachments to choose from is empty, create it
        if (availableAtt.isEmpty()) {
            for (Attachment a :attList) {
                availableAtt.add(new attSelectWrapper(a));
            }
            
            // Initialize with current selections
            for (attSelectWrapper attSW :availableAtt) {
                for (Id attId :attSelected) {
                    if (attSW.att.Id == attId) {
                        attSW.selected = true;
                    }
                }
            }
            PageReference pr = getSelected();
        }
        return availableAtt;
    }
    
    // Record current user selection of attachments
    public PageReference getSelected () {
        
        serviceVisit.attachmentIdSelected__c = '';
        selectedAtt.clear();
        for (attSelectWrapper attsw :availableAtt) {
            if (attsw.selected) {
                selectedAtt.add(attsw);
            }
        }
        for (Integer i=0; i<selectedAtt.size(); i++) {
            if (i+1 == selectedAtt.size()) {
                serviceVisit.attachmentIdSelected__c += selectedAtt[i].att.Id;
            } else {
                serviceVisit.attachmentIdSelected__c += selectedAtt[i].att.Id + ';';
            }
        }
        return null;
    }
/*    
    // Return list of attachment selected so far - used on the page for debug purposes
    public List<attSelectWrapper> getselectedATTWs() {
        if (selectedAtt.isEmpty()) {
            return null;
        } else {
            return selectedAtt;
        }
    }
*/    
    // Send the Work Order From PDF as an attachment to an email.
    public PageReference sendWorkOrder() {
        PageReference returnPage;
        List<String> toAddresses = new List<String>();
        List<Id> attIds = new List<Id>();
        List<Attachment> attToInclude = new List<Attachment>();
        
        // First save the selected Construction Requisition
        update serviceVisit;
        
        // Create the list of email recipients
        serviceVisit.Work_Order_Sent_To__c = '';
        if (userEmailAddresses != null && userEmailAddresses != '') {
            toAddresses.addAll(userEmailAddresses.split(';', 0));
            serviceVisit.Work_Order_Sent_To__c += userEmailAddresses;
        }
        if (contactEmailAddresses != null && contactEmailAddresses != '') {
            toAddresses.addAll(contactEmailAddresses.split(';', 0));
            serviceVisit.Work_Order_Sent_To__c += '; ' + contactEmailAddresses;
        }
        
        // Can only send email if we have some email recipients
        if (!toAddresses.isEmpty()) {
        
            // Define the email
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 

            // Reference the attachment page and pass in the Service Visit record Id
            if (!workorderTest) {
                PageReference pdf =  Page.WorkOrderFormPDF;
                pdf.getParameters().put('id', (String)serviceVisit.Id); 
                pdf.setRedirect(true);
            
                // Take the PDF content
                Blob b = pdf.getContent();
                
                // Create the Work Order Form email attachment
                Messaging.EmailFileAttachment[] efaList = new Messaging.EmailFileAttachment[selectedAtt.size()+1];
                Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
                efa.setFileName('WorkOrderForm.pdf');
                efa.setBody(b);
                efaList[0] = efa;
                
                // Include the user selected attachments if any
                if (!selectedAtt.isEmpty()) {
                    for (attSelectWrapper attSW :selectedAtt) {
                        attIds.add(attSW.att.Id);
                    }
                    attToInclude = [select Id, Name, Body, Description from Attachment where Id in :attIds];
                
                    for (Integer i=0; i<attToInclude.size(); i++) {
                        efa = new Messaging.EmailFileAttachment();
                        efa.setFileName(attToInclude[i].Name);
                        efa.setBody(attToInclude[i].Body);
                        efaList[i+1] = efa;
                    }
                }
                email.setFileAttachments(efaList);
            }
            
            // Sets the paramaters of the email
            email.setSubject(email_subject);
            email.setToAddresses(toAddresses);
            email.setPlainTextBody(email_body);
            
            // Sends the email
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
            
            // Record the date the email was sent and email addresses it was sent to (set above)
            serviceVisit.Work_Order_Date_Sent__c = system.now();
            serviceVisit.otherEmailSelected__c = null;
            serviceVisit.userIdEmailSelected__c = null;
            serviceVisit.attachmentIdSelected__c = null;
            serviceVisit.PO__c = null;
            update serviceVisit;
            
            returnPage = new PageReference('/' + serviceVisit.Id);
        } else {
            noEmailRecipients = true;
            returnPage = null;
        }
        return returnPage;
    }
    
    // Cancel the work order
    public PageReference cancelWorkOrder() {
        if (serviceVisit.otherEmailSelected__c != null || serviceVisit.userIdEmailSelected__c != null || 
                    serviceVisit.attachmentIdSelected__c != null || serviceVisit.PO__c != null) {
            serviceVisit.otherEmailSelected__c = null;
            serviceVisit.userIdEmailSelected__c = null;
            serviceVisit.attachmentIdSelected__c = null;
            serviceVisit.PO__c = null;
            update serviceVisit;
        }
        PageReference returnPage = new PageReference('/' + serviceVisit.Id);
        return returnPage;
    }
    
    public static testMethod void testWorkOrderForm() {
    
      ASeedAccountingSettingsSetupTest.testDataSetup(); 
    

        PageReference pr;
        
        // Create all the test data
        Account testAccount = new Account(
            Name = 'Test test',
            Branch__c = 'San Diego',
            ShippingStreet = '123 Main Street',
            ShippingCity = 'San Francisco',
            ShippingState = 'California',
            ShippingPostalCode = '94107');
        insert testAccount;
        Contact testContact = new Contact(
            LastName = 'testContact',
            Title = 'CEO',
            AccountId = testAccount.Id,
            Phone = '123-456-7890',
            Email = 'testContact@test.com.training',
            //Service_Contact__c = true,
            Contact_Type__c = 'Service Contact',
            MobilePhone = '456-789-0123');
        insert testContact;
        Case testCase = new Case(
            Subject = 'This is a test case for testing a work order form',
            Description = 'This is the description field',
            AccountId = testAccount.Id,
            ContactId = testContact.Id,
            Branch__c = 'San Diego',
            Origin = 'Web',
            Component__c = 'Inverter',
            Reason = 'System Down',
            Production_Effected__c = 'Yes',
            Days_Inverter_Down__c = 1,
            O_M_Issue_Tracking__c = 'Reactive');
        insert testCase;
        Opportunity testOpportunity = new Opportunity(
            Name = 'testOpportunity',
            AccountId = testAccount.Id,
            Description = 'This is the project description field',
            StageName = 'Prospecting',
            Financing__c = 'Cash',
            Project_Likelihood__c = '50%',
            CloseDate = system.today(),
            Service_Contract_Included__c = 'Yes');
        insert testOpportunity;
        AcctSeed__Project__c testProject = new AcctSeed__Project__c(
            Name = 'testProject',
            AcctSeed__Opportunity__c = testOpportunity.Id,
            Branch__c = 'San Diego',
            Site_Address__c = '123 Main Street',
            Site_City__c = 'San Francisco',
            Site_State__c = 'California',
            Site_Zip__c = '94107');
        insert testProject;
        Contract testContract = new Contract(
            AccountId = testAccount.Id,
            Contract_Amount__c = 10000,
            ContractTerm = 12,
            Service_Contract_Start_Date__c = system.today(),
            EndDate = system.today(),
            Description = 'This is the description field',
            ASProject__c = testProject.Id);
        insert testContract;
        SV__c testServiceVisit = new SV__c(
            Account__c = testAccount.Id,
            Visit_Date__c = system.today(),
            Notes__c = 'This is the notes field',
            Case__c = testCase.Id,
            Visit_Reason__c = 'Scheduled Site Inspection',
            Performed_By__c = 'Borrego',
            userIdEmailSelected__c = system.UserInfo.getUserId(),
            otherEmailSelected__c = 'testtest@test.com.training',
            Contract__c = testContract.Id);
        insert testServiceVisit;
        
        //Instantiate a new controller
        ApexPages.StandardController std = new ApexPages.StandardController(testServiceVisit);
        WorkOrderFormController ctl = new WorkOrderFormController(std);
        
        // Run the tests
        ctl.initEmailAddresses();
        ctl.workorderTest = true;
        ctl.serviceVisit.Contacts__c = testContact.Id;
        List<String> userEmail = new List<String>();
        userEmail.add(system.UserInfo.getUserId());
        ctl.setselectedToUsers(userEmail);
        List<String> selectedUsers = new List<String>();
        selectedUsers = ctl.getselectedToUsers();
        system.assertEquals(selectedUsers, userEmail);
        pr = ctl.selectEmailRecipients();
        SV__c sv = [select Id, Name, CreatedBy.Email from SV__c where Id =: testServiceVisit.Id];
        system.assertEquals(ctl.userEmailAddresses, sv.CreatedBy.Email + ';' + system.UserInfo.getUserEmail());
        system.assertEquals(ctl.contactEmailAddresses, 'testtest@test.com.training;testcontact@test.com.training');
        workOrderWrapper wow = ctl.getWorkOrderInfo();
        system.assertEquals(wow.woSV.Id, testServiceVisit.Id);
        pr = ctl.previewWorkOrder();
        system.assertEquals(pr, null);
        pr = ctl.cancelWorkOrder();
        system.assertNotEquals(pr, null);
        pr = ctl.sendWorkOrder();
        system.assertNotEquals(pr, null);
        ctl.getsolString();
        ctl.getSelected();
        ctl.getAttachments();
    }
}