objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <inlineHelpText>What sector is the customer classified under? 
**Only for Customer Accounts**</inlineHelpText>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Residential - Multi-Unit</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Small Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Recurring_Billing__c.object
<CustomObject>
    <description>Captures information related to recurring billings associated with customers. A recurring billing is a template for creating billings on a periodic basis.</description>
    <fields>
        <fullName>AcctSeed__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Customer, Customer and Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recurring Billings</relationshipLabel>
        <relationshipName>Recurring_Billings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Recurring Billing</label>
    <nameField>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Area_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to user record to identify Area Supervisor on a contract</description>
        <inlineHelpText>Area Supervisor on the contract</inlineHelpText>
        <label>Area Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Amount__c</fullName>
        <inlineHelpText>Total yearly amount of the service contract.</inlineHelpText>
        <label>Contract Amount (yearly)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Does_Contract_Auto_Renew__c</fullName>
        <description>indicate whether contract will auto-renew</description>
        <inlineHelpText>indicate whether contract will auto-renew</inlineHelpText>
        <label>Does Contract Auto Renew?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalator__c</fullName>
        <label>Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MinimumBillableTravelTime__c</fullName>
        <description>Minimum number of hours billable per service visit. If 0, all travel time is billable</description>
        <inlineHelpText>Minimum number of hours billable per service visit. If 0, all travel time is billable</inlineHelpText>
        <label>Minimum Billable Travel Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_M_Package__c</fullName>
        <label>O&amp;M Package</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Preventative</fullName>
                </value>
                <value>
                    <fullName>Comprehensive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regional_Manager_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to user record to identify Regional Manager on a contract</description>
        <inlineHelpText>Regional manager on the contract</inlineHelpText>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract_Start_Date__c</fullName>
        <inlineHelpText>The date that the service contract starts.</inlineHelpText>
        <label>Service Contract Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CreateBillingandBillingLineTestClass.cls
@isTest(seealldata=true)
public class CreateBillingandBillingLineTestClass 
{
    static testMethod Void createbilling() 
 {
          Account testrecord2 = new Account();
          testrecord2.Name='testaccount2';
          testrecord2.Branch__c='Mid-Atlantic';
          testrecord2.Phone='(609)-524-4500';
          testrecord2.Type='service';
          testrecord2.Industry='Electric Utilities';
          testrecord2.Job_Type__c='Private';
          testrecord2.Description='NY Community Solar - developer'; 
          insert testrecord2;
          
                user userid = [select id from user where isactive=true  and department ='o&m' and title like '%Manager%' limit 1];

          Contract testcontract= new Contract();
          testcontract.AccountId='0013000000LBRIs';
          testcontract.Description='test';
          testcontract.Contract_Status__c='Active';
          testcontract.Branch__c='New England';
          testcontract.O_M_Package__c='Reactive';
          testcontract.Does_Contract_Auto_Renew__c='Yes';
          testcontract.Service_Contract_Start_Date__c= Date.newinstance(2010, 11, 01);
          testcontract.ContractTerm=84;
          testcontract.EndDate= Date.newinstance(2018, 12, 13);
          testcontract.Contract_Amount__c=314.58; 
          testcontract.MinimumBillableTravelTime__c=0;
          testcontract.Status=' NullVoid';
          testcontract.Escalator__c=2;
          testcontract.Area_Supervisor__c =userid.id;
          testcontract.Regional_Manager_User__c = userid.id;
          insert testcontract;
          
           AcctSeed__Recurring_Billing__c testrecurringbilling= new AcctSeed__Recurring_Billing__c();
           testrecurringbilling.Name='Union ESD - Dartmouth Middle School - O&M';
           testrecurringbilling.AcctSeed__Customer__c='0013400001OT0Ox';
           testrecurringbilling.AcctSeed__Status__c='Active';
           testrecurringbilling.AcctSeed__Billing_Frequency__c='Anniversary in Advance';
           testrecurringbilling.AcctSeed__Next_Billing_Date__c=Date.newinstance(2020, 11, 30);
           testrecurringbilling.Service_Contract__c='80034000000VAYR';//'80034000002ELIf';
           insert testrecurringbilling;
           
           //string convertednextbillingdate = string.valueof(testrecurringbilling.AcctSeed__Next_Billing_Date__c);
           //system.debug('nextbillingdate'+  convertednextbillingdate);
           //String formattedDate = convertednextbillingdate.format();
            //system.debug('formattednextbillingdate'+  formattedDate );
            Datetime myDT = datetime.newInstance(testrecurringbilling.AcctSeed__Next_Billing_Date__c.year(), testrecurringbilling.AcctSeed__Next_Billing_Date__c.month(),testrecurringbilling.AcctSeed__Next_Billing_Date__c.day());
            system.debug('datetime'+  myDT);
           String myDate = myDT.format('MM/dd/YYYY');
           system.debug('formattednextbillingdate'+  myDate);
           
           Test.startTest();
           CreateBillingandBillingLine.createbilling(testrecurringbilling.AcctSeed__Customer__c,'a32340000025mFh',testrecurringbilling.Service_Contract__c,myDate);//'a3234000003tEuH'
           Test.stopTest();
          
        }
}