objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Proposal_Request__c.object
<CustomObject>
    <description>Proposal Request Tool for Sales Team</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>When is the due date on the proposal?</inlineHelpText>
        <label>Due Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposal Requests</relationshipLabel>
        <relationshipName>Proposal_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_State__c</fullName>
        <inlineHelpText>State the project is located- Sales Associate will be determined by this field</inlineHelpText>
        <label>Project State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFP_Location__c</fullName>
        <inlineHelpText>Where is the RFP? if website, please fill out Other RFP Location field</inlineHelpText>
        <label>RFP Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>Attached</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Box.com</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Associate_Responsible__c</fullName>
        <inlineHelpText>Select the Sales Operations Team Member who is responsible</inlineHelpText>
        <label>Sales Operations Team Member Responsible</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amanda Cain</fullName>
                </value>
                <value>
                    <fullName>Amy Stice</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Dea Bacchetti</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Proposal Request Submitted</fullName>
                </value>
                <value>
                    <fullName>Accepted by Proposal Manager</fullName>
                </value>
                <value>
                    <fullName>Slice n Dice Complete</fullName>
                </value>
                <value>
                    <fullName>First Draft in Progress</fullName>
                </value>
                <value>
                    <fullName>Draft Posted</fullName>
                </value>
                <value>
                    <fullName>Review Session Ended</fullName>
                </value>
                <value>
                    <fullName>Revision in Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Proposal Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Proposal Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Proposal_Tasks__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>Date the task is due</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Proposal_Request__r.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_Responsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Person responsible for the task</inlineHelpText>
        <label>Person Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Responsibility_Matrix</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal_Request__c</fullName>
        <inlineHelpText>The proposal request (RFP/RFQ) that the task is associated to</inlineHelpText>
        <label>Proposal Request</label>
        <referenceTo>Proposal_Request__c</referenceTo>
        <relationshipName>Responsibility_Matrix</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the Task</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Needed</fullName>
                    <default>true</default>
                    <label>Needed</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Proposal Task</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Proposal Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testProposalRequest.cls
/**
 * This class contains methods to test triggers and class files that are related to
 * the objects Proposal Request and Proposal Task.
 */
@isTest
private class testProposalRequest {

    static testMethod void testProposalTaskTrigger() {
    	
    	Account prAccount;
    	Opportunity prOpportunity;
    	Proposal_Request__c proposalRequest;
    	Proposal_Tasks__c proposalTask;
    	
    	// Create test data
    	prAccount = TestMethods.getAccount();
    	prOpportunity = TestMethods.getOpportunity();
    	proposalRequest = new Proposal_Request__c(
    		Opportunity__c = prOpportunity.Id,
    		Sales_Associate_Responsible__c = 'Other',
    		Project_State__c = 'California',
    		RFP_Location__c = 'Not Applicable',
    		Due_Date__c = system.now(),
    		Status__c = 'New'
    	);
    	insert proposalRequest;
    	
    	proposalTask = new Proposal_Tasks__c(
    		Proposal_Request__c = proposalRequest.Id,
    		Person_Responsible__c = UserInfo.getUserId()
    	);
    	insert proposalTask;
    	proposalRequest.Status__c = 'Draft Posted';
    	update proposalRequest;
    }
}