objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fixed_Cost__c</fullName>
        <label>Fixed Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <inlineHelpText>What sector is the customer classified under? 
**Only for Customer Accounts**</inlineHelpText>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Residential - Multi-Unit</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Small Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Fixed_Cost__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For indicating a Fixed-Cost Commission.
Please add the Amount manually in the &apos;Fixed Cost Amount&apos; field.</description>
        <inlineHelpText>For indicating a Fixed-Cost Commission.
Please add the Amount manually in the &apos;Fixed Cost Amount&apos; field.</inlineHelpText>
        <label>Fixed Cost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>Opportunity the commission is related to</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <inlineHelpText>Percent of Commission- required at creation</inlineHelpText>
        <label>Percent</label>
        <precision>9</precision>
        <scale>7</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User who is receiving the commission- required at creation</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <recordTypes>
        <fullName>Affiliates</fullName>
        <active>true</active>
        <label>Affiliates</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <inlineHelpText>Branch of the user.</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>North Carolina</fullName>
                </value>
                <value>
                    <fullName>Oregon</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>South Carolina</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Fixed_Cost__c.object
<CustomObject>
    <label>Fixed Cost</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Fixed Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fixed Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>State used for reporting and allocation</description>
        <inlineHelpText>State used for reporting and allocation</inlineHelpText>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Branch value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Opportunities (Branch)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Percent_Cap__c</fullName>
        <defaultValue>0.03</defaultValue>
        <label>Commission Percent Cap</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Government - Small</fullName>
                </value>
                <value>
                    <fullName>Utility Scale</fullName>
                </value>
                <value>
                    <fullName>ES Ground</fullName>
                </value>
                <value>
                    <fullName>Non ES Ground</fullName>
                </value>
                <value>
                    <fullName>ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Non ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>DG Solar</fullName>
                </value>
                <value>
                    <fullName>DG Wind</fullName>
                </value>
                <value>
                    <fullName>DG SAS</fullName>
                </value>
                <value>
                    <fullName>LSR PV</fullName>
                </value>
                <value>
                    <fullName>Bulk ES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <defaultValue>0.00</defaultValue>
        <inlineHelpText>Set to 1 if Sales Department. If not a Sales user, should be 0.</inlineHelpText>
        <label>Default Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/commission.cls
public class commission {
    /*Private String FixedCostValidationMessage ='When Fixed Cost is unchecked, Percent should not be blank  or 0'; 
        ApexPages.StandardController stdController;
        RecordType CurrentRecordType;
        RecordType AffiliateRecordType;
    private final Commission__c comm; 
    
        public commission(ApexPages.StandardController stdController) {
                this.comm = (Commission__c)stdController.getRecord(); 
                this.stdController = stdController;
                
                
                List<RecordType> ListOfRecordType=new List<RecordType>();
                
                if(this.comm.Recordtypeid!=null)  
                ListOfRecordType=[select ID,Name from RecordType where id=:this.comm.Recordtypeid];
                
                if (ListOfRecordType.size()>0)
                CurrentRecordType=ListOfRecordType[0];
           
           AffiliateRecordType=[Select ID from RecordType Where Name='Affiliates'];     
    }

    private Boolean show;
    public Boolean getself() {
        if (comm.User__c != null) {
         //   try {
                User self = [select Id from User where Id = :comm.User__c];
                if (UserInfo.getUserId() == self.Id) {
                    show = false;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You cannot create or edit a record for which you are the User.'));

                }else {
                    show = true;
                }
    //        } catch (Exception e) {
    //            show = false;
   //             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'You cannot create or edit a record for which you are the User.'));

   //         }
        } else {
            show = true;
        }  
        return show; 
    }
    public PageReference saveAndNew() {
    
        Double totalpercent = 0;
        Double tp = 0;
     
    if (CurrentRecordType==null && this.comm.Recordtypeid!=null){
                 List<RecordType> ListOfRecordType=new List<RecordType>();
                ListOfRecordType=[select ID,Name from RecordType where id=:this.comm.Recordtypeid];
                
                if (ListOfRecordType.size()>0)
                CurrentRecordType=ListOfRecordType[0];
    }
    
     
        If(CurrentRecordType!=null &&  CurrentRecordType.Name=='Affiliates' && comm.Fixed_Cost__c==false && (comm.Percent__c==null || comm.Percent__c==0)){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,FixedCostValidationMessage  ));
            return null;
        }
        else  if ((CurrentRecordType==null || (CurrentRecordType!=null &&  CurrentRecordType.Name!='Affiliates') )    &&  comm.Percent__c==null){
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Percent is Required.')); return null;
        }
        else{       
                Commission__c[] coms = [select Percent__c from Commission__c where (recordtypeid=null or RecordTypeid!=:AffiliateRecordType.id) and Opportunity__c = :comm.Opportunity__c];
                Opportunity opps = [select Commission_Percent_Cap__c from Opportunity where Id = :comm.Opportunity__c];
                if(opps.Commission_Percent_Cap__c == null){
                        opps.Commission_Percent_Cap__c = 3.00;
                }
                for (Integer i = 0; i <coms.size(); i++) {
                            if(coms[i].Percent__c != null){
                            totalpercent += coms[i].Percent__c;
                        }
                }
                
                
                if(comm.Percent__c!=null)
                    tp += totalpercent + comm.Percent__c;
                
                
                    try {
                        if (Double.valueOf(tp) <= opps.Commission_Percent_Cap__c || (CurrentRecordType!=null && CurrentRecordType.Name=='Affiliates')){
                            Upsert comm;
                            
                            PageReference newcontact ;

                            
                                if (CurrentRecordType!=null && CurrentRecordType.Name=='Affiliates')
                                    newcontact = new PageReference('/apex/CommissionAffiliateNew?RecordType='+CurrentRecordType.Id+'&'+'oid=' + comm.Opportunity__c );
                                else if (CurrentRecordType!=null && CurrentRecordType.Name!='Affiliates')
                                    newcontact = new PageReference('/apex/commission_new?RecordType='+CurrentRecordType.Id+'&'+'oid=' + comm.Opportunity__c );
                                else
                                    newcontact = new PageReference('/apex/commission_new?oid=' + comm.Opportunity__c );                                 
                                                                                            
                            newcontact.setRedirect(true);
                            return newcontact;
                        } else {
                            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Total Commission Percent cannot exceed ' +opps.Commission_Percent_Cap__c+'%. Total Commisison Percent is currently ' +totalpercent +'%. Your current commission exceeds the limit by ' + (tp-opps.Commission_Percent_Cap__c) +'%.'));
                            getSelf();
                            return null;
                        }
                     }  catch (System.DmlException e) {
                    //    System.debug(e.getDmlMessage(0));
                    //    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Commission Record Failed to insert. Please contact your System Administrator.'));
                        return null;
                    } 
         }
    }
    public PageReference saves() {
    
    
        Double totalpercent = 0;
        Double tp = 0;
    
    
       if (CurrentRecordType==null && this.comm.Recordtypeid!=null){
                 List<RecordType> ListOfRecordType=new List<RecordType>();
                ListOfRecordType=[select ID,Name from RecordType where id=:this.comm.Recordtypeid];
                
                if (ListOfRecordType.size()>0)
                CurrentRecordType=ListOfRecordType[0];
            }
         
        If(CurrentRecordType!=null && CurrentRecordType.Name=='Affiliates' &&  comm.Fixed_Cost__c==false && (comm.Percent__c==null || comm.Percent__c==0)){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING, FixedCostValidationMessage ));
            return null;
        }
        else  if ((CurrentRecordType==null || (CurrentRecordType!=null &&  CurrentRecordType.Name!='Affiliates') )    &&  comm.Percent__c==null){
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Percent is Required.')); return null;
        }
        else{        
            
                    Commission__c[] coms = [select Percent__c from Commission__c where (recordtypeid=null or RecordTypeid!=:AffiliateRecordType.id)  and  Opportunity__c = :comm.Opportunity__c];
                    Opportunity opps = [select Commission_Percent_Cap__c from Opportunity where Id = :comm.Opportunity__c];
                    if(opps.Commission_Percent_Cap__c == null){
                            opps.Commission_Percent_Cap__c = 3.00;
                    }
                    System.debug(coms);
                    for (Integer i = 0; i <coms.size(); i++) {
                            if(coms[i].Percent__c != null){
                            totalpercent += coms[i].Percent__c;
                            }
                    }
                    
                    if (comm.Percent__c!=null)
                        tp += totalpercent + comm.Percent__c;
                        
                        try {
                            if (Double.valueOf(tp) <= opps.Commission_Percent_Cap__c || (CurrentRecordType!=null && CurrentRecordType.Name=='Affiliates')){
                                return stdController.save();
                            } else {
                                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Total Commission Percent cannot exceed ' +opps.Commission_Percent_Cap__c+'%. Total Commisison Percent is currently ' +totalpercent +'%. Your current commission exceeds the limit by ' + (tp-opps.Commission_Percent_Cap__c) +'%.'));
                                getSelf();
                                return null;
                            }
                         }  catch (System.DmlException e) {
                            System.debug(e.getDmlMessage(0));
                            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Commission Record Failed to insert. Please contact your System Administrator.'));
                            return null;
                        } 
                        
                        
              }
    }
    public void setPercent() {
        try {
            User payee = [select Commission_Percentage__c from User where Id = :comm.User__c];
            comm.Percent__c = payee.Commission_Percentage__c;  
        } catch (Exception e) {
            System.debug(e);
            comm.Percent__c = 0.0; 
        }
    }
    public void setOpp() {
        if(ApexPages.currentPage().getParameters().get('oid') != null){
                comm.Opportunity__c = ApexPages.currentPage().getParameters().get('oid');
                comm.RecordTypeID= ApexPages.currentPage().getParameters().get('RecordType');
                List<RecordType> ListOfRecordType=new List<RecordType>();
                ListOfRecordType=[select ID,Name from RecordType where id=:this.comm.Recordtypeid];
                
                if (ListOfRecordType.size()>0)
                CurrentRecordType=ListOfRecordType[0];
        }
/*        String opps = ApexPages.currentPage().getParameters().get('CF00N80000002mpsx_lkid'); 
        if (opp != null){
            comm.Opportunity__c = opp;
        } else { 
            comm.Opportunity__c = opps;
        } */
   /* }
    public static testmethod void commissionTest() {
                       
        //Set Page Parameters 
        User other = [select Id from User where Name = 'Michael Hall']; 
        Account AccMake = new Account(Name = 'Knight - 2456',Type = 'Customers',Job_Type__c = 'Residential',Branch__c = 'Berkeley', 
                        Project_End_Date__c = null, ShippingCity = 'Park City'); insert AccMake;
        Opportunity opp = new Opportunity(OwnerId = other.Id, Name = 'Knight - 2456',AccountId = AccMake.Id,Type = 'Turnkey System',
                                                                                CloseDate = System.today(),StageName = 'Prospecting'); insert opp;
        Commission__c com = new Commission__c(User__c = other.Id, Percent__c = 3, Opportunity__c = opp.Id); insert com; 
        
        Test.startTest();
        
        //Test Paperwork Page
        PageReference pageRef = Page.commission_new;
        Test.setCurrentPage(pageRef);
        
        //Set Paperwork Parameters
        ApexPages.StandardController con = new ApexPages.StandardController(new Commission__c());
        commission ext = new commission(con);
        ApexPages.currentPage().getParameters().put('oid', opp.Id);
        
        
        //Call all methods on Paperwork page    
        ext = new commission(con);
              
          ext.setOpp();
          ext.getself();
          ext.setPercent();
          PageReference result2 = ext.saves();
          PageReference result = ext.saveAndNew();          
          
        //Test contractCA Page  
        PageReference pageRef2 = Page.commission_edit;
        Test.setCurrentPage(pageRef2);
        
        //Set Parameters
        ApexPages.StandardController con2 = new ApexPages.StandardController(com);
        commission ext2 = new commission(con2);
        ApexPages.currentPage().getParameters().put('oid', opp.Id);
        ApexPages.currentPage().getParameters().put('id', com.Id);
        
          ext2.getself();
          ext2.setPercent();
          PageReference result3 = ext2.saves();
          PageReference result4 = ext2.saveAndNew();                           
        
        Test.stopTest();
    }  */ 
}