objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Subcontractor Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bird Spikes</fullName>
                </value>
                <value>
                    <fullName>Signage</fullName>
                </value>
                <value>
                    <fullName>Boring</fullName>
                </value>
                <value>
                    <fullName>Carport installation</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Demolition</fullName>
                </value>
                <value>
                    <fullName>Electrical</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>EV Stations</fullName>
                </value>
                <value>
                    <fullName>Exploratory Excavations</fullName>
                </value>
                <value>
                    <fullName>Fencing</fullName>
                </value>
                <value>
                    <fullName>Fire Control</fullName>
                </value>
                <value>
                    <fullName>Third-Party Inspection/Testing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Roofer</fullName>
                </value>
                <value>
                    <fullName>Temp Labor</fullName>
                </value>
                <value>
                    <fullName>UG Utilities</fullName>
                </value>
                <value>
                    <fullName>MV</fullName>
                </value>
                <value>
                    <fullName>Mechanical</fullName>
                </value>
                <value>
                    <fullName>Site Services</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Landscaping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>Choose what type of asset.
Note: need to edit validation rule &quot;Storage Project Battery Only&quot; any time a new picklist value is added</description>
        <inlineHelpText>Choose what type of asset</inlineHelpText>
        <label>Asset Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Asset_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The service contract associated with the Asset</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the case to a Project
Used in Diaspark Integration</description>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Visit_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The case lookup field on the Service Visit record that was used to create the Asset at the time the Asset was created. Set automatically by the Create Asset button on the Service Visit record.</inlineHelpText>
        <label>Service Visit Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceContract_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related service contract # for account which this case was opened.</inlineHelpText>
        <label>Service Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Service Case</businessProcess>
        <description>used to log all reactive service cases and is default case type for email to case settings</description>
        <label>Reactive</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CaseServiceVisitRecordTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of allowed Service Visit record types based upon the related Case record type.</description>
    <fields>
        <fullName>Asset_Selection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asset Selection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Visit_Record_Types__c</fullName>
        <label>Service Visit Record Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CaseServiceVisitRecordTypes</label>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Dynamic_Field_Id_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>SV_Account__c</fullName>
        <label>SV.Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_Asset__c</fullName>
        <label>SV.Asset</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_Case__c</fullName>
        <label>SV.Case</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_ContractType__c</fullName>
        <label>SV.ContractType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_Contract__c</fullName>
        <label>SV.Contract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_Project__c</fullName>
        <label>SV.Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dynamic Field Id Setting</label>
</CustomObject>

objects/MaintenanceCaseServiceVisits__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Information about the Service Visit records that are automatically created when a Maintenance Case is created.</description>
    <fields>
        <fullName>Service_Visit_Record_Type__c</fullName>
        <label>Service Visit Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MaintenanceCaseServiceVisits</label>
</CustomObject>

objects/SFDC_Project__c.object
<CustomObject>
    <description>Project Management</description>
    <label>SFDCProject</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFDCProjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>shows type of asset from related Asset record</description>
        <formula>TEXT(Asset__r.Component_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>shows type of asset from related Asset record</inlineHelpText>
        <label>Asset Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Asset_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AC Panel Cabinet</fullName>
    </customValue>
    <customValue>
        <fullName>Battery Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Battery Enclosure</fullName>
    </customValue>
    <customValue>
        <fullName>BOP</fullName>
    </customValue>
    <customValue>
        <fullName>Central Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Combiner</fullName>
        <label>Combiner Box</label>
    </customValue>
    <customValue>
        <fullName>Communication Cabinet</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Module</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Racking</fullName>
    </customValue>
    <customValue>
        <fullName>Roof</fullName>
    </customValue>
    <customValue>
        <fullName>Solar Array</fullName>
    </customValue>
    <customValue>
        <fullName>String Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Switch Gear</fullName>
    </customValue>
    <customValue>
        <fullName>Tracker</fullName>
    </customValue>
    <customValue>
        <fullName>Transformer</fullName>
    </customValue>
    <customValue>
        <fullName>Weather Station</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Inverter</fullName>
        <isActive>false</isActive>
        <label>Inverter</label>
    </customValue>
    <masterLabel>Asset Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/NewServiceVisitController.cls
public with sharing class NewServiceVisitController {
	
	public List<SelectOption> recordTypeList {get; set;}
    public String selectedRecordTypeId {get; set;}
	public List<SelectOption> assetOptions {get; set;}
	public Boolean showRecordTypes {get; set;}
	public Boolean showAsset {get; set;}
	public Boolean fatalError {get; set;}
	public Boolean isNewServiceVisit {get; set;}

	Case cs;
	String selectedAsset;
	Map<Id, Asset> assetMap;
    String projectId, accountId, contractId, caseId, assetId;
    String projectName, accountName, contractName, caseName, contractType, assetName;
    String assetComponentType;
    String retURL;
    
    public NewServiceVisitController(ApexPages.StandardController stdController) {
		
		caseId = ApexPages.currentPage().getParameters().get('caseId');
		accountId = ApexPages.currentPage().getParameters().get('accId');
		assetId = ApexPages.currentPage().getParameters().get('assetId');
		retURL = '/';
		
		isNewServiceVisit = true;
        showAsset = false;
        showRecordTypes = false;
        fatalError = false;
        
		if (String.isNotBlank(assetId)) {
			List<Asset> assetList = new List<Asset>();
			assetList = [select Id, Name, AccountId, Account.Name, Component_Type__c, Contract__c, Contract__r.Name, Service_Visit_Case__c, Service_Visit_Case__r.CaseNumber, Project__c, Project__r.Name from Asset where Id = :assetId];
			Asset ast = assetList[0];
			assetName = ast.Name;
			accountId = ast.AccountId;
			accountName = ast.Account.Name;
			contractId = ast.Contract__c;
			contractName = ast.Contract__r.Name;
			projectId = ast.Project__c;
            projectName = ast.Project__r.Name;
            assetComponentType = ast.Component_Type__c;
            caseId = ast.Service_Visit_Case__c;
            caseName = ast.Service_Visit_Case__r.CaseNumber;
            
            retURL += assetId;
            
		} else {
			
			List<Case> listOfCases = new List<Case>();
			listOfCases = [select Id, CaseNumber, RecordTypeId, AccountId, Account.Name, ServiceContract_Case__c, ServiceContract_Case__r.ContractNumber, ServiceContract_Case__r.Type__c, Project__c, Project__r.Name from Case where Id = :caseId];
			contractId = null;
			
			if (!listOfCases.isEmpty()) {
				cs = listOfCases[0];
				accountId = cs.Accountid;
				contractId = cs.ServiceContract_Case__c;
				contractName = cs.ServiceContract_Case__r.ContractNumber;
				contractType = cs.ServiceContract_Case__r.Type__c;
				accountName = cs.Account.Name;
				caseName = cs.CaseNumber;
				projectId = cs.Project__c;
				projectName = cs.Project__r.Name;
			}
			
			if (contractId == null) {
				if (accountId != null) {
					Account acc = [select Name from Account where Id = :accountId];
					accountName = acc.name;
					list<Contract> listOfContracts  =[select Id, ContractNumber from Contract where AccountId = :accountId order by CreatedDate desc];
					
					if (listOfContracts != null && listOfContracts.size() > 0) {
						contractId = listOfContracts[0].Id;
						contractName = listOfContracts[0].contractNumber ;
					}
				}
			}
			
			if (String.isNotBlank(caseId)) {
				retURL += caseId;
			} else {
				if (String.isNotBlank(accountId)) {
					retURL += accountId;
				}
			}
		}
    }
	
	public PageReference initSelectLists() {
		PageReference pr = null;
		Boolean allowAssets = true;
		Set<String> rtNames = new Set<String>();
		
		// Create map of allowable Service Vist record types
		Id defaultRtId = null;
		selectedRecordTypeId = null;
		Map<Id, Schema.RecordTypeInfo> rtSVMap = Schema.SObjectType.SV__c.getRecordTypeInfosById();
		Map<Id, String> allowedRtNameMap = new Map<Id, String>();
		for (Schema.RecordTypeInfo rt :rtSVMap.values()) {
			if (rt.isAvailable() && rt.getName() != 'Master') {
				allowedRtNameMap.put(rt.getRecordTypeId(), rt.getName());
				if (rt.isDefaultRecordTypeMapping()) {
					defaultRtId = rt.getRecordTypeId();
				}
			}
		}
		
		// If we are creating Service Visit from an Asset, set Record Type based upon asset Component Type
		if (String.isNotBlank(assetId)) {
			allowAssets = false;
			rtNames.addAll(allowedRtNameMap.values());
			if (String.isNotBlank(assetComponentType)) {
				Map<String, MaintenanceCaseServiceVisits__c> maintCaseSVs = MaintenanceCaseServiceVisits__c.getAll();
				if (maintCaseSVs.containsKey(assetComponentType)) {
					Map<String, Schema.RecordTypeInfo> rtSVNameMap = Schema.SObjectType.SV__c.getRecordTypeInfosByName();
					if (rtSVNameMap.containsKey(maintCaseSVs.get(assetComponentType).Service_Visit_Record_Type__c)) {
						rtNames.clear();
						rtNames.add(maintCaseSVs.get(assetComponentType).Service_Visit_Record_Type__c);
					}
				}
			}
			
		} else {
			
			// If we are creating Service Visit from Case, further restrict record type list
			Map<String, CaseServiceVisitRecordTypes__c> csvrtMap = CaseServiceVisitRecordTypes__c.getAll();
			Map<Id, Schema.RecordTypeInfo> rtCaseMap = Schema.SObjectType.Case.getRecordTypeInfosById();
			if (String.isNotBlank(caseId)) {
				if (csvrtMap.containsKey(rtCaseMap.get(cs.RecordTypeId).getName())) {
					rtNames.addAll(csvrtMap.get(rtCaseMap.get(cs.RecordTypeId).getName()).Service_Visit_Record_Types__c.split(';'));
					allowAssets = csvrtMap.get(rtCaseMap.get(cs.RecordTypeId).getName()).Asset_Selection__c;
				}
			}
		}
		
		for (Id rt :allowedRtNameMap.keySet()) {
			if (!rtNames.contains(allowedRtNameMap.get(rt))) {
				allowedRtNameMap.remove(rt);
			}
		}
		
		if (allowedRtNameMap.containsKey(defaultRtId)) {
			selectedRecordTypeId = defaultRtId;
		}
		
		recordTypeList = new List<SelectOption>();
		for (Id rt :allowedRtNameMap.keySet()) {
			recordTypeList.add(new SelectOption(rt, allowedRTNameMap.get(rt)));
		}
		
		if (!recordTypeList.isEmpty()) {
			if (selectedRecordTypeId == null || recordTypeList.size() == 1) {
				selectedRecordTypeId = String.valueOf(recordTypeList[0].getValue());
			}
			
			if (recordTypeList.size() > 1) {
				showRecordTypes = true;
			}
		} else {
			selectedRecordTypeId = null;
		}
		
		// Create asset select list
		assetOptions = new List<SelectOption>();
		assetMap = new Map<Id, Asset>();
		assetOptions.add(new SelectOption('--None--','--None--'));
		Map<String, Schema.RecordTypeInfo> rtAssetMap = Schema.SObjectType.Asset.getRecordTypeInfosByName();
		if (String.isBlank(assetId)) {
			
			if (allowAssets) {
			    if (String.isNotBlank(projectId)) {
                    if (String.isNotBlank(caseId)) {
                        assetMap = new Map<Id, Asset>([select Id, Name from Asset where Project__c = :projectId and RecordTypeId =: rtAssetMap.get('Operations Asset').getRecordTypeId()]);
                    } else {
                        assetMap = new Map<Id, Asset>([select Id, Name from Asset where Project__c = :projectId]);
                    }
			    } else if (String.isNotBlank(contractId)) {
			        if (String.isNotBlank(caseId)) {
                        assetMap = new Map<Id, Asset>([select Id, Name from Asset where Contract__c = :contractId and RecordTypeId =: rtAssetMap.get('Operations Asset').getRecordTypeId()]);
                    } else {
                        assetMap = new Map<Id, Asset>([select Id, Name from Asset where Contract__c = :contractId]);
                    }
			    }
			    
                for (Asset a :assetMap.values()) {
                    assetOptions.add(new SelectOption(a.Id, a.Name));
                }
			}
			/*
			if (contractId != null && allowAssets) {
				//assetMap = new Map<Id, Asset>([select Id, Name, Contract__c from Asset where Contract__c = :contractId]);
				if (String.isNotBlank(caseId)) {
					assetMap = new Map<Id, Asset>([select Id, Name, Contract__c from Asset where Contract__c = :contractId and RecordTypeId =: rtAssetMap.get('Operations Asset').getRecordTypeId()]);
				} else {
					assetMap = new Map<Id, Asset>([select Id, Name, Contract__c from Asset where Contract__c = :contractId]);
				}
				
				
				for (Asset a :assetMap.values()) {
					assetOptions.add(new SelectOption(a.Id, a.Name));
				}
			}
			*/
			
		} else {
			assetOptions.add(new SelectOption(assetId, assetName));
		}
		
		if (assetOptions.size() > 1) {
			if (assetOptions.size() == 2) {
				selectedAsset = assetOptions[1].getValue();
			} else {
				selectedAsset = assetOptions[0].getValue();
				showAsset = true;
			}
		} else {
			selectedAsset = null;
		}
		
		system.debug('*****initSelectLists showRecordTypes = ' + showRecordTypes + ' recordTypeList.size = ' + recordTypeList.size() + ' showAsset = ' + showAsset + ' allowAssets = ' + allowAssets + ' assetMap.size = ' + assetMap.size() + ' assetOptions.size = ' + assetOptions.size());
		
		// if no need to select record types or assets, take user to the next step
		if (!showRecordTypes && !showAsset) {
			pr = serviceVisitNewEditPage();
		}
		
		return pr;
	}
    
    public String getselectedAsset() {
		return selectedAsset;
	}
	
	public void setselectedAsset(String aId) {
		selectedAsset = aId;
	}
    
	public pageReference serviceVisitNewEditPage(){
		Map<Id, Schema.RecordTypeInfo> rtSVMap = Schema.SObjectType.SV__c.getRecordTypeInfosById();
		pageReference pageRef;
		
		if (String.isBlank(assetId)) {
			if (selectedAsset != '--None--' && assetMap.containsKey(selectedAsset)) {
				assetId = assetMap.get(selectedAsset).Id;
				assetName = assetMap.get(selectedAsset).Name;
			}
		}
		
		if (isNewServiceVisit) {
			if (rtSVMap.containsKey(selectedRecordTypeId) && rtSVMap.get(selectedRecordTypeId).getName() == 'Reactive') {
				
				pageRef = new pageReference('/apex/ServiceVisit_Asset');
				pageRef.getparameters().put('RecordType', selectedRecordTypeId);
				pageRef.getparameters().put('accountId', accountId);
				pageRef.getparameters().put('caseId', caseId);
				pageRef.getparameters().put('contractId', contractId);
				pageRef.getparameters().put('projectId', projectId);
				pageRef.getparameters().put('contractType', contractType);
				pageRef.getparameters().put('assetId', assetId);
				
			} else {
				
				pageRef = new pageReference('/a0c/e');
				Dynamic_Field_Id_Setting__c fieldIds = Dynamic_Field_Id_Setting__c.getOrgDefaults();
				
				if (String.isNotBlank(selectedRecordTypeId)) {
					pageRef.getparameters().put('RecordType', selectedRecordTypeId);
				}
				
				pageRef.getparameters().put('CF' + fieldIds.SV_Account__c + '_lkid', accountId);
				pageRef.getparameters().put('CF' + fieldIds.SV_Account__c, accountName);
				
				pageRef.getparameters().put('CF' + fieldIds.SV_Case__c + '_lkid', caseId);
				pageRef.getparameters().put('CF' + fieldIds.SV_Case__c, caseName);
				
				pageRef.getparameters().put('CF' + fieldIds.SV_Contract__c + '_lkid', contractId);
				pageRef.getparameters().put('CF' + fieldIds.SV_Contract__c, contractName);
				
				pageRef.getparameters().put('CF' + fieldIds.SV_Project__c + '_lkid', projectId);
				pageRef.getparameters().put('CF' + fieldIds.SV_Project__c, projectName);
				
				pageRef.getparameters().put(fieldIds.SV_ContractType__c, contractType);
				
				pageRef.getparameters().put('CF' + fieldIds.SV_Asset__c + '_lkid', assetId);
				pageRef.getparameters().put('CF' + fieldIds.SV_Asset__c, assetName);
			}
		}
		
		pageRef.getparameters().put('retURL', retURL);   
		pageRef.setRedirect(true);     
		return pageRef;
	}
	
	// Record the case record type selected
    public PageReference saveRecordType() {
		PageReference pr = null;
		
		if (selectedRecordTypeId != null) {
			showRecordTypes = false;
			if (!showAsset) {
				pr = serviceVisitNewEditPage();
			}
		} else {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'You must select a record type.'));
		}
		
		return pr;
    }
    
    public PageReference cancelServiceVisit() {
		PageReference pr = new PageReference(retURL);
		return pr;
	}
	
	public PageReference saveAsset() {
		return serviceVisitNewEditPage();
	}
}