objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Automated__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, Commission was created when contract signed button was pushed. Used only for Commission type records</inlineHelpText>
        <label>Automated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>Opportunity the commission is related to</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <inlineHelpText>Percent of Commission- required at creation</inlineHelpText>
        <label>Percent</label>
        <precision>9</precision>
        <scale>7</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User who is receiving the commission- required at creation</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Con_Req__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipName>Con_Req</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the CO
Controlled by the approval process and recall button</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed by Customer</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Borrego Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>X - Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved By Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Tax rate to be added to the CO</inlineHelpText>
        <label>Tax Rate</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Change Order</label>
    <nameField>
        <displayFormat>SF-CR-{000000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>State used for reporting and allocation</description>
        <inlineHelpText>State used for reporting and allocation</inlineHelpText>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Branch value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Opportunities (Branch)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_Project__c.object
<CustomObject>
    <description>Project Management</description>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EC</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N300000021XqLEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SFDCProject</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFDCProjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Tax Rate</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Tax Rate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Commission_Percentage__c</fullName>
        <defaultValue>0.00</defaultValue>
        <inlineHelpText>Set to 1 if Sales Department. If not a Sales user, should be 0.</inlineHelpText>
        <label>Default Percent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/oppUpdates.cls
public class oppUpdates {
    public static void ownerUpdate(Map<Id, Opportunity> updatedOpps) {
        List<SFDC_Project__c> updatedProjects = new List<SFDC_Project__c>();
        for (SFDC_Project__c p : [SELECT EC__c, Opportunity__c FROM SFDC_Project__c WHERE Opportunity__c in :updatedOpps.keySet()]) {
            Opportunity parentOpportunity = updatedOpps.get(p.Opportunity__c);
            p.EC__c = parentOpportunity.OwnerId;       
            updatedProjects.add(p);
        }
        update updatedProjects;
    }
    
    public static void removeCommission(Map<Id, Opportunity> opps) {
        List<Commission__c> updatedComms = new List<Commission__c>();
        for (Commission__c comms : [select Percent__c from Commission__c where Opportunity__c in :opps.keySet()]) {            
            updatedComms.add(comms);
        }
        delete updatedComms;
    }
    
    public static void addCommission(Map<Id,Opportunity> opps) {
        Commission__c[] comm = new Commission__c[0];
        
        Map<Id, User> users = new Map<Id, User>([select Id, Name, ManagerId, Commission_Percentage__c from User]);
        
        Map<string,User> MapOfUser=new Map<string,User>();
        
        for (User CurrentUser:[select Id,Name,Commission_Percentage__c, ManagerId
                                     from User where Name = 'Matti Hirpa' or Name = 'Miles Hovis' or Name = 'Philip Hall']){
            MapOfUser.Put(CurrentUser.Name, CurrentUser);
        } 
        
        Map<ID,Opportunity> MapOfOpportunity=new Map<id,Opportunity>([Select id, Account.Branch__C from Opportunity
                                                                        Where id in :opps.KeySet()]);
        //User[] tandf = [select Id from User where Name = 'Matti Hirpa' or Name = 'Jon Sarno' or Name = 'Philip Hall'];
        //User[] tandf = [select Id from User where Name = 'Philip Hall'];
        Commission__c[] comms = [select User__c, Percent__c, Opportunity__c from Commission__c where Opportunity__c in :opps.keySet()];
        Map<Id, User> oppComms = new Map<Id, User>();   
        for (Opportunity o:opps.values()) {        
            oppComms.clear();
            id Userid=UserInfo.GetUserid();
            oppComms.put(o.Ownerid, users.get(o.Ownerid));
            //oppComms.put(users.get(tandf[0].Id).Id, users.get(tandf[0].Id));
            //oppComms.put(users.get(tandf[1].Id).Id, users.get(tandf[1].Id));
            //oppComms.put(users.get(tandf[2].Id).Id, users.get(tandf[2].Id));
            
            /*
            if(o.Account.Branch__c == 'XYZ' || o.Account.Branch__c == 'XYZ')
            Add Commision with define user and define commision
            */
            
            /*for (Integer m = 0; m < tandf.size(); m++) {
                oppComms.put(users.get(tandf[m].Id).Id, users.get(tandf[m].Id));
            }*/
            
            String Branch=MapOfOpportunity.Get(O.ID).Account.Branch__C;
            
            If(MapOfUser.ContainsKey('Philip Hall'))            
                oppComms.put(MapOfUser.Get('Philip Hall').Id, MapOfUser.Get('Philip Hall'));
            
            if(Branch == 'Boston' || Branch == 'Mid Atlantic'){
                If(MapOfUser.ContainsKey('Miles Hovis'))            
                    oppComms.put(MapOfUser.Get('Miles Hovis').Id, MapOfUser.Get('Miles Hovis'));
            }
            
            if(Branch == 'Berkeley' || Branch == 'San Diego' || Branch == 'Oakland' || Branch == 'Nor Cal' || Branch == 'So Cal'){
                If(MapOfUser.ContainsKey('Matti Hirpa'))            
                    oppComms.put(MapOfUser.Get('Matti Hirpa').Id, MapOfUser.Get('Matti Hirpa'));
            }
            
            if(users.containskey(Userid) && users.ContainsKey(users.get(Userid).ManagerId) && users.containsKey(users.get(users.get(Userid).ManagerId).Id)){
                oppComms.put(users.get(Userid).ManagerId, users.get(users.get(Userid).ManagerId));
            }
            if(users.containskey(Userid) && users.containsKey(users.get(Userid).ManagerId) && users.containsKey(users.get(users.get(Userid).ManagerId).ManagerId) && users.containsKey(users.get(users.get(users.get(Userid).ManagerId).ManagerId).Id)){
                oppComms.put(users.get(users.get(users.get(Userid).ManagerId).ManagerId).Id, users.get(users.get(users.get(Userid).ManagerId).ManagerId));
            }           
            if (comms.size() > 0) {
                for (Integer i = 0; i <comms.size(); i++) {
                    if (oppComms.containsKey(comms[i].User__c)) {
                        oppComms.remove(comms[i].User__c);                  
                    }
                }     
                List<User> result = new List<User>();
                result = oppComms.values();
                    
                for (Integer j = 0; j <result.size(); j++) {
                    if(result[j].Id==o.Ownerid && (result[j].Commission_Percentage__c==null || result[j].Commission_Percentage__c==0))
                        comm.add(new Commission__c(Opportunity__c = o.Id,
                        User__c = result[j].Id,
                        Automated__c = true,
                        Percent__c = 2));
                    else
                        comm.add(new Commission__c(Opportunity__c = o.Id,
                        User__c = result[j].Id,
                        Automated__c = true,
                        Percent__c = result[j].Commission_Percentage__c));
                }
            }
            if (comms.size() == 0) {
                List<User> result2 = new List<User>();
                result2 = oppComms.values();         
                for (Integer j = 0; j <result2.size(); j++) {
                    if(result2[j].Id==o.Ownerid  && (result2[j].Commission_Percentage__c==null || result2[j].Commission_Percentage__c==0))
                        comm.add(new Commission__c(Opportunity__c = o.Id,
                        User__c = result2[j].Id,
                        Automated__c = true,
                        Percent__c = 2));
                    else
                        comm.add(new Commission__c(Opportunity__c = o.Id,
                        User__c = result2[j].Id,
                        Automated__c = true,
                        Percent__c = result2[j].Commission_Percentage__c));
                }
            }
        }  
        insert comm;
    }
    
    public static void taxRateUpdate(Map<Id, Opportunity> oMap) {
        //The Tax Exemption Status field of the Opportunity record has just changed,
        //update the Tax Rate field on the associated Construction Requisitions
        
        //Get the associated Project, Construction Requisition, Account and Tax Rate records
        SFDC_Project__c[] proj = [select Id, Opportunity__c from SFDC_Project__c where Opportunity__c in:oMap.keySet()];
        Map<Id, SFDC_Project__c> pMap = new Map<Id, SFDC_Project__c>();
        for (Integer i=0; i<proj.size(); i++) {
            pMap.put(proj[i].Id, proj[i]);
        }
        if (proj.size() > 0) {
            Con_Req__c[] conreq = [select Id, Status__c, Tax_Rate__c, Project__c from Con_Req__c where Project__c in:pMap.keySet()];
            Map<Id, Con_Req__c> crMap = new Map<Id, Con_Req__c>();
            for (Integer j=0; j<conreq.size(); j++) {
                crMap.put(conreq[j].Id, conreq[j]);
            }
            if (conreq.size() > 0) {
                List<Id> aId = new List<Id>();
                for (Integer k=0; k<conreq.size(); k++) {
                    aId.add(oMap.get(pMap.get(conreq[k].Project__c).Opportunity__c).AccountId);
                }
                Account[] acc = [select Id, ShippingCity from Account where Id in:aId];
                Map<Id, Account> aMap = new Map<Id, Account>();
                List<String> sCity = new List<String>();
                for (Integer k=0; k<acc.size(); k++) {
                    aMap.put(acc[k].Id, acc[k]);
                    sCity.add(acc[k].ShippingCity);
                }
                Tax_Rate__c[] tr = [select Id, Tax_Rate__c, City__c from Tax_Rate__c where City__c in:sCity];
                Map<String, Tax_Rate__c> trMap = new Map<String, Tax_Rate__c>();
                for (Integer k=0; k<tr.size(); k++) {
                    trMap.put(tr[k].City__c, tr[k]);
                }
                List<Con_Req__c> conreqUp = new List<Con_Req__c>();
                for (Integer k=0; k<conreq.size(); k++) {
                    if (conreq[k].Status__c == 'New') {
                        if (oMap.get(pMap.get(conreq[k].Project__c).Opportunity__c).Tax_Exemption__c == 'Exempt') {
                            conreq[k].Tax_Rate__c = 0;
                        } else {
                            try {
                                conreq[k].Tax_Rate__c = trMap.get(aMap.get(oMap.get(pMap.get(conreq[k].Project__c).Opportunity__c).AccountId).ShippingCity).Tax_Rate__c;
                            } catch (Exception e) {
                                conreq[k].Tax_Rate__c = null;
                            }
                        }
                        conreqUp.add(conreq[k]);
                    }
                }
                if (conreqUp.size() > 0) {
                    update conreqUp;
                }
            }
        }
    }
    
	// Prevent recursive Opportunity trigger
	private static Boolean run = true;
	
	public static Boolean runOnce() {
		if (run) {
			run=false;
			return true;
		} else {
			return run;
		}
	}
    
    public static testMethod void NetAmountTest(){
        User owner = [select Id from User where Name = 'System User'];
        User other = [select Id from User where Name = 'Michael Hall']; 
        Account AccMake = new Account(Name = 'Knight - 2456',Type = 'Customers',Job_Type__c = 'Residential',Branch__c = 'Berkeley', 
                                         Project_End_Date__c = null, ShippingCity = 'Park City'); insert AccMake;
        Opportunity OppMake = new Opportunity(OwnerId = owner.Id, Name = 'Knight - 2456',AccountId = AccMake.Id,Type = 'Turnkey System', System_Owner_Account__c = AccMake.Id, 
                                                CloseDate = System.today(),StageName = 'Prospecting', Financing__c = 'Cash'); insert OppMake;
        
        SFDC_Project__c[] project = new SFDC_Project__c[0];
        project.add(new SFDC_Project__c(Name = 'Knight - 2456',Opportunity__c = OppMake.Id, Account__c = AccMake.Id, SFDC_Project_Stage__c = 'Sales', 
                                        Interconnection_Status__c = 'Submitted', Rebate_Status__c = null, SFDC_Project_End_Date__c = null, 
                                        Job_Number__c = '000-000', OwnerId = owner.Id)); 
        insert project;
        
        OppMake.StageName = 'Contract Signed';
        update OppMake;
        
        Commission__c comm = [select Id from Commission__c where Opportunity__c = :OppMake.Id LIMIT 1];
        delete comm;
        
        OppMake.StageName = 'Prospecting';
        update OppMake;
        OppMake.StageName = 'Closed Lost';
        OppMake.Loss_Reason__c='Lost To Competition- Price';
        OppMake.Won_Loss_Explanation__c = 'Competition low-balled us';
        OppMake.Loss_Category__c = 'Other';
        update OppMake;
        //OppMake.OwnerId = other.Id;
        //update OppMake;
    }
}