objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <inlineHelpText>What sector is the customer classified under? 
**Only for Customer Accounts**</inlineHelpText>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Residential - Multi-Unit</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Small Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ELI__c.object
<CustomObject>
    <description>Each line item can be recorded.</description>
    <fields>
        <fullName>Approved_Amount__c</fullName>
        <description>AP Profiles Only – Users read-only</description>
        <label>Approved Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Code</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Cost_Code__c.Name</field>
                <operation>notEqual</operation>
                <value>Travel</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cost_Code__c</referenceTo>
        <relationshipLabel>Expense Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expenditure_Amount__c</fullName>
        <formula>IF((ISPICKVAL(Expenditure_Type__c, &apos;Mileage&apos;)), Cost_Miles__c * Mileage_Rate__c, Cost_Miles__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expenditure Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Expenditure_Type__c</fullName>
        <label>Expenditure Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Airfare/Travel</fullName>
                </value>
                <value>
                    <fullName>Branch Meeting Expenses</fullName>
                </value>
                <value>
                    <fullName>Company Wide Meetings</fullName>
                </value>
                <value>
                    <fullName>Customer Meals &amp; Entertainment</fullName>
                </value>
                <value>
                    <fullName>Dues</fullName>
                </value>
                <value>
                    <fullName>Employee Meals &amp; Entertainment</fullName>
                </value>
                <value>
                    <fullName>Gas</fullName>
                </value>
                <value>
                    <fullName>Hotel</fullName>
                </value>
                <value>
                    <fullName>IT Expenses</fullName>
                </value>
                <value>
                    <fullName>Mileage</fullName>
                </value>
                <value>
                    <fullName>Moving and Relocation Expenses</fullName>
                </value>
                <value>
                    <fullName>Office Supplies</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other Employee Benefits</fullName>
                </value>
                <value>
                    <fullName>Parking/Tolls</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Proposal Costs</fullName>
                </value>
                <value>
                    <fullName>Rental Car</fullName>
                </value>
                <value>
                    <fullName>Training and Education</fullName>
                </value>
                <value>
                    <fullName>Vehicle Expense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expense_Header__c</fullName>
        <label>Expense Report</label>
        <referenceTo>ER__c</referenceTo>
        <relationshipLabel>Expense Line Items</relationshipLabel>
        <relationshipName>ExpRep</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Manager_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manager Profiles Only – User read-only</description>
        <label>Manager Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PV_Direct__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PV Direct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Expense Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rejected_Reason__c</fullName>
        <label>Rejected Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Out of Policy</fullName>
                </value>
                <value>
                    <fullName>No Receipt</fullName>
                </value>
                <value>
                    <fullName>Already Paid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <inlineHelpText>Enter the name of the vendor for the related expense.</inlineHelpText>
        <label>Vendor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Expense Line Item</label>
    <nameField>
        <displayFormat>EXP-LN-ITM {0000}</displayFormat>
        <label>Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ER__c.object
<CustomObject>
    <description>Individual expense reports.</description>
    <fields>
        <fullName>Month_Ending__c</fullName>
        <inlineHelpText>Choose the last day of the month you are submitting expenses for</inlineHelpText>
        <label>Month Ending</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Receipts_Attached__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field.  Checked by expRepButton.checkAtt if all Expense Line Items that require receipts have attachments.</description>
        <label>Receipts Attached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requested_Total__c</fullName>
        <label>Requested Total</label>
        <summarizedField>ELI__c.Expenditure_Amount__c</summarizedField>
        <summaryForeignKey>ELI__c.Expense_Header__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>PV Direct Approved</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Processed By Accounting</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Approved Total</label>
        <summarizedField>ELI__c.Expenditure_Amount__c</summarizedField>
        <summaryForeignKey>ELI__c.Expense_Header__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense Report-OLD</label>
    <nameField>
        <displayFormat>EXP-{0000}</displayFormat>
        <label>Expense Report #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Reports-OLD</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Government - Small</fullName>
                </value>
                <value>
                    <fullName>Utility Scale</fullName>
                </value>
                <value>
                    <fullName>ES Ground</fullName>
                </value>
                <value>
                    <fullName>Non ES Ground</fullName>
                </value>
                <value>
                    <fullName>ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Non ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>DG Solar</fullName>
                </value>
                <value>
                    <fullName>DG Wind</fullName>
                </value>
                <value>
                    <fullName>DG SAS</fullName>
                </value>
                <value>
                    <fullName>LSR PV</fullName>
                </value>
                <value>
                    <fullName>Bulk ES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/approveELI.cls
public class approveELI {
    
    private ELI__c[] eli = [select Id, Name, Expense_Header__c, Cost_Code__c, Vendor__c, Project__c, Expenditure_Type__c, PV_Direct__c,
                                Expenditure_Amount__c, Code__c, Date__c, Approved_Amount__c, Manager_Approval__c, Rejected_Reason__c from ELI__c 
                                where Expense_Header__c = :ApexPages.currentPage().getParameters().get('id')];
    
  /*  private ELI__c[] eli_pv = [select Id, Name, Expense_Header__c, Cost_Code__c, Vendor__c, Project__c, Expenditure_Type__c, PV_Direct__c,
                                Expenditure_Amount__c, Code__c, Date__c, Approved_Amount__c, Manager_Approval__c, Rejected_Reason__c 
                                from ELI__c where Expense_Header__c = :ApexPages.currentPage().getParameters().get('id') and PV_Direct__c = true]; */
                                             
    public ELI__c[] getEli(){
  /*      if(UserInfo.getName() == 'Brian von Moos'){
            return eli_pv;
        } else { */
            return eli;
     //   }
    }
    private ER__c exp = [select Name, User__c, Month_Ending__c, Status__c, Requested_Total__c, 
                            Total__c from ER__c where Id = :ApexPages.currentPage().getParameters().get('id')];
    public ER__c getER(){
        return exp;
    }
    public PageReference Save() {
        try{
            update eli;
            sendEmail();                     
            PageReference expRep = new PageReference('/' + ApexPages.currentPage().getParameters().get('id'));
            expRep.setRedirect(true);
    
            return expRep;
        } catch (DmlException e) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Only the Manager can approve Expense Lines. \n' + e)); 
            return null;
        } 
    }
    public PageReference SaveAll() {
        try{
            for(Integer i = 0; i<eli.size(); i++){
                eli[i].Manager_Approval__c = true;
            }
            update eli;
            sendEmail();                     
            PageReference expRep = new PageReference('/' + ApexPages.currentPage().getParameters().get('id'));
            expRep.setRedirect(true);
    
            return expRep;
        } catch (DmlException e) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Only the Manager can approve Expense Lines. \n' + e)); 
            return null;
        } 
    }
    public void sendEmail() {
        List<Id> elID = new List<Id>();
        for(Integer i = 0; i<eli.size(); i++){
            elID.add(eli[i].Id);
        }
        Attachment[] att = [select Name, Body, ContentType from Attachment where ParentId in :elID];
  
        update eli;
        submitApproval.app_rej(exp.Id, 'Approved.', 'Approve');
        
        User accounting = [select Id, Email from User where userrole.name = 'Purchasing and Logistics Manager' and IsActive = True];//FirstName = 'Anita' 
        User submitter = [select Name, LastName, FirstName from User where Id = :exp.User__c];
        
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
        
        PageReference pdf =  Page.expReport;
        pdf.getParameters().put('id',(String)exp.id); 
        pdf.setRedirect(true);

        // Take the PDF content
        Blob b;
        
        try{
            b = pdf.getContent();
        }
        catch(exception e){}
        
        // Create the email attachment
        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        efa.setFileName(submitter.LastName+'_'+submitter.FirstName+'.pdf');
        
        if(b!=null) efa.setBody(b);    
        
        String [] toAddresses = new String[] {accounting.Email};


        // Sends the email
        try {           
            Messaging.EmailFileAttachment[] attachments = new Messaging.EmailFileAttachment[0];
            if(b!=null) attachments.add(efa);
            
            Integer n = 0;  
            for(Integer i = 0; i < att.size(); i++){
                n += 1;
                Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();
                attach.setFileName('receipts('+n+').pdf');
                attach.setBody(att[i].Body);
                attachments.add(attach);
            }
            
            // Sets the paramaters of the email
            email.setSubject('Expense Report for '+submitter.Name);
            email.setToAddresses( toAddresses );
            email.setPlainTextBody( 'Attached is the expense report and receipts for '+submitter.Name+' for the month ending '
                                    +exp.Month_Ending__c+'.');                                       
            if(attachments.size()>0) email.setFileAttachments(attachments);
            
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        } catch (Exception e){
            Messaging.EmailFileAttachment[] attachments = new Messaging.EmailFileAttachment[0];
            if(b!=null) attachments.add(efa); 
            
            email.setSubject('Expense Report for '+submitter.Name);
            email.setToAddresses( toAddresses );
            email.setPlainTextBody( 'Attached is the expense report for '+submitter.Name+' for the month ending '
                                    +exp.Month_Ending__c+'. The receipts were too large to attach. They can be found here:'+
                                    ' http://na6.salesforce.com/'+exp.Id);                                       
            if(attachments.size()>0) email.setFileAttachments(attachments);
            
            if (!Test.isRunningTest()) {
            	Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
            }
        }
        
    }
    public PageReference Cancel() {
        submitApproval.app_rej(exp.Id, 'Rejected.', 'Reject');
        
        PageReference expRep = new PageReference('/' + ApexPages.currentPage().getParameters().get('id'));
        expRep.setRedirect(true);

        return expRep;
    }
    public static testmethod void approveTest() {
        User su = [select Id, ManagerId from User where Name = 'System User'];
  //    User bvm = [select Id from User where Name = 'Brian von Moos'];
        ER__c er = new ER__c(User__c = su.Id, Month_Ending__c = System.today(), Receipts_Attached__c = true);
        insert er;           
        
        
        User owner = [select Id from User where Name = 'System User'];
        Account acc = new Account(Name = 'Knight - 2456',Type = 'Customers',
                            Job_Type__c = 'Residential', Branch__c = 'Berkeley', 
                            Project_End_Date__c = null, ShippingCity = 'Petaluma'); 
        insert acc;
        
        
        Opportunity opp = new Opportunity(OwnerId = owner.Id, Name = 'Knight - 2456',AccountId = acc.Id,
                                    Type = 'Turnkey System',CloseDate = System.today(), StageName = 'Prospecting'); 
        insert opp;
        
        SFDC_project__c[] proj = new SFDC_project__c[0];
        proj.add(new SFDC_project__c(Name = 'Knight - 2456',Opportunity__c = opp.Id, Account__c = acc.Id, SFDC_Project_Stage__c = 'Sales', 
                                        Interconnection_Status__c = 'Submitted', Rebate_Status__c = null, SFDC_Project_End_Date__c = null, 
                                        Job_Number__c = '000-000', OwnerId = owner.Id)); 
        insert proj;
        
        
        ELI__c[] eli = new ELI__c[0];
        eli.add(new ELI__c(Expense_Header__c = er.Id, PV_Direct__c = true,Project__c=proj[0].id));
        eli.add(new ELI__c(Expense_Header__c = er.Id,Project__c=proj[0].id));
        insert eli;
        Blob b = Blob.valueOf('toast and jam');
        Attachment att = new Attachment(Name = 'Cheese!', ParentId = eli[0].Id, Body = b); insert att;
                            
        PageReference pageRef = Page.approveELI;
        Test.setCurrentPage(pageRef);
        
        ApexPages.currentPage().getParameters().put('id', er.Id);
        approveELI controller = new approveELI();
   /*       System.runAs(bvm){
                controller.getEli();
            } */
            controller.getEli();
            controller.getER();
            
            System.runAs(su){ 
                PageReference result2 = controller.Save();
            }
            PageReference result4 = controller.Save();
             
            PageReference result = controller.SaveAll();
             
            PageReference result3 = controller.Cancel();
            
            submitApproval.submit(er.Id, 'Approve');
            submitApproval.app_rej(er.Id, 'Rejected.', 'Reject');
                                  
    }    
     Public Static Boolean IsRecursiveUpdate{ get; set;}
     Public Static Boolean IsOpportunityLineItemUpdating{ get; set;}
}