objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Area_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to user record to identify Area Supervisor on a contract</description>
        <inlineHelpText>Area Supervisor on the contract</inlineHelpText>
        <label>Area Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Amount__c</fullName>
        <inlineHelpText>Total yearly amount of the service contract.</inlineHelpText>
        <label>Contract Amount (yearly)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Does_Contract_Auto_Renew__c</fullName>
        <description>indicate whether contract will auto-renew</description>
        <inlineHelpText>indicate whether contract will auto-renew</inlineHelpText>
        <label>Does Contract Auto Renew?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regional_Manager_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to user record to identify Regional Manager on a contract</description>
        <inlineHelpText>Regional manager on the contract</inlineHelpText>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract_Start_Date__c</fullName>
        <inlineHelpText>The date that the service contract starts.</inlineHelpText>
        <label>Service Contract Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Service_Contract_Escalator__c.object
<CustomObject>
    <description>stores escalator values for each year of service contract</description>
    <fields>
        <fullName>CurrentYearContractValue__c</fullName>
        <description>shows value of contract in current year with escalators applied - updated via trigger or WF</description>
        <inlineHelpText>shows value of contract in current year with escalators applied</inlineHelpText>
        <label>Current Year Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Contract_Start_Date__c</fullName>
        <description>displays Service Contract Start Date from related Contract</description>
        <formula>Service_Contract__r.Service_Contract_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>displays Service Contract Start Date from related Contract</inlineHelpText>
        <label>Service Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <description>displays the related contract</description>
        <inlineHelpText>displays the related contract</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Contract Escalators</relationshipLabel>
        <relationshipName>Service_Contract_Escalators</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>enter in 4 digit year</description>
        <inlineHelpText>enter in 4 digit year</inlineHelpText>
        <label>Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Contract Escalator</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Contract Escalator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Escalators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Renewcontractsbatch_Test.cls
@isTest class Renewcontractsbatch_Test {
    @isTest static void test() {
        // Use isolation mode-- we need to make test data
        Account a = new Account(Name='ABC Training Trust',Branch__c='New England',Phone='24352535',Type='Other',Description='Updated');
        
        insert a;
         DateTime dT = System.now();
         Date endDate = date.newinstance(dT.year(), dT.month(), dT.day());  
        
        user userid = [select id from user where isactive=true  and department ='o&m' and title like '%Manager%' limit 1];

             
   Contract c=new Contract (Name='ABC Training Trust',AccountId=a.id,Description='Updated Test',Branch__c='New England',Contract_Status__c='Active',
                            Does_Contract_Auto_Renew__c='Yes',Contract_Amount__c=20000,ContractTerm=12,Service_Contract_Start_Date__c=Date.newInstance(2018,12,05),Enddate=endDate ,Status='NullVoid',Area_Supervisor__c=userid.id,Regional_Manager_User__c=userid.id);
    
    insert c;
        c.Contract_Amount__c=10000;
        update c;
     System.Test.startTest();
    
    RenewContractsbatch rf = new RenewContractsbatch();
    UpdateLaborfieldBatch lb=new UpdateLaborfieldBatch ();
    system.debug('The answer' +rf);
    Database.executeBatch(rf,1);
    Database.executeBatch(lb,1);
     System.Test.stopTest();
        

    }
    @isTest static void test1() {
    
         DateTime dT = System.now();
         Date endDate = date.newinstance(dT.year(), dT.month(), dT.day()); 
        
        user userid = [select id from user where isactive=true  and department ='o&m' and title like '%Manager%' limit 1];

             
     Account a = new Account(Name='ABC Training Trust',Branch__c='New England',Phone='24352535',Type='Other',Description='Updated');
       insert a; 
    Contract c1=new Contract (Name='ABC Training Trust',AccountId=a.id,Description='Updated Test',Branch__c='New England',Contract_Status__c='Active',
                            Does_Contract_Auto_Renew__c='No',Contract_Amount__c=20000,ContractTerm=12,Service_Contract_Start_Date__c=Date.newInstance(2019,04,05),Enddate=endDate ,Status='NullVoid',RecordTypeId='012340000007kck',Area_Supervisor__c=userid.id,Regional_Manager_User__c=userid.id);
    
    insert c1;
         c1.Contract_Amount__c=10000;
        update c1;
        
        
        system.debug('this is contract -->' +c1);
    Service_Contract_Escalator__c testescalator=new Service_Contract_Escalator__c();
      testescalator.Service_Contract__c=c1.id;
      testescalator.Year__c=1;
      testescalator.CurrentYearContractValue__c=20000;
      
    insert testescalator;
    
    Service_Contract_Escalator__c testescalator1=new Service_Contract_Escalator__c();
      testescalator1.Service_Contract__c=c1.id;
      testescalator1.Year__c=2;
      testescalator1.CurrentYearContractValue__c=30000;
       insert testescalator1;
    
    
        system.debug('this is service escalator'+testescalator);
    System.Test.startTest();
    UpdateContractfieldBatch uf=new UpdateContractfieldBatch();
        UpdateLaborfieldBatch lb=new UpdateLaborfieldBatch ();
        system.debug('this is update testclass-->' +uf);
    
    Database.executeBatch(uf);
         Database.executeBatch(lb,1);
        
    System.Test.stopTest();
    }
}