objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <inlineHelpText>What sector is the customer classified under? 
**Only for Customer Accounts**</inlineHelpText>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Residential - Multi-Unit</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Small Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Amount__c</fullName>
        <inlineHelpText>Total yearly amount of the service contract.</inlineHelpText>
        <label>Contract Amount (yearly)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Does_Contract_Auto_Renew__c</fullName>
        <description>indicate whether contract will auto-renew</description>
        <inlineHelpText>indicate whether contract will auto-renew</inlineHelpText>
        <label>Does Contract Auto Renew?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalator__c</fullName>
        <label>Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Labor_Escalator__c</fullName>
        <description>Labor rate escalator for this contract</description>
        <inlineHelpText>Labor rate escalator for this contract</inlineHelpText>
        <label>Labor Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MinimumBillableTravelTime__c</fullName>
        <description>Minimum number of hours billable per service visit. If 0, all travel time is billable</description>
        <inlineHelpText>Minimum number of hours billable per service visit. If 0, all travel time is billable</inlineHelpText>
        <label>Minimum Billable Travel Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_M_Package__c</fullName>
        <label>O&amp;M Package</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Preventative</fullName>
                </value>
                <value>
                    <fullName>Comprehensive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes.</description>
        <inlineHelpText>Hourly rate stated in contract</inlineHelpText>
        <label>Regional Manager Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Contract_Start_Date__c</fullName>
        <inlineHelpText>The date that the service contract starts.</inlineHelpText>
        <label>Service Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_1_OT__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes</description>
        <inlineHelpText>Hourly(OT) rate stated in contract</inlineHelpText>
        <label>Solar Electrician 1 - OT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_1__c</fullName>
        <defaultValue>105</defaultValue>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes.</description>
        <inlineHelpText>Hourly rate stated in contract</inlineHelpText>
        <label>Solar Electrician 1 Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_2_OT__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes</description>
        <inlineHelpText>Hourly(OT) rate stated in contract</inlineHelpText>
        <label>Solar Electrician 2 - OT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_2__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes.</description>
        <inlineHelpText>Hourly rate stated in contract</inlineHelpText>
        <label>Solar Electrician 2 Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Engineer__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes</description>
        <inlineHelpText>Hourly rate stated in contract</inlineHelpText>
        <label>Solar Engineer Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Service_Contract_Escalator__c.object
<CustomObject>
    <description>stores escalator values for each year of service contract</description>
    <fields>
        <fullName>Escalator__c</fullName>
        <description>displays escalator % from the field Escalator from related contract</description>
        <formula>Service_Contract__r.Escalator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>displays escalator % from the field Escalator from related contract</inlineHelpText>
        <label>Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Labor_Escalator__c</fullName>
        <description>Used to bring over Labor rate escalator from contract.</description>
        <inlineHelpText>Used to bring over Labor rate escalator from contract.</inlineHelpText>
        <label>Labor Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Service_Contract_Start_Date__c</fullName>
        <description>displays Service Contract Start Date from related Contract</description>
        <formula>Service_Contract__r.Service_Contract_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>displays Service Contract Start Date from related Contract</inlineHelpText>
        <label>Service Contract Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Contract Escalator</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Contract Escalator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Escalators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/servicecontractescalatorTestClass.cls
@isTest(seealldata=true)
public class servicecontractescalatorTestClass 
{
    static testMethod Void servicecontractescalatormethod() 
 {
      Account testrecord2 = new Account();
      testrecord2.Name='testaccount2';
      testrecord2.Branch__c='Mid-Atlantic';
      testrecord2.Phone='(609)-524-4500';
      testrecord2.Type='service';
      testrecord2.Industry='Electric Utilities';
      testrecord2.Job_Type__c='Private';
      testrecord2.Description='NY Community Solar - developer'; 
      insert testrecord2;
      user userid = [select id from user where isactive=true  and department ='o&m' and title like '%Manager%' limit 1];
      Contract testcontract= new Contract();
      testcontract.AccountId='0013000000LBRIs';
      testcontract.Description='test';
      testcontract.Contract_Status__c='Active';
      testcontract.Branch__c='New England';
      testcontract.O_M_Package__c='Reactive';
      testcontract.Does_Contract_Auto_Renew__c='Yes';
      testcontract.Service_Contract_Start_Date__c= Date.newinstance(2016, 11, 01);
      testcontract.ContractTerm=24;
      testcontract.EndDate= Date.newinstance(2018, 11, 02);
      testcontract.Contract_Amount__c=314.58; 
      testcontract.MinimumBillableTravelTime__c=0;
      testcontract.Status=' NullVoid';
      testcontract.Escalator__c=2;
      testcontract.Solar_Electrician_1_OT__c=100;
      testcontract.Labor_Escalator__c=2;
      testcontract.Solar_Electrician_1__c=100;
      testcontract.Solar_Electrician_2__c=200; 
      testcontract.Solar_Electrician_2_OT__c=100; 
      testcontract.Regional_Manager__c=100;
      testcontract.Solar_Engineer__c=100;
      testcontract.Solar_Engineer_OT__c=200; 
     testcontract.Area_Supervisor__c=userid.id;
     testcontract.Regional_Manager_User__c=userid.id;
      insert testcontract;
      
      
      
      Service_Contract_Escalator__c testescalator=new Service_Contract_Escalator__c();
      testescalator.Service_Contract__c=testcontract.id;
      testescalator.PriorYearContractValue__c=314.58;
      testescalator.CurrentYearContractValue__c=314.58;
      testescalator.Year__c=1;
      insert testescalator;
      
      
      String convertedamount=String.valueOf(testcontract.Contract_Amount__c);
      String convertedsolarrate1=String.valueOf(testcontract.Solar_Electrician_1__c);
      String convertedsolarotrate1=String.valueOf(testcontract.Solar_Electrician_1_OT__c);
      String convertedsolarrate2=String.valueOf(testcontract.Solar_Electrician_2__c);
      String convertedsolarotrate2=String.valueOf(testcontract.Solar_Electrician_2_OT__c);
      String convertedregionalmanagerrate=String.valueOf(testcontract.Regional_Manager__c);
      String convertedsolarengineerrate=String.valueOf(testcontract.Solar_Engineer__c);
      String convertedsolarengineerotrate=String.valueOf(testcontract.Solar_Engineer_OT__c);
      
      
      Test.startTest();
      servicecontractescalator.createEscalators(testcontract.id,testcontract.ContractTerm,convertedamount, testcontract.Escalator__c,convertedsolarrate1,testcontract.Labor_Escalator__c,convertedsolarotrate1,convertedsolarrate2,convertedsolarotrate2,convertedregionalmanagerrate,convertedsolarengineerrate,convertedsolarengineerotrate,2);
      updateservicecontractescalator.createEscalators(testcontract.id,testcontract.ContractTerm,convertedamount, testcontract.Escalator__c,convertedsolarrate1,testcontract.Labor_Escalator__c,convertedsolarotrate1,convertedsolarrate2,convertedsolarotrate2,convertedregionalmanagerrate,convertedsolarengineerrate,convertedsolarengineerotrate);
      testcontract.EndDate=Date.newinstance(2020,11, 02);
      Update testcontract;
      Test.stopTest();
      
      
     
      
             }
}