objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <inlineHelpText>What sector is the customer classified under? 
**Only for Customer Accounts**</inlineHelpText>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Residential - Multi-Unit</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Small Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related opportunity from which the assets were created.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <formula>Contract__r.Project_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Project End date on the related project.</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <formula>ASProject__r.SFDC_Project_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The date on which the related project is set to end.</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Monthly_Production__c.object
<CustomObject>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>January</fullName>
                </value>
                <value>
                    <fullName>February</fullName>
                </value>
                <value>
                    <fullName>March</fullName>
                </value>
                <value>
                    <fullName>April</fullName>
                </value>
                <value>
                    <fullName>May</fullName>
                </value>
                <value>
                    <fullName>June</fullName>
                </value>
                <value>
                    <fullName>July</fullName>
                </value>
                <value>
                    <fullName>August</fullName>
                </value>
                <value>
                    <fullName>September</fullName>
                </value>
                <value>
                    <fullName>October</fullName>
                </value>
                <value>
                    <fullName>November</fullName>
                </value>
                <value>
                    <fullName>December</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000}</displayFormat>
        <label>Monthly Production Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Productions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>State used for reporting and allocation</description>
        <inlineHelpText>State used for reporting and allocation</inlineHelpText>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Branch value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Opportunities (Branch)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Government - Small</fullName>
                </value>
                <value>
                    <fullName>Utility Scale</fullName>
                </value>
                <value>
                    <fullName>ES Ground</fullName>
                </value>
                <value>
                    <fullName>Non ES Ground</fullName>
                </value>
                <value>
                    <fullName>ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Non ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>DG Solar</fullName>
                </value>
                <value>
                    <fullName>DG Wind</fullName>
                </value>
                <value>
                    <fullName>DG SAS</fullName>
                </value>
                <value>
                    <fullName>LSR PV</fullName>
                </value>
                <value>
                    <fullName>Bulk ES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Production_Update__c.object
<CustomObject>
    <description>These are system production updates that are given to us from customers.</description>
    <fields>
        <fullName>H_Total__c</fullName>
        <description>Total hours inverter has been running</description>
        <label>H-Total</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inverter__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Production Updates</relationshipLabel>
        <relationshipName>PUps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Irradiance__c</fullName>
        <label>Irradiance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Production__c</fullName>
        <label>Monthly Production</label>
        <referenceTo>Monthly_Production__c</referenceTo>
        <relationshipLabel>Production Updates</relationshipLabel>
        <relationshipName>Production_Updates</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Date__c</fullName>
        <description>Date that update was read off inverter</description>
        <label>Read Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Temperature__c</fullName>
        <label>Temperature (degrees F)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>kWh_lifetime__c</fullName>
        <description>Number of kWh from inverter report</description>
        <label>kWh (lifetime)</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Production Update</label>
    <nameField>
        <label>Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/prodUpdate.cls
public class prodUpdate {
    private Monthly_Production__c mPs;
    public prodUpdate(ApexPages.StandardController stdController) {
        this.mPs = (Monthly_Production__c)stdController.getRecord();
    }
    
    public List<Production_Update__c> puList;  // list of components to appear in the multi-line
    public PageReference reset() {
        puList = [select kWh_lifetime__c, Report_Date__c, Inverter__c, H_Total__c, Temperature__c, Irradiance__c from Production_Update__c
                           where Monthly_Production__c = :System.currentPageReference().getParameters().get('id')];
        return null;
    }             
    public List<Production_Update__c> getPUs() {
        if(puList == null) reset(); 
        return puList;
    }
    public void setComponents(List<Production_Update__c> PUs) {
        puList = PUs;
    }
    public PageReference add() {
        puList.add(New Production_Update__c(Monthly_Production__c = ApexPages.currentPage().getParameters().get('id')));
        return null;
    }
    public PageReference saves() {
        if (ApexPages.currentPage().getParameters().get('id') != null){
            Monthly_Production__c mp = [select Id from Monthly_Production__c where Id = :ApexPages.currentPage().getParameters().get('id')];
            update mp;         
            upsert puList;
        } else {
            insert mPs;
            for (Integer i = 0; i <puList.size(); i++) {
                puList[i].Monthly_Production__c = mPs.Id;
            }
            insert puList;
        }
        PageReference newcontact = new PageReference('/' + mPs.Id);
        newcontact.setRedirect(true);
        return newcontact;
    }
    public static testMethod void prodTest(){
    
    Account acc = new Account(Name = 'Knight - 2456',Type = 'Customers',Job_Type__c = 'Residential',Branch__c = 'Berkeley', 
                                     Project_End_Date__c = null, ShippingCity = 'Park City'); insert acc;
    Contract c = new Contract(AccountId = acc.Id); insert c;
    Monthly_Production__c mp = new Monthly_Production__c(Month__c = 'January'); insert mp;
    
   List<Asset> LA = [select Id from Asset LIMIT 1];
    Asset a;
    
    IF(LA!=null && LA.Size()>0)
      a=LA[0];
    /*   
      Opportunity Opp=new Opportunity(Name = 'Test Opportunity',StageName='Contract Signed',CloseDate=System.today() ); Insert Opp;
    Product2 P=[SELECT ID FROM PRODUCT2 WHERE Family='Inverters' LIMIT 1];
    Asset a =new Asset();
    a.Account=acc;
    a.Name = 'Test Asset';
    a.Opportunity__c=Opp.ID;
    a.Product2=P ;
    Insert a; */
    
    List<Production_Update__c> PUs = new List<Production_Update__c>();
     IF (a!=null){
        Production_Update__c PU= new Production_Update__c( kWh_lifetime__c = 1000, Report_Date__c = System.today(), Monthly_Production__c = mp.Id);
   
        PU.Inverter__c = a.Id;
        PUs.add(PU);
        }

        
    PageReference pageRef = Page.contractReq;
        Test.setCurrentPage(pageRef);
        
        //Set Page Parameters
        ApexPages.StandardController con = new ApexPages.StandardController(new Monthly_Production__c());
        prodUpdate ext = new prodUpdate(con);
        
        ext = new prodUpdate(con);  
        //Call all methods on New page 
        ext.setComponents(PUs);
        ext.getPUs();
        PageReference result = ext.saves();
        PageReference result1 = ext.add();
        PageReference result2 = ext.reset();
        
        ApexPages.currentPage().getParameters().put('id', mp.Id);
        ext = new prodUpdate(con);  
        //Call all methods on New page 
        ext.setComponents(PUs);
        ext.getPUs();
        PageReference result4 = ext.add();
    //    PageReference result3 = ext.saves();     
        PageReference result5 = ext.reset(); 
    }
}