objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Subcontractor Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bird Spikes</fullName>
                </value>
                <value>
                    <fullName>Signage</fullName>
                </value>
                <value>
                    <fullName>Boring</fullName>
                </value>
                <value>
                    <fullName>Carport installation</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Demolition</fullName>
                </value>
                <value>
                    <fullName>Electrical</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>EV Stations</fullName>
                </value>
                <value>
                    <fullName>Exploratory Excavations</fullName>
                </value>
                <value>
                    <fullName>Fencing</fullName>
                </value>
                <value>
                    <fullName>Fire Control</fullName>
                </value>
                <value>
                    <fullName>Third-Party Inspection/Testing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Roofer</fullName>
                </value>
                <value>
                    <fullName>Temp Labor</fullName>
                </value>
                <value>
                    <fullName>UG Utilities</fullName>
                </value>
                <value>
                    <fullName>MV</fullName>
                </value>
                <value>
                    <fullName>Mechanical</fullName>
                </value>
                <value>
                    <fullName>Site Services</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Landscaping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>Choose what type of asset.
Note: need to edit validation rule &quot;Storage Project Battery Only&quot; any time a new picklist value is added</description>
        <inlineHelpText>Choose what type of asset</inlineHelpText>
        <label>Asset Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Asset_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The service contract associated with the Asset</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>ServiceContract_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related service contract # for account which this case was opened.</inlineHelpText>
        <label>Service Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Landscaping</fullName>
        <active>true</active>
        <businessProcess>Landscaping%2FWashing</businessProcess>
        <description>used by O&amp;M team to scheudule landscaping</description>
        <label>Landscaping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <businessProcess>Project</businessProcess>
        <description>One-off projects such as due diligence visits, retrofits/rebuilds, DAS replacements</description>
        <label>Project</label>
    </recordTypes>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <businessProcess>Warranty</businessProcess>
        <description>for all cases that are under Borrego Warranty</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CaseServiceVisitRecordTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of allowed Service Visit record types based upon the related Case record type.</description>
    <fields>
        <fullName>Asset_Selection__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Asset Selection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Visit_Record_Types__c</fullName>
        <label>Service Visit Record Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CaseServiceVisitRecordTypes</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <description>Used to track warranty claims for all projects</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Dynamic_Field_Id_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>SV_Account__c</fullName>
        <label>SV.Account</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_Asset__c</fullName>
        <label>SV.Asset</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_Case__c</fullName>
        <label>SV.Case</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_ContractType__c</fullName>
        <label>SV.ContractType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_Contract__c</fullName>
        <label>SV.Contract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SV_Project__c</fullName>
        <label>SV.Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dynamic Field Id Setting</label>
</CustomObject>

objects/MaintenanceCaseServiceVisits__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Information about the Service Visit records that are automatically created when a Maintenance Case is created.</description>
    <fields>
        <fullName>Default_Technician_Id__c</fullName>
        <inlineHelpText>Id of the Contact record to be used for the Technician__c field on the new Service Visit record.</inlineHelpText>
        <label>Default Technician Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Visit_Record_Type__c</fullName>
        <label>Service Visit Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MaintenanceCaseServiceVisits</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>DAS</fullName>
        <active>true</active>
        <description>All data acquisition and display kiosk related hardware and software</description>
        <label>DAS</label>
    </recordTypes>
    <recordTypes>
        <fullName>Inverter</fullName>
        <active>true</active>
        <description>DC to AC inverters- Central, Micro</description>
        <label>Inverter</label>
    </recordTypes>
    <recordTypes>
        <fullName>Miscellaneous</fullName>
        <active>true</active>
        <description>Hardware and materials specified by BSS but not covered in other categories</description>
        <label>Miscellaneous</label>
    </recordTypes>
    <recordTypes>
        <fullName>Racking</fullName>
        <active>true</active>
        <description>Industry Solar Racking solutions and BSS solutions</description>
        <label>Racking</label>
    </recordTypes>
    <recordTypes>
        <fullName>Transformer</fullName>
        <active>true</active>
        <label>Transformer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>shows type of asset from related Asset record</description>
        <formula>TEXT(Asset__r.Component_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>shows type of asset from related Asset record</inlineHelpText>
        <label>Asset Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>used for all Non-Reactive, Non-PM Service Visits</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Asset_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AC Panel Cabinet</fullName>
    </customValue>
    <customValue>
        <fullName>Battery Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Battery Enclosure</fullName>
    </customValue>
    <customValue>
        <fullName>BOP</fullName>
    </customValue>
    <customValue>
        <fullName>Central Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Combiner</fullName>
        <label>Combiner Box</label>
    </customValue>
    <customValue>
        <fullName>Communication Cabinet</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Module</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Racking</fullName>
    </customValue>
    <customValue>
        <fullName>Roof</fullName>
    </customValue>
    <customValue>
        <fullName>Solar Array</fullName>
    </customValue>
    <customValue>
        <fullName>String Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Switch Gear</fullName>
    </customValue>
    <customValue>
        <fullName>Tracker</fullName>
    </customValue>
    <customValue>
        <fullName>Transformer</fullName>
    </customValue>
    <customValue>
        <fullName>Weather Station</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Inverter</fullName>
        <isActive>false</isActive>
        <label>Inverter</label>
    </customValue>
    <masterLabel>Asset Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/testNewServiceVisitController.cls
@isTest
private class testNewServiceVisitController {
	
	/*
	 *	Test methods for NewServiceVisitController
	 *
	 */
	
	// Create test data
	@testSetup static void nsvTestData() {
		
		Dynamic_Field_Id_Setting__c fieldIds = new Dynamic_Field_Id_Setting__c(
    		SetupOwnerId = UserInfo.getOrganizationId(),
    		SV_Account__c = 'field1',
    		SV_Case__c = 'field2',
    		SV_Contract__c = 'field3',
    		SV_Project__c = 'field4',
    		SV_ContractType__c = 'field5',
    		SV_Asset__c = 'field6'
    	);
    	insert fieldIds;
    	
    	Account acc = new Account(Name = 'nsvAccount');
    	insert acc;
    	
    	Contact con = new Contact(FirstName = 'Generic', LastName = 'Technician', Title = 'Solar Tech', AccountId = acc.Id);
    	insert con;
    	
    	List<MaintenanceCaseServiceVisits__c> mcsvList = new List<MaintenanceCaseServiceVisits__c>();
    	mcsvList.add(new MaintenanceCaseServiceVisits__c(Name = 'BOP', Default_Technician_Id__c = con.Id, Service_Visit_Record_Type__c = 'PM-Site Grounds'));
    	mcsvList.add(new MaintenanceCaseServiceVisits__c(Name = 'Combiner', Default_Technician_Id__c = con.Id, Service_Visit_Record_Type__c = 'PM-Combiner Box'));
    	mcsvList.add(new MaintenanceCaseServiceVisits__c(Name = 'Communication Cabinet', Default_Technician_Id__c = con.Id, Service_Visit_Record_Type__c = 'PM-Communication Cabinet'));
    	mcsvList.add(new MaintenanceCaseServiceVisits__c(Name = 'DAS', Default_Technician_Id__c = con.Id, Service_Visit_Record_Type__c = 'PM-Weather Station/DAS'));
    	mcsvList.add(new MaintenanceCaseServiceVisits__c(Name = 'Inverter', Default_Technician_Id__c = con.Id, Service_Visit_Record_Type__c = 'PM-Inverters'));
    	mcsvList.add(new MaintenanceCaseServiceVisits__c(Name = 'Solar Array', Default_Technician_Id__c = con.Id, Service_Visit_Record_Type__c = 'PM-Solar Array'));
    	mcsvList.add(new MaintenanceCaseServiceVisits__c(Name = 'Switch Gear', Default_Technician_Id__c = con.Id, Service_Visit_Record_Type__c = 'PM-MV Switchgear'));
    	mcsvList.add(new MaintenanceCaseServiceVisits__c(Name = 'Transformer', Default_Technician_Id__c = con.Id, Service_Visit_Record_Type__c = 'PM-Transformers'));
    	insert mcsvList;
    	
    	List<CaseServiceVisitRecordTypes__c> csvrtList = new List<CaseServiceVisitRecordTypes__c>();
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Construction Closeout', Asset_Selection__c = false, Service_Visit_Record_Types__c = 'Other'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Addtional Services', Asset_Selection__c = true, Service_Visit_Record_Types__c = 'Reactive'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Inspection', Asset_Selection__c = true, Service_Visit_Record_Types__c = 'Reactive'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Landscaping', Asset_Selection__c = false, Service_Visit_Record_Types__c = 'Other'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Maintenance Case', Asset_Selection__c = true, Service_Visit_Record_Types__c = 'PM-Combiners;PM-Inverters;PM-Modules;PM-MV Switchgear;PM-Racking;PM-Site Grounds;PM-Transformers;PM-Weather Station/DAS;PM-Wireways/Conduit'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Module Washing', Asset_Selection__c = false, Service_Visit_Record_Types__c = 'Other'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'O&M Admin Support', Asset_Selection__c = false, Service_Visit_Record_Types__c = 'Other'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Operational Commissioning', Asset_Selection__c = false, Service_Visit_Record_Types__c = 'Other'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Performance Investigation', Asset_Selection__c = true, Service_Visit_Record_Types__c = 'Reactive'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Preoperational Commissioning', Asset_Selection__c = false, Service_Visit_Record_Types__c = 'Other'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Project', Asset_Selection__c = false, Service_Visit_Record_Types__c = 'Other'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Reactive', Asset_Selection__c = true, Service_Visit_Record_Types__c = 'Reactive'));
    	csvrtList.add(new CaseServiceVisitRecordTypes__c(Name = 'Warranty', Asset_Selection__c = true, Service_Visit_Record_Types__c = 'Reactive'));
    	insert csvrtList;
    	
    	Contract cntrct = new Contract(Name = 'nsvContract', AccountId = acc.Id, Type__c = 'O&M');
    	insert cntrct;
    	
    	Product2 p = new Product2(Name = 'Miscellaneous', IsActive = true);
    	insert p;
    	
    	Map<String, Schema.RecordTypeInfo> rtAssetMap = Schema.SObjectType.Asset.getRecordTypeInfosByName();
    	List<Asset> assetList = new List<Asset>();
    	assetList.add(new Asset(Name = 'nsvAsset1', AccountId = acc.Id, Product2Id = p.Id, RecordTypeId = rtAssetMap.get('Operations Asset').getRecordTypeId(), Contract__c = cntrct.Id, Component_Type__c = 'Transformer'));//modified by DK to fix Deployment Error
    	assetList.add(new Asset(Name = 'nsvAsset2', AccountId = acc.Id, Product2Id = p.Id, RecordTypeId = rtAssetMap.get('Operations Asset').getRecordTypeId(), Contract__c = cntrct.Id, Component_Type__c = 'BOP'));
    	insert assetList;
    	
    	Map<String, Schema.RecordTypeInfo> rtCaseMap = Schema.SObjectType.Case.getRecordTypeInfosByName();
    	Case testCase = new Case(AccountId = acc.Id, ServiceContract_Case__c = cntrct.Id, RecordTypeId = rtCaseMap.get('Maintenance Case').getRecordTypeId());
    	insert testCase;
	}
	
	static testMethod void nsvTest1() {
		ApexPages.StandardController std;
		NewServiceVisitController ctl;
		
		SV__c sv = new SV__c();
		Account testAccount = [select Id from Account];
		std = new ApexPages.StandardController(sv);
    	ApexPages.currentPage().getParameters().put('accId', testAccount.Id);
		ctl = new NewServiceVisitController(std);
		
		Case testCase = [select Id from Case];
    	std = new ApexPages.StandardController(sv);
    	ApexPages.currentPage().getParameters().put('caseId', testCase.Id);
		ctl = new NewServiceVisitController(std);
		ctl.initSelectLists();
		ctl.selectedRecordTypeId = ctl.recordTypeList[1].getValue();
		ctl.saveRecordType();
		
		List<Asset> assetList = new List<Asset>();
		assetList = [select Id from Asset];
		ctl.setselectedAsset(assetList[0].Id);
		String selectedAsset = ctl.getselectedAsset();
		ctl.saveAsset();
		
		std = new ApexPages.StandardController(sv);
    	ApexPages.currentPage().getParameters().put('assetId', assetList[0].Id);
		ctl = new NewServiceVisitController(std);
		ctl.initSelectLists();
		ctl.cancelServiceVisit();
	}
}