objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <inlineHelpText>What sector is the customer classified under? 
**Only for Customer Accounts**</inlineHelpText>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Residential - Multi-Unit</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Small Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>State used for reporting and allocation</description>
        <inlineHelpText>State used for reporting and allocation</inlineHelpText>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Branch value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Opportunities (Branch)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development_Only__c</fullName>
        <label>Non Revenue Generating Project</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_Bid_Date__c</fullName>
        <label>Expected Bid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Government - Small</fullName>
                </value>
                <value>
                    <fullName>Utility Scale</fullName>
                </value>
                <value>
                    <fullName>ES Ground</fullName>
                </value>
                <value>
                    <fullName>Non ES Ground</fullName>
                </value>
                <value>
                    <fullName>ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Non ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>DG Solar</fullName>
                </value>
                <value>
                    <fullName>DG Wind</fullName>
                </value>
                <value>
                    <fullName>DG SAS</fullName>
                </value>
                <value>
                    <fullName>LSR PV</fullName>
                </value>
                <value>
                    <fullName>Bulk ES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Sites__c</fullName>
        <description>used with roll up helper</description>
        <inlineHelpText>Manually entered # of Sites created in SF related to this opportunity</inlineHelpText>
        <label># of Sites</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PreSaleDesignAttchment__c.object
<CustomObject>
    <description>This object is used to add one checkbox in Attachment window for Presale design object</description>
    <fields>
        <fullName>AttachmentID__c</fullName>
        <description>This id points to related attachment</description>
        <label>Attachment ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkDesign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This points to work design field</description>
        <label>Working Design</label>
        <type>Checkbox</type>
    </fields>
    <label>PreSale Design Attchment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreSale Design Attchments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PSD__c.object
<CustomObject>
    <fields>
        <fullName>Job_Type__c</fullName>
        <formula>TEXT( Opportunity__r.Account.Job_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>The opportunity that the Pre-Sales Design is related too.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Sales Designs</relationshipLabel>
        <relationshipName>Pre_Sales_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Pre-Sales Design</label>
    <nameField>
        <displayFormat>P-SD-{000000}</displayFormat>
        <label>Pre-Sales Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Sales Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/clsPSDAttachmentView.cls
//Made inactive 8/7/2018 as part of 2018.07 b Sprint
//Was causing an issue when we were trying to get the Site Installation Type fields to match on the Oppty and Site.
//After removing that field from this Apex Class we realized we no longer need this functionality. 

public with sharing class clsPSDAttachmentView {

/*    Public Attachment Attch{get; Set;}
    
    Public PreSaleDesignAttchment__c  FileAttachment{get; set;}
    
    public Id AttachId;
    
    Public clsPSDAttachmentView (){
    
        List<Attachment> ListOfAttachment=[Select  BODY, BodyLength, ContentType, CreatedById
                            , CreatedDate, Id, IsDeleted, IsPrivate, LastModifiedById, LastModifiedDate
                            , Name, OwnerId, ParentId, SystemModstamp From Attachment 
                            where ID=:ApexPages.currentPage().getParameters().get('id')];
          AttachId=  ApexPages.currentPage().getParameters().get('id');    
                      
        IF(ListOfAttachment!=null && ListOfAttachment.size()>0){
        
            Attch=ListOfAttachment[0];
            List<PreSaleDesignAttchment__c > ListOfFileAttachment=[Select AttachmentID__c,id,WorkDesign__c
                                From PreSaleDesignAttchment__c where AttachmentID__c=:Attch.id];

            IF(ListOfFileAttachment!=null && ListOfFileAttachment.size()>0)            
                FileAttachment=ListOfFileAttachment[0];                
            else
                FileAttachment=new PreSaleDesignAttchment__c ();
            
       
        }
         
    
    }
    Public PageReference CancelAttach(){
    
    
    
        PageReference PR=new PageReference('/'+Attch.ParentId );
        
        PR.getParameters().Put('id',Attch.ParentId);
        PR.setRedirect(true);
        return PR;
    
    }
     Public PageReference EditAttachment(){
    
       // PageReference PageRef=new ApexPages.StandardController(TempCase);
       // return PageRef;
       return null; 
    }

    static testMethod void Test_clsPSDAttachmentView () {
            User owner = [select Id from User where Name = 'System User'];
        Account acc = new Account(Name = 'Knight - 2456',Type = 'Customers',
                            Job_Type__c = 'Residential', Branch__c = 'Berkeley', 
                            Project_End_Date__c = null, ShippingCity = 'Petaluma'); 
        insert acc;
        
        Opportunity opp = new Opportunity(OwnerId = owner.Id, Name = 'Knight - 2456',AccountId = acc.Id, of_Sites__c = 1,
                                    Type = 'Turnkey System',CloseDate = System.today(), StageName = 'Prospecting'); 
        insert opp;
        opp.StageName = 'Qualified';
        opp.Development_Only__c = 'No';
        opp.Expected_Bid_Date__c = system.today();
        update opp;
        PSD__C TempPSD=new PSD__c();//[Select ID From PSD__c LIMIT 1];
        TempPSD.Opportunity__c=Opp.Id;
        INSERT TempPSD;
            Attachment att=new Attachment();
            att.ParentId=TempPSD.ID;
            Blob attachBody = Blob.valueOf('attachment body');
            att.Name='Test';
            att.Body=attachBody ;
            insert att;
            
            PreSaleDesignAttchment__c PADA=NEW PreSaleDesignAttchment__c ();
            PADA.AttachmentID__c=att.ID;
            
            
        ApexPages.currentPage().getParameters().pUT('id',att.ID);
        clsPSDAttachmentView CPA=new clsPSDAttachmentView ();
        CPA.CancelAttach();
        CPA.EditAttachment();
    }
*/
}