objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Subcontractor Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bird Spikes</fullName>
                </value>
                <value>
                    <fullName>Signage</fullName>
                </value>
                <value>
                    <fullName>Boring</fullName>
                </value>
                <value>
                    <fullName>Carport installation</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Demolition</fullName>
                </value>
                <value>
                    <fullName>Electrical</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>EV Stations</fullName>
                </value>
                <value>
                    <fullName>Exploratory Excavations</fullName>
                </value>
                <value>
                    <fullName>Fencing</fullName>
                </value>
                <value>
                    <fullName>Fire Control</fullName>
                </value>
                <value>
                    <fullName>Third-Party Inspection/Testing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Roofer</fullName>
                </value>
                <value>
                    <fullName>Temp Labor</fullName>
                </value>
                <value>
                    <fullName>UG Utilities</fullName>
                </value>
                <value>
                    <fullName>MV</fullName>
                </value>
                <value>
                    <fullName>Mechanical</fullName>
                </value>
                <value>
                    <fullName>Site Services</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Landscaping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Dynamic_Field_Id_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Asset_Contract__c</fullName>
        <label>Asset.Contract</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_ProductWarrantyStartDate__c</fullName>
        <label>Asset.ProductWarrantyStartDate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_Project__c</fullName>
        <label>Asset.Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_ServiceVisitCase__c</fullName>
        <label>Asset.ServiceVisitCase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dynamic Field Id Setting</label>
</CustomObject>

objects/Pending_Work__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Associated_Service_Visit_to_Close__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Service Visit in which the Pending work item was addressed</inlineHelpText>
        <label>Associated Service Visit to Close</label>
        <referenceTo>SV__c</referenceTo>
        <relationshipLabel>Pending Work (Associated Service Visit to Close)</relationshipLabel>
        <relationshipName>Pending_Work1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Contract must be associated with the same Project as the Pending Work</errorMessage>
            <filterItems>
                <field>Contract.ASProject__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Display the Status of the Pending Work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>show how/where the pending work was created, used mostly in PB and VR</description>
        <inlineHelpText>show how/where the pending work was created</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Auto Created</fullName>
                </value>
                <value>
                    <fullName>Manual Creation SV</fullName>
                </value>
                <value>
                    <fullName>Manual Creation Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pending Work</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Pending Work Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pending Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Not In Use: See Reasons Not In Use-Requires approval from CC
Project Specific Approved: CC has approved this product for a specific job only
CC Approved for Sale: CC has approved the product
Standard: CC Approved plus installed on min of 2 jobs</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1- Standard</fullName>
                </value>
                <value>
                    <fullName>2- Conditionally Approved</fullName>
                </value>
                <value>
                    <fullName>3- Under Evaluation</fullName>
                </value>
                <value>
                    <fullName>4- Not in Use</fullName>
                    <default>true</default>
                    <label>4- Not in Use</label>
                </value>
                <value>
                    <fullName>5- O&amp;M In Use</fullName>
                </value>
                <value>
                    <fullName>6- O&amp;M Not In Use</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Miscellaneous</fullName>
        <active>true</active>
        <description>Hardware and materials specified by BSS but not covered in other categories</description>
        <label>Miscellaneous</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related account for the Service Contract.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The case on which the service visit was scheduled.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>auto checks off when all of the following fields have been completed:  Visit End Date, Billable?, Hours on Site, Travel Time.</inlineHelpText>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testAsset_ServiceVisitCtlExt.cls
@isTest
private class testAsset_ServiceVisitCtlExt {
    
    /*
     *  Test methods for Asset_ServiceVisitCtlExt
     *
     */
    
    // Create test data
    @testSetup static void asvTestData() {
        
        Dynamic_Field_Id_Setting__c fieldIds = new Dynamic_Field_Id_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            Asset_ServiceVisitCase__c = 'field1',
            Asset_Project__c = 'field2',
            Asset_Contract__c = 'field3',
            Asset_ProductWarrantyStartDate__c = 'field4'
        );
        insert fieldIds;
        
        Product2 p = new Product2(Name = 'Miscellaneous', IsActive = true);
        insert p;
        
        Account acc = new Account(Name = 'asvAccount');
        insert acc;
        Case cas = new Case(Status ='New', Priority = 'Medium', Origin = 'Email');
        insert cas;
        Contract cntrct = new Contract(Name = 'asvContract', AccountId = acc.Id, Type__c = 'O&M');
        insert cntrct;
        Map<id,SV__c> svMap=new Map<id,SV__c>();
        list<SV__c> svlist=new list<SV__c>();
        SV__c sv = new SV__c(Account__c = acc.Id, Contract__c = cntrct.Id,Case__c=cas.id);
        insert sv;
        sv.Completed__c=true;
        update sv;
        svMap.put(sv.id, sv);
        svlist.add(sv);
        Pending_Work__c pw=new Pending_Work__c();
        pw.Associated_Service_Visit_to_Close__c=sv.id;
        pw.Status__c='Open';
        insert pw;
        pw.Status__c='Assigned';
        update pw;
        //ServiceVisitService.caseBillingStatus(null,svMap,true,false,false,false);
        delete sv;
        undelete sv;
        
        
    }

    static testMethod void asvTest1() {
        
        SV__c sv = [select Id from SV__c ];
        
        ApexPages.StandardController std = new ApexPages.StandardController(sv);
        ApexPages.currentPage().getParameters().put('serviceVisitId', sv.Id);
        ApexPages.currentPage().getParameters().put('retURL', '/');
        Asset_ServiceVisitCtlExt ctl = new Asset_ServiceVisitCtlExt(std);
        
        ctl.initRecordTypes();
    }
}