objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Subcontractor Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bird Spikes</fullName>
                </value>
                <value>
                    <fullName>Signage</fullName>
                </value>
                <value>
                    <fullName>Boring</fullName>
                </value>
                <value>
                    <fullName>Carport installation</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Demolition</fullName>
                </value>
                <value>
                    <fullName>Electrical</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>EV Stations</fullName>
                </value>
                <value>
                    <fullName>Exploratory Excavations</fullName>
                </value>
                <value>
                    <fullName>Fencing</fullName>
                </value>
                <value>
                    <fullName>Fire Control</fullName>
                </value>
                <value>
                    <fullName>Third-Party Inspection/Testing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Roofer</fullName>
                </value>
                <value>
                    <fullName>Temp Labor</fullName>
                </value>
                <value>
                    <fullName>UG Utilities</fullName>
                </value>
                <value>
                    <fullName>MV</fullName>
                </value>
                <value>
                    <fullName>Mechanical</fullName>
                </value>
                <value>
                    <fullName>Site Services</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Landscaping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Landscaping</fullName>
        <active>true</active>
        <businessProcess>Landscaping%2FWashing</businessProcess>
        <description>used by O&amp;M team to scheudule landscaping</description>
        <label>Landscaping</label>
    </recordTypes>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <businessProcess>Project</businessProcess>
        <description>One-off projects such as due diligence visits, retrofits/rebuilds, DAS replacements</description>
        <label>Project</label>
    </recordTypes>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <businessProcess>Warranty</businessProcess>
        <description>for all cases that are under Borrego Warranty</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Area_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to user record to identify Area Supervisor on a contract</description>
        <inlineHelpText>Area Supervisor on the contract</inlineHelpText>
        <label>Area Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_First_Escalator_to_be_Applied__c</fullName>
        <label>Date of First Escalator to be Applied</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Escalator_Details__c</fullName>
        <label>Escalator Details</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Escalator_Details</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalator__c</fullName>
        <label>Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monitoring_Required__c</fullName>
        <description>Does the contract require that we monitor the site?</description>
        <inlineHelpText>Does the contract require that we monitor the site?</inlineHelpText>
        <label>Monitoring Required?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Options__c</fullName>
        <description>payment options will eventually auto-populate value on Billings and set off automated process, please make sure its accurate before activating contract.     SHOULD MATCH Billing Frequency field on RECURRING BILLING OBJECT and PAYMENT OPTIONS on Opportunity.</description>
        <inlineHelpText>payment options will eventually auto-populate value on Billings and set off automated process, please make sure its accurate before activating contract.</inlineHelpText>
        <label>Payment Options</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lump Sum</fullName>
                    <label>Anniversary in Advance</label>
                </value>
                <value>
                    <fullName>Anniversary Semi-Annual in Arrears</fullName>
                </value>
                <value>
                    <fullName>Annual - Jan to Dec in Advance</fullName>
                    <label>Annual in Advance - Jan to Dec</label>
                </value>
                <value>
                    <fullName>Arrears Per % of visits completed</fullName>
                </value>
                <value>
                    <fullName>Long-Term Multiple Years in Advance</fullName>
                    <label>Long-Term in Advance</label>
                </value>
                <value>
                    <fullName>Mid Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Monthly in Advance</fullName>
                </value>
                <value>
                    <fullName>Monthly in Arrears</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Advance</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Advance Equal Installments</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Arrears</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Arrears Equal Installments</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual in Advance</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual in Arrears</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regional_Manager_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to user record to identify Regional Manager on a contract</description>
        <inlineHelpText>Regional manager on the contract</inlineHelpText>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract_Tier__c</fullName>
        <description>describes levels of performance guarantee coverage on O&amp;M contracts</description>
        <inlineHelpText>Tier 1 = Borrego has a performance or availability guarantee in place 
Tier 2 = Reactive package 
Tier 3 = Basic package 
Tier 4 = Less than Basic package
Tier 10 = Not Currently Contracted or Warranty</inlineHelpText>
        <label>Service Contract Tier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 0</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4</fullName>
                </value>
                <value>
                    <fullName>Tier 10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <description>Used to track warranty claims for all projects</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ContractTypeCaseRecordTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A mapping of Contract Type__c to allowable Case record types.</description>
    <fields>
        <fullName>Case_Record_Types__c</fullName>
        <label>Case Record Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ContractTypeCaseRecordTypes</label>
</CustomObject>

objects/Dynamic_Field_Id_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Case_Branch__c</fullName>
        <label>Case.Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_ContractType__c</fullName>
        <label>Case.ContractType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Project__c</fullName>
        <label>Case.Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_ServiceContractCase__c</fullName>
        <label>Case.ServiceContractCase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dynamic Field Id Setting</label>
</CustomObject>

globalValueSets/Escalator_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Increases per calendar year</fullName>
    </customValue>
    <customValue>
        <fullName>Increases on anniversary date of contract</fullName>
    </customValue>
    <masterLabel>Escalator Details</masterLabel>
</GlobalValueSet>

globalValueSets/Yes_No.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>PM Only</fullName>
        <isActive>false</isActive>
        <label>PM Only</label>
    </customValue>
    <masterLabel>Yes/No</masterLabel>
</GlobalValueSet>

classes/testCase_ContractCtlExt.cls
@isTest
private class testCase_ContractCtlExt {
    
    /*
     *  Test methods for Case_ContractCtlExt
     *
     */
    
    // Create test data
    @testSetup static void ccTestData() {
        
        Dynamic_Field_Id_Setting__c fieldIds = new Dynamic_Field_Id_Setting__c(
            SetupOwnerId = UserInfo.getOrganizationId(),
            Case_ServiceContractCase__c = 'field1',
            Case_Project__c = 'field2',
            Case_Branch__c = 'field3',
            Case_ContractType__c= 'field4'
        );
        insert fieldIds;
        
       user userid = [select id from user where isactive=true  and department ='o&m' and title like '%Manager%' limit 1];
        
        List<ContractTypeCaseRecordTypes__c> ctcrtList = new List<ContractTypeCaseRecordTypes__c>();
        ctcrtList.add(new ContractTypeCaseRecordTypes__c(Name = 'Borrego Warranty', Case_Record_Types__c = 'Construction Closeout;Operational Commissioning;Preoperational Commissioning;Warranty'));
        ctcrtList.add(new ContractTypeCaseRecordTypes__c(Name = 'O&M', Case_Record_Types__c = 'Additional Services;Landscaping;Maintenance Case;Module Washing;Performance Investigation;Reactive'));
        ctcrtList.add(new ContractTypeCaseRecordTypes__c(Name = 'O&M and Warranty', Case_Record_Types__c = 'Additional Services;Landscaping;Maintenance Case;Module Washing;Performance Investigation;Reactive'));
        ctcrtList.add(new ContractTypeCaseRecordTypes__c(Name = 'O&M T&M', Case_Record_Types__c = 'Additional Services;Landscaping;Maintenance Case;Module Washing;Performance Investigation;Reactive'));
        ctcrtList.add(new ContractTypeCaseRecordTypes__c(Name = 'Project', Case_Record_Types__c = 'Project'));
        insert ctcrtList;
        
        Account acc = new Account(Name = 'ccAccount');
        insert acc;
        
        Contract cntrct = new Contract(Name = 'ccContract', Contract_Status__c = 'Active', Escalator__c = 2, Escalator_Details__c = 'Increases per calendar year', Date_of_First_Escalator_to_be_Applied__c = system.today(), Payment_Options__c = 'Monthly in Advance', AccountId = acc.Id, Type__c = 'O&M',Service_Contract_Tier__c='Tier 0',
      Monitoring_Required__c ='No',Area_Supervisor__c=userid.id,Regional_Manager_User__c=userid.id);
        insert cntrct;
    }
    
    static testMethod void ccTest1() {
        
        Contract cntrct = [select Id from Contract];
        
        ApexPages.StandardController std = new ApexPages.StandardController(cntrct);
        ApexPages.currentPage().getParameters().put('contractId', cntrct.Id);
        ApexPages.currentPage().getParameters().put('retURL', '/');
        Case_ContractCtlExt ctl = new Case_ContractCtlExt(std);
        
        ctl.initRecordTypes();
        ctl.selectedRecordTypeId = ctl.recordTypeList[1].getValue();
        ctl.saveRecordType();
    }
}