objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
        <label>GL Variable 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Accounts (GL Variable 1)</relationshipLabel>
        <relationshipName>AccountsGLAV1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
        <label>GL Variable 2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 2</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Accounts (GL Variable 2)</relationshipLabel>
        <relationshipName>AccountsGLAV2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
        <label>GL Variable 3</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 3</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Accounts (GL Variable 3)</relationshipLabel>
        <relationshipName>AccountsGLAV3</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Account_Payable_Line__c.object
<CustomObject>
    <description>Line item expense associated with an payable. The aggregation of multiple payable lines constitute a payable record.</description>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related PO Line for allocation of cost.</inlineHelpText>
        <label>Purchase Order Line</label>
        <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>Account Payable Lines</relationshipLabel>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Expense_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Upon posting a debit entry will be made to this account and a corresponding credit entry will be made to the AP Control account set in the Accounting Settings Tab or the AP Control Override indicated in the Account Payable Parent.</inlineHelpText>
        <label>Expense GL Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Expense</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Payable Lines</relationshipLabel>
        <relationshipName>Project_Payable_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
        <label>GL Variable 1</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Accounting Variable must have a Type of &quot;GL Account Variable 1&quot;.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Payable Lines (GL Variable 1)</relationshipLabel>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Sales Segment- defaults based on what is on the Project</inlineHelpText>
        <label>GL Variable 2</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Accounting Variable must have a Type of &quot;GL Account Variable 2&quot;.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 2</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Payable Lines (GL Variable 2)</relationshipLabel>
        <relationshipName>Account_Payable_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Ops Division- defaults based on what is listed on the Project</inlineHelpText>
        <label>GL Variable 3</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Accounting Variable must have a Type of &quot;GL Account Variable 3&quot;.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 3</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Payable Lines (GL Variable 3)</relationshipLabel>
        <relationshipName>Account_Payable_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payable Line</label>
    <nameField>
        <displayFormat>APL-{00000}</displayFormat>
        <label>Payable Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payable Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Accounting_Variable__c.object
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>Used to determine GL Account Variables 1-4 and Time Card Variables 1-2.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GL Account Variable 1</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 2</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 3</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 4</fullName>
                </value>
                <value>
                    <fullName>Time Card Variable 1</fullName>
                </value>
                <value>
                    <fullName>Time Card Variable 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__GL_Account__c.object
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>Denotes the major grouping for financial reporting.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                    <default>true</default>
                    <label>Expense</label>
                </value>
                <value>
                    <fullName>Balance Sheet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Service_Contract_Branch__c</fullName>
        <description>pulls in the O&amp;M Service Contract branch from the related Contract</description>
        <formula>TEXT(Contract__r.Branch__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>pulls in the O&amp;M Service Contract branch from the related Contract</inlineHelpText>
        <label>Service Contract Branch</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
        <label>GL Variable 1</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Accounting Variable must have a Type of &quot;GL Account Variable 1&quot; and must have a status of Active. One or more of these conditions have not been met.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
        <label>GL Variable 2</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Accounting Variable must have a Type of &quot;GL Account Variable 2&quot; and must have a status of Active. One or more of these conditions have not been met.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 2</value>
            </filterItems>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Project Tasks (GL Account Variable 2)</relationshipLabel>
        <relationshipName>Project_Tasks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Project the PO Line is for</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AccountPayableLineHandler.cls
/*
* Author: Madan (Forcebrain Developer)
* Date: Sept 7, 2017
* Description: Handler class of AP Line object trigger
*/
public Class AccountPayableLineHandler {
    public static void populateFields(List<AcctSeed__Account_Payable_Line__c> listNew) {
        Set<Id> setExpGLAccId = new Set<Id>();
        Set<Id> setPOLId = new Set<Id>();
        for(AcctSeed__Account_Payable_Line__c apl:listNew) {
            if(apl.AcctSeed__Expense_GL_Account__c != null) {
                setExpGLAccId.add(apl.AcctSeed__Expense_GL_Account__c);
            }
            
            if(apl.AcctSeedERP__Purchase_Order_Line__c != null) {
                setPOLId.add(apl.AcctSeedERP__Purchase_Order_Line__c);
            }
        }
        
        // Create Map of GL Account by Id
        Map<Id,AcctSeed__GL_Account__c> mapGLAccount = new Map<Id,AcctSeed__GL_Account__c>();
        if(setExpGLAccId.size() > 0) {
            mapGLAccount = new Map<Id,AcctSeed__GL_Account__c>(
                                        [Select Id,Name From AcctSeed__GL_Account__c 
                                            Where ID IN:setExpGLAccId]);
        }
        
        // Create Map of POL by Id
        Map<Id,AcctSeedERP__Purchase_Order_Line__c> mapPOL = new Map<Id,AcctSeedERP__Purchase_Order_Line__c>();
        if(setPOLId.size() > 0) {
            mapPOL = new Map<Id,AcctSeedERP__Purchase_Order_Line__c>(
                                        [Select Id, AcctSeedERP__Project__c, AcctSeedERP__Project__r.Service_Contract_Branch__c 
                                            From AcctSeedERP__Purchase_Order_Line__c 
                                            Where ID IN:setPOLId]);
        }
        
        
        // Create Map by Branch Name to Branch record
        Map<String,AcctSeed__Accounting_Variable__c> mapBranchByName = new Map<String,AcctSeed__Accounting_Variable__c>();
        for(AcctSeed__Accounting_Variable__c branch:[Select Id,Name,AcctSeed__Type__c From AcctSeed__Accounting_Variable__c 
                                                            Where AcctSeed__Type__c='GL Account Variable 1']) {
            mapBranchByName.put(branch.name,branch);
            if(branch.Name == 'Mid-Atlantic') {
                mapBranchByName.put('Mid Atlantic',branch);
            }
        }
        
        // set O&M Sales Segment and O&M Ops Division id from Accounting Variable records[Filter by name and Type]
        Id omSalesSegmentId, omOpsDivisionId;
        for(AcctSeed__Accounting_Variable__c accVariable:[Select Id,Name,AcctSeed__Type__c From AcctSeed__Accounting_Variable__c 
                                                        Where Name='O&M']) {
            if(accVariable.Name == 'O&M' && accVariable.AcctSeed__Type__c=='GL Account Variable 2') {
                omSalesSegmentId = accVariable.Id;
            } else if(accVariable.Name == 'O&M' && accVariable.AcctSeed__Type__c=='GL Account Variable 3') {
                omOpsDivisionId = accVariable.Id;
            }
        }
        
        for(AcctSeed__Account_Payable_Line__c apl:listNew) {
            if(apl.AcctSeed__Expense_GL_Account__c != null) {
                // If Starts with 1213
                if(mapGLAccount.get(apl.AcctSeed__Expense_GL_Account__c).Name.startsWith('1213')) {
                    // Set Branch lookup to Corporate Branch
                    apl.AcctSeed__GL_Account_Variable_1__c = mapBranchByName.get('Corporate').Id;
                    apl.AcctSeed__GL_Account_Variable_2__c = null;
                    apl.AcctSeed__GL_Account_Variable_3__c = null;
                    
                    /* Commented On client Request(Madan) - Sept 11, 2017
                    if(apl.AcctSeedERP__Purchase_Order_Line__c != null && 
                            mapPOL.containsKey(apl.AcctSeedERP__Purchase_Order_Line__c)) {
                        apl.AcctSeed__Project__c = mapPOL.get(apl.AcctSeedERP__Purchase_Order_Line__c).AcctSeedERP__Project__c;
                    } else {
                        apl.AcctSeed__Project__c = null;
                    }
                    */
                } else if(mapGLAccount.get(apl.AcctSeed__Expense_GL_Account__c).Name.startsWith('3700') ||
                            mapGLAccount.get(apl.AcctSeed__Expense_GL_Account__c).Name.startsWith('4300') || 
                            mapGLAccount.get(apl.AcctSeed__Expense_GL_Account__c).Name.startsWith('4301')) {
                    apl.AcctSeed__GL_Account_Variable_2__c = omSalesSegmentId;
                    apl.AcctSeed__GL_Account_Variable_3__c = omOpsDivisionId;
                    
                    /* Commented On client Request(Madan) - Sept 11, 2017
                    // Project Mapping
                    if(apl.AcctSeedERP__Purchase_Order_Line__c != null && 
                            mapPOL.containsKey(apl.AcctSeedERP__Purchase_Order_Line__c)) {
                        apl.AcctSeed__Project__c = mapPOL.get(apl.AcctSeedERP__Purchase_Order_Line__c).AcctSeedERP__Project__c;
                    } else {
                        apl.AcctSeed__Project__c = null;
                    }
                    */
                    
                    // Branch Mapping(Set Branch(GL Account Variable 1 on APL from APL => Project => Service Contract Branch))
                    if(apl.AcctSeedERP__Purchase_Order_Line__c != null && 
                            mapPOL.containsKey(apl.AcctSeedERP__Purchase_Order_Line__c) &&
                            apl.AcctSeed__Project__c != null &&
                            mapPOL.get(apl.AcctSeedERP__Purchase_Order_Line__c).AcctSeedERP__Project__r.Service_Contract_Branch__c != null
                            ) {
                        String branchName = mapPOL.get(apl.AcctSeedERP__Purchase_Order_Line__c).AcctSeedERP__Project__r.Service_Contract_Branch__c;
                        //System.debug('================branchName: ' + branchName);
                        if(mapBranchByName.containsKey(branchName)) {
                            apl.AcctSeed__GL_Account_Variable_1__c = mapBranchByName.get(branchName).Id;
                            apl.AcctSeed__Project_Task__c = null;
                            //System.debug('=============BRANCH SET:');
                        } else {
                            apl.AcctSeed__GL_Account_Variable_1__c = null;
                        }
                    } else {
                        apl.AcctSeed__GL_Account_Variable_1__c = null;
                    }
                }
            }
        }
    }
}