objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__Accounting_Type__c</fullName>
        <inlineHelpText>Used in filtered lookups for Accounts Payable and Billing screens to limit selection of Accounts to those marked as Customers or Vendors for use by Accounting.</inlineHelpText>
        <label>Accounting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Customer and Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Credit_Card_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This field denotes a credit card vendor. If checked this account will display in the credit card field filtered lookup on the expense object.</inlineHelpText>
        <label>Credit Card Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Subcontractor Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bird Spikes</fullName>
                </value>
                <value>
                    <fullName>Signage</fullName>
                </value>
                <value>
                    <fullName>Boring</fullName>
                </value>
                <value>
                    <fullName>Carport installation</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Demolition</fullName>
                </value>
                <value>
                    <fullName>Electrical</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>EV Stations</fullName>
                </value>
                <value>
                    <fullName>Exploratory Excavations</fullName>
                </value>
                <value>
                    <fullName>Fencing</fullName>
                </value>
                <value>
                    <fullName>Fire Control</fullName>
                </value>
                <value>
                    <fullName>Third-Party Inspection/Testing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Roofer</fullName>
                </value>
                <value>
                    <fullName>Temp Labor</fullName>
                </value>
                <value>
                    <fullName>UG Utilities</fullName>
                </value>
                <value>
                    <fullName>MV</fullName>
                </value>
                <value>
                    <fullName>Mechanical</fullName>
                </value>
                <value>
                    <fullName>Site Services</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Landscaping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>All Borrego Customers or Potential Customers</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>ALL MATERIAL VENDORS who we will submit a PO to- Major and Minor Components</description>
        <label>Vendor- Material</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Acct_Branch__c</fullName>
        <formula>TEXT(Account.Branch__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>branch that is associated with the Account related to the contract</inlineHelpText>
        <label>Account Branch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Amount__c</fullName>
        <inlineHelpText>Total yearly amount of the service contract.</inlineHelpText>
        <label>Contract Amount (yearly)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Service Job Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Costs_this_year__c</fullName>
        <inlineHelpText>The total amount of money spent on service cost for the current year.</inlineHelpText>
        <label>Service Costs (this year)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Schedule_months__c</fullName>
        <label>Service Frequency (months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related account for the Service Contract.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <description>Pulling picklist value from contract status from the service contract object. To help with a validation rule for con reqs</description>
        <formula>TEXT( Contract__r.Contract_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulling picklist value from contract status from the service contract object</inlineHelpText>
        <label>Contract Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Approximate Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Soiling__c</fullName>
        <description>what are the soil conditions at the site at the time of the visit</description>
        <inlineHelpText>what are the soil conditions at the site at the time of the visit</inlineHelpText>
        <label>Soiling</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Heavy</fullName>
                </value>
                <value>
                    <fullName>Light</fullName>
                </value>
                <value>
                    <fullName>Clean</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vegetation__c</fullName>
        <description>Allows for tracking of  grass/weed height when we go to site.</description>
        <inlineHelpText>grass/weed height</inlineHelpText>
        <label>Vegetation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>6&quot;</fullName>
                </value>
                <value>
                    <fullName>12&quot;</fullName>
                </value>
                <value>
                    <fullName>18&quot;</fullName>
                </value>
                <value>
                    <fullName>24&quot;</fullName>
                </value>
                <value>
                    <fullName>30&quot;</fullName>
                </value>
                <value>
                    <fullName>36&quot;+</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <inlineHelpText>The date on which the service visit is scheduled to occur/start.</inlineHelpText>
        <label>Visit Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Visit_Reason__c</fullName>
        <inlineHelpText>The reason or service that is being provided.</inlineHelpText>
        <label>Visit Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Module Wash</fullName>
                </value>
                <value>
                    <fullName>Landscape Maintenance</fullName>
                </value>
                <value>
                    <fullName>Scheduled Service Other</fullName>
                </value>
                <value>
                    <fullName>Reactive Service</fullName>
                </value>
                <value>
                    <fullName>Construction Closeout</fullName>
                </value>
                <value>
                    <fullName>Snow Removal</fullName>
                </value>
                <value>
                    <fullName>Preoperational commissioning</fullName>
                </value>
                <value>
                    <fullName>Operational commissioning</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Primary preventive maintenance</fullName>
                </value>
                <value>
                    <fullName>Secondary preventive maintenance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weather_Conditions__c</fullName>
        <description>what are the weather conditions at the site during visit.</description>
        <inlineHelpText>what are the weather conditions at the site during visit.</inlineHelpText>
        <label>Weather Conditions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sunny</fullName>
                </value>
                <value>
                    <fullName>Partly Sunny</fullName>
                </value>
                <value>
                    <fullName>Cloudy</fullName>
                </value>
                <value>
                    <fullName>Rainy</fullName>
                </value>
                <value>
                    <fullName>Snow</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ServiceCostsThisYearRollUp.cls
public class ServiceCostsThisYearRollUp {
	/*
	private ApexPages.StandardSetController setController;
	public String filterId {get; private set;}
	public Boolean isError {get; private set;}
	public Boolean isProcessed {get; private set;}
	private List<Id> svConIds = new List<Id>();
	public List<Contract> selectedSVCons {get; private set;}
	
	public ServiceCostsThisYearRollUp(ApexPages.StandardSetController setController) {
                                
        selectedSVCons = new List<Contract>();
        this.setController = setController;
        filterId = setController.getFilterId().subString(0,15);
        isError = FALSE;
        isProcessed = FALSE;
		for (Contract con : (Contract[])setController.getSelected()) {
			svConIds.add(con.Id);
		}
		
		if (svConIds.size() > 0) {
			selectedSVCons = [SELECT Id, ContractNumber, Project__c, Acct_Branch__c, Contract_Number__c, Type__c, Contract_Status__c, Service_Costs_this_year__c FROM Contract WHERE Id IN: svConIds];
		} else {
			isError = TRUE;
			ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.INFO, 'You must select at least one Service Contract.'));
		}
    }
    
    public PageReference rollupServiceCosts() {
        
         Savepoint sp = Database.setSavepoint();
        
        try {
            ServiceCostsThisYearRollUpUtility.rollUpServiceCosts(svConIds);
            selectedSVCons = [SELECT Id, ContractNumber, Project__c, Acct_Branch__c, Contract_Number__c, Type__c, Contract_Status__c, Service_Costs_this_year__c FROM Contract WHERE Id IN: svConIds];
            ApexPages.addmessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Service Costs (this year) has been recalculated for ' + svConIds.size() + ' Service Contracts.'));
            isProcessed = TRUE;   
        }
        catch (Exception ex) {
            Database.rollback(sp);
            ApexPages.addMessages(ex);
        }
        
        return null;
    }
    
    @IsTest(SeeAllData=true)
    public static void testServiceCostsThisYearRollUp() {
        List<Account> accounts = new List<Account>();
        
        accounts.add(
            new Account(
                Name = 'TOOTALOO',
                AcctSeed__Accounting_Type__c = 'Customer and Vendor',
                AcctSeed__Credit_Card_Vendor__c = true,
                ShippingCity = 'Park City'
            )
        );

        accounts.add(
            new Account(
                Name = 'LOOTJUNK',
                AcctSeed__Accounting_Type__c = 'Customer and Vendor',
                AcctSeed__Credit_Card_Vendor__c = true,
                ShippingCity = 'Park City'
            )
        );
        
        accounts.add(
            new Account(
                Name = 'JAMBONAROO',
                AcctSeed__Accounting_Type__c = 'Customer and Vendor',
                AcctSeed__Credit_Card_Vendor__c = true,
                ShippingCity = 'Park City'
            )
        );            
        insert accounts;
        
        accounts[0].AcctSeed__Accounting_Type__c = 'Vendor';
        accounts[1].AcctSeed__Accounting_Type__c = 'Vendor';
        accounts[2].AcctSeed__Accounting_Type__c = 'Vendor';
        update accounts;
        
        // Create a Service Contract and Service Visits
        List<Contract> svContracts = new List<Contract>();
        svContracts.add(
        	new Contract(
        		AccountId = accounts[0].Id,
        		Contract_Amount__c = 30000,
        		ContractTerm = 120,
        		Service_Schedule_months__c = 12
        	)
        );
        insert svContracts;
        
        List<SV__c> serviceVisits = new List<SV__c>();
        serviceVisits.add(
        	new SV__c(
        		Account__c = accounts[0].Id,
        		Visit_Date__c = system.today(),
        		Visit_Reason__c = 'Reactive Service',
        		Vegetation__c = '6"',
        		Soiling__c = 'Light',
        		Weather_Conditions__c = 'Sunny',
        		Cost__c = 500,
        		Status__c = 'Complete',
        		Contract__c = svContracts[0].Id,
        		Notes__c = 'This is a note'
        	)
        );
        serviceVisits.add(
        	new SV__c(
        		Account__c = accounts[0].Id,
        		Visit_Date__c = system.today(),
        		Visit_Reason__c = 'Reactive Service',
        		Vegetation__c = '6"',
        		Soiling__c = 'Light',
        		Weather_Conditions__c = 'Sunny',
        		Cost__c = 500,
        		Status__c = 'Complete',
        		Contract__c = svContracts[0].Id,
        		Notes__c = 'This is a note'
        	)
        );
        insert serviceVisits;
        
        ApexPages.StandardSetController setController = new ApexPages.StandardSetController(svContracts);
        ServiceCostsThisYearRollUp rusc = new ServiceCostsThisYearRollUp(setController);

        rusc.rollupServiceCosts();
        
    }
    */
}