objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <inlineHelpText>What sector is the customer classified under? 
**Only for Customer Accounts**</inlineHelpText>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Residential - Multi-Unit</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Small Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Small_Business_Type__c</fullName>
        <inlineHelpText>List any Small Business designations here</inlineHelpText>
        <label>Small Business Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Women Owned</fullName>
                </value>
                <value>
                    <fullName>HUBZone</fullName>
                </value>
                <value>
                    <fullName>Veteran Owned</fullName>
                </value>
                <value>
                    <fullName>Service Disabled Veteran Owned</fullName>
                </value>
                <value>
                    <fullName>8(a) Owned Disadvantaged</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Native American Owned</fullName>
                </value>
                <value>
                    <fullName>Minority Owned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Target_Market__c</fullName>
        <inlineHelpText>Select the target market of the Account- Only required on Customer Accounts</inlineHelpText>
        <label>Target Market</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Affordable Housing</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Brownfield / Landfill</fullName>
                </value>
                <value>
                    <fullName>Commercial / Industrial</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Energy Services Company (ESCO)</fullName>
                </value>
                <value>
                    <fullName>Equity Fund</fullName>
                </value>
                <value>
                    <fullName>Federal / GSA</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverage</fullName>
                </value>
                <value>
                    <fullName>Independent Power Broker</fullName>
                </value>
                <value>
                    <fullName>Lender</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
                <value>
                    <fullName>Municipal</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Tax Equity Provider</fullName>
                </value>
                <value>
                    <fullName>Utility-Scale Solar</fullName>
                </value>
                <value>
                    <fullName>Water District</fullName>
                </value>
                <value>
                    <fullName>Wholesale Distributed Generation (WDG)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <inlineHelpText>Regional office responsible for Project</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>North Carolina</fullName>
                </value>
                <value>
                    <fullName>Oregon</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>South Carolina</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <inlineHelpText>Project the line item is associated with- Automatically fills in when the line item is created from the Project</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Sales Order</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Sales_Order__c</fullName>
        <inlineHelpText>Sales Order associated with the requisition
Automatically gets entered when creating a req from the Project</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Line</relationshipLabel>
        <relationshipName>Sales_Order_Line</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Dynamic_Field_Id_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Sales_Order_Line_Ent__c</fullName>
        <label>Sales Order Line Ent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line_Project_Field_Id__c</fullName>
        <label>Sales Order Line Project Field Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Line_Sales_Order_Field_Id__c</fullName>
        <label>Sales Order Line Sales Order Field Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dynamic Field Id Setting</label>
</CustomObject>

classes/ConstructionReqControllerExtTest.cls
@isTest(seeAllData=true)
    public class ConstructionReqControllerExtTest {
    static void ConstructionReqControllerExtTest1() 
 {
        
        // Create test data
        Account vendorAccount = new Account(
            Branch__c = 'New England',
            Name = 'TESTvendor',
            Phone = '123-456-7890',
            Target_Market__c = 'Agriculture',
            Type = 'Customers',
            Job_Type__c = 'Private',
            Small_Business_Type__c = 'Veteran Owned',
            Description = 'This is a test',
            ShippingCity = 'San Francisco'
        );
        insert vendorAccount;

        AcctSeed__Project__c testProject = [SELECT Id, Name, AcctSeed__Opportunity__c, AcctSeed__Account__c FROM AcctSeed__Project__c WHERE Name =: 'Loft 27'];
        AcctSeed__Project_Task__c projectTask = [SELECT Id, Name, AcctSeed__Project__c FROM AcctSeed__Project_Task__c WHERE AcctSeed__Project__c =: testProject.Id AND Name =: 'Solar Modules'];
        AcctSeedERP__Sales_Order__c salesOrder = [SELECT Id, Name, Project__c FROM AcctSeedERP__Sales_Order__c WHERE Project__c =: testProject.Id];
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE Name =: 'Major Component'];
                
        // Add the parameters to our page
        Dynamic_Field_Id_Setting__c FieldIds = [SELECT Sales_Order_Line_Project_Field_Id__c, Sales_Order_Line_Sales_Order_Field_Id__c, Sales_Order_Line_Ent__c FROM Dynamic_Field_Id_Setting__c];
        ApexPages.currentPage().getParameters().put('CF' + FieldIds.Sales_Order_Line_Project_Field_Id__c, testProject.Id);
        ApexPages.currentPage().getParameters().put('CF' + FieldIds.Sales_Order_Line_Sales_Order_Field_Id__c, salesOrder.Id);
        ApexPages.currentPage().getParameters().put('ent', FieldIds.Sales_Order_Line_Ent__c);
        ApexPages.currentPage().getParameters().put('RecordType', rt.Id);
                
        //Instantiate a new controller to test the page
        AcctSeedERP__Sales_Order_Line__c conrequisition = new AcctSeedERP__Sales_Order_Line__c();
        ApexPages.StandardController std = new ApexPages.StandardController(conrequisition);
        ConstructionReqControllerExt ctl = new ConstructionReqControllerExt(std);
        ctl.initConstructionReq();
        List<SelectOption> opt = ctl.getProjProducts();
        ctl.requiredFieldSetForTest(testProject.AcctSeed__Account__c, projectTask.Id, vendorAccount.Id, opt[1].getValue());
        PageReference pr = ctl.saveMajorConstructionReq();
    } 
    }