objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <inlineHelpText>What sector is the customer classified under? 
**Only for Customer Accounts**</inlineHelpText>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Residential - Multi-Unit</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Small Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Con_Req__c.object
<CustomObject>
    <fields>
        <fullName>Project_PM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Project Manager
Automatically pulls from the Owner listed on the Project</inlineHelpText>
        <label>Project PM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N80000002yrRJEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Original product quantity
Referenced when updating or changing the product and quantity</inlineHelpText>
        <label>Original Quantity-old</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Visit</label>
        <referenceTo>SV__c</referenceTo>
        <relationshipName>Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the CO
Controlled by the approval process and recall button</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed by Customer</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Borrego Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>X - Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved By Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Cost_Tax__c</fullName>
        <formula>Sales_Tax__c +  Shipping__c +  Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Subcontractor Account
Must be an account in Salesforce</inlineHelpText>
        <label>Vendor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Change Orders (Vendor Account)</relationshipLabel>
        <relationshipName>Con_Req</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Order</label>
    <nameField>
        <displayFormat>SF-CR-{000000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <formula>ASProject__r.SFDC_Project_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The date on which the related project is set to end.</inlineHelpText>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <formula>TEXT(Contract__r.Branch__c)</formula>
        <inlineHelpText>pulls value from Branch field on related Service Contract</inlineHelpText>
        <label>Service Contract Branch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Approximate Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <inlineHelpText>The date on which the service visit is scheduled to occur/start.</inlineHelpText>
        <label>Visit Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/contractReq.cls
public class contractReq {
    private List<Con_Req__c> reqs = new List<Con_Req__c>();
    private List<Id> svId = new List<Id>();
    private Contract cntract; 
    public contractReq(ApexPages.StandardController controller) {
        this.cntract= (Contract)controller.getRecord();
    }
    public List<Con_Req__c> getReqs() {
        SV__c[] svs = [select Id from SV__c where Contract__c = :cntract.Id];
        for (Integer m = 0; m <svs.size(); m++) {
        	svId.add(svs[m].Id);
        }
        reqs = [select Id, Name, Status__c, Total_Cost_Tax__c, Project_PM__c, Service_Visit__c, RecordTypeId from Con_Req__c where Service_Visit__c in :svId];    
        if(reqs.size() > 0) {
        	return reqs;
        } else {
        	return null;
        }
    }
    public static testMethod void contractTest(){
    
    Account acc = new Account(Name = 'Knight - 2456',Type = 'Customers',Job_Type__c = 'Residential',Branch__c = 'Berkeley', 
    								 Project_End_Date__c = null, ShippingCity = 'Park City'); insert acc;
 	Contract c = new Contract(AccountId = acc.Id); insert c;
 	SV__c sv = new SV__c(Contract__c = c.Id, Visit_Date__c = System.Today(), Cost__c = 10.00); insert sv;
    Con_Req__c req = new Con_Req__c(Service_Visit__c = sv.Id, Vendor_Account__c = acc.Id, Quantity__c = 10.00, Unit_Price__c = 30); insert req;
    
    PageReference pageRef = Page.contractReq;
	    Test.setCurrentPage(pageRef);
	    
	    //Set Page Parameters
	    ApexPages.StandardController con = new ApexPages.StandardController(new Contract());
	    contractReq ext = new contractReq(con);
	    
	    ApexPages.currentPage().getParameters().put('id', c.Id);
	    ext = new contractReq(con);  
	    //Call all methods on New page 
			ext.getReqs();  
    }
}