objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Account_Payable__c.object
<CustomObject>
    <description>Used to document liabilities to outside vendor, contact, or employee.</description>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
        <relationshipLabel>Payables</relationshipLabel>
        <relationshipName>Accounts_Payable</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <formula>IF(AcctSeed__Total__c &lt; 0,&quot;Credit Memo&quot;, &quot;Invoice&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically determined by the sum of the Accounts Payable Lines. If total Accounts Payable lines are negative the document is a Credit Memo. If Positive then it is an Invoice.</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>An Account Payable can have either the Account (Vendor), Contact or User (Employee) as the Payee.  One object must be chosen.</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Vendor, Customer and Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Accounts Filtered on Accounting Type=Vendor and Accounting Active=True</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Project_Payable_Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Final_Invoice__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if this is the final invoice. Upon approval the corresponding PO will be updated. Only one Invoice can be marked &quot;Final Invoice&quot;.</inlineHelpText>
        <label>Final Invoice</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <inlineHelpText>Enter the total amount of the invoice here. Required upon creation or edit.</inlineHelpText>
        <label>Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NTE_PO__c</fullName>
        <formula>TEXT( Purchase_Order__r.Not_To_Exceed__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Not To Exceed field of the Purchase Order.</inlineHelpText>
        <label>NTE PO</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Filled out when an AP Invoice is created from a Purchase Order. References the PO the Invoice is paying. Only for Project related Invoices.</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
        <relationshipName>Accounts_Payable</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payable</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>AP_Invoice_Line_Total_CO_POL__c</fullName>
        <description>USE THIS</description>
        <formula>AP_Line_CO_Total__c + AP_Invoice_Line_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Amount of AP Invoices associated with the PO
Includes CO and PO Lines</inlineHelpText>
        <label>AP Invoice Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO_Total__c</fullName>
        <formula>Change_Order_Total__c + Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Amount of the Purchase Order
Includes CO&apos;s, Freight, Sales Tax</inlineHelpText>
        <label>PO Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountPayable_ApprovalCTL.cls
public with sharing class AccountPayable_ApprovalCTL {

	// Controller for the approval process approval page for object Account Payable
	
	public AcctSeed__Account_Payable__c apRecord {get; set;}
	public AcctSeedERP__Purchase_Order__c poRecord {get; set;}
	public String Comment {get; set;}
	public Boolean isPO {get; set;}
	Id apRecordId;
	ProcessInstanceWorkItem PIWI;
    List<ProcessInstanceWorkItem> workItemList = new List<ProcessInstanceWorkItem>();
    Id targetId;
    Boolean finalInvoice;
    
    public AccountPayable_ApprovalCTL() {
    	
    	// Get the Account Payable record and current approval process work item
    	apRecordId = ApexPages.currentPage().getParameters().get('apId');
    	apRecord = [select Id, Name, Owner.Name, AcctSeed__Vendor__c, Invoice_Amount__c, Final_Invoice__c, NTE_PO__c, Purchase_Order__c,AcctSeed__Type__c  
    				from AcctSeed__Account_Payable__c where Id = :apRecordId];
    	finalInvoice = apRecord.Final_Invoice__c;	// Current value of Final Invoice field - so we can later determine if the user has changed it
    	
    	if (apRecord.Purchase_Order__c != null) {
    		poRecord = [select Id, PO_Total__c, AP_Invoice_Line_Total_CO_POL__c from AcctSeedERP__Purchase_Order__c where Id = :apRecord.Purchase_Order__c];
    		isPO = true;
    	} else {
    		isPO = false;
    	}
    	workItemList = [select Id, ProcessInstance.TargetObjectId, ProcessInstanceId, OriginalActorId, ActorId 
					from ProcessInstanceWorkitem where Id = :ApexPages.currentPage().getParameters().get('id')];
        
		if (!workItemList.isEmpty()) {
            PIWI = workItemList[0];
            targetId = PIWI.ProcessInstance.TargetObjectId;
        }
    }
    
    private Pagereference goBack() {
		Pagereference pr = new Pagereference('/' + targetId);
		pr.SetRedirect(true);
		return pr;
	}
	
	public void doApprove() {
		Approval.Processworkitemrequest objReq = new Approval.Processworkitemrequest();
		objReq.setAction('Approve');
		objReq.setComments(Comment);
		objReq.setWorkitemId(PIWI.ID);
		objReq.setNextApproverIds(new Id[] {UserInfo.getUserId()});
		Approval.ProcessResult result2 =  Approval.process(objReq);   
	}
        
	public Pagereference cancel() {
		return goBack();
	}
	
	public PageReference reject() {
		if(String.isEmpty(comment)) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please provide reject reason in Comments Box!'));
			
			return null;
		}
		
		Approval.Processworkitemrequest objReq = new Approval.Processworkitemrequest();
		objReq.setAction('Reject');
		objReq.setComments(Comment);
		objReq.setWorkitemId(PIWI.Id);
		objReq.setNextApproverIds(new Id[] {UserInfo.getUserId()});
		Approval.ProcessResult result2 =  Approval.process(objReq);               
		return goBack();
	}
    
    public PageReference approve() {           
		
		// Update the AP Invoice if the Final Invoice field has changed
		if (finalInvoice != apRecord.Final_Invoice__c) {
			update apRecord;
		}
		doApprove();
		return goBack();
	}
}