objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Small_Business_Type__c</fullName>
        <inlineHelpText>List any Small Business designations here</inlineHelpText>
        <label>Small Business Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Women Owned</fullName>
                </value>
                <value>
                    <fullName>HUBZone</fullName>
                </value>
                <value>
                    <fullName>Veteran Owned</fullName>
                </value>
                <value>
                    <fullName>Service Disabled Veteran Owned</fullName>
                </value>
                <value>
                    <fullName>8(a) Owned Disadvantaged</fullName>
                </value>
                <value>
                    <fullName>Small Business</fullName>
                </value>
                <value>
                    <fullName>Native American Owned</fullName>
                </value>
                <value>
                    <fullName>Minority Owned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <label>Utility Company</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PG&amp;E</fullName>
                </value>
                <value>
                    <fullName>SCE</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E</fullName>
                </value>
                <value>
                    <fullName>NSTAR</fullName>
                </value>
                <value>
                    <fullName>National Grid</fullName>
                </value>
                <value>
                    <fullName>CPAU</fullName>
                </value>
                <value>
                    <fullName>SVP</fullName>
                </value>
                <value>
                    <fullName>Healdsburg</fullName>
                </value>
                <value>
                    <fullName>SMUD</fullName>
                </value>
                <value>
                    <fullName>AP+T</fullName>
                </value>
                <value>
                    <fullName>PSNH</fullName>
                </value>
                <value>
                    <fullName>IID</fullName>
                </value>
                <value>
                    <fullName>LADWP</fullName>
                </value>
                <value>
                    <fullName>Bear Valley Electric</fullName>
                </value>
                <value>
                    <fullName>GWP</fullName>
                </value>
                <value>
                    <fullName>Roseville Electric</fullName>
                </value>
                <value>
                    <fullName>Other - Northern CA</fullName>
                </value>
                <value>
                    <fullName>Other - Southern CA</fullName>
                </value>
                <value>
                    <fullName>Other - East Coast</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>Austin Energy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <inlineHelpText>Branch of the user.</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>North Carolina</fullName>
                </value>
                <value>
                    <fullName>Oregon</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>South Carolina</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>State used for reporting and allocation</description>
        <inlineHelpText>State used for reporting and allocation</inlineHelpText>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Branch value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Opportunities (Branch)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Lead_Source_Specifics__c</fullName>
        <inlineHelpText>A brief description of the specific lead source implemented to create this opportunity.</inlineHelpText>
        <label>Opportunity Lead Source Specifics</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Lead_Source__c</fullName>
        <inlineHelpText>Affiliate: formal partnership; Direct Marketing: direct mail/email campaign; Event/Tradeshow: our presence at an event; Formal RFP: an RFP we competed in; Prospected: PDs efforts; Referral/Repeat: an existing customer referred us or is giving new business</inlineHelpText>
        <label>Opportunity Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Anderson Optimization</fullName>
                </value>
                <value>
                    <fullName>Bid Boards</fullName>
                </value>
                <value>
                    <fullName>Customer Originated - Email</fullName>
                </value>
                <value>
                    <fullName>Customer Originated - Phone</fullName>
                </value>
                <value>
                    <fullName>Customer Originated - RFP</fullName>
                </value>
                <value>
                    <fullName>Customer Originated - Social Media</fullName>
                </value>
                <value>
                    <fullName>Customer Originated - Website</fullName>
                </value>
                <value>
                    <fullName>Direct Marketing Campaign</fullName>
                </value>
                <value>
                    <fullName>Event/Tradeshow</fullName>
                </value>
                <value>
                    <fullName>GIS Campaign</fullName>
                </value>
                <value>
                    <fullName>MQL notification</fullName>
                </value>
                <value>
                    <fullName>Prospected</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <label>Opportunity Utility Company</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PG&amp;E</fullName>
                </value>
                <value>
                    <fullName>SCE</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E</fullName>
                </value>
                <value>
                    <fullName>NSTAR</fullName>
                </value>
                <value>
                    <fullName>National Grid</fullName>
                </value>
                <value>
                    <fullName>TMLP</fullName>
                </value>
                <value>
                    <fullName>WMECO</fullName>
                </value>
                <value>
                    <fullName>Unitil</fullName>
                </value>
                <value>
                    <fullName>CPAU</fullName>
                </value>
                <value>
                    <fullName>SVP</fullName>
                </value>
                <value>
                    <fullName>Healdsburg</fullName>
                </value>
                <value>
                    <fullName>SMUD</fullName>
                </value>
                <value>
                    <fullName>AP+T</fullName>
                </value>
                <value>
                    <fullName>PSNH</fullName>
                </value>
                <value>
                    <fullName>IID</fullName>
                </value>
                <value>
                    <fullName>LADWP</fullName>
                </value>
                <value>
                    <fullName>Bear Valley Electric</fullName>
                </value>
                <value>
                    <fullName>GWP</fullName>
                </value>
                <value>
                    <fullName>Roseville Electric</fullName>
                </value>
                <value>
                    <fullName>Other - Northern CA</fullName>
                </value>
                <value>
                    <fullName>Other - Southern CA</fullName>
                </value>
                <value>
                    <fullName>Other - East Coast</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>Fitchburg Gas and Electric/Unitil</fullName>
                </value>
                <value>
                    <fullName>MetED</fullName>
                </value>
                <value>
                    <fullName>PNM</fullName>
                </value>
                <value>
                    <fullName>El Paso Electric</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>Indianapolis Power &amp; Light (IPL)</fullName>
                </value>
                <value>
                    <fullName>PREPA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ContactRollupCountTest.cls
@isTest 
public class ContactRollupCountTest
{
    static testMethod void testMethod1() 
    {
        
        Account acc = new Account();
        acc.Name ='Name';
        acc.Small_Business_Type__c='HUBZone';
        acc.Branch__c='Boston';
        acc.Type='Architect';
        acc.Description='Test desc';
        insert acc;
        
        Contact con=new Contact();
        con.Lastname='Test name';
        con.accountid=acc.id;
        insert con;
       
        opportunity opp= new Opportunity();
        opp.Name= 'Test opp';
        opp.closedate=date.today();
        opp.Stagename='Prospecting';
        opp.amount=100;
        opp.Accountid=acc.id;
        opp.Opportunity_Lead_Source__c='Affiliate';
        opp.Opportunity_Lead_Source_Specifics__c='Test desc';
        opp.Utility_Company__c='SCE';
        opp.Utility_Zone__c='A';
        opp.Estimated_PB3_Submission_Date__c=date.today();
        
        insert opp;
        
        Opportunitycontactrole ocr=new Opportunitycontactrole();
        ocr.Contactid=con.id;
        ocr.OpportunityId= opp.id;
        ocr.Role='Influencer';
        insert ocr;
        
        
        Test.startTest();

            ContactRollupCount obj = new ContactRollupCount();
            DataBase.executeBatch(obj); 
            ContactRollupCountscheduler sh1 = new ContactRollupCountscheduler();

            String sch = '0 0 23 * * ?'; 
            system.schedule('Test Check', sch, sh1); 

            
        Test.stopTest();
    }
}