objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Subcontractor Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bird Spikes</fullName>
                </value>
                <value>
                    <fullName>Signage</fullName>
                </value>
                <value>
                    <fullName>Boring</fullName>
                </value>
                <value>
                    <fullName>Carport installation</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Demolition</fullName>
                </value>
                <value>
                    <fullName>Electrical</fullName>
                </value>
                <value>
                    <fullName>Engineer</fullName>
                </value>
                <value>
                    <fullName>EV Stations</fullName>
                </value>
                <value>
                    <fullName>Exploratory Excavations</fullName>
                </value>
                <value>
                    <fullName>Fencing</fullName>
                </value>
                <value>
                    <fullName>Fire Control</fullName>
                </value>
                <value>
                    <fullName>Third-Party Inspection/Testing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Roofer</fullName>
                </value>
                <value>
                    <fullName>Temp Labor</fullName>
                </value>
                <value>
                    <fullName>UG Utilities</fullName>
                </value>
                <value>
                    <fullName>MV</fullName>
                </value>
                <value>
                    <fullName>Mechanical</fullName>
                </value>
                <value>
                    <fullName>Site Services</fullName>
                </value>
                <value>
                    <fullName>Civil</fullName>
                </value>
                <value>
                    <fullName>Landscaping</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>ServiceContract_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related service contract # for account which this case was opened.</inlineHelpText>
        <label>Service Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <description>Name of person who went to service the system.</description>
        <inlineHelpText>Personnel who worked on the problem on site. If no one goes to site</inlineHelpText>
        <label>Technician</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related account for the Service Contract.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The case on which the service visit was scheduled.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to specific Borrego Solar (O&amp;M) account, where all technicians should be listed as contacts</description>
        <inlineHelpText>individual who did the work, if unable to find, add the contact to the Borrego Solar (O&amp;M) account.</inlineHelpText>
        <label>Technician</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <value>00180000010MDi3</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Visits (Technician)</relationshipLabel>
        <relationshipName>Service_Visits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testCase_SVTechnicianCtlExt.cls
@isTest
private class testCase_SVTechnicianCtlExt {
	
	/*
	 *	Test methods for Case_SVTechnicianCtlExt
	 *
	 */
	
	// Create test data
	@testSetup static void csvtTestData() {
		
    	Account acc = new Account(Name = 'csvtAccount');
    	insert acc;
    	
    	Contact con = new Contact(LastName = 'csvtContact', AccountId = acc.Id);
    	insert con;
    	
    	Contract cntrct = new Contract(Name = 'asvContract', AccountId = acc.Id, Type__c = 'O&M');
    	insert cntrct;
    	
    	Case cs = new Case(AccountId = acc.Id, ServiceContract_Case__c = cntrct.Id);
    	insert cs;
    	
    	List<SV__c> svList = new List<SV__c>();
    	svList.add(new SV__c(Account__c = acc.Id, Contract__c = cntrct.Id, Technician__c = null, Case__c = cs.Id));
    	svList.add(new SV__c(Account__c = acc.Id, Contract__c = cntrct.Id, Technician__c = con.Id, Case__c = cs.Id));
    	svList.add(new SV__c(Account__c = acc.Id, Contract__c = cntrct.Id, Technician__c = con.Id, Case__c = cs.Id));
    	insert svList;
	}
	
    static testMethod void csvtTest1() {
		
		List<SV__c> svList = new List<SV__c>();
		ApexPages.StandardSetController stdSet = new ApexPages.StandardSetController(svList);
		Case_SVTechnicianCtlExt ctl = new Case_SVTechnicianCtlExt(stdSet);
		
		svList = [select Id, Technician__c from SV__c];
		stdSet = new ApexPages.StandardSetController(svList);
		stdSet.setSelected(svList);
		ctl = new Case_SVTechnicianCtlExt(stdSet);
		ctl.saveServiceVisits();
    }
}