objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <inlineHelpText>What sector is the customer classified under? 
**Only for Customer Accounts**</inlineHelpText>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Residential - Multi-Unit</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Small Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>PO_Total__c</fullName>
        <formula>Approved_PO_Total__c +  Pending_PO_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PO Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>PO_Total__c</fullName>
        <label>Approved PO Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BL-{0}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Con_PO__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Construction Purchase Orders</relationshipLabel>
        <relationshipName>Construction_Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Construction Purchase Orders</relationshipLabel>
        <relationshipName>Construction_Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Cost_Change__c</fullName>
        <label>Total Cost Change</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Construction Purchase Order</label>
    <nameField>
        <displayFormat>SF-PO-{000000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Construction Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Con_Req__c.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Project the CO is related to</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Change Orders</relationshipLabel>
        <relationshipName>Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Line Item</label>
        <referenceTo>Budget_Line_Item__c</referenceTo>
        <relationshipName>ConReq</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product you are adding to the Opportunity or PO</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Change Orders (New Product)</relationshipLabel>
        <relationshipName>Con_Req</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipName>Con_Req</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Con_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Subcontractor PO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Con_PO__c</referenceTo>
        <relationshipName>R00N80000002kftHEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Original product quantity
Referenced when updating or changing the product and quantity</inlineHelpText>
        <label>Original Quantity-old</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Visit</label>
        <referenceTo>SV__c</referenceTo>
        <relationshipName>Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Order</label>
    <nameField>
        <displayFormat>SF-CR-{000000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Orders</pluralLabel>
    <recordTypes>
        <fullName>Subcontractor</fullName>
        <active>false</active>
        <description>For requesting subcontractors</description>
        <label>Subcontractor Requisition</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related project that the service contract was created for.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Government - Small</fullName>
                </value>
                <value>
                    <fullName>Utility Scale</fullName>
                </value>
                <value>
                    <fullName>ES Ground</fullName>
                </value>
                <value>
                    <fullName>Non ES Ground</fullName>
                </value>
                <value>
                    <fullName>ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Non ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>DG Solar</fullName>
                </value>
                <value>
                    <fullName>DG Wind</fullName>
                </value>
                <value>
                    <fullName>DG SAS</fullName>
                </value>
                <value>
                    <fullName>LSR PV</fullName>
                </value>
                <value>
                    <fullName>Bulk ES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_Requested__c</fullName>
        <label>Qty Requested</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <inlineHelpText>Cost of the product, filled out by Procurement</inlineHelpText>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Subcontractor</fullName>
        <active>true</active>
        <label>Subcontractor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Approximate Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/conPO.cls
public class conPO {
    public static void updatePrice(Map<Id, Con_PO__c> pos) {        
        Map<Id, Con_Req__c> reqs = new Map<Id, Con_Req__c>();   //Map of PO Ids and Requisitions
        Map<Id, Budget_Line_Item__c> blis = new Map<Id, Budget_Line_Item__c>(); //Map of BLIs
        List<Id> reqBli = new List<Id>();   //List of BLIs from Reqs
        List<Budget_Line_Item__c> lines = new List<Budget_Line_Item__c>();  //List of BLIs
        List<Id> svId = new List<Id>(); //List of SV from Reqs
        Map<Id, SV__c> svs = new Map<Id, SV__c>();  //Map of SVs
        Map<Id, Id> reqSV = new Map<Id, Id>();
        List<SV__c> visits = new List<SV__c>();
        
        //Query Reqs, put PO ID and Req in reqs map, add Req BLI to reqBLI list
        Con_Req__c[] req = [select Budget_Line_Item__c, Purchase_Order__c, Service_Visit__c from Con_Req__c where Purchase_Order__c in :pos.keySet()];
        for (Integer i = 0; i <req.size(); i++) {
            reqs.put(req[i].Purchase_Order__c, req[i]);
            reqBli.add(req[i].Budget_Line_Item__c);
            svId.add(req[i].Service_Visit__c);
            reqSV.put(req[i].Id, req[i].Service_Visit__c);
        }
        //Query BLIs from reqBli list to get PO_Total, put BLIs in blis Map
        List<Budget_Line_Item__c> bli = new List<Budget_Line_Item__c>();
        if(reqBli.size() > 0){      
            bli = [select Id, PO_Total__c from Budget_Line_Item__c where Id in :reqBli];
            for (Integer i = 0; i <bli.size(); i++) {
                blis.put(bli[i].Id, bli[i]); 
            }
        }
        List<SV__c> sv = new List<SV__c>();
        if(svId.size() > 0){
            sv = [select Id, Cost__c from SV__c where Id in :svId];
            for (Integer i = 0; i <sv.size(); i++) {
                svs.put(sv[i].Id, sv[i]);
            }
        }
        //Query POs in map passed from Trigger for Total Cost Change
        Con_PO__c[] p = [select Id, Total_Cost_Change__c from Con_PO__c where Id in :pos.keySet()];
        if(bli.size()> 0){
        //Loop through POs
            for (Integer i = 0; i <p.size(); i++) {
            //Loop through BLIs
                for (Integer m = 0; m <bli.size(); m++) {
                    //If number of POs equals number of BLIs, POs and BLIs are one to one. (PO-Req-BLI not PO-Reqs-BLI)
                    if (i == m) {
                        //Add Total Cost Change to BLI PO Total and add BLI to lines list
                        if(blis.get(reqs.get(p[i].Id).Budget_Line_Item__c).PO_Total__c == null){
                            blis.get(reqs.get(p[i].Id).Budget_Line_Item__c).PO_Total__c = 0.0;
                        } 
                        blis.get(reqs.get(p[i].Id).Budget_Line_Item__c).PO_Total__c += pos.get(p[i].Id).Total_Cost_Change__c;
                        lines.add(blis.get(reqs.get(p[i].Id).Budget_Line_Item__c));
                    //If number of POs not equal to BLIs, BLI will loop through multiple times. 
                    } else {
                        //Add Total Cost Change to BLI PO Total then set the value of that BLI in lines list.
                        blis.get(reqs.get(p[i].Id).Budget_Line_Item__c).PO_Total__c += pos.get(p[i].Id).Total_Cost_Change__c;
                        lines.set(m, blis.get(reqs.get(p[i].Id).Budget_Line_Item__c));
                    }
                }
            }
        }   
        if(sv.size()>0){
            for (Integer i = 0; i <p.size(); i++) {
                for (Integer m = 0; m <sv.size(); m++) {
                    //If number of POs equals number of BLIs, POs and BLIs are one to one. (PO-Req-BLI not PO-Reqs-BLI)
                    if (i == m) {
                        //Add Total Cost Change to BLI PO Total and add BLI to lines list
                        if(svs.get(reqs.get(p[i].Id).Service_Visit__c).Cost__c == null) {
                            svs.get(reqs.get(p[i].Id).Service_Visit__c).Cost__c = 0.00;
                        }
                        svs.get(reqs.get(p[i].Id).Service_Visit__c).Cost__c += pos.get(p[i].Id).Total_Cost_Change__c;
                        visits.add(svs.get(reqs.get(p[i].Id).Service_Visit__c));
                    //If number of POs not equal to BLIs, BLI will loop through multiple times. 
                    } else {
                        //Add Total Cost Change to BLI PO Total then set the value of that BLI in lines list.
                        svs.get(reqs.get(p[i].Id).Service_Visit__c).Cost__c += pos.get(p[i].Id).Total_Cost_Change__c;
                        visits.set(m, svs.get(reqs.get(p[i].Id).Service_Visit__c));
                    }
                }
            }
        }
        //Update BLIs
        if(lines.size() > 0) {
            update lines; 
        }
        if(visits.size() > 0) {
            update visits; 
        }
    }
    public static void upQTY(Con_PO__c[] po){
        List<Id> poID = new List<Id>();
        List<Id> poProd = new List<Id>();
        for(Integer i = 0; i<po.size(); i++){
            poID.add(po[i].Id);
            poProd.add(po[i].Product__c);
        }
        List<Id> project = new List<Id>();
        List<Id> opp = new List<Id>();
        Map<Id, Con_Req__c> poReq = new Map<Id, Con_Req__c>();
        Map<Id, Id> reqProjOpp = new Map<Id, Id>();
        List<OpportunityLineItem> oli = new List<OpportunityLineItem>();
        Map<Id, List<OpportunityLineItem>> opLine = new Map<Id, List<OpportunityLineItem>>();
        Map<Id, Id> poEntry = new Map<Id, Id>();
        
        Con_Req__c[] cr = [select Purchase_Order__c, ASProject__c, Quantity__c, Service_Visit__c from Con_Req__c where Purchase_Order__c in :poID];
        for(Integer i = 0; i<cr.size(); i++){
            poReq.put(cr[i].Purchase_Order__c, cr[i]);
            project.add(cr[i].ASProject__c);
        } 
        AcctSeed__Project__c[] proj = [select AcctSeed__Opportunity__c, Id from AcctSeed__Project__c where Id in :project];
        for(Integer i = 0; i<proj.size(); i++){
            reqProjOpp.put(proj[i].Id, proj[i].AcctSeed__Opportunity__c);
            opp.add(proj[i].AcctSeed__Opportunity__c);
        }
        Opportunity[] opps = [select o.Id, (select OpportunityId, PricebookEntryId, Qty_Requested__c from OpportunityLineItems) from Opportunity o 
                                        where o.Id in :opp];
        for(Integer i = 0; i<opps.size(); i++){
            opLine.put(opps[i].Id, opps[i].OpportunityLineItems);
        }
        PricebookEntry[] pbe = [select Product2Id, Id from PricebookEntry  where Product2Id in :poProd];
        for(Integer i = 0; i<pbe.size(); i++){
            poEntry.put(pbe[i].Id, pbe[i].Id);
        }
        Map<Id, OpportunityLineItem> upOLI = new Map<Id, OpportunityLineItem>();
        for(Integer i = 0; i<po.size(); i++){
            if(poReq!=null && poReq.ContainsKey(po[i].Id) && poReq.get(po[i].Id).Service_Visit__c == null){
                Double requested = 0;           
                List<OpportunityLineItem> nOLI = opLine.get(reqProjOpp.get(poReq.get(po[i].Id).ASProject__c));
                for(Integer m = 0; m<nOLI.size(); m++){
                    requested = po[i].Quantity__c - poReq.get(po[i].Id).Quantity__c;
                    if(poEntry.get(nOLI[m].PricebookEntryId) != null){
                    
                        if(nOLI[m].Qty_Requested__c!=null)
                            nOLI[m].Qty_Requested__c += requested;
                        else
                            nOLI[m].Qty_Requested__c = requested;
                            
                        upOLI.put(nOLI[m].Id, nOLI[m]);
                    }
                }
            }
        }
        if(upOLI.size() > 0){
           approveELI.IsOpportunityLineItemUpdating=true;   
            update upOLI.values();
           approveELI.IsOpportunityLineItemUpdating=false;               
        }                               
    }  
    public static testMethod void conPOTest(){
    
    Account acc = new Account(Name = 'Knight - 2456',Type = 'Customers',Job_Type__c = 'Residential',Branch__c = 'Berkeley', 
                                     Project_End_Date__c = null, ShippingCity = 'Park City'); insert acc;
    AcctSeed__Project__c p = ProjectTest.setupTestProj();
    Contract con = new Contract(AccountId = acc.Id); insert con; 
    SV__c sv = new SV__c(Contract__c = con.Id, Visit_Date__c = System.Today(), Cost__c = 10.00); insert sv;
    
   // Budget__c budget = new Budget__c(ASProject__c = p.Id);  insert budget; 
   // Budget_Line_Item__c bli = new Budget_Line_Item__c(Budget__c = budget.Id, Pending_PO_Total__c = 0.0); insert bli;
    
    List<RecordType> LR=[select Id,Name from RecordType where Name IN ('Major Component PO','Subcontractor PO')];
    
    RecordType major,SubContractorPO;
    
    IF(LR!=Null && LR.Size()>0){
        For(RecordType RT:LR){
            if(RT.Name=='Major Component PO')
                major=RT;
            else if(RT.Name=='Subcontractor PO')
                SubContractorPO=RT;
        }
    }
    
    Product2 ProdMake;
    User bh = [select Id from User where Name = 'Bradley Hibberd'];
    System.runAs(bh){
        ProdMake = new Product2(Name = 'Sharp 170', Manufacturer__c = 'Sharp', Family = 'Solar Modules', 
                                        Cost__c = 15, IsActive = true, Status__c = 'Approved for Sale'); insert ProdMake;
    }
    TEST.starttest();
    Con_PO__c po = new Con_PO__c(Unit_Price__c = 10.00,Recordtypeid=SubContractorPO.id); insert po;
    Con_PO__c po2 = new Con_PO__c(Unit_Price__c = 10.00,Recordtypeid=SubContractorPO.id); insert po2;
    Con_Req__c[] req = new Con_Req__c[1];
/*    req.add(new Con_Req__c(Service_Visit__c = sv.Id, Vendor_Account__c = acc.Id, Quantity__c = 10.00,Purchase_Order__c = po.Id,  
                                Unit_Price__c = 30, Date_Needed__c = System.Today(), Tax_Rate__c = 7.25, Product__c = ProdMake.Id)); 
    req.add(new Con_Req__c(Project__c = p.Id, Vendor_Account__c = acc.Id, Quantity__c = 10.00, Purchase_Order__c = po2.Id, 
                                Unit_Price__c = 30, Budget_Line_Item__c = bli.Id, Date_Needed__c = System.Today(), Tax_Rate__c = 7.25));*/
  
   req[0]=new Con_Req__c(Service_Visit__c = sv.Id, Vendor_Account__c = acc.Id, Quantity__c = 10.00, Purchase_Order__c = po.Id, 
                                Unit_Price__c = 30, Date_Needed__c = System.Today(), Tax_Rate__c = 7.25, Product__c = ProdMake.Id); 
//    req[1]=new Con_Req__c(ASProject__c = p.Id, Vendor_Account__c = acc.Id, Quantity__c = 10.00, Purchase_Order__c = po2.Id, 
 //                               Unit_Price__c = 30, Budget_Line_Item__c = bli.Id, Date_Needed__c = System.Today(), Tax_Rate__c = 7.25);
  
  
    insert req;                                                     
    po.Unit_Price__c = 12.00; update po;
    po2.Unit_Price__c = 12.00; update po2;
    	test.stoptest();
    }
    
    public static testMethod void conPOTest2(){
    	
    Account acc = new Account(Name = 'Knight - 2456',Type = 'Customers',Job_Type__c = 'Residential',Branch__c = 'Berkeley', 
                                     Project_End_Date__c = null, ShippingCity = 'Park City'); insert acc;
    AcctSeed__Project__c p = ProjectTest.setupTestProj();
    Contract con = new Contract(AccountId = acc.Id); insert con; 
    SV__c sv = new SV__c(Contract__c = con.Id, Visit_Date__c = System.Today(), Cost__c = 10.00); insert sv;
    
    //Budget__c budget = new Budget__c(ASProject__c = p.Id);  insert budget; 
    //Budget_Line_Item__c bli = new Budget_Line_Item__c(Budget__c = budget.Id, Pending_PO_Total__c = 0.0); insert bli;
    
    List<RecordType> LR=[select Id,Name from RecordType where Name IN ('Major Component PO','Subcontractor PO')];
    
    RecordType major,SubContractorPO;
    
    IF(LR!=Null && LR.Size()>0){
        For(RecordType RT:LR){
            if(RT.Name=='Major Component PO')
                major=RT;
            else if(RT.Name=='Subcontractor PO')
                SubContractorPO=RT;
        }
    }
    
    Product2 ProdMake;
    User bh = [select Id from User where Name = 'Bradley Hibberd'];
    System.runAs(bh){
        ProdMake = new Product2(Name = 'Sharp 170', Manufacturer__c = 'Sharp', Family = 'Solar Modules', 
                                        Cost__c = 15, IsActive = true, Status__c = 'Approved for Sale'); insert ProdMake;
    }
    TEST.starttest();
    Con_PO__c po = new Con_PO__c(Unit_Price__c = 10.00,Recordtypeid=SubContractorPO.id); insert po;
    Con_PO__c po2 = new Con_PO__c(Unit_Price__c = 10.00,Recordtypeid=SubContractorPO.id); insert po2;
    Con_Req__c[] req = new Con_Req__c[1];
/*    req.add(new Con_Req__c(Service_Visit__c = sv.Id, Vendor_Account__c = acc.Id, Quantity__c = 10.00,Purchase_Order__c = po.Id,  
                                Unit_Price__c = 30, Date_Needed__c = System.Today(), Tax_Rate__c = 7.25, Product__c = ProdMake.Id)); 
    req.add(new Con_Req__c(Project__c = p.Id, Vendor_Account__c = acc.Id, Quantity__c = 10.00, Purchase_Order__c = po2.Id, 
                                Unit_Price__c = 30, Budget_Line_Item__c = bli.Id, Date_Needed__c = System.Today(), Tax_Rate__c = 7.25));*/
  
   req[0]=new Con_Req__c(Service_Visit__c = sv.Id, Vendor_Account__c = acc.Id, Quantity__c = 10.00, Purchase_Order__c = po.Id, 
                                Unit_Price__c = 30, Date_Needed__c = System.Today(), Tax_Rate__c = 7.25, Product__c = ProdMake.Id); 
   // req[1]=new Con_Req__c(ASProject__c = p.Id, Vendor_Account__c = acc.Id, Quantity__c = 10.00, Purchase_Order__c = po2.Id, 
    //                            Unit_Price__c = 30, Budget_Line_Item__c = bli.Id, Date_Needed__c = System.Today(), Tax_Rate__c = 7.25);
  
  
    insert req;                                                     
    
    po2.RecordTypeId = major.Id;
    po2.Quantity__c = 12.00;
    update po2;
    TEST.stoptest();
    }
}