objects/Account.object
<CustomObject>
    <fields>
        <fullName>Job_Type__c</fullName>
        <inlineHelpText>What sector is the customer classified under? 
**Only for Customer Accounts**</inlineHelpText>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>Residential - Multi-Unit</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Small Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>All Borrego Customers or Potential Customers</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Expected_Rebate__c</fullName>
        <description>Automatically populated from the associated Opportunity record Expected Rebate field.</description>
        <formula>AcctSeed__Opportunity__r.Expected_Rebate__c</formula>
        <inlineHelpText>Automatically populated from the associated Opportunity record Expected Rebate field.</inlineHelpText>
        <label>Expected Rebate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <formula>IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;Cash&quot;), &quot;Cash &quot;, NULL) +
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;PPA&quot;), &quot;PPA &quot;, NULL) + 
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;Lease&quot;), &quot;Lease &quot;, NULL) +
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;PACE&quot;), &quot;PACE &quot;, NULL) +  
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;TEML (tax -exempt municipal lease)&quot;), &quot;TEML (tax -exempt municipal lease) &quot;, NULL) + 
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;GO Bond&quot;), &quot;GO Bond &quot;, NULL) +
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;Other&quot;), &quot;Other &quot;, NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>How the project is financed- designated on the Opportunity</inlineHelpText>
        <label>Financing Options Provided</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inverter_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Inverter delivery</inlineHelpText>
        <label>Inverter Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Module_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Module delivery</inlineHelpText>
        <label>Module Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Racking_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Racking delivery</inlineHelpText>
        <label>Racking Delivery Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>O_M_Project</fullName>
        <active>true</active>
        <description>Used for O&amp;M Projects</description>
        <label>O&amp;M Project</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Job_Type__c</fullName>
        <formula>IF(Account.GroSolar__c = &apos;FALSE&apos; , &apos;Commercial&apos;, IF(Account.GroSolar__c  = &apos;TRUE&apos;, &apos;Residential&apos;, &apos;Commercial&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically filled in to show if the project is residential or commercial based on associated account.</inlineHelpText>
        <label>Job Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <businessProcess>Project</businessProcess>
        <description>One-off projects such as due diligence visits, retrofits/rebuilds, DAS replacements</description>
        <label>Project</label>
    </recordTypes>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Service Case</businessProcess>
        <description>used to log all reactive service cases and is default case type for email to case settings</description>
        <label>Reactive</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approximate_Install_Date__c</fullName>
        <description>This is the approximate date that customer expects that installation will begin.</description>
        <inlineHelpText>Required at Project Awarded- This is the approximate date that customer expects that installation will begin.</inlineHelpText>
        <label>Approximate Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Rebate__c</fullName>
        <description>This is the dollar value of the rebate we expect project to be eligable for.</description>
        <inlineHelpText>Expected Rebate Amount- required at Project Awarded. Enter $0 if rebate is not applicable</inlineHelpText>
        <label>Expected Rebate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <inlineHelpText>Denotes the Financing that was selected when the contract was signed.</inlineHelpText>
        <label>Final Financing Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PPA – Borrego</fullName>
                </value>
                <value>
                    <fullName>PPA - 3rd Party</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>HELOC</fullName>
                </value>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PPA</fullName>
                </value>
                <value>
                    <fullName>PACE</fullName>
                </value>
                <value>
                    <fullName>TEML (tax-exempt municipal lease)</fullName>
                </value>
                <value>
                    <fullName>GO Bond</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inverter_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Date of Inverter Delivery</inlineHelpText>
        <label>Inverter Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Government - Small</fullName>
                </value>
                <value>
                    <fullName>Utility Scale</fullName>
                </value>
                <value>
                    <fullName>ES Ground</fullName>
                </value>
                <value>
                    <fullName>Non ES Ground</fullName>
                </value>
                <value>
                    <fullName>ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Non ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>DG Solar</fullName>
                </value>
                <value>
                    <fullName>DG Wind</fullName>
                </value>
                <value>
                    <fullName>DG SAS</fullName>
                </value>
                <value>
                    <fullName>LSR PV</fullName>
                </value>
                <value>
                    <fullName>Bulk ES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Module_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Module Delivery Date</inlineHelpText>
        <label>Module Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposal_Submitted_Date__c</fullName>
        <label>First Proposal Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_System_Size__c</fullName>
        <inlineHelpText>Current proposed system size in watts</inlineHelpText>
        <label>Proposed System Size (watts)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Racking_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Racking Delivery Date</inlineHelpText>
        <label>Racking Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The individual or entity that will own the system.</inlineHelpText>
        <label>System Owner-Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (System Owner)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Rate__c</fullName>
        <inlineHelpText>What is the host customer&apos;s or offtaker&apos;s current utility rate? You can find this on their bill.</inlineHelpText>
        <label>Current Utility Rate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E A</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E AL-TOU</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E AL-TOU DGR</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E PA</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E PA-T-1</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A6</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A-10</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A-10 TOU</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E E-19</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E E-20</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-1</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-4</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-5</fullName>
                </value>
                <value>
                    <fullName>SCE GS-1</fullName>
                </value>
                <value>
                    <fullName>SCE GS-2</fullName>
                </value>
                <value>
                    <fullName>SCE GS-2 TOU</fullName>
                </value>
                <value>
                    <fullName>SCE GS-3-A</fullName>
                </value>
                <value>
                    <fullName>SCE-GS-3-B</fullName>
                </value>
                <value>
                    <fullName>SCE-GS-3-R</fullName>
                </value>
                <value>
                    <fullName>SCE TOU-8-A</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-B</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-CPP</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-R</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-1</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-2</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-3</fullName>
                </value>
                <value>
                    <fullName>LADWP A1A</fullName>
                </value>
                <value>
                    <fullName>LADWP A2A</fullName>
                </value>
                <value>
                    <fullName>NSTAR B7-TOU</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pending_Work__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pending Work</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Pending Work Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pending Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CasePendingWorkTest.cls
@isTest
private class CasePendingWorkTest {

    @isTest(SeeAllData=true)    
    static void CasePendingWorkTest_V1() {
        id CustomerRecordType  = [select id, DeveloperName from RecordType where SobjectType = 'Account' and DeveloperName = 'Customer' limit 1].id ;
        id ReactiveRecordType  = [select id, DeveloperName from RecordType where SobjectType = 'Case' and DeveloperName = 'Service' limit 1].id ;
        id PR_OMPROJECT  = [select id, DeveloperName from RecordType where SobjectType = 'AcctSeed__Project__c' and DeveloperName = 'O_M_Project' limit 1].id ;
        
        /*
        Account testAccount = new Account();
        testAccount.RecordTypeId = CustomerRecordType ;
        testAccount.Name = '12345-ACCOUNT' ;
        testAccount.Type = 'Customers' ;
        testAccount.Industry = 'Agriculture' ;
        testAccount.Job_Type__c = 'Public' ;
        testAccount.Description = '12345' ;
        //testAccount.Name = 'Silicon Valley' ;
        testAccount.Phone = '12345' ;
        insert testAccount ; 
        
        Contact testContact = new Contact(LastName = 'testContact', Title = 'CEO', AccountId = testAccount.Id, Phone = '123-456-7890', Email = 'testContact@testContact.com');
        insert testContact;
        
         //Create Opportunity
        Opportunity testOpportunity = new Opportunity(Name = 'Test test', AccountId = testAccount.Id, CloseDate = System.today(),Module_Delivery_Date__c =system.now().Date(),         
                                                            Inverter_Delivery_Date__c =system.now().Date(), Racking_Delivery_Date__c =system.now().Date(), StageName = 'Prospecting', Amount = 500000,
                                                            Type = 'Turnkey System', Approximate_Install_Date__c = System.today(), System_Owner__c = testContact.Id, Expected_Rebate__c = 0,
                                                            Proposal_Submitted_Date__c = System.today(), Proposed_System_Size__c = 10000, Utility_Rate__c = 'N/A', Financing__c = 'Cash',
                                                            Prevailing_Wage__c = 'No', Original_Contract_System_Size__c = 1000, RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Captive/OnSite').getRecordTypeId());
        insert testOpportunity; 
        
        //Create a Project for this test
        AcctSeed__Project__c testProject = new AcctSeed__Project__c(RecordTypeId = PR_OMPROJECT, Name = '1234 - 2456',AcctSeed__Account__c = testAccount.Id, AcctSeed__Opportunity__c = testOpportunity.Id, Job_Number__c = 'TEST-TEST' , Site_State__c ='T1234-TEST-1234T' ); // , Name = '1234 - 2456',AcctSeed__Account__c = testAccount.Id, AcctSeed__Opportunity__c = testOpportunity.Id, Job_Number__c = 'TEST-TEST' , Site_State__c ='T1234-TEST-1234T'
        //testProject.Site_State__c='MA';
        //testProject.Job_Number__c='99999-9999999';           
        insert testProject; 
        system.debug('testProject.Job_Number__c>> ' + testProject.Job_Number__c);
        */
        AcctSeed__Project__c rcdProject = [select id, AcctSeed__Account__c ,(select id from Contracts__r where Contract_Status__c = 'Active' limit 1)from AcctSeed__Project__c where id = 'a1t340000034Qdj' limit 1];
        
        
        Pending_Work__c rcdPendingWork = new Pending_Work__c();
        rcdPendingWork.Project__c = rcdProject.id ;   
        rcdPendingWork.Status__c = 'Open';
        insert rcdPendingWork ; 
        
        Case rcdCase = new Case();
        rcdCase.AccountId = rcdProject.AcctSeed__Account__c ; //testAccount.id ; 
        rcdCase.RecordTypeId = ReactiveRecordType ; 
        rcdCase.Project__c = rcdProject.id ;   
        rcdCase.Status = 'New' ; 
        rcdCase.Priority = 'Medium' ; 
        rcdCase.Origin = 'Web' ; 
        rcdCase.Reason = 'Other' ;
        //rcdCase.ServiceContract_Case__c = rcdProject.Contracts__r[0].id ;
         rcdCase.Case_Start_Date__c = date.today().adddays(-2);
        insert rcdCase ;
        
        ApexPages.Standardcontroller std = new ApexPages.Standardcontroller( rcdCase );
        CasePendingWork obj = new CasePendingWork(std);
        obj.CreateReactiveService() ; 
        obj.lstPendingWork[0].selected = true ;
        obj.CreateReactiveService() ;   
    }
}