objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Active_Budget__c</fullName>
        <label>Active Budget</label>
        <summarizedField>Budget_Line_Item__c.Active_Budget__c</summarizedField>
        <summaryForeignKey>Budget_Line_Item__c.Budget__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Actual_Budget__c</fullName>
        <label>Actuals - TL</label>
        <summarizedField>Budget_Line_Item__c.Actual_Budget__c</summarizedField>
        <summaryForeignKey>Budget_Line_Item__c.Budget__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PM_Initial_Projection__c</fullName>
        <label>PM Budget</label>
        <summarizedField>Budget_Line_Item__c.PM_Initial_Projection__c</summarizedField>
        <summaryForeignKey>Budget_Line_Item__c.Budget__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PO_Total__c</fullName>
        <formula>Approved_PO_Total__c +  Pending_PO_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PO Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pending_PO_Total__c</fullName>
        <label>Pending PO Total</label>
        <summarizedField>Budget_Line_Item__c.Pending_PO_Total__c</summarizedField>
        <summaryForeignKey>Budget_Line_Item__c.Budget__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sales_Budget__c</fullName>
        <label>Sales Budget</label>
        <summarizedField>Budget_Line_Item__c.Sales_Budget__c</summarizedField>
        <summaryForeignKey>Budget_Line_Item__c.Budget__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Budget_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Active_Budget__c</fullName>
        <label>Active Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Actual_Budget__c</fullName>
        <label>Actual Cost - TL</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Budget Line Items</relationshipLabel>
        <relationshipName>BudgetLine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Category_Code__c</fullName>
        <formula>Cost_Code__r.Category__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Code_Name__c</fullName>
        <formula>Cost_Code__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Code Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Remaining__c</fullName>
        <formula>Active_Budget__c - Line_Item_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PM_Active_Discrepancy__c</fullName>
        <formula>PM_Initial_Projection__c - PO_plus_Cost_To_Commit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PM/Active Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PM_Initial_Projection__c</fullName>
        <label>PM Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PO_Total__c</fullName>
        <label>Approved PO Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pending_PO_Total__c</fullName>
        <label>Pending PO Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Budget__c</fullName>
        <label>Sales Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_PM_Budget_Disceprancy__c</fullName>
        <formula>Sales_Budget__c - PM_Initial_Projection__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales/PM Budget Variance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_PO__c</fullName>
        <formula>PO_Total__c + Pending_PO_Total__c +  Approved_Sub_Change_Order_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PO Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Budget Line Item</label>
    <nameField>
        <displayFormat>BL-{0}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budget Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Con_Req__c.object
<CustomObject>
    <fields>
        <fullName>Budget_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Line Item</label>
        <referenceTo>Budget_Line_Item__c</referenceTo>
        <relationshipName>ConReq</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Status__c</fullName>
        <formula>TEXT( Purchase_Order__r.Status__c )</formula>
        <label>PO Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <label>Vendor Part Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product you are adding to the Opportunity or PO</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Change Orders (New Product)</relationshipLabel>
        <relationshipName>Con_Req</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Con_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Subcontractor PO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Con_PO__c</referenceTo>
        <relationshipName>R00N80000002kftHEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the CO
Controlled by the approval process and recall button</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed by Customer</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Borrego Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>X - Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved By Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>IF(
	OR( 
		Quantity__c = null, 
		Quantity__c = 0.00
	), 
	Unit_Price__c , Unit_Price__c * Quantity__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pre-Tax Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Subcontractor Account
Must be an account in Salesforce</inlineHelpText>
        <label>Vendor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Change Orders (Vendor Account)</relationshipLabel>
        <relationshipName>Con_Req</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Order</label>
    <nameField>
        <displayFormat>SF-CR-{000000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ELI__c.object
<CustomObject>
    <description>Each line item can be recorded.</description>
    <fields>
        <fullName>Approved_Amount__c</fullName>
        <description>AP Profiles Only – Users read-only</description>
        <label>Approved Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Line Item</label>
        <referenceTo>Budget_Line_Item__c</referenceTo>
        <relationshipLabel>Expense Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Code__c</fullName>
        <formula>Cost_Code__r.Category__c</formula>
        <label>Category Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expense_Header__c</fullName>
        <label>Expense Report</label>
        <referenceTo>ER__c</referenceTo>
        <relationshipLabel>Expense Line Items</relationshipLabel>
        <relationshipName>ExpRep</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vendor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Expense Line Items</relationshipLabel>
        <relationshipName>Expense_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense Line Item</label>
    <nameField>
        <displayFormat>EXP-LN-ITM {0000}</displayFormat>
        <label>Line Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Approximate Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>Used for any notes regarding the service visit that you want to appear on the work order form</inlineHelpText>
        <label>Service Visit Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/bli_detail.cls
public class bli_detail {
    
    private String lockStyle = '';
    private String unlockStyle = '';
    
    private Budget_Line_Item__c[] bli = [select Id, Name, Actual_Budget__c, Cost_Code_Name__c,  
                                            Category_Code__c, Sales_Budget__c, PM_Initial_Projection__c, Sales_PM_Budget_Disceprancy__c, 
                                            Total_PO__c, Pending_PO_Total__c, Active_Budget__c, Cost_Remaining__c, PM_Active_Discrepancy__c, 
                                            Notes__c, (select Name, Id, PO_Status__c, Product__c, Part_Number__c, Vendor_Account__c, Total_Cost__c, 
                                            Status__c, RecordTypeId, Purchase_Order__c from ConReq__r),(select Name, Code__c, Vendor_Account__c, 
                                            Approved_Amount__c, Expense_Header__c, Id from Expense_Line_Items__r) from Budget_Line_Item__c 
                                            where Budget__c = :ApexPages.currentPage().getParameters().get('id')];              
    public Budget_Line_Item__c[] getBli(){
        return bli;
    }
    private Budget__c budget;
    public void setBudget() {
        budget = [select Id, Name, OwnerId, PO_Total__c, Total_Cost_Remaining__c, Actual_Budget__c, Margin_Sales__c, Active_Actual_Variance__c, Margin_Actual__c, Margin_PM__c, Margin_Active__c, Project__c, Total_Contract_Value__c, PM_Lock__c, Sales_Budget__c, PM_Initial_Projection__c, Total_Sales_PM_Discrepancy__c, Total_PM_Active_Discrepancy__c, Active_Budget__c, Pending_PO_Total__c, Approved_PO_Total__c from Budget__c where Id =:ApexPages.currentPage().getParameters().get('id')];
        if (budget.PM_Lock__c == true){
                    lockStyle = 'display:none';
            } else {
                    unlockStyle = 'display:none';
            }
    }
    public Budget__c getBudget(){
            return budget;
    }
    public String getLock(){
            return lockStyle;
    }
    public String getUnlock(){
            return unlockStyle;
    }
    public PageReference PMsave() {
        update bli;
        setBudget();
        return null;
    }
    public PageReference SaveAndLock() {
        update bli;
        
        budget.PM_Lock__c = true;
        update budget;
        
        PageReference budgetPage = new PageReference('/apex/budget?id=' + budget.Id);
        budgetPage.setRedirect(true);

        return budgetPage; 
    }
    public PageReference Cancel() {
        
        PageReference budgetPage = new PageReference('/' + budget.Id);
        budgetPage.setRedirect(true);

        return budgetPage; 
    }

    public static testmethod void budgetTest() {
                       
        //Set Page Parameters 
        
        
       // Budget__c bud = [select Id from Budget__c where Project__c != null and PM_Lock__c = false LIMIT 1];
       // Budget__c bud2 = [select Id from Budget__c where Project__c != null and PM_Lock__c = true LIMIT 1];
        
        
        Account acc = new Account(Name = 'Knight - 2456',Type = 'Customers',Job_Type__c = 'Residential',Branch__c = 'Berkeley', 
                     Project_End_Date__c = null, ShippingCity = 'Park City'); insert acc;
       SFDC_Project__c p = ProjectTestOld.setupTestProj();
       Contract con = new Contract(AccountId = acc.Id); insert con; 
        SV__c sv = new SV__c(Contract__c = con.Id, Visit_Date__c = System.Today(), Cost__c = 10.00); insert sv;
        
        Budget__c bud = new Budget__c(Project__c = p.Id,PM_Lock__c = false);  insert bud ; 
        Budget_Line_Item__c bli1 = new Budget_Line_Item__c(Budget__c = bud .Id, Pending_PO_Total__c = 0.0); insert bli1;
            
        Budget__c bud2 = new Budget__c(Project__c = p.Id,PM_Lock__c = true );  insert bud2 ; 
        Budget_Line_Item__c bli2 = new Budget_Line_Item__c(Budget__c = bud2 .Id, Pending_PO_Total__c = 0.0); insert bli2;
        
        
        Test.startTest();
        
        PageReference pageRef = Page.budget;
        Test.setCurrentPage(pageRef);
        
        bli_detail controller = new bli_detail();
        ApexPages.currentPage().getParameters().put('id', bud.Id);
        
          controller.getBli();
          controller.getBudget(); 
          controller.getLock();
          controller.getUnlock(); 
          PageReference result2 = controller.PMsave();
          PageReference result = controller.SaveAndLock();
          PageReference result3 = controller.Cancel();                
        
        
        PageReference pageRef2 = Page.budget;
        Test.setCurrentPage(pageRef2);
        
        bli_detail controller2 = new bli_detail();
        ApexPages.currentPage().getParameters().put('id', bud2.Id);
        
          controller2.getBli();
          controller2.setBudget();
          controller2.getBudget(); 
          controller2.getLock();
          controller2.getUnlock();           
        
        Test.stopTest();
    }    
}