objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Accounting_Period__c.object
<CustomObject>
    <customHelpPage>AcctSeed__AccountingPeriodHelp</customHelpPage>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <fields>
        <fullName>AcctSeed__End_Date__c</fullName>
        <inlineHelpText>Accounting periods are typically used as months. This denotes the end of the period. Fiscal Months are supported. A period end date can not cross over into the start and end date range of another period.</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Start_Date__c</fullName>
        <inlineHelpText>Accounting periods are typically used as months. This denotes the beginning of the period. Fiscal Months are supported. A period beginning date can not cross over into the start and end date range of another period.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>&quot;Open&quot; allows new transactions to be saved to this period. &quot;Closed&quot; prevents new records from being saved to this period.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Expense_Line__c.object
<CustomObject>
    <description>Line item used to document a specific expense incurred by an employee. The aggregation of multiple expense lines constitutes an expense report.</description>
    <fields>
        <fullName>AcctSeed__Expense_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field denotes how the Accounting Department will classify the expense on a profit &amp; loss statement for the project or company.</inlineHelpText>
        <label>Expense GL Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Used_in_Expense_Reports__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Expense Lines</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Expense_Report__c</fullName>
        <inlineHelpText>Expense Report name.</inlineHelpText>
        <label>Expense Report</label>
        <referenceTo>AcctSeed__Expense_Report__c</referenceTo>
        <relationshipLabel>Expense Lines</relationshipLabel>
        <relationshipName>Expense_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <formula>Text(AcctSeed__Expense_Report__r.AcctSeed__Status__c)</formula>
        <inlineHelpText>Status of the expense report. This is controlled by the approval process.</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal_Entry_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>populates the corresponding JEL created from the expense report</description>
        <inlineHelpText>populates the corresponding JEL created from the expense report</inlineHelpText>
        <label>Journal Entry Line</label>
        <referenceTo>AcctSeed__Journal_Entry_Line__c</referenceTo>
        <relationshipLabel>Expense Lines</relationshipLabel>
        <relationshipName>Expense_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense Line</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Expense Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Expense_Report__c.object
<CustomObject>
    <description>Used to document expenses incurred by an employee.</description>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Status of the expense report controlled by the approval process.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense Report</label>
    <nameField>
        <label>Expense Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Journal_Entry__c.object
<CustomObject>
    <description>Used to document accounting related entries into the transaction table.</description>
    <fields>
        <fullName>AcctSeed__Accounting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to specify accounting period for financial reporting. Accounting period must have a value of Open.</inlineHelpText>
        <label>Accounting  Period</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <infoMessage>The accounting period status must be open</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
        <relationshipLabel>Journal Entry</relationshipLabel>
        <relationshipName>Journal_Entry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Journal_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Used to date transaction lines of journal entry line unless populates specifically on the journal entry line.</inlineHelpText>
        <label>Journal Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in approvals of Journal Entries and therefore related detail lines. A value of &quot;Posted&quot; indicates the record is final all debit and credit lines have been entered into the transaction object.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Waiting for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Journal Entry</label>
    <nameField>
        <label>Journal Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Journal_Entry_Line__c.object
<CustomObject>
    <description>Line level entry associated with a journal entry. The aggregation of multiple journal entry lines constitute a journal entry record.</description>
    <fields>
        <fullName>AcctSeed__Journal_Entry__c</fullName>
        <inlineHelpText>Related parent object.</inlineHelpText>
        <label>Journal Entry</label>
        <referenceTo>AcctSeed__Journal_Entry__c</referenceTo>
        <relationshipLabel>Journal Entry Lines</relationshipLabel>
        <relationshipName>Journal_Entry_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Journal Entry Line</label>
    <nameField>
        <displayFormat>JEL-{00000}</displayFormat>
        <label>Journal Entry Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in filtered look ups to limit the selection of inactive projects.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <fields>
        <fullName>AcctSeed__End_Date__c</fullName>
        <inlineHelpText>The date a project task ends on.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Start_Date__c</fullName>
        <inlineHelpText>The date this Project Task is set to start on.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in filtered lookups to eliminate inactive and completed projects from selection.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ExpenseReportsController.cls
public class ExpenseReportsController {
    Set<Id> setSelectedId = new Set<Id>();
    String retUrl;
    public ExpenseReportsController(ApexPages.StandardSetController stdSetCont) {
        if(ApexPages.currentPage().getParameters().containsKey('retUrl')) {
            retUrl = ApexPages.currentPage().getParameters().get('retUrl');
        }
        
        for(sObject selectedObj:stdSetCont.getSelected()) {
            setSelectedId.add((Id)selectedObj.get('Id'));
            
            
        }
    }
    
    public PageReference doLoad() {
        Savepoint sp = Database.setSavepoint();
        try {
            System.debug('=============setSelectedId: ' + setSelectedId);
            
            if(setSelectedId.size() > 0) {
                //List<AcctSeed__Journal_Entry__c> insertJournalEntries = new List<AcctSeed__Journal_Entry__c>();
                Map<Integer,List<AcctSeed__Journal_Entry_Line__c>> mapJEI = new Map<Integer,List<AcctSeed__Journal_Entry_Line__c>>();
                
				// Create Single Journal Entry Record
				AcctSeed__Journal_Entry__c JE = new AcctSeed__Journal_Entry__c();
				JE.AcctSeed__Journal_Date__c = System.today();
				JE.Name = System.now().format('yyyyMMdd') + ' Expense Reports';
				
				AcctSeed__Accounting_Period__c accPeriod;
				// Search Accounting Period Record for current Month
				String periodName = System.now().year() + '-' + System.now().format('MM');
				for(AcctSeed__Accounting_Period__c aPeriod:[Select Id From AcctSeed__Accounting_Period__c Where Name=:periodName Limit 1]) {
					accPeriod = aPeriod;
				}
				
				// Create new Accounting Period Record for current Month if not exist in Open Stage
				if(accPeriod == null) {
					Integer numberOfDays = Date.daysInMonth(System.now().year(), System.now().month());
					accPeriod = new AcctSeed__Accounting_Period__c(
										Name=periodName,
										AcctSeed__Start_Date__c=Date.newInstance(System.now().year(),System.now().month(),1),
										AcctSeed__End_Date__c=Date.newInstance(System.now().year(),System.now().month(),numberOfDays),
										AcctSeed__Status__c='Open');
					insert accPeriod;
				}
				
				JE.AcctSeed__Accounting_Period__c = accPeriod.Id;
				insert JE;
				
				List<AcctSeed__Expense_Report__c> lstExpenseReport = [Select Id,
                                                        (Select Id, AcctSeed__Expense_GL_Account__c,Branch__c,AcctSeed__Date__c,
                                                                AcctSeed__Project__c,Sales_Segment__c,AcctSeed__Amount__c,
                                                                AcctSeed__Project_Task__c,AcctSeed__Internal_Comment__c,Ops_Division__c
                                                            From AcctSeed__Expense_Lines__r) 
                                                        From AcctSeed__Expense_Report__c a 
                                                    Where Id IN:setSelectedId];
				
				// Collect Branch Name to populate Branch Lookup
				Set<String> setBranchName = new Set<String>();
				for(AcctSeed__Expense_Report__c er:lstExpenseReport) {
					for(AcctSeed__Expense_Line__c expLine:er.AcctSeed__Expense_Lines__r) {
                    	if(expLine.Branch__c != null) {
                    		if(expLine.Branch__c == 'Mid Atlantic') {
                    			setBranchName.add('Mid-Atlantic');
                    		}
                    		setBranchName.add(expLine.Branch__c);
                    	}
					}
				}
				map<String,AcctSeed__Accounting_Variable__c> mapBranchToAccountingVar = new Map<String,AcctSeed__Accounting_Variable__c>();
				
				if(setBranchName.size() > 0) {
					for(AcctSeed__Accounting_Variable__c branch:[Select Id,Name From AcctSeed__Accounting_Variable__c 
																					Where AcctSeed__Type__c='GL Account Variable 1' AND 
																					AcctSeed__Active__c=true AND
																					Name IN:setBranchName]) {
						if(branch.Name == 'Mid-Atlantic') {
                			mapBranchToAccountingVar.put('Mid Atlantic',branch);
                		}
						mapBranchToAccountingVar.put(branch.Name,branch);
						
					}
				}
				
				Integer index = 0;
				for(AcctSeed__Expense_Report__c er:lstExpenseReport) {
                    
                    mapJEI.put(index,new List<AcctSeed__Journal_Entry_Line__c>());
                    for(AcctSeed__Expense_Line__c expLine:er.AcctSeed__Expense_Lines__r) {
                        AcctSeed__Journal_Entry_Line__c jei = new AcctSeed__Journal_Entry_Line__c();
                        jei.AcctSeed__GL_Account__c = expLine.AcctSeed__Expense_GL_Account__c;
                        jei.AcctSeed__Date__c = expLine.AcctSeed__Date__c;
                        jei.AcctSeed__Project__c = expLine.AcctSeed__Project__c;
                        jei.AcctSeed__Debit__c = expLine.AcctSeed__Amount__c;
                        jei.AcctSeed__Project_Task__c = expLine.AcctSeed__Project_Task__c;
                        
                        // Set Branch
                        if(expLine.Branch__c != null && mapBranchToAccountingVar.containsKey(expLine.Branch__c)) {
                        	jei.AcctSeed__GL_Account_Variable_1__c = mapBranchToAccountingVar.get(expLine.Branch__c).Id;
                        }
                        
                        jei.Description__c = expLine.AcctSeed__Internal_Comment__c;
                        
                        jei.AcctSeed__GL_Account_Variable_3__c = expLine.Ops_Division__c;
                        jei.AcctSeed__GL_Account_Variable_2__c = expLine.Sales_Segment__c;
						jei.Expense_Line__c = expLine.Id;
                        mapJEI.get(index).add(jei);
                    }
                    index++;                                    
                }
                
				// Insert Child Records and also first populate Parent id
				List<AcctSeed__Journal_Entry_Line__c> insertChildJEI = new List<AcctSeed__Journal_Entry_Line__c>();
				for(Integer i:mapJEI.keySet()) {
					Id parentId = JE.Id;
					for(AcctSeed__Journal_Entry_Line__c jel:mapJEI.get(i)) {
						jel.AcctSeed__Journal_Entry__c = parentId;
						insertChildJEI.add(jel);
					}
				}
				
				if(insertChildJEI.size() > 0) {
					insert insertChildJEI;
					
					// Create Map of ExpenseLine Id to Journal Entry Line Id
					Map<Id,Id> mapExpLineIdToJEId = new Map<Id,Id>();
					for(AcctSeed__Journal_Entry_Line__c jel:insertChildJEI) {
						mapExpLineIdToJEId.put(jel.Expense_Line__c,jel.Id);
					}
					
					// Populate JEI Id to Expense Line records
					List<AcctSeed__Expense_Line__c> updateExpLine = new LIst<AcctSeed__Expense_Line__c>();
					for(AcctSeed__Expense_Report__c er:lstExpenseReport) {
	                    for(AcctSeed__Expense_Line__c expLine:er.AcctSeed__Expense_Lines__r) {
	                    	expLine.Journal_Entry_Line__c = mapExpLineIdToJEId.get(expLine.Id);
	                    	updateExpLine.add(expLine);
	                    }
					}
					
					if(updateExpLine.size() > 0) {
						update updateExpLine;
					}
				}
				
				return new PageReference('/' + JE.Id);
                //return goBack();
            } else {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select Atleast one Record.'));
            }
        } catch(Exception ex) {
        	Database.rollback(sp);
        	
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ex.getMessage()));
            System.debug('===========EXCEPTION: ' + ex.getMessage() + '==' + ex.getStackTraceString());
        }
        return null;
    }
    
    public PageReference goBack() {
        if(String.isNotEmpty(retUrl)) {
            return new PageReference(retUrl);
        }
        return null;
    }
}