objects/Account.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Which branch office will be handling account</description>
        <inlineHelpText>The Branch office where the account is located. For accounts working with the entire organization, enter &quot;Corporate&quot;</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>Orange County</fullName>
                </value>
                <value>
                    <fullName>Puerto Rico</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>Silicon Valley</fullName>
                </value>
                <value>
                    <fullName>Sonoma County</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Number__c</fullName>
        <externalId>true</externalId>
        <label>Job Number</label>
        <length>8</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <inlineHelpText>Regional office responsible for Project</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>North Carolina</fullName>
                </value>
                <value>
                    <fullName>Oregon</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>South Carolina</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>external ID</description>
        <externalId>true</externalId>
        <inlineHelpText>Generated automatically from Type and Branch fields upon Creation</inlineHelpText>
        <label>Job Number</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pricing_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the pricing request associated with this project. Used to drive PVBid integration.</description>
        <inlineHelpText>Lookup to the pricing request associated with this project. Used to drive PVBid integration.</inlineHelpText>
        <label>Pricing Request</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are no pricing requests associated with this project&apos;s opportunity.</errorMessage>
            <filterItems>
                <field>$Source.AcctSeed__Opportunity__c</field>
                <operation>equals</operation>
                <valueField>Pricing_Tool_Approval__c.Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pricing_Tool_Approval__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProjectId</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <fields>
        <fullName>Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cost_Code__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PVBidComponentID__c</fullName>
        <description>PVBid ID for integration</description>
        <externalId>true</externalId>
        <label>PVBid Component ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cost Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>State used for reporting and allocation</description>
        <inlineHelpText>State used for reporting and allocation</inlineHelpText>
        <label>State</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Branch value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Opportunities (Branch)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Accounting Variable with filter for Variable 3 and Record Type</description>
        <label>Team</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity Team value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 3</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricing_Tool_Approval__c.object
<CustomObject>
    <fields>
        <fullName>BidId__c</fullName>
        <description>The ID of the bid within the PVBid system.</description>
        <externalId>true</externalId>
        <inlineHelpText>The ID of the bid within the PVBid system.</inlineHelpText>
        <label>BidId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobilization_Date__c</fullName>
        <description>Pulls in the approximate install date, unless blank. Field is manually filled in in that case.</description>
        <inlineHelpText>Pulls in the approximate install date, unless blank. Field is manually filled in in that case.</inlineHelpText>
        <label>Mobilization Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>The opportunity that the pricing tool approval is related to</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pricing Requests</relationshipLabel>
        <relationshipName>Pricing_Tool_Approvals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Production_Guarantee_Level__c</fullName>
        <inlineHelpText>should include % ;  if none, put none; also include duration</inlineHelpText>
        <label>Production Guarantee Level and Duration</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <description>The ID of the project within the PVBid system.</description>
        <externalId>true</externalId>
        <inlineHelpText>The ID of the project within the PVBid system.</inlineHelpText>
        <label>ProjectId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <label>Pricing Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PVBidExtensionTests.cls
@isTest(seeAllData=false)
public class PVBidExtensionTests {

    private static Pricing_Tool_Approval__c request;
    private static AcctSeed__Project__c project;
    
    @testSetup
    public static void setup() {
      ASeedAccountingSettingsSetupTest.testDataSetup(); 
    }
    
    static void init () {
        Account a = new Account (Name = 'Vandelay Industries');
        insert a;
        
        Opportunity o = new Opportunity ();
        o.Amount = 100000;
        o.Name = 'Testing PVBid';
        o.CloseDate = System.today().addDays(7);
        o.StageName = 'Prospecting';
        o.AccountId = a.Id;
        //o.Team__c='a1O5500000CTyCo';
        insert o;
        
        request = new Pricing_Tool_Approval__c ();
        request.ProjectId__c = '1701';
        request.BidId__c = '5305';
        request.Production_Guarantee_Level__c = 'test';
        request.Opportunity__c = o.Id;
        request.Mobilization_Date__c = Date.newInstance(2018, 9, 1);      
        insert request;
        
        project = new AcctSeed__Project__c ();
        project.Branch__c = 'Boston';
        project.Pricing_Request__c = request.Id;
        project.AcctSeed__Opportunity__c = o.Id;
        project.Job_Number__c = '12345';
        project.Name = 'test';
        insert project;
        
        Cost_Code__c testCC = new Cost_Code__c ();
        testCC.Name = 'AC Electrical - Labor';
        testCC.Number__c = '01-1530';
        testCC.Category__c = 'L';
        testCC.PVBidComponentID__c = '388';
        insert testCC;
    }
    
    static testMethod void testPVBidSync () {
        init ();
        System.Test.startTest();

        Apexpages.StandardController prController = new Apexpages.StandardController(request);
        PVBidExtension ext = new  PVBidExtension(prController);  
        
        // set the variables that are set by the JS since we're headless here.
        ext.finalEPC = '1';
        ext.ineligibleCosts = '1';
        ext.finalEPCTotal = '1';
        ext.directMarginPercentage = '1';
        ext.modulePriceAssumption = '1';
        ext.systemSize = '1';
        ext.grossMargin = '1';
        ext.bidTitle = 'placeholder';
        ext.DirectCOGS = '1000.25';
        ext.DirectCOGSPerWatt = '25';
        ext.esdFinalPrice = '5';
        ext.esdCost = '1';
        ext.grossMarginPercentage = '0.25';
        ext.directMarginDollars = '500';
        ext.UtilityUpgrades='0.25';
        ext.AffiliateFee='0.25';
        ext.storagemargin='0.25';
        ext.storageenergy ='25';
        ext.energystoragesys ='25';
        ext.enerystorageunit ='25';
        ext.pvtotal ='25';
        ext.storagepower = '25';
            
        
        
        
        ext.receiveDataFromPVBid();      
        
        System.Test.stopTest();
    }
    
    static testMethod void testPVBidLineItemSync () {
        init ();
        System.Test.startTest();

        Apexpages.StandardController projectController = new Apexpages.StandardController(project);
        PVBidLineItemSyncExtension ext = new  PVBidLineItemSyncExtension(projectController);  
        
        // set the variables that are set by the JS since we're headless here.
        ext.componentIds = '388,';
        ext.costs = '1234,';
        ext.titles = '01-1530 - AC Electrical - Labor,';
        
        ext.addLineItems();   
        ext.errorCondition();
        ext.successCondition();
        
        System.Test.stopTest();
    }
}