objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__Accounting_Type__c</fullName>
        <inlineHelpText>Used in filtered lookups for Accounts Payable and Billing screens to limit selection of Accounts to those marked as Customers or Vendors for use by Accounting.</inlineHelpText>
        <label>Accounting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Vendor</fullName>
                </value>
                <value>
                    <fullName>Customer and Vendor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>All Borrego Customers or Potential Customers</description>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>ALL MATERIAL VENDORS who we will submit a PO to- Major and Minor Components</description>
        <label>Vendor- Material</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AcctSeedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <inlineHelpText>Project the line item is associated with- Automatically fills in when the line item is created from the Project</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cost_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Cost code of the line item. Lookup to the Cost Code Object- Must be equal to the Line Item Name</inlineHelpText>
        <label>Cost Code</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.Not_In_Rollup__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Cost_Code__c.Old__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Not_In_Rollup__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Cost_Code__c.Old__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Cost_Code__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Not_In_Rollup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for Cost Code migration</description>
        <label>Not In Rollup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Old__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used for CC migration</inlineHelpText>
        <label>Old</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Code__c</fullName>
        <formula>AcctSeedERP__Project_Task__r.Cost_Code__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the Cost Code entered in the Line Item associated with the PO Line</inlineHelpText>
        <label>Cost Code</label>
        <type>Text</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>equals</operation>
                <value>Customer, Customer and Vendor</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Order</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Sales Order</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>The manual field the manager enters to reflect the case start date</inlineHelpText>
        <label>Case Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Service Case</businessProcess>
        <description>used to log all reactive service cases and is default case type for email to case settings</description>
        <label>Reactive</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>pulls over Active user checkbox from SF user record</description>
        <formula>SF_User_Record__r.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>pulls over Active user checkbox from SF user record</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Cost_Code__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Old__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Old</label>
        <type>Checkbox</type>
    </fields>
    <label>Cost Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__Accounting_Type__c</fullName>
        <label>Tax Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Taxable Product</fullName>
                </value>
                <value>
                    <fullName>Tax Exempt Product</fullName>
                </value>
                <value>
                    <fullName>Tax Rate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Due_Days__c</fullName>
        <label>Payment Due (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Proposal Sent</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>Approved</fullName>
        <active>true</active>
        <description>Quote has been approved and many attributes are locked down.</description>
        <label>Approved</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/quoteTriggerTest.cls
@isTest(SeeAllData=true)
public class quoteTriggerTest {
   static testMethod void insertApprovedQuote() {
       Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Vendor- Material').getRecordTypeId();
       Id caseRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Reactive').getRecordTypeId();
       Id projectTaskRecordType = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId();
      
       Account a = new Account();
       a.Name = 'this is my test account';
       a.AcctSeed__Accounting_Type__c = 'Customer and Vendor';
       a.RecordTypeId = devRecordTypeId;
       insert a;
       
       Account testaccount = new Account();
       testaccount.Name = 'this has no record type';
       testaccount.AcctSeed__Accounting_Type__c = 'Vendor';
       insert testaccount;

       Contact c = new Contact();
       c.FirstName = 'Test';
       c.LastName = 'Test';
       c.AccountId = testaccount.id;
       c.Phone = '11111111';
       insert c;
       
       Cost_Code__c cc = new Cost_Code__c();
       cc.Active__c = true;
       cc.Old__c = false;
       cc.Number__c = '11111111';
       insert cc;
       
       AcctSeed__Project__c p = new AcctSeed__Project__c();
       p.Account__c = a.id;
       insert p;
       
       AcctSeed__Project_Task__c pt = new AcctSeed__Project_Task__c();
       pt.RecordTypeId = projectTaskRecordType;
       pt.AcctSeed__Project__c = p.id;
       pt.Cost_Code__c = cc.id;
       pt.Not_In_Rollup__c = false;
       insert pt;
       
       AcctSeedERP__Sales_Order__c so = new AcctSeedERP__Sales_Order__c();
       so.Project__c = p.id;
       so.AcctSeedERP__Customer__c = a.id;
       insert so;
       
       Case newCase = new Case();
       //case.recordtypeId = caseRecordType;
       newCase.RecordTypeId = caseRecordType;
       newCase.AccountId = testaccount.id;
       newCase.Status = 'Active';
       newCase.Priority = 'High';
       //newCase.Project__c = 
       newCase.Case_Start_Date__c = Date.today();
       insert newCase;
       
       
       
       SBQQ__Quote__c quote = new SBQQ__Quote__c();
       quote.SBQQ__Account__c = testaccount.id;
       quote.SBQQ__Status__c = 'Approved';
       quote.SBQQ__Primary__c = true;
       quote.Case__c = newCase.Id;
       quote.Payment_Due_Days__c = 10;
       quote.Project__c = p.id;
       quote.Labor_Billing__c ='Billable';
       insert quote;
       
       SBQQ__QuoteLine__c ql1 = new SBQQ__QuoteLine__c();
       ql1.SBQQ__Quote__c = quote.id;
       ql1.Vendor__c = a.id;
       ql1.SBQQ__NetPrice__c = 5.00;
       ql1.SBQQ__Quantity__c = 1;
       ql1.SBQQ__Description__c = 'test';
       ql1.SBQQ__Number__c = 1;
       ql1.Tax_Category__c = 'Labor - Internal';
       ql1.SBQQ__PricingMethod__c = 'List';
       ql1.Vendor__c = a.id;
       ql1.Project__c = p.id;
       //ql1.SBQQ__ProductFamily__c = 'Labor and Service';
       ql1.SBQQ__Product__c = [SELECT Id FROM Product2 WHERE Family = 'Labor and Service' LIMIT 1].id;
       ql1.Project_Line_Item__c = pt.id;
       insert ql1;
       Test.StartTest();
       
       quote.SBQQ__Status__c = 'Accepted';
       update quote;
       
       Test.StopTest();
       //
       //SBQQ__Quote__c newquote = [SELECT Id FROM SBQQ__Quote__c WHERE SBQQ__Status__c = 'Approved' AND Name = 'Q-00019' LIMIT 1];
       
       //newquote.SBQQ__Status__c = 'Accepted';
       //update newquote;
       
       //Case newcase = [SELECT Id FROM Case WHERE CaseNumber  = '00257654' LIMIT 1];
       
       //newcase.Status = 'Active';
       //update newcase;
       //newCase.Status = 'Closed';
      // update newCase;
       
       //newcase.Status = 'Closed';
       //update newcase;
       //
       //AcctSeedERP__Purchase_Order_Line__c pol = new AcctSeedERP__Purchase_Order_Line__c();
       
       
       
   }
}