objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
        <label>GL Variable 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Accounts (GL Variable 1)</relationshipLabel>
        <relationshipName>AccountsGLAV1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Account_Payable__c.object
<CustomObject>
    <description>Used to document liabilities to outside vendor, contact, or employee.</description>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in approvals of accounts payable records and therefore related detail lines. A value of &quot;Posted&quot; indicates the record is final and a debit and credit line have been entered into the transaction object for each account payable line.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>ON HOLD</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <formula>IF(AcctSeed__Total__c &lt; 0,&quot;Credit Memo&quot;, &quot;Invoice&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Automatically determined by the sum of the Accounts Payable Lines. If total Accounts Payable lines are negative the document is a Credit Memo. If Positive then it is an Invoice.</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payable</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Account_Payable_Line__c.object
<CustomObject>
    <description>Line item expense associated with an payable. The aggregation of multiple payable lines constitute a payable record.</description>
    <fields>
        <fullName>AcctSeed__Account_Payable__c</fullName>
        <inlineHelpText>Reference to Accounts Payable the line is associated with</inlineHelpText>
        <label>Payable</label>
        <referenceTo>AcctSeed__Account_Payable__c</referenceTo>
        <relationshipName>Project_Account_Payable_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
        <label>GL Variable 1</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Accounting Variable must have a Type of &quot;GL Account Variable 1&quot;.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Payable Lines (GL Variable 1)</relationshipLabel>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Internal_Comment__c</fullName>
        <inlineHelpText>Used to record comments for internal communication within your organization. These comments are not seen by customers.</inlineHelpText>
        <label>Internal Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description of the line or more details about the invoice</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Payable Line</label>
    <nameField>
        <displayFormat>APL-{00000}</displayFormat>
        <label>Payable Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payable Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Accounting_Variable__c.object
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>Used to determine GL Account Variables 1-4 and Time Card Variables 1-2.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GL Account Variable 1</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 2</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 3</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 4</fullName>
                </value>
                <value>
                    <fullName>Time Card Variable 1</fullName>
                </value>
                <value>
                    <fullName>Time Card Variable 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Expense_Line__c.object
<CustomObject>
    <description>Line item used to document a specific expense incurred by an employee. The aggregation of multiple expense lines constitutes an expense report.</description>
    <fields>
        <fullName>AcctSeed__Account_Payable_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Reference to related Account Payable Line. Expenses are bundled into Accounts Payable documents for approval and payment.</inlineHelpText>
        <label>Payable Line</label>
        <referenceTo>AcctSeed__Account_Payable_Line__c</referenceTo>
        <relationshipLabel>Expense Lines</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Credit_Card_Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>This field is required if the expense is not to be reimbursed to the employee, but a corporate credit card.</inlineHelpText>
        <label>Credit Card Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Credit_Card_Vendor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Expense Lines</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Expense_Report__c</fullName>
        <inlineHelpText>Expense Report name.</inlineHelpText>
        <label>Expense Report</label>
        <referenceTo>AcctSeed__Expense_Report__c</referenceTo>
        <relationshipLabel>Expense Lines</relationshipLabel>
        <relationshipName>Expense_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>GL Variable 1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Expense Lines</relationshipLabel>
        <relationshipName>Expense_Lines2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Internal_Comment__c</fullName>
        <inlineHelpText>Used to record comments for internal communication within your organization. These comments are not seen by customers.</inlineHelpText>
        <label>Internal Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <formula>Text(AcctSeed__Expense_Report__r.AcctSeed__Status__c)</formula>
        <inlineHelpText>Status of the expense report. This is controlled by the approval process.</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Expense Line</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Expense Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Expense_Report__c.object
<CustomObject>
    <description>Used to document expenses incurred by an employee.</description>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Status of the expense report controlled by the approval process.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Posted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReportBranch__c</fullName>
        <inlineHelpText>Expense Report Branch. This is automatically set based on the user profile.</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense Report</label>
    <nameField>
        <label>Expense Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MapExpenseLineToAccountPayableLine.cls
public class MapExpenseLineToAccountPayableLine {
	
	public static void mapExpenseFieldsToAccountPayable(Map<Id,AcctSeed__Expense_Line__c> oldLines, Map<Id,AcctSeed__Expense_Line__c> newLines) {
		List<AcctSeed__Account_Payable_Line__c> apLineUpdate = new List<AcctSeed__Account_Payable_Line__c>();
		Map<String,AcctSeed__Accounting_Variable__c> accountVar1Map = new Map<String,AcctSeed__Accounting_Variable__c>();
		
		for (AcctSeed__Expense_Line__c newLine : [Select Id, AcctSeed__Expense_Report__c, AcctSeed__Expense_Report__r.ReportBranch__c
													From AcctSeed__Expense_Line__c Where Id In :newLines.keySet()]) {
				accountVar1Map.put(newLine.AcctSeed__Expense_Report__r.ReportBranch__c,null);											
		}
		
		for (AcctSeed__Accounting_Variable__c glAccountVar : [Select Id, Name From AcctSeed__Accounting_Variable__c Where Name In :accountVar1Map.keySet() And AcctSeed__Type__c = 'GL Account Variable 1'])	{
			accountVar1Map.put(glAccountVar.Name, glAccountVar);	
		}
		
		for (AcctSeed__Expense_Line__c newLine : [Select Id, AcctSeed__Account_Payable_Line__c, AcctSeed__Internal_Comment__c, AcctSeed__Expense_Report__r.ReportBranch__c, AcctSeed__Account_Payable_Line__r.AcctSeed__Account_Payable__r.AcctSeed__Status__c
															From AcctSeed__Expense_Line__c Where Id In :newLines.keySet()]) {
																
			AcctSeed__Expense_Line__c oldLine = oldLines.get(newLine.Id);
																
			if (oldLine.AcctSeed__Account_Payable_Line__c == null && newLine.AcctSeed__Account_Payable_Line__c != null && newLine.AcctSeed__Account_Payable_Line__r.AcctSeed__Account_Payable__r.AcctSeed__Status__c != 'Posted') {
				newLine.AcctSeed__Account_Payable_Line__r.Description__c = newLine.AcctSeed__Internal_Comment__c;
				newLine.AcctSeed__Account_Payable_Line__r.AcctSeed__GL_Account_Variable_1__c = accountVar1Map.get(newLine.AcctSeed__Expense_Report__r.ReportBranch__c) != null ? accountVar1Map.get(newLine.AcctSeed__Expense_Report__r.ReportBranch__c).Id : null;
				apLineUpdate.add(newLine.AcctSeed__Account_Payable_Line__r);
			}
		}
		
		update apLineUpdate;
	}
	
	@isTest(seeAllData=true)
	public static void testMapExpenseFieldsToAccountPayable() {
		TestDataSuite.initialize();
		Integer i = 0;
		
		Map<Id,AcctSeed__Expense_Report__c> expenseReports = new Map<Id,AcctSeed__Expense_Report__c>();
		
		for (AcctSeed__Expense_Line__c el : [Select Id, AcctSeed__Internal_Comment__c, AcctSeed__Expense_Report__r.Id From AcctSeed__Expense_Line__c Where Id In :TestDataSuite.expenses]) {		
			el.AcctSeed__Internal_Comment__c = 'Test' + i;
			//el.AcctSeed__Expense_Report__r.ReportBranch__c = 'Sales';
			el.AcctSeed__Account_Payable_Line__c = TestDataSuite.accountPayableLines[i].Id;
			
			if (!expenseReports.containsKey(el.AcctSeed__Expense_Report__r.Id))
				expenseReports.put(el.AcctSeed__Expense_Report__r.Id,el.AcctSeed__Expense_Report__r);
			i++;
		}
		
		update expenseReports.values();
		update TestDataSuite.expenses;
		
		i = 0;
		 
		for (AcctSeed__Account_Payable_Line__c apLine : [Select Id, Description__c, AcctSeed__GL_Account_Variable_1__r.Name, (Select Id, AcctSeed__Expense_Report__r.ReportBranch__c From AcctSeed__Expenses__r) From AcctSeed__Account_Payable_Line__c Where Id In :TestDataSuite.accountPayableLines]) {
			
			if (apLine.AcctSeed__Expenses__r != null && !apLine.AcctSeed__Expenses__r.isEmpty()) {
				System.assertEquals(apLine.AcctSeed__Expenses__r[0].AcctSeed__Expense_Report__r.ReportBranch__c, apLine.AcctSeed__GL_Account_Variable_1__r.Name);
				System.assertEquals('Test' + i, apLine.Description__c);
			}	
			i++;
		}
	}
}