objects/Account.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <inlineHelpText>Effected component on site. If the whole electrical system is effected, the component is the point of connection (example: switch gear)</inlineHelpText>
        <label>Component</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Inverter</fullName>
                </value>
                <value>
                    <fullName>Module</fullName>
                </value>
                <value>
                    <fullName>Racking</fullName>
                </value>
                <value>
                    <fullName>Electrical</fullName>
                </value>
                <value>
                    <fullName>Roof</fullName>
                </value>
                <value>
                    <fullName>DAS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Tracker</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Switch Gear</fullName>
                </value>
                <value>
                    <fullName>Transformer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Component__c.object
<CustomObject>
    <description>part to maintenance case</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Components</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <label>Component Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Combiner Boxes</fullName>
                </value>
                <value>
                    <fullName>Contractual/Special Requirements</fullName>
                </value>
                <value>
                    <fullName>DAS/Metering Inspection</fullName>
                </value>
                <value>
                    <fullName>Exposed Wireways</fullName>
                </value>
                <value>
                    <fullName>Inverter</fullName>
                </value>
                <value>
                    <fullName>Inverters</fullName>
                </value>
                <value>
                    <fullName>Modules &amp; Mounting</fullName>
                </value>
                <value>
                    <fullName>Roof</fullName>
                </value>
                <value>
                    <fullName>Site Grounds</fullName>
                </value>
                <value>
                    <fullName>Tracker</fullName>
                </value>
                <value>
                    <fullName>Transformers</fullName>
                </value>
                <value>
                    <fullName>Weather Station</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Follow_Up_Required__c</fullName>
        <label>Follow Up Required</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Performed during visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Component</label>
    <nameField>
        <displayFormat>CMPT-{0}</displayFormat>
        <label>Component Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Brings over notes from the Lead</description>
        <inlineHelpText>Shows any notes from the unconverted Lead. Add new notes about the contact in here.</inlineHelpText>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Maintenance_Item__c.object
<CustomObject>
    <description>to store check list items for maintenance case</description>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>checkoff if maintenance was completed.  leave unchecked if it was not</inlineHelpText>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <label>Component Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Combiner Boxes</fullName>
                </value>
                <value>
                    <fullName>Contractual/Special Requirements</fullName>
                </value>
                <value>
                    <fullName>DAS/Metering Inspection</fullName>
                </value>
                <value>
                    <fullName>Exposed Wireways</fullName>
                </value>
                <value>
                    <fullName>Inverters</fullName>
                </value>
                <value>
                    <fullName>Modules &amp; Mounting</fullName>
                </value>
                <value>
                    <fullName>Roof</fullName>
                </value>
                <value>
                    <fullName>Site Grounds</fullName>
                </value>
                <value>
                    <fullName>Tracker</fullName>
                </value>
                <value>
                    <fullName>Transformers</fullName>
                </value>
                <value>
                    <fullName>Weather Station</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Maintenance Items</relationshipLabel>
        <relationshipName>Maintenance_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Required__c</fullName>
        <label>Follow Up Required</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Performed During Visit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Maintenance Item</label>
    <nameField>
        <displayFormat>MAINT-{0}</displayFormat>
        <label>Maintenance Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testComponentMaintenance.cls
@isTest(SeeAllData = true)
private class testComponentMaintenance {
    
    /*
     *  Test methods for CaseMaintenanceReportController.cls and ComponentMaintenanceCtrlExt.cls
     *
     */
    
    static void initCmpMaintData(Case cs, List<Component__c> cmpList) {
        
        Account acc = new Account(
            Name = 'CmpMaintAccount'
        );
        insert acc;
        
        Contact cnt = new Contact(
            AccountId = acc.Id,
            LastName = 'CmpMaintContact'
        );
        insert cnt;
        
        cs.AccountId = acc.Id;
        cs.ContactId = cnt.Id;
        cs.RecordTypeId = '012340000007kUM';
        insert cs;
        
        cmpList.add(new Component__c(
            Case__c = cs.Id,
            Component_Type__c = 'Transformers',
            Summary__c = 'Transformer summary')
        );
        cmpList.add(new Component__c(
            Case__c = cs.Id,
            Component_Type__c = 'Roof',
            Summary__c = 'Roof summary')
        );
        insert cmpList;
    }
    
    static testMethod void testCmpMaintCtrlExt() {
        
        Case cs = new Case();
        List<Component__c> cmpList = new List<Component__c>();
        
        initCmpMaintData(cs, cmpList);
        
        //Instantiate a new controller with an existing Component record
        ApexPages.StandardController std = new ApexPages.StandardController(cmpList[0]);
        ComponentMaintenanceCtrlExt ctl = new ComponentMaintenanceCtrlExt(std);
        
        ctl.saveAll();
        ctl.saveAndNew();
        
        //Instantiate a new controller with a new Component record
        Component__c cmp = new Component__c();
        std = new ApexPages.StandardController(cmp);
        ApexPages.currentPage().getParameters().put('caseId', cs.Id);
        ctl = new ComponentMaintenanceCtrlExt(std);
        
        ctl.saveComponent();
    }
    
    static testMethod void testCaseMaintRepCtrl() {
        
        Case cs = new Case();
        List<Component__c> cmpList = new List<Component__c>();
        List<Maintenance_Item__c> miList = new List<Maintenance_Item__c>();
        
        initCmpMaintData(cs, cmpList);
        
        List<Id> cmpIds = new List<Id>();
        for (Component__c cmp :cmpList) {
            cmpIds.add(cmp.Id);
        }
        miList = new List<Maintenance_Item__c>();
        miList = [select Id, Component_Type__c, Completed__c, Follow_Up_Required__c, Component__c, Notes__c 
                from Maintenance_Item__c where Component__c in :cmpIds];
        for (Maintenance_Item__c mi :miList) {
            mi.Completed__c = true;
            mi.Follow_Up_Required__c = 'Yes';
        }
        update miList;
        
        //Instantiate a new controller with the Case record
        ApexPages.StandardController std = new ApexPages.StandardController(cs);
        CaseMaintenanceReportController ctl = new CaseMaintenanceReportController(std);
        ctl.getDocumentLogoUrl();
        //ctl.ComponentImage();
        //ctl.ComponentSummary();
        
    }
}