objects/Account.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__Billing_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to configure formatting and display of fields in Billing PDF. Overrides the default Billing Format defined in Accounting Settings.</inlineHelpText>
        <label>Billing Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Billing</value>
            </filterItems>
            <infoMessage>The Type must equal &quot;Billing&quot;</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Accounts (Billing Format)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Private</fullName>
        <active>true</active>
        <description>Used for accounts containing private or personal information</description>
        <label>Private</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Accounting_Variable__c.object
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>Used to determine GL Account Variables 1-4 and Time Card Variables 1-2.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GL Account Variable 1</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 2</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 3</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 4</fullName>
                </value>
                <value>
                    <fullName>Time Card Variable 1</fullName>
                </value>
                <value>
                    <fullName>Time Card Variable 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Billing_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to configure formatting and display of fields in Billing PDF.</inlineHelpText>
        <label>Billing Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Billing</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Billing</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Project_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Ledger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Denotes the associated ledger.</inlineHelpText>
        <label>Ledger</label>
        <referenceTo>AcctSeed__Ledger__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <formula>IF(AcctSeed__Total__c &lt; 0, &apos;Credit Memo&apos;,&apos;Invoice&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Type of Billing- either Invoice or Credit Memo
If Total &gt;0 = Invoice
If Total &lt;0 = Credit Memo</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing_Format__c.object
<CustomObject>
    <description>Used to store configuration and default settings related to the pdf generation of a record.</description>
    <fields>
        <fullName>AcctSeed__Default_Email_Template__c</fullName>
        <inlineHelpText>This is the email template used when emailing Billing PDF Invoices. Use the Template Unique Name NOT the Template Name when populating this field.</inlineHelpText>
        <label>Default Email Template</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>The type of record this PDF Format is associated.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Visualforce_PDF_Page__c</fullName>
        <inlineHelpText>The API name of the Visualforce page that is used to display the PDF rendition of the Billing.</inlineHelpText>
        <label>Visualforce PDF Page</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PDF Format</label>
    <nameField>
        <label>PDF Format Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__GL_Account__c.object
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <fields>
        <fullName>AcctSeed__Bank__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates if the GL Account is a Bank account and can be selected to record Cash Receipts, Cash Disbursements and use the Bank Reconciliation.</inlineHelpText>
        <label>Bank</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Sub_Type_1__c</fullName>
        <inlineHelpText>Used in conjunction with the Type field to further classify GL Accounts in reports. This pick list is dependent on Type.</inlineHelpText>
        <label>Sub Type 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assets</fullName>
                </value>
                <value>
                    <fullName>Cost of Goods Sold</fullName>
                </value>
                <value>
                    <fullName>Facilities</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Liabilities</fullName>
                </value>
                <value>
                    <fullName>Owners Equity</fullName>
                </value>
                <value>
                    <fullName>Product Revenue</fullName>
                </value>
                <value>
                    <fullName>Sales &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Service Revenue</fullName>
                </value>
                <value>
                    <fullName>General &amp; Administrative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>Denotes the major grouping for financial reporting.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                    <default>true</default>
                    <label>Expense</label>
                </value>
                <value>
                    <fullName>Balance Sheet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Ledger__c.object
<CustomObject>
    <description>Used to associate and aggregate financial transaction or budget entries with a specific entity.</description>
    <fields>
        <fullName>AcctSeed__Billing_Activity_Statement_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the billing activity statement format here. The billing activity statement format is the PDF format used to send billing activity statements to a customer.</inlineHelpText>
        <label>Billing Activity Statement Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Activity Statement</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Activity Statement</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Ledgers (Billing Activity Statement Format)</relationshipLabel>
        <relationshipName>Billing_Activity_Statement_Formats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Billing_Outstanding_Statement_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the billing outstanding statement format here. The billing outstanding statement format is the PDF format used to send billing outstanding statements to a customer.</inlineHelpText>
        <label>Billing Outstanding Statement Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Outstanding Statement</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Outstanding Statement</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Ledgers (Billing Outstanding Statement Format)</relationshipLabel>
        <relationshipName>Billing_Outstanding_Statement_Formats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                    <default>true</default>
                    <label>Budget</label>
                </value>
                <value>
                    <fullName>Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Recurring_Billing__c.object
<CustomObject>
    <description>Captures information related to recurring billings associated with customers. A recurring billing is a template for creating billings on a periodic basis.</description>
    <fields>
        <fullName>AcctSeed__Ledger__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Denotes the associated ledger.</inlineHelpText>
        <label>Ledger</label>
        <referenceTo>AcctSeed__Ledger__c</referenceTo>
        <relationshipLabel>Recurring Billings</relationshipLabel>
        <relationshipName>Recurring_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recurring Billing</label>
    <nameField>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AvaAcctSeed__CBAvaTaxSetting__c.object
<CustomObject>
    <description>Object To Store Avalara Service URL, Credentials, and Preferences</description>
    <fields>
        <fullName>AvaAcctSeed__GL_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>GL Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Balance Sheet</value>
            </filterItems>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Sub_Type_1__c</field>
                <operation>equals</operation>
                <value>Liabilities</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Avalara</relationshipLabel>
        <relationshipName>Avalara</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Avalara Account</label>
    <nameField>
        <label>Avalara Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Avalara</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AmortizationEntriesControllerTest.cls
@isTest
private class AmortizationEntriesControllerTest {
    static testMethod void testIt() {
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        List<AcctSeed__GL_Account__c> glAccounts = new List<AcctSeed__GL_Account__c>();
        
        AcctSeed__GL_Account__c glAccount = new AcctSeed__GL_Account__c();
        glAccount.AcctSeed__Sub_Type_1__c = 'Liabilities';
        glAccount.AcctSeed__Type__c = 'Balance Sheet';
        glAccounts.add(glAccount);
        
        AcctSeed__GL_Account__c bankAcc = new AcctSeed__GL_Account__c();
        bankAcc.AcctSeed__Bank__c = true;
        glAccounts.add(bankAcc);
        
        AcctSeed__GL_Account__c debitAcc = new AcctSeed__GL_Account__c();
        debitAcc.Name = '2306';
        glAccounts.add(debitAcc);

        AcctSeed__GL_Account__c creditAcc = new AcctSeed__GL_Account__c();
        creditAcc.Name = '3100';
        glAccounts.add(creditAcc);

        insert glAccounts;
        
        AvaAcctSeed__CBAvaTaxSetting__c avaTax = new AvaAcctSeed__CBAvaTaxSetting__c();
        avaTax.AvaAcctSeed__GL_Account__c = glAccounts[0].Id;
        insert avaTax;
        
        List<AcctSeed__Billing_Format__c> billingFormats = new List<AcctSeed__Billing_Format__c>();
        AcctSeed__Billing_Format__c billingFormat = new AcctSeed__Billing_Format__c();
        billingFormat.AcctSeed__Type__c = 'Billing';
        billingFormat.AcctSeed__Visualforce_PDF_Page__c = 'MassSubmit';
        billingFormat.AcctSeed__Default_Email_Template__c = 'X10_Days_to_Deadline_Date';
        billingFormats.add(billingFormat);
        
        AcctSeed__Billing_Format__c billingFormat1 = new AcctSeed__Billing_Format__c();
        billingFormat1.AcctSeed__Type__c = 'Activity Statement';
        billingFormat1.AcctSeed__Visualforce_PDF_Page__c = 'MassSubmit';
        billingFormat1.AcctSeed__Default_Email_Template__c = 'X10_Days_to_Deadline_Date';
        billingFormats.add(billingFormat1);
        
        AcctSeed__Billing_Format__c billingFormat2 = new AcctSeed__Billing_Format__c();
        billingFormat2.AcctSeed__Type__c = 'Outstanding Statement';
        billingFormat2.AcctSeed__Visualforce_PDF_Page__c = 'MassSubmit';
        billingFormat2.AcctSeed__Default_Email_Template__c = 'X10_Days_to_Deadline_Date';
        billingFormats.add(billingFormat2);
        
        AcctSeed__Billing_Format__c billingFormat3 = new AcctSeed__Billing_Format__c();
        billingFormat3.AcctSeed__Type__c = 'Purchase Order';
        billingFormat3.AcctSeed__Visualforce_PDF_Page__c = 'MassSubmit';
        billingFormat3.AcctSeed__Default_Email_Template__c = 'X10_Days_to_Deadline_Date';
        billingFormats.add(billingFormat3);
        
        AcctSeed__Billing_Format__c billingFormat4 = new AcctSeed__Billing_Format__c();
        billingFormat4.AcctSeed__Type__c = 'Packing Slip';
        billingFormat4.AcctSeed__Visualforce_PDF_Page__c = 'MassSubmit';
        billingFormat4.AcctSeed__Default_Email_Template__c = 'X10_Days_to_Deadline_Date';
        billingFormats.add(billingFormat4);
        
        insert billingFormats;
        
        AcctSeed__Ledger__c ledger = new AcctSeed__Ledger__c();
        ledger.AcctSeed__Type__c = 'Transactional';
        ledger.AcctSeed__Billing_Activity_Statement_Format__c = billingFormats[1].Id;
        ledger.AcctSeed__Billing_Outstanding_Statement_Format__c = billingFormats[2].Id;
        ledger.AcctSeed__Default_Bank_Account__c = glAccounts[1].Id;
        ledger.AcctSeed__Default_Billing_Format__c = billingFormats[0].Id;
        ledger.AcctSeed__Default_Purchase_Order_Format__c = billingFormats[3].Id;
        ledger.AcctSeed__Default_Packing_Slip_Format__c = billingFormats[4].Id;
        insert ledger;
        
        AcctSeed__Accounting_Period__c period = new AcctSeed__Accounting_Period__c();
        period.AcctSeed__Status__c = 'Open';
        period.Name = '2019-06';
        period.AcctSeed__Start_Date__c = Date.today();
        period.AcctSeed__End_Date__c = Date.today().addDays(30);
        insert period;
        
        //AcctSeed__Recurring_Billing__c recurringBilling = new AcctSeed__Recurring_Billing__c();
        //insert recurringBilling;

        List<AcctSeed__Accounting_Variable__c> accVars = new List<AcctSeed__Accounting_Variable__c>();

        AcctSeed__Accounting_Variable__c accVar1 = new AcctSeed__Accounting_Variable__c();
        accVar1.Name = 'O&M';
        accVar1.AcctSeed__Type__c = 'GL Account Variable 1';
        accVars.add(accVar1);

        AcctSeed__Accounting_Variable__c accVar2 = new AcctSeed__Accounting_Variable__c();
        accVar2.Name = 'O&M';
        accVar2.AcctSeed__Type__c = 'GL Account Variable 2';
        accVars.add(accVar2);

        AcctSeed__Accounting_Variable__c accVar3 = new AcctSeed__Accounting_Variable__c();
        accVar3.Name = 'O&M';
        accVar3.AcctSeed__Type__c = 'GL Account Variable 3';
        accVars.add(accVar3);

        insert accVars;
        // AcctSeed__Project_Task__c

        AcctSeed__Billing__c billing = new AcctSeed__Billing__c();
        billing.AcctSeed__Ledger__c = ledger.Id;
        billing.AcctSeed__Accounting_Period__c = period.Id;
        billing.AcctSeed__Customer__c = acc.Id;
        billing.AcctSeed__Billing_Format__c = billingFormats[0].Id;
        insert billing;
        
        Test.startTest();
            Test.setCurrentPage(Page.AmortizationEntries);
            ApexPages.StandardController stdController = new ApexPages.StandardController(billing);
            AmortizationEntriesController ext = new AmortizationEntriesController(stdController);
            // ext.billing.User__c = UserInfo.getUserId();
            ext.submit();
            ext.back();
            // ext.billing.User__c = '0053400000BeTYZ';
            // ext.submit();
        Test.stopTest();
    }
}