objects/AcctSeedERP__Purchase_Order__c.object
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product on the PO Line
Defaults as the Product listed on the Requisition
PRINTS ON THE PO</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order__c</fullName>
        <inlineHelpText>Purchase Order the PO Line Is associated with</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Quantity__c</fullName>
        <inlineHelpText>Quantity to order
For Subcontractors, enter 1</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vendor_Description__c</fullName>
        <inlineHelpText>Description of the Product for the vendor
PRINTS ON THE PO</inlineHelpText>
        <label>Vendor Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Con_Req__c.object
<CustomObject>
    <fields>
        <fullName>Purchase_Order2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Purchase Order the CO will modify
Must be a PO for the Vendor listed on the CO</inlineHelpText>
        <label>Purchase Order</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Vendor_Account__c</field>
                <operation>equals</operation>
                <valueField>AcctSeedERP__Purchase_Order__c.AcctSeedERP__Vendor__c</valueField>
            </filterItems>
            <filterItems>
                <field>AcctSeedERP__Purchase_Order__c.AcctSeedERP__Status__c</field>
                <operation>notEqual</operation>
                <value>Closed, Rejected, Cancelled</value>
            </filterItems>
            <infoMessage>PO Vendor field must be the same as CO Vendor Account field and PO Status field cannot be Closed, Cancelled, or Rejected.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
        <relationshipLabel>Change Orders</relationshipLabel>
        <relationshipName>Change_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the CO
Controlled by the approval process and recall button</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed by Customer</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Borrego Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>X - Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved By Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Change Order</label>
    <nameField>
        <displayFormat>SF-CR-{000000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__Inventory_Type__c</fullName>
        <inlineHelpText>Type of Inventory for Accounting Seed- Default to Purchased</inlineHelpText>
        <label>Inventory Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Purchased</fullName>
                </value>
                <value>
                    <fullName>Manufactured</fullName>
                </value>
                <value>
                    <fullName>Kit</fullName>
                </value>
                <value>
                    <fullName>Raw Material</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Unit_Cost__c</fullName>
        <inlineHelpText>Used throughout Accounting Seed- Enter $1 for default
Borrego does not use this functionality</inlineHelpText>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Not In Use: See Reasons Not In Use-Requires approval from CC
Project Specific Approved: CC has approved this product for a specific job only
CC Approved for Sale: CC has approved the product
Standard: CC Approved plus installed on min of 2 jobs</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1- Standard</fullName>
                </value>
                <value>
                    <fullName>2- Conditionally Approved</fullName>
                </value>
                <value>
                    <fullName>3- Under Evaluation</fullName>
                </value>
                <value>
                    <fullName>4- Not in Use</fullName>
                    <default>true</default>
                    <label>4- Not in Use</label>
                </value>
                <value>
                    <fullName>5- O&amp;M In Use</fullName>
                </value>
                <value>
                    <fullName>6- O&amp;M Not In Use</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_po_Imbed.cls
/**
 *	Test methods for po_Imbed.cls
 */
@isTest(SeeAllData=true)
private class Test_po_Imbed {
	
	static testMethod void testImbed() {
		PageReference pageRef = Page.po;
		Test.setCurrentPage(pageRef);
		
		AcctSeedERP__Purchase_Order__c po = new AcctSeedERP__Purchase_Order__c ();
		insert po;
		
		Con_Req__c co = new Con_Req__c(Purchase_Order2__c = po.Id, Status__c = 'Borrego Approved');
		insert co;
		
		Product2 pr = new Product2(Name = 'TestProduct', AcctSeed__Inventory_Type__c = 'Purchased', AcctSeed__Unit_Cost__c = 100);
		insert pr;
		
		AcctSeedERP__Purchase_Order_Line__c pol = new AcctSeedERP__Purchase_Order_Line__c(AcctSeedERP__Purchase_Order__c = po.Id, AcctSeedERP__Product__c = pr.Id, AcctSeedERP__Quantity__c = 1, Vendor_Description__c = ' This is the vendor description');
		insert pol;
		
		ApexPages.StandardController con = new ApexPages.StandardController(po);
		
		po_imbed ext = new po_imbed(con);
		ext.getPM();
		ext.getUser();
		ext.getpoClean();
		ext.getListOfPOs();
		ext.getListOfCOs();
	}
    
    static testMethod void testOMPrintPo() {
		PageReference pageRef = Page.OMVFtemplate;
		Test.setCurrentPage(pageRef);
		
		AcctSeedERP__Purchase_Order__c po = new AcctSeedERP__Purchase_Order__c ();
		insert po;
		
		Con_Req__c co = new Con_Req__c(Purchase_Order2__c = po.Id, Status__c = 'Borrego Approved');
		insert co;
		
		Product2 pr = new Product2(Name = 'TestProduct', AcctSeed__Inventory_Type__c = 'Purchased', AcctSeed__Unit_Cost__c = 100);
		insert pr;
		
		AcctSeedERP__Purchase_Order_Line__c pol = new AcctSeedERP__Purchase_Order_Line__c(AcctSeedERP__Purchase_Order__c = po.Id, AcctSeedERP__Product__c = pr.Id, AcctSeedERP__Quantity__c = 1, Vendor_Description__c = ' This is the vendor description');
		insert pol;
		
		ApexPages.StandardController con = new ApexPages.StandardController(po);
		
		OMPrintPO ext = new OMPrintPO(con);
		ext.getPM();
		ext.getUser();
		ext.getpoClean();
		ext.getListOfPOs();
		ext.getListOfCOs();
	}
}