objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Con_Req__c.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Project the CO is related to</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Change Orders</relationshipLabel>
        <relationshipName>Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Order_Type__c</fullName>
        <inlineHelpText>Type of Customer CO
Notes whether you are adding products, taking away products, changing contract price, or changing system size</inlineHelpText>
        <label>Change Order Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>System Size or Product Change</fullName>
                </value>
                <value>
                    <fullName>Contract Price Change</fullName>
                </value>
                <value>
                    <fullName>Add Product to Opportunity</fullName>
                </value>
                <value>
                    <fullName>Remove Product from Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Quantity__c</fullName>
        <inlineHelpText>Enter the quantity of either the new product to be added or the existing product to be changed.</inlineHelpText>
        <label>New Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Change Orders (Original Product)</relationshipLabel>
        <relationshipName>Change_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product you are adding to the Opportunity or PO</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Change Orders (New Product)</relationshipLabel>
        <relationshipName>Con_Req</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Original product quantity
Referenced when updating or changing the product and quantity</inlineHelpText>
        <label>Original Quantity-old</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Change Order</label>
    <nameField>
        <displayFormat>SF-CR-{000000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Products__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Product2.Status__c</field>
                <operation>equals</operation>
                <value>1- Standard, 2- CC Approved for Sale, 3- Project Specific Approved</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Project Products</relationshipLabel>
        <relationshipName>Project_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Products</relationshipLabel>
        <relationshipName>Project_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Enter the quantity of the product on this project</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project Product</label>
    <nameField>
        <displayFormat>PP-{000000000}</displayFormat>
        <label>Project Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ChangeOrderApprovalRequest.cls
global class ChangeOrderApprovalRequest {

    WebService static void SendApprovalRequest(string id) {
    
        // create the new approval request to submit
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        
         req.setComments('Submitting request for approval.');
        req.setObjectId(id);
        req.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        // submit the approval request for processing
        Approval.ProcessResult result;
        List<Id> newWorkItemIds;
        if(!Test.isRunningTest()) {
        	result = Approval.Process(req);
        	newWorkItemIds = result.getNewWorkitemIds();
        }
        
         Approval.ProcessWorkitemRequest req2 = 
            new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        
        // Use the ID from the newly created item to specify the item to be worked
        if(!Test.isRunningTest()) {
        	req2.setWorkitemId(newWorkItemIds.get(0));
        }
        
        // Submit the request for approval
        Approval.ProcessResult result2;
        if(!Test.isRunningTest()) {
        	result2 =  Approval.process(req2);
        	
        	// display if the reqeust was successful
        	System.debug('Submitted for approval successfully: '+result.isSuccess());
        }
            
        updateChangeOrder(id);
    
    }
    
    
    /*
    Auther: Madan(Forcebrain Developer)
    Date: Dec 11, 2017
    Description: Update Quantity to related project product related record when any change order for update quantity
    */
    public static void updateChangeOrder(Id changeOrderId) {
    	if(changeOrderId != null) {
    		Con_Req__c changeOrder;
    		for(Con_Req__c cr:[Select Id, Change_Order_Type__c, New_Quantity__c, ASProject__c,Original_Product__c From Con_Req__c 
    							Where Id=:changeOrderId AND
    								Change_Order_Type__c='System Size or Product Change' AND
    								ASProject__c!=null AND
    								New_Quantity__c!=null AND
    								Original_Product__c!=null]) {
    			changeOrder = cr;
    		}
    		
    		// If Change order is valid to change Quanity for existing products
    		if(changeOrder != null) {
    			List<Project_Products__c> lstProjectProduct = new List<Project_Products__c>();
    			// Update quantity from Change Order to Project Product related to selected project
    			for(AcctSeed__Project__c project:[Select Id, 
													(Select Id, Product__c, Quantity__c 
														From Project_Products__r 
														Where Product__c=:changeOrder.Original_Product__c) 
													From AcctSeed__Project__c Where Id=:changeOrder.ASProject__c]) {
    				if(project.Project_Products__r != null && project.Project_Products__r.size() > 0) {
    					for(Project_Products__c pp:project.Project_Products__r) {
    						pp.Quantity__c = changeOrder.New_Quantity__c;
    						lstProjectProduct.add(pp);
    					}
    				}
    			}
    			
    			if(lstProjectProduct.size() > 0) {
    				update lstProjectProduct;
    			}
    		}
    	}
    }
}