objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related project that the service contract was created for.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <description>Pulling picklist value from contract status from the service contract object. To help with a validation rule for con reqs</description>
        <formula>TEXT( Contract__r.Contract_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pulling picklist value from contract status from the service contract object</inlineHelpText>
        <label>Contract Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ServiceVisit_ProjectCtlExt.cls
public with sharing class ServiceVisit_ProjectCtlExt {
	
	/*
	 *	Service Visit controller extension - allows user to select a project and then to
	 *	select an active contract from a list of contracts related to the project.
	 *
	 */
	
	ApexPages.StandardController stdController;
	
	public SV__c serviceVisit {get; set;}
	public Boolean fatalError {get; set;}
	
	String selectedContract;
	
	public ServiceVisit_ProjectCtlExt(ApexPages.StandardController stdController) {
		
		try {
			this.serviceVisit = (SV__c)stdController.getRecord();
			this.serviceVisit = [select Id, Name, Project__c, Contract__c, Contract__r.ContractNumber from SV__c where Id = :this.serviceVisit.Id];
			fatalError = false;
		} catch(Exception e) {
			fatalError = true;
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Fatal error: ' + e.getMessage()));
		}
	}
	
	public List<SelectOption> getcontracts() {
		List<SelectOption> contractOptions = new List<SelectOption>();
		List<Contract> contractList = new List<Contract>();
		
		selectedContract = null;
		contractOptions.add(new SelectOption('--None--','--None--'));
		if (serviceVisit.Project__c != null) {
			contractList = [select Id, ContractNumber, ASProject__c, Contract_Status__c from Contract where ASProject__c = :serviceVisit.Project__c and Contract_Status__c = 'Active' order by ContractNumber];
			for (Contract c :contractList) {
				contractOptions.add(new SelectOption(c.Id, c.ContractNumber));
				if (serviceVisit.Contract__c == c.Id) {
					selectedContract = c.Id;
				}
			}
			
			if (selectedContract == null) {
				if (serviceVisit.Contract__c != null) {
					contractOptions.add(new SelectOption(serviceVisit.Contract__c, serviceVisit.Contract__r.ContractNumber));
					selectedContract = serviceVisit.Contract__c;
				} else {
					selectedContract = (contractOptions.size() == 2) ? contractOptions[1].getValue() : contractOptions[0].getValue();
				}
			}
		}
		
		return contractOptions;
	}
	
	public String getselectedContract() {
		return selectedContract;
	}
	
	public void setselectedContract(String cId) {
		selectedContract = cId;
	}
	
	public PageReference projectChanged() {
		serviceVisit.Contract__c = null;
		return null;
	}
	
	public PageReference saveServiceVisit() {
		PageReference pr = null;
		
		if (selectedContract == '--None--') {
			selectedContract = null;
		}
		
		serviceVisit.Contract__c = selectedContract;
		try {
			update serviceVisit;
			pr = new PageReference('/' + serviceVisit.Id);
			pr.setRedirect(true);
		} catch(Exception e) {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Service Visit save exception: ' + e.getMessage()));
		}
		
		return pr;
	}
}