objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Direct_Margin__c</fullName>
        <formula>(Final_Contract_PriceProject__c - ( AcctSeed__Budgeted_Amount__c-  Cat_OH_Budgeted2__c ))/Final_Contract_PriceProject__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Direct Margin on the Project
Contract Price-COGS/Contract Price</inlineHelpText>
        <label>Direct Margin %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pricing_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the pricing request associated with this project. Used to drive PVBid integration.</description>
        <inlineHelpText>Lookup to the pricing request associated with this project. Used to drive PVBid integration.</inlineHelpText>
        <label>Pricing Request</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>There are no pricing requests associated with this project&apos;s opportunity.</errorMessage>
            <filterItems>
                <field>$Source.AcctSeed__Opportunity__c</field>
                <operation>equals</operation>
                <valueField>Pricing_Tool_Approval__c.Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pricing_Tool_Approval__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProjectId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Segment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used for reporting and allocation</inlineHelpText>
        <label>Business Unit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Business Unit value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>GL Account Variable 2</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Projects (Business Unit)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Development</fullName>
        <active>true</active>
        <label>Development</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Direct_Margin__c</fullName>
        <label>Direct Margin</label>
        <summarizedField>Pricing_Tool_Approval__c.Direct_Margin__c</summarizedField>
        <summaryFilterItems>
            <field>Pricing_Tool_Approval__c.Status__c</field>
            <operation>equals</operation>
            <value>Final Approval, Approval Pending, Preliminary Approval</value>
        </summaryFilterItems>
        <summaryForeignKey>Pricing_Tool_Approval__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ESU_kWh__c</fullName>
        <label>Energy Storage Unit $/kWh</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>System_kWh__c</fullName>
        <label>Energy Storage System $/kWh</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Utility_Upgrades__c</fullName>
        <inlineHelpText>From most recently approved Pricing Request</inlineHelpText>
        <label>Utility Upgrades</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricing_Tool_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Affiliate_Fee__c</fullName>
        <description>Updated with value from PVbid using PVbid sync button.</description>
        <inlineHelpText>Updated with value from PVbid using PVbid sync button.</inlineHelpText>
        <label>Affiliate Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BidId__c</fullName>
        <description>The ID of the bid within the PVBid system.</description>
        <externalId>true</externalId>
        <inlineHelpText>The ID of the bid within the PVBid system.</inlineHelpText>
        <label>BidId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bid_Title__c</fullName>
        <label>Bid Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bid_URL__c</fullName>
        <label>Bid URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Dev_COGS__c</fullName>
        <description>Updated with value from PVbid using PVbid sync button.</description>
        <inlineHelpText>Updated with value from PVbid using PVbid sync button.</inlineHelpText>
        <label>Dev COGS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Direct_COGS__c</fullName>
        <inlineHelpText>Solar and Storage Total Direct Cost of Goods Sold</inlineHelpText>
        <label>Total Direct COGS $</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Direct_COGS_w__c</fullName>
        <inlineHelpText>Solar and Storage Direct Cost of Goods Sold in dollars per watt</inlineHelpText>
        <label>Total DCOGS $/W</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Direct_Margin__c</fullName>
        <inlineHelpText>Enter the Direct Margin % from the pricing tool, driven by the markup value within PVbid</inlineHelpText>
        <label>Direct Margin % from Pricing Tool</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Direct_Margins__c</fullName>
        <label>Direct Margin $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ESD_Contribution_Margin__c</fullName>
        <inlineHelpText>Energy Storage Department Contribution Margin</inlineHelpText>
        <label>Storage Margin (%)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ESD_Direct_COGS__c</fullName>
        <description>Required if Opportunity includes Storage.</description>
        <inlineHelpText>Energy Storage Division Direct Cost of Goods Sold. Required if Opportunity includes Storage.</inlineHelpText>
        <label>Storage Direct COGS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ESD_Final_Price__c</fullName>
        <inlineHelpText>Energy Storage Department Final Price</inlineHelpText>
        <label>Storage Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ESU_kWh__c</fullName>
        <label>Energy Storage Unit $/kWh</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_EPC_Total__c</fullName>
        <inlineHelpText>(S+S Direct COGS* Markup %) + S+S Direct COGS</inlineHelpText>
        <label>Total Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_EPC_W__c</fullName>
        <label>EPC $/W</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Margin_Percentage__c</fullName>
        <description>Gross Margin Percentage from Pricing Tool</description>
        <inlineHelpText>Gross Margin Percentage from Pricing Tool</inlineHelpText>
        <label>Gross Margin Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gross_Margin_from_the_Pricing_Tool__c</fullName>
        <inlineHelpText>Enter the Gross Margin $ amount from the Pricing Tool</inlineHelpText>
        <label>Gross Margin $ from the Pricing Tool</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ineligible_costs__c</fullName>
        <label>Ineligible costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Module_Price_Assumption__c</fullName>
        <label>Module Price Assumption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>The opportunity that the pricing tool approval is related to</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pricing Requests</relationshipLabel>
        <relationshipName>Pricing_Tool_Approvals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PVBid_Snapshot_Time__c</fullName>
        <description>The timestamp on the PVBid snapshot that is creating when synchronizing the bid.</description>
        <inlineHelpText>The timestamp on the PVBid snapshot that is creating when synchronizing the bid.</inlineHelpText>
        <label>PVBid Snapshot Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PV_Total__c</fullName>
        <label>PV Total $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <description>The ID of the project within the PVBid system.</description>
        <externalId>true</externalId>
        <inlineHelpText>The ID of the project within the PVBid system.</inlineHelpText>
        <label>ProjectId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Approval status of the current pricing tool approval record</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Preliminary Approval</fullName>
                </value>
                <value>
                    <fullName>Final Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Previously Approved</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Storage_Energy_kWh__c</fullName>
        <label>Storage Energy (kWh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Storage_Power_kW__c</fullName>
        <label>Storage Power (kW)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Size_from_Pricing_Tool__c</fullName>
        <inlineHelpText>STC Watts (Pricing inputs cell K188)</inlineHelpText>
        <label>PV System Size from Estimating Tool</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_kWh__c</fullName>
        <label>Energy Storage System $/kWh</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Utility_Upgrades__c</fullName>
        <description>Updated with value from PVbid using PVbid sync button.</description>
        <inlineHelpText>Updated with value from PVbid using PVbid sync button.</inlineHelpText>
        <label>Utility Upgrades</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <label>Pricing Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Requests</pluralLabel>
    <recordTypes>
        <fullName>Development</fullName>
        <active>true</active>
        <label>Development</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Segment__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Shared Services</fullName>
                </value>
                <value>
                    <fullName>EPC</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>ESD</fullName>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PVBidExtension.cls
public without sharing class PVBidExtension {
    final ApexPages.StandardController controller;
    
    /**
     * Variables to sync from PVBid to SFDC
     * */
    public String finalEPC {get; set;}
    public String ineligibleCosts {get; set;}
    public String finalEPCTotal {get; set;}
    public String directMarginPercentage {get; set;}
    public String modulePriceAssumption {get; set;}
    public String systemSize {get; set;}
    public String grossMargin {get; set;}
    public String bidTitle {get; set;}
    public String directMarginDollars {get; set;}
    public String directCOGS {get; set;}
    public String directCOGSPerWatt {get; set;}
    public String grossMarginPercentage {get; set;}
    public String esdCost {get; set;}
    public String esdFinalPrice {get; set;}
    public String snapshotCreationDate {get; set;}
    public String AffiliateFee {get; set;}
     public String UtilityUpgrades{get; set;}
    public string finaldevcogssum{get; set;}
    public string storagemargin{get; set;}
    
    public string storagepower{get; set;}
    public string storageenergy{get; set;}
    public string energystoragesys{get; set;}
    public string enerystorageunit{get; set;}
    public string pvtotal{get; set;}

    
    /**
     * Variables to send to the JavaScript to do its job
     * */
    public Id pricingRequestId;
    public String bidId {get; set;}
    public String projectId {get; set;}
    public Boolean isPricingRequestLocked {get; set;}
    
    /**
     * Variables to keep in memory and potentially modify
     **/
    private Pricing_Tool_Approval__c theRequest;
    
    /**
     * Standard constructor used to initialize the data elements needed for processing within the JavaScript (isLocked, BidId, and ProjectId).
     * 
     * */
    public PVBidExtension (ApexPages.StandardController controller)
    {
        this.controller = controller;
        
        pricingRequestId = controller.getId();
        theRequest = [SELECT Id, BidId__c, ProjectId__c, Status__c FROM Pricing_Tool_Approval__c WHERE Id = :pricingRequestId LIMIT 1];
        
        bidId = theRequest.BidId__c;
        projectId = theRequest.ProjectId__c;
        //isPricingRequestLocked = theRequest.Status__c != 'New' ;
          if((theRequest.Status__c != 'Recalled') && (theRequest.Status__c != 'New'))
          {
            isPricingRequestLocked = true;
          }
    }
    
    /**
     * Called from the JavaScript actionMethod in order to perform all writes to the Salesforce data model.
     * 
     * */
    public PageReference receiveDataFromPVBid () {
        
        // Execute DML to save fields to the database
        Pricing_Tool_Approval__c request = [SELECT Id, Final_EPC_W__c, Ineligible_costs__c, Final_EPC_Total__c, 
                                            Direct_Margin__c, Module_Price_Assumption__c, System_Size_from_Pricing_Tool__c, 
                                            Gross_Margin_from_the_Pricing_Tool__c, Bid_Title__c, Bid_URL__c,
                                            Direct_Margins__c, Direct_COGS__c, Direct_COGS_w__c, Gross_Margin_Percentage__c,
                                            ESD_Final_Price__c, ESD_Direct_COGS__c, PVBid_Snapshot_Time__c,Affiliate_Fee__c,ESD_Contribution_Margin__c,Utility_Upgrades__c ,
                                            Storage_Power_kW__c,Storage_Energy_kWh__c,System_kWh__c,ESU_kWh__c,PV_Total__c

                                            
                                            FROM Pricing_Tool_Approval__c WHERE Id = :pricingRequestId LIMIT 1];
        
       /* AcctSeed__Project__c getbunit = new AcctSeed__Project__c();
        
       getbunit = [select Sales_Segment__r.name from AcctSeed__Project__c where Pricing_Request__c = :pricingRequestId];
        if (getbunit.sales_segment__r.name == 'Development'){
            
            request.Dev_COGS__c = decimal.valueOf(finaldevcogssum);
        }*/
    
        List<Pricing_Tool_Approval__c> getblist =[select Opportunity__r.team__c from Pricing_Tool_Approval__c where id=:pricingRequestid];
        
       Pricing_Tool_Approval__c getbunit=new Pricing_Tool_Approval__c();
      //  getbunit=[];
        if(getblist.size() >0)
        {
            getbunit =getblist.get(0) ;
        system.debug('Team Id' +getbunit);
         AcctSeed__Accounting_Variable__c teamname=new AcctSeed__Accounting_Variable__c ();
            if (!test.isRunningTest())  {
                 teamname=[select name from AcctSeed__Accounting_Variable__c  where id=:getbunit.Opportunity__r.team__c];
            
       
        
           
      if((teamname.name=='Dev - Emerging')||(teamname.name=='Dev - New England')||(teamname.name=='Dev - New York')||(teamname.name=='Dev- Overhead'))
        {
        
         request.Dev_COGS__c = decimal.valueOf(finaldevcogssum);
         }
        }
         }
  
        
        request.Final_EPC_W__c = Decimal.valueOf(finalEPC);
        request.Ineligible_costs__c = Decimal.valueOf(ineligibleCosts);
        request.Final_EPC_Total__c = Decimal.valueOf(finalEPCTotal);
        request.Direct_Margin__c = Decimal.valueOf(directMarginPercentage);
        request.Module_Price_Assumption__c = modulePriceAssumption;
        request.System_Size_from_Pricing_Tool__c = Decimal.valueOf(systemSize);
        request.Gross_Margin_from_the_Pricing_Tool__c = Decimal.valueOf(grossMargin);
        request.Bid_Title__c = bidTitle;
        request.Bid_URL__c = 'https://dashboard.pvbid.com/#!/projects/' + projectId + '/bids/' + bidId + '/fields';
        request.Direct_Margins__c = Decimal.valueOf(directMarginDollars);
        request.Direct_COGS__c = Decimal.valueOf(directCOGS);
        request.Direct_COGS_w__c = Decimal.valueOf(directCOGSPerWatt);
        request.ESD_Final_Price__c = Decimal.valueOf(esdFinalPrice);//made the changes to bring the storage final price from pvbid to salesforce.
        request.ESD_Direct_COGS__c = Decimal.valueOf(esdCost);
        request.Gross_Margin_Percentage__c = Decimal.valueOf(grossMarginPercentage);
        system.debug('AF' +AffiliateFee);
        request.Affiliate_Fee__c=Decimal.valueOf(AffiliateFee);
        request.Utility_Upgrades__c=Decimal.valueOf(UtilityUpgrades);
         request.ESD_Contribution_Margin__c=Decimal.valueOf(storagemargin);
        
        system.debug('look-->' +storagepower);
        if (storagepower !=''){
        request.Storage_Power_kW__c=decimal.valueof(storagepower);
        }
         system.debug('look-->' +storageenergy);
        if (storageenergy !=''){
        request.Storage_Energy_kWh__c=Decimal.valueOf(storageenergy);
        }
         system.debug('look-->' +energystoragesys);
        if (energystoragesys !=''){
        request.System_kWh__c =Decimal.valueOf(energystoragesys);
        }
         system.debug('look-->' +enerystorageunit);
        if (enerystorageunit !=''){
        request.ESU_kWh__c =Decimal.valueOf(enerystorageunit);
        }
         system.debug('look-->' +pvtotal);
        if (pvtotal != ''){
        request.PV_Total__c=Decimal.valueOf(pvtotal);
        }

        
        
        
        if (snapshotCreationDate != null && snapshotCreationDate.length() > 0) {
            
            // Snapshot comes back from PVBid in an unsupported JavaScript date format. Modify the snapshot string so that we can deserialize it in JS and then input into Salesforce.
            String parsableSnapshotTime = '"' + snapshotCreationDate.substring(0, snapshotCreationDate.length() - 6) + '"';
            try {
                request.PVBid_Snapshot_Time__c = (DateTime) JSON.deserialize(parsableSnapshotTime, DateTime.class);
            }
            catch (Exception e) {
                System.debug(LoggingLevel.WARN, 'Failed to parse DateTime from snapshot date=' + parsableSnapshotTime + ', projectId=' + projectId + ', bidId=' + bidId);
            }
        }
         
        // Sync data to the pricing request and then return to the detail page. 
        update request;
        return new PageReference('/' + pricingRequestId);
    }
    
    /**
     * Used to stay on the visualforce page and display an error message. User can escape by pressing the browser back button.
     * */
    public PageReference errorCondition () {
        
        return null;
    }
    
    /**
     * Used to set/update the project/bid ids from within the JavaScript code.
     * 
     * */
    public PageReference setProjectAndBid () {
        theRequest.BidId__c = bidId;
        theRequest.ProjectId__c = projectId;
        update theRequest;
        
        return null;
    }
}