objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Sales_Budget_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales Budget Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Sales Order</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Dynamic_Field_Id_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Con_Req_Group_Project_Field_Id__c</fullName>
        <label>Con Req Group Project Field Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Con_Req_Group_Sales_Order_Field_Id__c</fullName>
        <label>Con Req Group Sales Order Field Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dynamic Field Id Setting</label>
</CustomObject>

classes/constructionreqcontroller.cls
public with sharing class constructionreqcontroller
{
    @AuraEnabled
      
    public  static string redirect(Id ProId) {
        string result;
        //   Dynamic_Field_Id_Setting__c dynamicfieldid=new Dynamic_Field_Id_Setting__c();
        //  List<Dynamic_Field_Id_Setting__c > dynamicid=[select Con_Req_Group_Project_Field_Id__c ,Con_Req_Group_Sales_Order_Field_Id__c from Dynamic_Field_Id_Setting__c];
        // dynamicfieldid=dynamicid.get(0);
        //  string salesorderid=dynamicfieldid.Con_Req_Group_Sales_Order_Field_Id__c;
        //result=salesorderid;
        
        
        
        AcctSeedERP__Sales_Order__c salesvalues=new AcctSeedERP__Sales_Order__c();
        AcctSeed__Project__c projectvalues=new AcctSeed__Project__c ();
        List<AcctSeedERP__Sales_Order__c > sales=[SELECT Id, Name, Project__c FROM AcctSeedERP__Sales_Order__c where Project__c = :ProId Limit 1];
        if(sales.size()>0)
        {
            salesvalues=sales.get(0);
            result=salesvalues.Id;
            
            
            List<AcctSeed__Project__c> project = [SELECT Id, Name, Owner.Name FROM AcctSeed__Project__c where Id = :ProId limit 1];
            if(project.size()>0)
            {
                projectvalues=project.get(0);
                
                string ownername=projectvalues.Owner.Name;
            }
            
            
            
            
            
            
        }
        
        
        else
        {
            String errormsg='Cannot create new Con Req Group unless Project has a Sales Order associated with it.';
            result=errormsg;
        }
        return result;
    }
    
    
    /*  this is th apex class for lightning component Lock sales budget (Project object)  */
   @AuraEnabled      
    public  static string locksales(Id ProId) {
        
        Boolean lockresult;
        string sendlockresult;
        AcctSeed__Project__c lockvalue=new AcctSeed__Project__c ();
        
        
        List<AcctSeed__Project__c> project = [SELECT id,Sales_Budget_Locked__c FROM AcctSeed__Project__c where Id = :ProId limit 1];
        if(project.size()>0){
            lockvalue = project.get(0);
            lockresult = lockvalue.Sales_Budget_Locked__c;
            
        }
        
        system.debug('lock Result-->'  +lockresult);
        if (lockresult == true){
            
            sendlockresult = 'Already Sales budget locked.';
            
        }
        else{
            
          sendlockresult  ='/apex/LockSalesBudget?id='+lockvalue.id;
            
      }
            system.debug('final-->' +sendlockresult);
        return sendlockresult;  
    }
    
}