objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <businessProcess>Project</businessProcess>
        <description>One-off projects such as due diligence visits, retrofits/rebuilds, DAS replacements</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related project that the service contract was created for.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JobNumber__c</fullName>
        <description>cross-object Auto-Fill from SFDC_Project__c  Job_Number__c External ID field upon createProject</description>
        <formula>ASProject__r.Job_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field derives from the Project&apos;s Job Number Example: &quot;901-0004&quot;</inlineHelpText>
        <label>Project Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Case_ProjectCtlExt.cls
public with sharing class Case_ProjectCtlExt 
{

   /*
   *  Case controller for case creation from a Project - creates list of allowable record types
   *  for selection and pre-populates several fields.
   *
   */
   private ApexPages.StandardSetController stdSetCon;
   public List<Contract> selectedContracts;
   
   String Projectnumber;
   String retURL;
  // public List<AcctSeed__Project__c> lstQuery{get;set;}
   public List<Contract> lstQuery{get;set;}
   public Case_ProjectCtlExt(ApexPages.StandardController stdController) 
   {
        this.stdSetCon = stdSetCon;
        system.debug('Controller - '+stdSetCon);
        Projectnumber = ApexPages.currentpage().getParameters().get('JOB_NUMBER');   
        system.debug('Job Id'+Projectnumber);       
        lstQuery=new List<Contract>();
        Contract ctr = new Contract();   
        if(Projectnumber!=NULL)
        {
            string Query='SELECT id,ContractNumber,ASProject__c,Type__c FROM Contract WHERE JobNumber__c =:Projectnumber AND Contract_Status__c=\'ACTIVE\'';
          
            lstQuery=Database.query(Query);
            
            system.debug('No of projects = '+lstQuery.size());
            
            //for(integer i=0;i<lstQuery.size();i++)
            //{
                //ctr = lstQuery.get(0);
                //system.debug('Contractnumber ' +ctr.ContractNumber);
                
            //}
         }
    }
    // public PageReference movetocase() {
        //system.debug('movetocase - '+stdSetCon);
        //PageReference pr = null;
        //selectedContracts = stdSetCon.getSelected();        
        //system.debug('Contract id ' +selectedContracts[0].Id);
        //if (selectedContracts.size() == 1) {
            
            //pr = new PageReference('/apex/Case_Contract?contractId=' + selectedContracts[0].Id + '&retURL=/apex/Case_Tab');
            //pr.setRedirect(true);
            
       // } else {
           // ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'You must select only one Contract.'));
        //}
        
        //return pr;
   // }
}