objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Recurring_Billing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Billing</label>
        <referenceTo>AcctSeed__Recurring_Billing__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to Service Contract</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing_Line__c.object
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <fields>
        <fullName>AcctSeed__Billing__c</fullName>
        <inlineHelpText>Reference to parent object.</inlineHelpText>
        <label>Billing</label>
        <referenceTo>AcctSeed__Billing__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Project_Billing_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Hours_Units__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Quantity for Product Pricing, Hours for Service pricing.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Rate__c</fullName>
        <inlineHelpText>Required- Product or Service Rate</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Upon posting a credit entry will be made to this GL Account and a corresponding debit entry will be made to the AR Control Account set in the Accounting Settings Tab.</inlineHelpText>
        <label>Revenue GL Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Revenue</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Recurring_Billing__c.object
<CustomObject>
    <description>Captures information related to recurring billings associated with customers. A recurring billing is a template for creating billings on a periodic basis.</description>
    <fields>
        <fullName>AcctSeed__Next_Billing_Date__c</fullName>
        <label>Next Billing Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillingDaysinCurrentEscalator__c</fullName>
        <description>used to determine billing rate</description>
        <formula>(CurrentPeriodEndDate__c-CurrentPeriodStartDate__c) 
- 
IF(CurrentPeriodEndDate__c&gt;Service_Contract__r.CurrentEscalatorEndDate__c, 
CurrentPeriodEndDate__c-Service_Contract__r.CurrentEscalatorEndDate__c, 0)
+1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Days in Current Escalator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BillingDaysinPreviousEscalator__c</fullName>
        <description>used for determining the rate on billings</description>
        <formula>IF((CurrentPeriodStartDate__c&lt;Service_Contract__r.CurrentEscalatorStartDate__c), 
(Service_Contract__r.CurrentEscalatorStartDate__c-CurrentPeriodStartDate__c),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Days in Previous Escalator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BillingDaysin__c</fullName>
        <description>used to calculate number of days to bill in next escalator period</description>
        <formula>IF(CurrentPeriodEndDate__c&gt;Service_Contract__r.CurrentEscalatorEndDate__c, 
CurrentPeriodEndDate__c-Service_Contract__r.CurrentEscalatorEndDate__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Days in Next Escalator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Recurring Billings</relationshipLabel>
        <relationshipName>Recurring_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recurring Billing</label>
    <nameField>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>EscalatorYearofContract__c</fullName>
        <formula>IF(ISPICKVAL(Escalator_Details__c, &quot;Increases on anniversary date of contract&quot;), Year_of_Contract__c,
(YEAR(TODAY()) - YEAR( Service_Contract_Start_Date__c ) + 1)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Escalator Year of Contract</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_due_days__c</fullName>
        <inlineHelpText>how many days the customer has to pay us</inlineHelpText>
        <label>Payment due (days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Service_Contract_Escalator__c.object
<CustomObject>
    <description>stores escalator values for each year of service contract</description>
    <fields>
        <fullName>Contract_Value_Per_Day__c</fullName>
        <description>formula based on current year contract value/ 365</description>
        <formula>CurrentYearContractValue__c / ( Service_Contract__r.Current_Year_Contract_End__c - Service_Contract__r.Current_Year_Contract_Start__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>formula based on current year contract value/ 365</inlineHelpText>
        <label>Contract Value Per Day</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <description>displays the related contract</description>
        <inlineHelpText>displays the related contract</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Contract Escalators</relationshipLabel>
        <relationshipName>Service_Contract_Escalators</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>enter in 4 digit year</description>
        <inlineHelpText>enter in 4 digit year</inlineHelpText>
        <label>Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Contract Escalator</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Contract Escalator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Escalators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CalculateBillingLineRate.cls
global class CalculateBillingLineRate
{
   webservice static String CalculateRate(Id customerId, Id recurringbillingId, Id servicecontractId,Id billingrecordId)
   {
         AcctSeed__Recurring_Billing__c recbill1= new AcctSeed__Recurring_Billing__c();
         //AcctSeed__Billing_Line__c recbillingline1= new AcctSeed__Billing_Line__c();
         Contract cont=new Contract(); 
         AcctSeed__Billing_Line__c recbillingline1=[select id from AcctSeed__Billing_Line__c where AcctSeed__Billing__c=:billingrecordId and AcctSeed__Revenue_GL_Account__c='a1m80000000p2kE'];
         
         recbill1 = [SELECT Name,AcctSeed__Next_Billing_Date__c, BillingDaysinCurrentEscalator__c,BillingDaysinPreviousEscalator__c,BillingDaysin__c from AcctSeed__Recurring_Billing__c where id=:recurringbillingId];
         system.debug('Billing Days'+  recbill1.BillingDaysinCurrentEscalator__c);
         system.debug('Prev Billing Days'+  recbill1.BillingDaysinPreviousEscalator__c);
         system.debug('Billing Days in'+  recbill1.BillingDaysin__c );
         cont= [SELECT EscalatorYearofContract__c,Payment_due_days__c FROM Contract where id=:servicecontractId];
         decimal escalator = cont.EscalatorYearofContract__c;
          decimal precontr=escalator - 1;
          decimal nextcontr=escalator + 1;
          
          Service_Contract_Escalator__c serescpre = new Service_Contract_Escalator__c ();
          
          Service_Contract_Escalator__c serescnext = new Service_Contract_Escalator__c ();
          Service_Contract_Escalator__c seresc = new Service_Contract_Escalator__c ();
          
          List<Service_Contract_Escalator__c> liCurr = new List<Service_Contract_Escalator__c>();
          List<Service_Contract_Escalator__c> liNext = new List<Service_Contract_Escalator__c>();
          List<Service_Contract_Escalator__c> liPrev = new List<Service_Contract_Escalator__c>();
            
          liPrev=[select Contract_Value_Per_Day__c from Service_Contract_Escalator__c where Year__c=:precontr and Service_Contract__c=:servicecontractId];
          liNext=[select Contract_Value_Per_Day__c from Service_Contract_Escalator__c where Year__c=:nextcontr and Service_Contract__c=:servicecontractId];
          liCurr=[select Contract_Value_Per_Day__c from Service_Contract_Escalator__c where Year__c=:escalator and Service_Contract__c=:servicecontractId];
          
          decimal calcprevvalue = 0;
          decimal calcnextvalue =0;
          decimal calccurrvalue=0;
          if(liPrev.size() > 0){
              serescpre = liPrev[0];
              system.debug('value per day prev' +serescpre.Contract_Value_Per_Day__c);
              calcprevvalue=serescpre.Contract_Value_Per_Day__c  *  recbill1.BillingDaysinPreviousEscalator__c; 
          }
          if(liNext.size() > 0){
              serescnext= liNext[0];
              system.debug('value per day next' +serescnext.Contract_Value_Per_Day__c);
              calcnextvalue = serescnext.Contract_Value_Per_Day__c * recbill1.BillingDaysin__c;
          }
          if(liCurr.size() > 0)
          {
              seresc= liCurr[0];
              system.debug('value per day current' +seresc.Contract_Value_Per_Day__c);
              calccurrvalue= seresc.Contract_Value_Per_Day__c * recbill1.BillingDaysinCurrentEscalator__c;
          }
          recbillingline1.AcctSeed__Rate__c=calcprevvalue+calcnextvalue+calccurrvalue;
          system.debug('prev'+calcprevvalue+ ' Curr' +calccurrvalue + ' next' +calcnextvalue+ ' total' +recbillingline1.AcctSeed__Rate__c);
          //recbillingline1.AcctSeed__Hours_Units__c=50;
          
          update recbillingline1;
          return 'BillingLine Rate has been updated';
          }
         
          
          }