objects/AcctSeed__Account_Payable__c.object
<CustomObject>
    <description>Used to document liabilities to outside vendor, contact, or employee.</description>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in approvals of accounts payable records and therefore related detail lines. A value of &quot;Posted&quot; indicates the record is final and a debit and credit line have been entered into the transaction object for each account payable line.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>ON HOLD</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payable</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Account_Payable_Line__c.object
<CustomObject>
    <description>Line item expense associated with an payable. The aggregation of multiple payable lines constitute a payable record.</description>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related PO Line for allocation of cost.</inlineHelpText>
        <label>Purchase Order Line</label>
        <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>Account Payable Lines</relationshipLabel>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Account_Payable__c</fullName>
        <inlineHelpText>Reference to Accounts Payable the line is associated with</inlineHelpText>
        <label>Payable</label>
        <referenceTo>AcctSeed__Account_Payable__c</referenceTo>
        <relationshipName>Project_Account_Payable_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Amount__c</fullName>
        <inlineHelpText>Currency field to record amount of line.</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Expense_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Upon posting a debit entry will be made to this account and a corresponding credit entry will be made to the AP Control account set in the Accounting Settings Tab or the AP Control Override indicated in the Account Payable Parent.</inlineHelpText>
        <label>Expense GL Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Expense</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Payable Lines</relationshipLabel>
        <relationshipName>Project_Payable_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Work break down structure for projects, such as: Phases, Deliverables or Roles.</inlineHelpText>
        <label>Project Task</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.AcctSeed__Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project_Task__c</referenceTo>
        <relationshipLabel>Payable Lines</relationshipLabel>
        <relationshipName>Project_Payable_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Project or Job for allocation of cost.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Payable Lines</relationshipLabel>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Change Order for allocation of cost.</inlineHelpText>
        <label>Change Order</label>
        <referenceTo>Con_Req__c</referenceTo>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retention__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the associated retention. If the AP Line is affiliated with a retention, link it here.</inlineHelpText>
        <label>Retention</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AcctSeed__Project__c</field>
                <operation>equals</operation>
                <valueField>Retention__c.Project__c</valueField>
            </filterItems>
            <filterItems>
                <field>Retention__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>AP Retention</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Retention__c</referenceTo>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payable Line</label>
    <nameField>
        <displayFormat>APL-{00000}</displayFormat>
        <label>Payable Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payable Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in filtered look ups to limit the selection of inactive projects.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Change_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change Order</label>
        <referenceTo>Con_Req__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>ChangeOrder</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roll_Up_Account_Payable_Line_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Transaction Amounts for Account Payable Lines- Status= Paid</description>
        <label>Dollars Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Up_All_Account_Payable_Lines__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of all posted account payable lines with GL 36XX for a Project</description>
        <inlineHelpText>Roll up all AP Invoices GL Code 36XX and Posted</inlineHelpText>
        <label>Original JTD Cost Invoiced-NOT USED</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Up_Solar_Account_Payable_Lines__c</fullName>
        <label>Solar Account Payable Lines</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <inlineHelpText>Project the line item is associated with- Automatically fills in when the line item is created from the Project</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in filtered lookups to eliminate inactive and completed projects from selection.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Non_PO_Costs_RollUp__c</fullName>
        <label>Non-PO Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>On_Hold_Invoices__c</fullName>
        <inlineHelpText>Invoices with ON HOLD status, needing a PO</inlineHelpText>
        <label>On Hold Invoices</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Up_All_Account_Payable_Lines__c</fullName>
        <inlineHelpText>Total amount of posted AP Lines affiliated with the line item</inlineHelpText>
        <label>Roll Up AP Lines</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>Roll_Up_All_Account_Payable_Lines__c</fullName>
        <inlineHelpText>Sum of related AP lines (Invoices) that are related to the PO Line</inlineHelpText>
        <label>AP Lines Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Con_Req__c.object
<CustomObject>
    <fields>
        <fullName>AP_Line_CO_Total__c</fullName>
        <description>updated via a Trigger, upon creation of a Change Order with the value in the field Amount of Project CO Total from related project.</description>
        <inlineHelpText>updates with value in the field Amount of Project Change Order Total from related project.</inlineHelpText>
        <label>AP Line CO Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Change Order</label>
    <nameField>
        <displayFormat>SF-CR-{000000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Retention__c.object
<CustomObject>
    <fields>
        <fullName>Roll_Up_AP_Lines__c</fullName>
        <inlineHelpText>The total amount of all related AP Lines.</inlineHelpText>
        <label>Roll Up AP Lines</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Retention</label>
    <nameField>
        <displayFormat>Retention-{00000000}</displayFormat>
        <label>Retention Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retentions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountPayableLineRollUp.cls
public with sharing class AccountPayableLineRollUp {
    
    /*
     *  Methods to rollup the sum of various fields on Account Payable Line records to related objects.
     *  This is performed asynchronously because of the number of queries performed.
     *
     */
    public static Set<Id> setAccountPayableStatusChanged {get;set;}
    
    @future
    public static void rollUpAccountPayableLine(Set<Id> ptIds, Set<Id> pIds, Set<Id> polIds, Set<Id> coIds, Set<Id> rIds) {
        
        //Fields to roll up for all Account Payable Lines
        list<RollUpSummaryUtility.fieldDefinition> fieldDefinitionsSolar = 
            new list<RollUpSummaryUtility.fieldDefinition> {
                new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Amount__c', 'Roll_Up_Solar_Account_Payable_Lines__c')
            };
        
        //Fields to roll up for Posted Account Payable Lines
        list<RollUpSummaryUtility.fieldDefinition> fieldDefinitionsPosted = 
            new list<RollUpSummaryUtility.fieldDefinition> {
                new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Amount__c', 'Roll_Up_Account_Payable_Line_Amount__c')
            };
        
        //Fields to roll up for all Account Payable Lines
        list<RollUpSummaryUtility.fieldDefinition> fieldDefinitionsAll = 
            new list<RollUpSummaryUtility.fieldDefinition> {
                new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Amount__c', 'Roll_Up_All_Account_Payable_Lines__c')
            };
        
        //Fields to roll up for all Account Payable Lines that are on hold
        list<RollUpSummaryUtility.fieldDefinition> fieldDefinitionsAllHold = 
            new list<RollUpSummaryUtility.fieldDefinition> {
                new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Amount__c', 'On_Hold_Invoices__c')
            };
        
        //Fields to roll up for all Account Payable Lines
        list<RollUpSummaryUtility.fieldDefinition> fieldDefinitionsAllCO = 
            new list<RollUpSummaryUtility.fieldDefinition> {
                new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Amount__c', 'AP_Line_CO_Total__c')
            };  
         //system.debug('Amount' +fieldDefinitionsAllCO.AcctSeed__Amount__c);
         
         //system.debug('Co Total' +fieldDefinitionsAllCO.AP_Line_CO_Total__c);
         
        //Fields to roll up for all Account Payable Lines - roll up to Retention
        list<RollUpSummaryUtility.fieldDefinition> fieldDefinitionsRetentionAPL = 
            new list<RollUpSummaryUtility.fieldDefinition> {
                new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Amount__c', 'Roll_Up_AP_Lines__c')
            };
        
        //Fields to roll up for all Account Payable Lines with null CO and null POL - roll up to Project Task
        list<RollUpSummaryUtility.fieldDefinition> fieldDefinitionsNonPOCosts = 
            new list<RollUpSummaryUtility.fieldDefinition> {
                new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Amount__c', 'Non_PO_Costs_RollUp__c')
            };
        
        // Record the parent Ids in APLine records that need to have a roll up calculated
        List<AcctSeed__Account_Payable_Line__c> recordsPT = new List<AcctSeed__Account_Payable_Line__c>();
        for (Id i :ptIds) {
            recordsPT.add(new AcctSeed__Account_Payable_Line__c(AcctSeed__Project_Task__c = i));
        }
        List<AcctSeed__Account_Payable_Line__c> recordsP = new List<AcctSeed__Account_Payable_Line__c>();
        for (Id i :pIds) {
            recordsP.add(new AcctSeed__Account_Payable_Line__c(AcctSeed__Project__c = i));
        }
        List<AcctSeed__Account_Payable_Line__c> recordsPOL = new List<AcctSeed__Account_Payable_Line__c>();
        for (Id i :polIds) {
            recordsPOL.add(new AcctSeed__Account_Payable_Line__c(AcctSeedERP__Purchase_Order_Line__c = i));
        }
        List<AcctSeed__Account_Payable_Line__c> recordsCO = new List<AcctSeed__Account_Payable_Line__c>();
        for (Id i :coIds) {
            recordsCO.add(new AcctSeed__Account_Payable_Line__c(Change_Order__c = i));
        }
        List<AcctSeed__Account_Payable_Line__c> recordsR = new List<AcctSeed__Account_Payable_Line__c>();
        for (Id i :rIds) {
            recordsR.add(new AcctSeed__Account_Payable_Line__c(Retention__c = i));
        }
        
        // Create the Expense GL Account filter and the Project Task record type filter
        List<AcctSeed__GL_Account__c> glaList = new List<AcctSeed__GL_Account__c>();
        glaList = [select Id from AcctSeed__GL_Account__c where Name like '3%'];
        String glaFilter = '';
        if (glaList.size() > 0) {
            glaFilter += ' and (AcctSeed__Expense_GL_Account__c = \'' + glaList[0].Id + '\'';
            for (Integer i=1; i<glaList.size(); i++) {
                glaFilter += ' or AcctSeed__Expense_GL_Account__c = \'' + glaList[i].Id + '\'';
            }
            glaFilter += ')';
        }
        
        Map<String, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName();
        String liFilter = '';
        if (rtMap.containsKey('Budget Line Item')) {
            liFilter = ' and AcctSeed__Project_Task__r.RecordTypeId = \'' + rtMap.get('Budget Line Item').getRecordTypeId() + '\'';
        }
        
        // Set up the Cost Code filters
        RollUpSummaryUtility.costCodeIdFilters ccIdFilters = new RollUpSummaryUtility.costCodeIdFilters();
        String moduleFilter = '';
        if (ccIdFilters.moduleIdFilter != '') {
            moduleFilter = ' and AcctSeed__Account_Payable__r.AcctSeed__Status__c = \'Posted\' and AcctSeed__Project_Task__r.Cost_Code__c in ' + ccIdFilters.moduleIdFilter;
        }
        String solarModuleFilter = '';
        if (ccIdFilters.solarModuleIdFilter != '') {
            solarModuleFilter = ' and AcctSeed__Account_Payable__r.AcctSeed__Status__c = \'Posted\' and AcctSeed__Project_Task__r.Cost_Code__c in ' + ccIdFilters.solarModuleIdFilter;
        }
        
        // Execute the roll ups
        if (!recordsPT.isEmpty()) {
            // Changed By Madan - Sept 11, 2017(Added additional Filter Invoice Status should not be Canceled Or Rejected)
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsAll, recordsPT, 'AcctSeed__Account_Payable_Line__c', 'AcctSeed__Project_Task__c', 'AcctSeed__Project_Task__c', ' and Invoice_Status__c != \'Rejected\' AND Invoice_Status__c != \'Canceled\'' + glaFilter);
            
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsAllHold, recordsPT, 'AcctSeed__Account_Payable_Line__c', 'AcctSeed__Project_Task__c', 'AcctSeed__Project_Task__c', ' and Invoice_Status__c = \'ON HOLD\'');
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsNonPOCosts, recordsPT, 'AcctSeed__Account_Payable_Line__c', 'AcctSeed__Project_Task__c', 'AcctSeed__Project_Task__c', ' and Change_Order__c = null and AcctSeedERP__Purchase_Order_Line__c = null');
        }
        
        if (!recordsP.isEmpty()) {
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsPosted, recordsP, 'AcctSeed__Account_Payable_Line__c', 'AcctSeed__Project__c', 'AcctSeed__Project__c', 'and AcctSeed__Account_Payable__r.AcctSeed__Status__c = \'Posted\' and (AcctSeed__Account_Payable__r.AcctSeed__Payment_Status__c = \'Paid\' or AcctSeed__Account_Payable__r.AcctSeed__Payment_Status__c = \'Partially Paid\')');
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsAll, recordsP, 'AcctSeed__Account_Payable_Line__c', 'AcctSeed__Project__c', 'AcctSeed__Project__c', 'and AcctSeed__Account_Payable__r.AcctSeed__Status__c = \'Posted\'' + glaFilter + liFilter);
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsSolar, recordsP, 'AcctSeed__Account_Payable_Line__c', 'AcctSeed__Project__c', 'AcctSeed__Project__c', solarModuleFilter + ' and Use_Old_CC__c = true');
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsSolar, recordsP, 'AcctSeed__Account_Payable_Line__c', 'AcctSeed__Project__c', 'AcctSeed__Project__c', moduleFilter + ' and Use_Old_CC__c = false');
        }
        
        if (!recordsPOL.isEmpty()) {
            // Changed By Madan - Sept 11, 2017(Added additional Filter Invoice Status should not be Canceled Or Rejected)
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsAll, recordsPOL, 'AcctSeed__Account_Payable_Line__c', 'AcctSeedERP__Purchase_Order_Line__c', 'AcctSeedERP__Purchase_Order_Line__c', ' AND Invoice_Status__c != \'Rejected\' AND Invoice_Status__c!=\'Canceled\' ');
        }
        
        
        system.debug('Roll Up Total' +recordsCO);
        
        system.debug('Total' +fieldDefinitionsAllCO);
        
        if (!recordsCO.isEmpty()) {
        
        system.debug('Entering if condition');
            // Changed By Madan - Sept 11, 2017(Added additional Filter Invoice Status should not be Canceled Or Rejected)
            // changed by divya on 8/28/2019 (additional filter for payment status partially paid on AP)
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsAllCO, recordsCO, 'AcctSeed__Account_Payable_Line__c', 'Change_Order__c', 'Con_req__c', ' AND (Invoice_Status__c!=\'Rejected\' AND Invoice_Status__c!=\'Canceled\') and (AcctSeed__Account_Payable__r.AcctSeed__Status__c != \'Rejected\') and (AcctSeed__Account_Payable__r.AcctSeed__Payment_Status__c = \'Paid\' or AcctSeed__Account_Payable__r.AcctSeed__Payment_Status__c = \'Unpaid\' or AcctSeed__Account_Payable__r.AcctSeed__Payment_Status__c = \'Partially Paid\')');
        }
        
        system.debug('Roll Up Total' +recordsCO);
        
        if (!recordsR.isEmpty()) {
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsRetentionAPL, recordsR, 'AcctSeed__Account_Payable_Line__c', 'Retention__c', 'Retention__c', ' and AcctSeed__Account_Payable__r.AcctSeed__Status__c != \'Rejected\'');
        }
    }
}