objects/AcctSeedERP__Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Status__c</fullName>
        <inlineHelpText>Status of PO
Controlled by Procurement and Accounting</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Aaron Approved</fullName>
                </value>
                <value>
                    <fullName>Procurement Approved</fullName>
                </value>
                <value>
                    <fullName>PM Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Vendor</fullName>
                </value>
                <value>
                    <fullName>Vendor Received PO</fullName>
                </value>
                <value>
                    <fullName>Vendor Shipped Material</fullName>
                </value>
                <value>
                    <fullName>Partially Received: Warehouse</fullName>
                </value>
                <value>
                    <fullName>Partially Received: Job Site</fullName>
                </value>
                <value>
                    <fullName>Received In-Full: Warehouse</fullName>
                </value>
                <value>
                    <fullName>Received In-Full: Job Site</fullName>
                </value>
                <value>
                    <fullName>Material Deposit Paid</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Need More Information</fullName>
                </value>
                <value>
                    <fullName>Invoice Processed</fullName>
                </value>
                <value>
                    <fullName>Order on Hold</fullName>
                </value>
                <value>
                    <fullName>Paid out of Branch Account</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Invoice Received</fullName>
                </value>
                <value>
                    <fullName>Pending Retention Billing</fullName>
                </value>
                <value>
                    <fullName>Bill and Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Commissioning</fullName>
                </value>
                <value>
                    <fullName>Pending Next Milestone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order__c</fullName>
        <inlineHelpText>Purchase Order the PO Line Is associated with</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Unit_Price__c</fullName>
        <inlineHelpText>defaults to $1 when created from a construction requisition
if manually creating, enter $1
Needed for Accounting Seed functionality</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Construction_Req__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Construction Requisition- where the PO Line was generated from
Automatically filled in when the PO Line is created</inlineHelpText>
        <label>Construction Requisition</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Construction Requisition value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>$Source.AcctSeedERP__Project__c</field>
                <operation>equals</operation>
                <valueField>AcctSeedERP__Sales_Order_Line__c.AcctSeedERP__Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeedERP__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PO Line created from the req
This is filled in when the req is converted to a PO</inlineHelpText>
        <label>Purchase Order Line</label>
        <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>Sales Order Line</relationshipLabel>
        <relationshipName>Sales_Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Construction_Req__c</fullName>
        <inlineHelpText>SOL# for Service Requisitions
Will be filled out upon Approval of the Requisition</inlineHelpText>
        <label>Construction Req Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the Req- automatically updated with the approval process</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ASRecallReq.cls
global class ASRecallReq {
    webService static void ASRecallReq(Id[] reqId){
        AcctSeedERP__Sales_Order_Line__c requisition = [select Id, AcctSeedERP__Purchase_Order_Line__c,Status__c from AcctSeedERP__Sales_Order_Line__c where Id in :reqId];      
        List<AcctSeedERP__Purchase_Order_Line__c> ListOfConPO = [select Id,AcctSeedERP__Unit_Price__c from AcctSeedERP__Purchase_Order_Line__c where Id = :requisition.AcctSeedERP__Purchase_Order_Line__c];
        
        If(ListOfConPO!=null && ListOfConPO.size()>0){
            ListOfConPO[0].AcctSeedERP__Unit_Price__c = 0;    
            update ListOfConPO[0];
        }

        requisition.Status__c = 'Recalled'; 
        update requisition;
    }
    
    webService static String ASRecallReqNew(Id reqId) {
    	
    	// Attempt to recall an already approved Contstruction Requisition.  Only allow the recall to happen if the Construction Requisition has
    	// an associated Purchase Order Line whose Purchase Order has a Status field that is either Cancelled or Rejected.
    	AcctSeedERP__Sales_Order_Line__c conreq = new AcctSeedERP__Sales_Order_Line__c();
    	List<AcctSeedERP__Purchase_Order_Line__c> polList = new List<AcctSeedERP__Purchase_Order_Line__c>();
    	AcctSeedERP__Purchase_Order__c po = new AcctSeedERP__Purchase_Order__c();
    	
    	conreq = [SELECT Id, AcctSeedERP__Purchase_Order_Line__c, Status__c, Approval_Status__c FROM AcctSeedERP__Sales_Order_Line__c WHERE Id =: reqId];
    	if (conreq != NULL) {
    		if (conreq.AcctSeedERP__Purchase_Order_Line__c != NULL) {
    			polList = [SELECT Id, AcctSeedERP__Unit_Price__c, Construction_Req__c, AcctSeedERP__Purchase_Order__c FROM AcctSeedERP__Purchase_Order_Line__c 
    							WHERE Id =: conreq.AcctSeedERP__Purchase_Order_Line__c OR Construction_Req__c =: conreq.Id];
    			if (polList.size() > 0) {
    				po = [SELECT Id, AcctSeedERP__Status__c FROM AcctSeedERP__Purchase_Order__c WHERE Id =: polList[0].AcctSeedERP__Purchase_Order__c];
    				if (po.AcctSeedERP__Status__c == 'Cancelled' || po.AcctSeedERP__Status__c == 'Rejected') {
    					for(AcctSeedERP__Purchase_Order_Line__c pol : polList) {
    						pol.AcctSeedERP__Unit_Price__c = 0;
    					}
    					update polList;
    					conreq.Status__c = 'Recalled';
    					conreq.Approval_Status__c = 'Recalled';
    					update conreq;
    				} else {
    					// Error - can't recall a Construction Requisition associated with a PO that is not Cancelled or Rejected
    					return('POerror');
    				}
    			} else {
    				// Error - can't recall a Construction Requisition that does not have a Purchase Order Line
    				return('POLerror');
    			}
    		} else {
    			// Error - can't recall a Construction Requisition that does not have a Purchase Order Line
    			return('POLerror');
    		}
    	} else {
    		// Error - no Construction Requisition provided
    		return('ConReqError');
    	}
    	return('Success');
    }
}