objects/AcctSeed__GL_Account__c.object
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Journal_Entry__c.object
<CustomObject>
    <description>Used to document accounting related entries into the transaction table.</description>
    <label>Journal Entry</label>
    <nameField>
        <label>Journal Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Journal_Entry_Line__c.object
<CustomObject>
    <description>Line level entry associated with a journal entry. The aggregation of multiple journal entry lines constitute a journal entry record.</description>
    <fields>
        <fullName>AcctSeed__Credit__c</fullName>
        <inlineHelpText>The right side of a double entry accounting transaction. Represented as a negative amount in the transactions table.</inlineHelpText>
        <label>Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Debit__c</fullName>
        <inlineHelpText>The left side of a double entry accounting transaction. Represented as a positive amount in the transactions table.</inlineHelpText>
        <label>Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Upon posting a debit or credit entry will be made to this account in transaction table depending on the value entered in the debit or credit field.</inlineHelpText>
        <label>GL Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Expense</value>
            </filterItems>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Balance Sheet</value>
            </filterItems>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Revenue</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Journal Entry Lines</relationshipLabel>
        <relationshipName>Journal_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Journal_Entry__c</fullName>
        <inlineHelpText>Related parent object.</inlineHelpText>
        <label>Journal Entry</label>
        <referenceTo>AcctSeed__Journal_Entry__c</referenceTo>
        <relationshipLabel>Journal Entry Lines</relationshipLabel>
        <relationshipName>Journal_Entry_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Parent_Status__c</fullName>
        <formula>TEXT(AcctSeed__Journal_Entry__r.AcctSeed__Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Work break down structure for projects, such as: Phases, Deliverables or Roles.</inlineHelpText>
        <label>Project Task</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AcctSeed__Project__c</field>
                <operation>equals</operation>
                <valueField>AcctSeed__Project_Task__c.AcctSeed__Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project_Task__c</referenceTo>
        <relationshipLabel>Journal Entry Lines</relationshipLabel>
        <relationshipName>Journal_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Project or Job for allocation of cost.</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Journal Entry Lines</relationshipLabel>
        <relationshipName>Journal_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Old_CC__c</fullName>
        <description>HIdden field - &quot;Use Old CC&quot; field from the related Project record.  Used in the roll up triggers.</description>
        <formula>AcctSeed__Project__r.Use_Old_CC__c</formula>
        <label>Use Old CC</label>
        <type>Checkbox</type>
    </fields>
    <label>Journal Entry Line</label>
    <nameField>
        <displayFormat>JEL-{00000}</displayFormat>
        <label>Journal Entry Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Roll_Up_Journal_Entry_Lines_Credit__c</fullName>
        <label>Roll Up Journal Entry Lines Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Up_Journal_Entry_Lines_Debit__c</fullName>
        <label>Roll Up Journal Entry Lines Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Up_Solar_Journal_Entry_Lines_Credit__c</fullName>
        <label>Solar Journal Entry Lines Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Up_Solar_Journal_Entry_Lines_Debit__c</fullName>
        <label>Solar Journal Entry Lines Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Use_Old_CC__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used for Cost Code migration</inlineHelpText>
        <label>Use Old CC</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <inlineHelpText>Project the line item is associated with- Automatically fills in when the line item is created from the Project</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cost_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Cost code of the line item. Lookup to the Cost Code Object- Must be equal to the Line Item Name</inlineHelpText>
        <label>Cost Code</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.Not_In_Rollup__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Cost_Code__c.Old__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Not_In_Rollup__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Cost_Code__c.Old__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Cost_Code__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roll_Up_Journal_Entry_Credit__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of all Journal Entry Line credits affiliated with Project Task.</description>
        <label>Roll Up Journal Entry Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Roll_Up_Journal_Entry_Debit__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Pull from Journal Entry Line affiliated with Project Task</description>
        <label>Roll Up Journal Entry Debit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Use_Old_CC__c</fullName>
        <description>HIdden field - &quot;Use Old CC&quot; field from the related Project record.  Used in the roll up triggers.</description>
        <formula>AcctSeed__Project__r.Use_Old_CC__c</formula>
        <label>Use Old CC</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Code__c.object
<CustomObject>
    <label>Cost Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JournalPosted.cls
public with sharing class JournalPosted {
    
    /*
     *  Methods to rollup the sum of various fields on Journal Entry Line records to related objects.
     *  This is performed asynchronously because of the number of queries performed.
     *
     */
    
    @future
    public static void rollUpJournalPosted(Set<Id> jeIds, Boolean sendEmail) {
        
        List<AcctSeed__Journal_Entry_Line__c> records = new List<AcctSeed__Journal_Entry_Line__c>();
        records = [select Id, AcctSeed__Debit__c, AcctSeed__Credit__c, AcctSeed__Project_Task__c, AcctSeed__Project__c, Use_Old_CC__c from AcctSeed__Journal_Entry_Line__c where AcctSeed__Journal_Entry__c in :jeIds];
        /*
        List<AcctSeed__Journal_Entry_Line__c> recordsSolar = new List<AcctSeed__Journal_Entry_Line__c>();
        List<AcctSeed__Journal_Entry_Line__c> recordsModule = new List<AcctSeed__Journal_Entry_Line__c>();
        for (AcctSeed__Journal_Entry_Line__c jel :records) {
            if (jel.Use_Old_CC__c) {
                recordsSolar.add(jel);
            } else {
                recordsModule.add(jel);
            }
        }
        */
        
        if (!records.isEmpty()) {
            
            //Fields to roll up for all JournalEntryLine
            List<RollUpSummaryUtility.fieldDefinition> fieldDefinitionsAll = 
                new List<RollUpSummaryUtility.fieldDefinition> {
                    new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Debit__c', 'Roll_Up_Journal_Entry_Debit__c'),
                    new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Credit__c', 'Roll_Up_Journal_Entry_Credit__c')
                };
            
            //Fields to roll up for all JournalEntryLine on Project
            List<RollUpSummaryUtility.fieldDefinition> fieldDefinitionsSolarProject = 
                new List<RollUpSummaryUtility.fieldDefinition> {
                    new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Credit__c', 'Roll_Up_Solar_Journal_Entry_Lines_Credit__c'),
                    new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Debit__c', 'Roll_Up_Solar_Journal_Entry_Lines_Debit__c')
                };
            
            //Fields to roll up for all JournalEntryLine on Project
            List<RollUpSummaryUtility.fieldDefinition> fieldDefinitionsAllProject = 
                new List<RollUpSummaryUtility.fieldDefinition> {
                    new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Debit__c', 'Roll_Up_Journal_Entry_Lines_Debit__c'),
                    new RollUpSummaryUtility.fieldDefinition('SUM', 'AcctSeed__Credit__c', 'Roll_Up_Journal_Entry_Lines_Credit__c')
                };
            
            //Query filter for GL Account
            List<AcctSeed__GL_Account__c> glaList = new List<AcctSeed__GL_Account__c>();
            glaList = [select Id from AcctSeed__GL_Account__c where Name like '36%'];
            String glaFilter = '';
            if (glaList.size() > 0) {
                glaFilter += ' and (AcctSeed__GL_Account__c = \'' + glaList[0].Id + '\'';
                for (Integer i=1; i<glaList.size(); i++) {
                    glaFilter += ' or AcctSeed__GL_Account__c = \'' + glaList[i].Id + '\'';
                }
                glaFilter += ')';
            }
            
            // Query filter for Line Item record type
            List<RecordType> liRtList = new List<RecordType>([select Id from RecordType 
                    where Name = 'Budget Line Item' and SobjectType = 'AcctSeed__Project_Task__c']);
            String liFilter = '';
            if (!liRtList.isEmpty()) {
                liFilter = ' and AcctSeed__Project_Task__r.RecordTypeId = \'' + liRtList[0].Id + '\'';
            }
            
            // Set up the Cost Code filters
            RollUpSummaryUtility.costCodeIdFilters ccIdFilters = new RollUpSummaryUtility.costCodeIdFilters();
            String moduleFilter = '';
            if (ccIdFilters.moduleIdFilter != '') {
                moduleFilter = ' and AcctSeed__Project_Task__r.Cost_Code__c in ' + ccIdFilters.moduleIdFilter;
            }
            String solarModuleFilter = '';
            if (ccIdFilters.solarModuleIdFilter != '') {
                solarModuleFilter = ' and AcctSeed__Project_Task__r.Cost_Code__c in ' + ccIdFilters.solarModuleIdFilter;
            }
            
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsAll, records, 'AcctSeed__Journal_Entry_Line__c', 'AcctSeed__Project_Task__c', 'AcctSeed__Project_Task__c', glaFilter + ' and AcctSeed__Parent_Status__c = \'Posted\' ');
            
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsAllProject, records, 'AcctSeed__Journal_Entry_Line__c', 'AcctSeed__Project__c', 'AcctSeed__Project__c', glaFilter + liFilter + ' and AcctSeed__Parent_Status__c = \'Posted\' ');
            
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsSolarProject, records, 'AcctSeed__Journal_Entry_Line__c', 'AcctSeed__Project__c', 'AcctSeed__Project__c', glaFilter + solarModuleFilter + ' and Use_Old_CC__c = true' + ' and AcctSeed__Parent_Status__c = \'Posted\' ');
            
            RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsSolarProject, records, 'AcctSeed__Journal_Entry_Line__c', 'AcctSeed__Project__c', 'AcctSeed__Project__c', glaFilter + moduleFilter + ' and Use_Old_CC__c = false'  + ' and AcctSeed__Parent_Status__c = \'Posted\' ');
            
            /*
            if (!recordsSolar.isEmpty()) {
                RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsSolarProject, recordsSolar, 'AcctSeed__Journal_Entry_Line__c', 'AcctSeed__Project__c', 'AcctSeed__Project__c', glaFilter + solarModuleFilter + '   and AcctSeed__Parent_Status__c = \'Posted\' ');
            }
            if (!recordsModule.isEmpty()) {
                RollUpSummaryUtility.rollUpTrigger(fieldDefinitionsSolarProject, recordsModule, 'AcctSeed__Journal_Entry_Line__c', 'AcctSeed__Project__c', 'AcctSeed__Project__c', glaFilter + moduleFilter + '   and AcctSeed__Parent_Status__c = \'Posted\' ');
            }
            */
            
            // Send email to running user and owner of the Journal Entry record
            if (sendEmail) {
                String runningUserEmail = UserInfo.getUserEmail();
                List<AcctSeed__Journal_Entry__c> jeList = new List<AcctSeed__Journal_Entry__c>();
                jeList = [select Id, Name, OwnerId, Owner.Email from AcctSeed__Journal_Entry__c where Id in :jeIds];
                Messaging.SingleEmailMessage mail;
                List<String> toAddresses = new List<String>();
                String baseURL = URL.getSalesforceBaseUrl().toExternalForm();
                for (AcctSeed__Journal_Entry__c je :jeList) {
                    mail = new Messaging.SingleEmailMessage();
                    toAddresses.clear();
                    toAddresses.add(runningUserEmail);
                    toAddresses.add(je.Owner.Email);
                    mail.setToAddresses(toAddresses);
                    mail.setSubject('Journal Entry ' + je.Name + ' Post/Unpost Process Complete');
                    mail.setPlainTextBody('The Post/Unpost process has completed for'
                        + ' Journal Entry ' + je.Name
                        + '\n' + baseURL + '/' + je.Id);
                    if (!Test.isRunningTest()) {
                        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                    }
                }
            }
        }
    }
}