objects/AcctSeed__Accounting_Variable__c.object
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>Used to determine GL Account Variables 1-4 and Time Card Variables 1-2.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GL Account Variable 1</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 2</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 3</fullName>
                </value>
                <value>
                    <fullName>GL Account Variable 4</fullName>
                </value>
                <value>
                    <fullName>Time Card Variable 1</fullName>
                </value>
                <value>
                    <fullName>Time Card Variable 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Accounting Variables</relationshipLabel>
        <relationshipName>Accounting_Variables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Set automatically by trigger.  Used by the time card functionality to link a Site record to a Time Card Line.</inlineHelpText>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Accounting Variables</relationshipLabel>
        <relationshipName>Accounting_Variables_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in filtered look ups to limit the selection of inactive projects.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <inlineHelpText>Pulls the install type from the Site

Used by report &apos;Projects with Line Items and Site info&apos; for job cost info</inlineHelpText>
        <label>Site Install Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <inlineHelpText>Project the line item is associated with- Automatically fills in when the line item is created from the Project</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Start_Date__c</fullName>
        <inlineHelpText>The date this Project Task is set to start on.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in filtered lookups to eliminate inactive and completed projects from selection.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Time_Card__c.object
<CustomObject>
    <description>Used to document the time associated with an employee for a given time card period.</description>
    <fields>
        <fullName>AcctSeed__Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Look up to Salesforce User.</inlineHelpText>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in approvals of Time Cards and related detail lines. A value of &quot;Posted&quot; indicates the record is final and a debit and credit line have been entered into the transaction object for each Time Card Day.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Waiting for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Time_Card_Period__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Used for grouping of Time Card Lines. Currently only 7 day Time card periods are supported.</inlineHelpText>
        <label>Time Card Period</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>This Time Period has been Closed. Please contact your administrator to make any changes to this period.</errorMessage>
            <filterItems>
                <field>AcctSeed__Time_Card_Period__c.AcctSeed__Status__c</field>
                <operation>notEqual</operation>
                <value>Closed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Time_Card_Period__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Actual</fullName>
                    <default>true</default>
                    <label>Actual</label>
                </value>
                <value>
                    <fullName>Budget</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Time_Card_Line__c.object
<CustomObject>
    <description>Used to document the project and project task associated with a time card. Time card lines aggregate to a specific time card.</description>
    <fields>
        <fullName>AcctSeed__Project_Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Task</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.AcctSeed__Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project_Task__c</referenceTo>
        <relationshipLabel>Time Card Lines</relationshipLabel>
        <relationshipName>Time_Card_Line_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Time Card Lines</relationshipLabel>
        <relationshipName>Time_Card_Line_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Time_Card_Variable_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter one of the following Categories: 
Development 
Engineering 
Change 
Construction Administration
Overhead - Admin Project</inlineHelpText>
        <label>Time Card Variable 1</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Accounting Variable must have a Type of &quot;Time Card Variable 1&quot;.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Time Card Variable 1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Time Card Lines</relationshipLabel>
        <relationshipName>Time_Card_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Time_Card_Variable_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Time Card Variable 2</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Accounting Variable must have a Type of &quot;Time Card Variable 2&quot;.</errorMessage>
            <filterItems>
                <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Time Card Variable 2</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
        <relationshipLabel>Time Card Lines (Time Card Variable 2)</relationshipLabel>
        <relationshipName>Time_Card_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Time_Card__c</fullName>
        <label>Time Card</label>
        <referenceTo>AcctSeed__Time_Card__c</referenceTo>
        <relationshipName>Time_Card_Line_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Card Line</label>
    <nameField>
        <displayFormat>TCL-{00000}</displayFormat>
        <label>Time Card Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Card Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Time_Card_Period__c.object
<CustomObject>
    <description>Used to capture the specific time frame e.g. start date and end date associated with a time card.</description>
    <fields>
        <fullName>AcctSeed__Start_Date__c</fullName>
        <inlineHelpText>Beginning of the Time Card Period. Typically a Monday or Sunday.</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>&quot;Open&quot; indicates that Time Cards can be entered for this period. &quot;Closed&quot; indicates that no new Time Cards can be entered for this period.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Time Card Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Card Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TimeCardControllerCustom.cls
public with sharing class TimeCardControllerCustom {
    
    // Methods to support custom Time Card and Line Item cloning.
    private final AcctSeed__Time_Card__c tc;
    
    public Boolean isPeriodError {get; set;}
    public Boolean isEmployeeError {get; set;}
    public AcctSeed__Time_Card__c timecard {get; set;}
    public List<AcctSeed__Time_Card_Period__c> tcpList = new List<AcctSeed__Time_Card_Period__c>();
    
    // Initialize by cloning the current Time Card and reading in all current active Time Card Periods
    public TimeCardControllerCustom(ApexPages.StandardController stdController) {
        AcctSeed__Time_Card__c card;
        
        this.tc = (AcctSeed__Time_Card__c)stdController.getRecord();
        isPeriodError = FALSE;
        isEmployeeError = FALSE;
        card = [SELECT Id, AcctSeed__Employee__c, AcctSeed__Time_Card_Period__c, OwnerId FROM AcctSeed__Time_Card__c WHERE Id =: tc.Id];
        system.debug('Look Here Card' +card);
        timecard = card.clone(false,true,false,false);
        system.debug('TC Clone' +timecard);
        timecard.AcctSeed__Time_Card_Period__c = NULL;  // Force user to select a new Time Card Period
        tcpList = [SELECT Id, Name, AcctSeed__Start_Date__c, AcctSeed__Status__c FROM AcctSeed__Time_Card_Period__c WHERE AcctSeed__Status__c =: 'Open' ORDER BY AcctSeed__Start_Date__c ASC];
    }
    
    // Populate and return the drop-down list of Time Card Periods for user selection
    public List<SelectOption> getTimeCardPeriods() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', '--None--'));
        for (AcctSeed__Time_Card_Period__c tcp : tcpList) {
            options.add(new SelectOption(tcp.Id, tcp.Name));
        }
        return options;
    }
    
    // For testing purposes, set the Time Card Period
    public void timeCardPeriodSetForTest(Id tcpId) {
        timecard.AcctSeed__Time_Card_Period__c = tcpId;
    }

/*
    // Save just the Time Card and don't bother with the Line Items
    public PageReference saveTimeCard() {
        Savepoint sp = Database.setSavepoint();
        try {
            insert timecard;
        }
        catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage()));
            Database.rollback(sp);
            return null;
        }
        PageReference tcPage = new ApexPages.Standardcontroller(timecard).view();
        tcPage.setRedirect(true);
        return (tcPage);
    }
*/  

    // Save the cloned Time Card and clone and save associated Line Items
    public PageReference saveCloneLineItems() {
        
        List<AcctSeed__Time_Card_Line__c> tclines = new List<AcctSeed__Time_Card_Line__c>();
        List<AcctSeed__Time_Card_Line__c> tclinesClone = new List<AcctSeed__Time_Card_Line__c>();
        
        isPeriodError = FALSE;
        isEmployeeError = FALSE;
        if (timecard.AcctSeed__Time_Card_Period__c == NULL) {
            isPeriodError = TRUE;
        }
        if (timecard.AcctSeed__Employee__c == NULL) {
            isEmployeeError = TRUE;
        }
        
        if (isPeriodError || isEmployeeError) {
            return NULL;
        }
        
        timecard.OwnerId = UserInfo.getUserId();
        timecard.AcctSeed__Status__c = 'In Process';
        
        Savepoint sp = Database.setSavepoint();
        try {
            system.debug('this is insert');
           insert timecard;
            system.debug('LOOK HERE TC' +tc.Id);
            system.debug('Look here Timecard' +timecard.Id);
            tclines = [SELECT Id, AcctSeed__Time_Card__c, AcctSeed__Project__c, AcctSeed__Project_Task__c, AcctSeed__Time_Card_Variable_1__c, AcctSeed__Time_Card_Variable_2__c FROM AcctSeed__Time_Card_Line__c WHERE AcctSeed__Time_Card__c =: tc.Id];
            system.debug('Look here TCL' +tclines);
            //system.debug('AC2' +tclines.AcctSeed__Time_Card_Variable_2__c);
            for (AcctSeed__Time_Card_Line__c tcl : tclines) {
                tclinesClone.add(
                    new AcctSeed__Time_Card_Line__c(
                        AcctSeed__Time_Card__c = timecard.Id,
                        AcctSeed__Project__c = tcl.AcctSeed__Project__c,
                        AcctSeed__Project_Task__c = tcl.AcctSeed__Project_Task__c,
                        AcctSeed__Time_Card_Variable_1__c = tcl.AcctSeed__Time_Card_Variable_1__c,
                        AcctSeed__Time_Card_Variable_2__c = tcl.AcctSeed__Time_Card_Variable_2__c
                    )
                );  
            }
    
            if (tclinesClone.size() > 0) {
            //tclinesClone=tclines.clone(false);
            insert tclinesClone;
             
             
            }
            //made the changes on 8/12/2020 to fix the accounting seed managed pacakage upgrade duplication error.
            List<AcctSeed__Time_Card_Line__c>tclines1=new List<AcctSeed__Time_Card_Line__c>();
             tclines1 = [SELECT Id, AcctSeed__Time_Card__c, AcctSeed__Project__c, AcctSeed__Project_Task__c, AcctSeed__Time_Card_Variable_1__c, AcctSeed__Time_Card_Variable_2__c FROM AcctSeed__Time_Card_Line__c WHERE( AcctSeed__Time_Card__c =: timecard.Id and AcctSeed__Time_Card_Variable_2__c=null) ];//
             system.debug('Look Here delete' +tclines1);
             if(tclines1 .size()>0)
             {
             delete tclines1 ;
             }
          
        }
        catch(Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage()));
            Database.rollback(sp);
            return null;
        }
        
        PageReference tcPage = new ApexPages.Standardcontroller(timecard).edit();
        tcPage.setRedirect(true);
        return (tcPage);
    }

    @isTest(seeAllData=true)
    public static void TimeCardControllerCustomTest() {
        User[] users;
        AcctSeed__Time_Card_Period__c[] periods;
        
        // Create some dummy data to use for the test
        Profile p = [select id from profile where name='Sys Admin w/o HR'];
        users = [SELECT Id, Name FROM User WHERE ProfileId = :p.Id AND IsActive = true];
        periods = [SELECT Id, Name, AcctSeed__Start_Date__c, AcctSeed__Status__c FROM AcctSeed__Time_Card_Period__c WHERE AcctSeed__Status__c =: 'Open' ORDER BY AcctSeed__Start_Date__c DESC];
        
        //List<AcctSeed__Project__c> projects = new List<AcctSeed__Project__c>();
        //projects = [SELECT Id FROM AcctSeed__Project__c];
        
       
        
        List<AcctSeed__Accounting_Variable__c> accVariable = new List<AcctSeed__Accounting_Variable__c>();
        accVariable = [SELECT Id FROM AcctSeed__Accounting_Variable__c where AcctSeed__Type__c = 'Time Card Variable 1'];
        
       
        
        List<Site__c> sites=new List<Site__c>();
        sites=[select Id,Project__c from Site__c where Project__c!=null limit 1 ];
        Site__c newsite=new Site__c();
        newsite=sites.get(0);
        
         List<AcctSeed__Project_Task__c> projectTasks = new List<AcctSeed__Project_Task__c>();
        projectTasks = [SELECT Id FROM AcctSeed__Project_Task__c where AcctSeed__Project__c=:newsite.Project__c limit 10];
        
        
         List<AcctSeed__Accounting_Variable__c> accVariable1 = new List<AcctSeed__Accounting_Variable__c>();
        accVariable1 = [SELECT Id FROM AcctSeed__Accounting_Variable__c where AcctSeed__Type__c = 'Time Card Variable 2' and Site__c=:newsite.Id];
 
        List<AcctSeed__Time_Card__c> timeCards = new List<AcctSeed__Time_Card__c>();
        timeCards.add(
            new AcctSeed__Time_Card__c(
                AcctSeed__Time_Card_Period__c = periods[1].Id,
                AcctSeed__Employee__c = users[0].Id,
                AcctSeed__Status__c = 'In Process'
            )   
        );
        
        insert timeCards;
        
        List<AcctSeed__Time_Card_Line__c> timeCardLines = new List<AcctSeed__Time_Card_Line__c>();
        
        timeCardLines.add(
            new AcctSeed__Time_Card_Line__c(
               AcctSeed__Project__c = newsite.Project__c,
               AcctSeed__Project_Task__c = projectTasks[0].Id,
               AcctSeed__Time_Card__c = timeCards[0].Id,
               AcctSeed__Time_Card_Variable_1__c = accVariable[0].Id,
                 AcctSeed__Time_Card_Variable_2__c= accVariable1[0].Id,
                Site__c=newsite.Id
            )
        );
        
        timeCardLines.add(
            new AcctSeed__Time_Card_Line__c(
               AcctSeed__Project__c = newsite.Project__c,
               AcctSeed__Project_Task__c = projectTasks[0].Id,
               AcctSeed__Time_Card__c = timeCards[0].Id,
               AcctSeed__Time_Card_Variable_1__c = accVariable[0].Id,
                AcctSeed__Time_Card_Variable_2__c= accVariable1[0].Id,
               Site__c=newsite.Id
                
            )
        );
       insert timeCardLines;
        
        // Add the Id of the dummy Time Card as a parameter to our Page
        ApexPages.currentPage().getParameters().put('id', timeCards[0].Id);
        
        //Instantiate a new controller to test the page
        ApexPages.StandardController std = new ApexPages.StandardController(timeCards[0]);
        TimeCardControllerCustom ctl = new TimeCardControllerCustom(std);
        List<SelectOption> opt = ctl.getTimeCardPeriods();
        ctl.timeCardPeriodSetForTest(periods[0].Id);
        PageReference pr = ctl.saveCloneLineItems();
    }
}