objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <businessProcess>Project</businessProcess>
        <description>One-off projects such as due diligence visits, retrofits/rebuilds, DAS replacements</description>
        <label>Project</label>
    </recordTypes>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <businessProcess>Warranty</businessProcess>
        <description>for all cases that are under Borrego Warranty</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related project that the service contract was created for.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Paid</fullName>
        <active>true</active>
        <description>Paid O&amp;M Service Contracts</description>
        <label>Paid</label>
    </recordTypes>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <description>Used to track warranty claims for all projects</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProjectListView_CreateCaseCtl.cls
public with sharing class ProjectListView_CreateCaseCtl {
    
    public class Contract_Class {
        public Contract contrct {get; set;}
        private String retURL;
        
        Contract_Class(Contract c, String r) {
            this.contrct = c;
            this.retURL = r;
        }
        
        public PageReference createCase() {
            
            String warrantyRecordTypeId = (this.contrct.Contract_Status__c != 'Active') ? String.valueOf(Schema.SObjectType.Case.getRecordTypeInfosByName().get('Warranty').getRecordTypeId()) : '';
            PageReference pr = new PageReference('/apex/Case_Contract?contractId=' + this.contrct.Id + '&caseRecordTypeId=' + warrantyRecordTypeId + '&retURL=' + this.retURL);
            pr.setRedirect(true);
        
            return pr;
        }
    }
    
    public List<Contract_Class> contractDisplayList {get; set;}
    
    public List<AcctSeed__Project__c> selectedProjects;
    
    private ApexPages.StandardSetController stdSetPro;
    private String roleName;
    
    public ProjectListView_CreateCaseCtl(ApexPages.StandardSetController stdSetPro) {
        List<Contract> lstQuery = new List<Contract>();
        String projectId;
        String retURL;
        
        this.stdSetPro = stdSetPro;
        selectedProjects = new List<AcctSeed__Project__c>();
        
        projectId = ApexPages.currentpage().getParameters().get('projectId');
        if (String.isNotBlank(projectId)) {
            retURL = '/' + projectId;
            selectedProjects.add(new AcctSeed__Project__c(Id = projectId));
        } else {
            retURL = '/apex/Project_Tab';
            selectedProjects = stdSetPro.getSelected();
        }
        
        contractDisplayList = new List<Contract_Class>();
        roleName = [select Id, Name from UserRole where Id = : UserInfo.getUserRoleId()].Name;
        
        if (selectedProjects.size() == 1) {
            lstQuery = [select Id, ContractNumber, ASProject__c, Type__c, Contract_Status__c FROM Contract WHERE ASProject__c = :selectedProjects[0].Id and (Contract_Status__c = 'Active' or Contract_Status__c = 'Expired' or Contract_Status__c = 'Paid Contract Complete')];
            for (Contract c :lstQuery) {
                if (roleName == 'O&M Warranty Project Manager') {
                    contractDisplayList.add(new Contract_Class(c, retURL));
                } else {
                    if (c.Contract_Status__c == 'Active') {
                        contractDisplayList.add(new Contract_Class(c, retURL));
                    }
                }
            }
        } else {
            ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'You must select only one Project.'));
        }
    }
}