objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The organization you would like to pay you for your product or service. This is a filtered lookup to the Account where Accounting Status equals &quot;Customer&quot; or &quot;Customer &amp; Vendor&quot;.</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Customer, Customer and Vendor</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Total__c</fullName>
        <inlineHelpText>Grand Total for Billing.</inlineHelpText>
        <label>Total</label>
        <summarizedField>AcctSeed__Billing_Line__c.AcctSeed__Total__c</summarizedField>
        <summaryForeignKey>AcctSeed__Billing_Line__c.AcctSeed__Billing__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Customer_Invoicing_Information__c</fullName>
        <description>This field is used in BillingsevicePDF</description>
        <label>Customer Invoicing Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to Service Contract</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to work order object</description>
        <inlineHelpText>Look up to work order object</inlineHelpText>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing_Line__c.object
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <fields>
        <fullName>AcctSeed__Billing__c</fullName>
        <inlineHelpText>Reference to parent object.</inlineHelpText>
        <label>Billing</label>
        <referenceTo>AcctSeed__Billing__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Project_Billing_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Hours_Units__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Quantity for Product Pricing, Hours for Service pricing.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Rate__c</fullName>
        <inlineHelpText>Required- Product or Service Rate</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Total__c</fullName>
        <formula>AcctSeed__Sub_Total__c +  AcctSeed__Tax_Amount2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Billing Line Total: Hours * Units + Tax</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AvaAcctSeed__LineTax__c</fullName>
        <inlineHelpText>Sales Tax Calculated For This Line - Cannot Be Edited</inlineHelpText>
        <label>Sales Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Categorize the Billing Line - for O&amp;M Billings</inlineHelpText>
        <label>Tax Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cell Modem Plan</fullName>
                    <label>Cell Modem Data Plan</label>
                </value>
                <value>
                    <fullName>Data Storage</fullName>
                </value>
                <value>
                    <fullName>Drive Time/Travel - Internal</fullName>
                </value>
                <value>
                    <fullName>Drive Time/Travel - Sub-C</fullName>
                </value>
                <value>
                    <fullName>Electronic Output</fullName>
                </value>
                <value>
                    <fullName>Engineering Services</fullName>
                </value>
                <value>
                    <fullName>Equipment Rental/Leases</fullName>
                </value>
                <value>
                    <fullName>Insulation Testing</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Labor - Internal</fullName>
                </value>
                <value>
                    <fullName>Labor - Sub-C</fullName>
                </value>
                <value>
                    <fullName>Module Washing</fullName>
                </value>
                <value>
                    <fullName>Optional Extended Warranties</fullName>
                </value>
                <value>
                    <fullName>Parts/Material</fullName>
                </value>
                <value>
                    <fullName>PeGu</fullName>
                </value>
                <value>
                    <fullName>Reimbursable Expenses</fullName>
                </value>
                <value>
                    <fullName>S&amp;H</fullName>
                </value>
                <value>
                    <fullName>Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Service Contract</fullName>
                </value>
                <value>
                    <fullName>Snow Removal</fullName>
                </value>
                <value>
                    <fullName>Storage Rental</fullName>
                    <label>Storage</label>
                </value>
                <value>
                    <fullName>Vegetation Management</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                    <isActive>false</isActive>
                    <label>Admin</label>
                </value>
                <value>
                    <fullName>Admin Hours</fullName>
                    <isActive>false</isActive>
                    <label>Admin Hours</label>
                </value>
                <value>
                    <fullName>Annual Cell Modem Data Plan</fullName>
                    <isActive>false</isActive>
                    <label>Annual Cell Modem Data Plan</label>
                </value>
                <value>
                    <fullName>Approval Fees</fullName>
                    <isActive>false</isActive>
                    <label>Approval Fees</label>
                </value>
                <value>
                    <fullName>Delivery Charge</fullName>
                    <isActive>false</isActive>
                    <label>Delivery Charge Equip Rental/Lease</label>
                </value>
                <value>
                    <fullName>Device Monitoring/Data Storage and Maintenance</fullName>
                    <isActive>false</isActive>
                    <label>Device Monitoring/Data Storage and Maintenance</label>
                </value>
                <value>
                    <fullName>Drive Time/Travel</fullName>
                    <isActive>false</isActive>
                    <label>Drive Time/Travel</label>
                </value>
                <value>
                    <fullName>Environmental Charge</fullName>
                    <isActive>false</isActive>
                    <label>Environmental Fee Equip Rental/Lease</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Enter a description of the Billing Line</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>identifies request in terms of type of work</inlineHelpText>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COO</fullName>
                </value>
                <value>
                    <fullName>Operations</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                    <isActive>false</isActive>
                    <label>Administrative</label>
                </value>
                <value>
                    <fullName>Commissioning</fullName>
                    <isActive>false</isActive>
                    <label>Commissioning</label>
                </value>
                <value>
                    <fullName>Handof</fullName>
                    <isActive>false</isActive>
                    <label>Handof</label>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                    <isActive>false</isActive>
                    <label>Miscellaneous</label>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                    <isActive>false</isActive>
                    <label>Onboarding</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Regional_Manager_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to user record to identify Regional Manager on a contract</description>
        <inlineHelpText>Regional manager on the contract</inlineHelpText>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Performance_Guarantee__c.object
<CustomObject>
    <description>NO LONGER IN USE _ THESE FIELDS HAVE BEEN MOVED TO THE OPPORTUNITY</description>
    <fields>
        <fullName>service_contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used with Lookup Helper</description>
        <inlineHelpText>auto-updates contract associated with project</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Performance Guarantees</relationshipLabel>
        <relationshipName>service_contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Performance Guarantee</label>
    <nameField>
        <displayFormat>PG-{000}</displayFormat>
        <label>Production Guarantee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance Guarantees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BillingServicePDFController.cls
public class BillingServicePDFController {

    public static Double summaryTaxes { get; set; }
    public static String casenumber { get; set; }
    Public static string attname {get; set;}
    public boolean render{get; set;}
    public static list<contact> getattnames {get;set;}
     Public static string managername {get; set;}
     Public static string custinvoiceinfo {get; set;}
    
      
    public List<AcctSeed__Billing_Line__c> billingLines { get; set; }

    public BillingServicePDFController(ApexPages.StandardController controller) {
        summaryTaxes = 0;
        billingLines = new List<AcctSeed__Billing_Line__c>([
                SELECT Id, Category__c,Description__c,
                        AcctSeed__Hours_Units__c, AcctSeed__Rate__c,
                        AcctSeed__Total__c, AvaAcctSeed__LineTax__c,
                        Case__r.Subject, Case__r.CaseNumber,WorkOrder__r.WorkOrderNumber
                FROM AcctSeed__Billing_Line__c
                WHERE AcctSeed__Billing__c = :controller.getId()
        ]);
        for (AcctSeed__Billing_Line__c currBillingLine : billingLines) {
            if (currBillingLine.AvaAcctSeed__LineTax__c != null) {
                summaryTaxes += currBillingLine.AvaAcctSeed__LineTax__c;
                
            }
            casenumber=currBillingLine.Case__r.CaseNumber;
            
        }
       system.debug('this is main id-->' +controller.getId());
            AcctSeed__Billing__c getscno = new AcctSeed__Billing__c();
           getscno= [select  AcctSeed__Customer__r.Id ,AcctSeed__Customer__r.parentId ,AcctSeed__Customer__r.Name,Service_Contract__c,Service_Contract__r.Regional_Manager_User__c,Customer_Invoicing_Information__c from AcctSeed__Billing__c where id =:controller.getId() ];
           system.debug('this is scid-->' +getscno);
            managername = getscno.Service_Contract__r.Regional_Manager_User__c;
             custinvoiceinfo = getscno.Customer_Invoicing_Information__c;
            string accparentid = getscno.AcctSeed__Customer__r.parentId;
   
           system.debug('get id-->' +accparentid);
        
           getattnames = [SELECT email FROM contact where contact_type__c includes ('O&M Billing Contact') and accountid =:accparentid ];//'0013400001PBfH3'
           system.debug('this is the list'  +getattnames);
        
        if (getscno.AcctSeed__Customer__r.Name == 'C2 Special Situations Group'){
            
            render = true;
            
        }
        
          //   list<contact> getattnames = new list<contact>();
          //  list<ContractContactRole> getattnames = new list<ContractContactRole>();
          //  getattnames = [SELECT Contact.name FROM ContractContactRole where contractid=:getscno.Service_Contract__c  ];
  /*          for (contact getnames :getattnames)
        {
            string a;
            if (a ==''){
                
                attname = getnames.email;
                a=getnames.email
            }
            else{
                attname = attname + ',' +getnames.email;
            }
        }    
         system.debug('final names-->' +attname);*/
       /*    string a ='';
           string b ='';
            for(ContractContactRole getnames :getattnames)
            {
                 system.debug('this is getnames--> ' +getnames.contact.name);
                system.debug('this is a--->' +a);
                system.debug('this is attname--->' +attname);
                if (a == ''){
                    
                    b = getnames.contact.name;
                    a= getnames.contact.name;
                }else if( a != getnames.contact.name){
                    
                    b = b +',' + getnames.contact.name;
                    a= getnames.contact.name;
                }
                
              
                    
                    
                }
               
               
                  attname = b;             */
        
    }
    
}