objects/AcctSeedERP__Purchase_Order_Line__c.object
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PO Line created from the req
This is filled in when the req is converted to a PO</inlineHelpText>
        <label>Purchase Order Line</label>
        <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>Sales Order Line</relationshipLabel>
        <relationshipName>Sales_Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testASconPOatt.cls
@isTest(SeeAllData = true)
private class testASconPOatt {
    
    static testMethod void poTest() {
        
        AcctSeedERP__Sales_Order_Line__c[] sol = [select Id, AcctSeedERP__Purchase_Order_Line__c from AcctSeedERP__Sales_Order_Line__c where AcctSeedERP__Purchase_Order_Line__c != null];
        List<AcctSeedERP__Purchase_Order_Line__c> purchaseOrderLines = new List<AcctSeedERP__Purchase_Order_Line__c>();
        purchaseOrderLines = [select Id from AcctSeedERP__Purchase_Order_Line__c where Id = :sol[0].AcctSeedERP__Purchase_Order_Line__c];
        
        //Set Page Parameters
        ApexPages.StandardController con = new ApexPages.StandardController(purchaseOrderLines[0]);
        ASconPOatt ext = new ASconPOatt(con);
        
        //Call all methods on New page 
        ext.getAtts(); 
        ext.getFiles();
     }    
}