objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Shipping_City__c</fullName>
        <inlineHelpText>City where material should be shipped
Pulls from the Ship To Company Account Address
PRINTS ON PO</inlineHelpText>
        <label>Shipping City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Shipping_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Company where material should be shipped
Pulls from the Requisition &quot;Ship To Account&quot; field
PRINTS ON THE PO</inlineHelpText>
        <label>Shipping Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders (Ship To Company)</relationshipLabel>
        <relationshipName>Purchase_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Shipping_Postal_Code__c</fullName>
        <inlineHelpText>Zip Code where material should be shipped 
Pulls from the Ship To Company Account Address 
PRINTS ON PO</inlineHelpText>
        <label>Shipping Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Shipping_State__c</fullName>
        <inlineHelpText>State where material should be shipped 
Pulls from the Ship To Company Account Address 
PRINTS ON PO</inlineHelpText>
        <label>Shipping State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Shipping_Street__c</fullName>
        <inlineHelpText>Street Address where material should be shipped 
Pulls from the Ship To Company Account Address 
PRINTS ON PO</inlineHelpText>
        <label>Shipping Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_Total__c</fullName>
        <formula>Change_Order_Total__c + Total_Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Amount of the Purchase Order
Includes CO&apos;s, Freight, Sales Tax</inlineHelpText>
        <label>PO Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Project_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Line item the PO Line is associated to
Automatically fills in when PO Line is created from a requisition</inlineHelpText>
        <label>Project Task</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.AcctSeedERP__Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project_Task__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Project the PO Line is for</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order__c</fullName>
        <inlineHelpText>Purchase Order the PO Line Is associated with</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>POLine_Total__c</fullName>
        <formula>IF( ISPICKVAL( Final_Invoice_Status__c , &quot;Approved&quot;) || ISPICKVAL( Final_Invoice_Status__c , &quot;Posted&quot;) , Roll_Up_All_Account_Payable_Lines__c , (Unit_Cost__c * AcctSeedERP__Quantity__c) + Freight__c + Sales_Tax__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field computes (Unit Cost X Qty) + Freight + Sales Tax + Use Tax unless this Purchase Order Line is associated with an AP Invoice that is marked Final Invoice.</inlineHelpText>
        <label>POLine Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VendorPOwPOLNotification.cls
public class VendorPOwPOLNotification {
    
    public Id poId {get; set;}
    
    private AcctSeedERP__Purchase_Order__c poRecord;
    private List<AcctSeedERP__Purchase_Order_Line__c> poLines;
    
    public VendorPOwPOLNotification() {
        
        // The poId comes to the page via the visualforce email template (Vendor_PO_w_POL_Notification)
        poRecord = null;
        poLines = null;
    }
    
    public AcctSeedERP__Purchase_Order__c getPurchaseOrder() {
        if (poRecord == null) {
            poRecord = new AcctSeedERP__Purchase_Order__c();
            poRecord = [select Id, Name, PO_Total__c, AcctSeedERP__Shipping_Company__c, AcctSeedERP__Shipping_Street__c, AcctSeedERP__Shipping_City__c, AcctSeedERP__Shipping_State__c,AcctSeedERP__Shipping_Postal_Code__c   from AcctSeedERP__Purchase_Order__c  where Id = :poId ];
            }
          return poRecord;
    }
    
    public List<AcctSeedERP__Purchase_Order_Line__c> getPOLines() {
        if (poLines == null) {
            poLines = new List<AcctSeedERP__Purchase_Order_Line__c>();
            poLines = [select Id, Name, AcctSeedERP__Project__r.Name, POLine_Total__c, AcctSeedERP__Project_Task__r.Name 
                    from AcctSeedERP__Purchase_Order_Line__c where AcctSeedERP__Purchase_Order__c = :poId ];
        }
        return poLines;
    }
}