objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeedERP__Quantity_Ordered__c</fullName>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Budgeted_Revenue__c</fullName>
        <description>Summary of Revenue budgeted at the Project Task Level.</description>
        <inlineHelpText>Total amount of Billing Line Items</inlineHelpText>
        <label>Budgeted Revenue</label>
        <summarizedField>AcctSeed__Project_Task__c.AcctSeed__Budgeted_Revenue__c</summarizedField>
        <summaryForeignKey>AcctSeed__Project_Task__c.AcctSeed__Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <fields>
        <fullName>AcctSeed__Budgeted_Revenue__c</fullName>
        <inlineHelpText>Budgeted Revenue for a Project Task. Amount should be a positive value.
Amount of the line item on the SOV, entered by Accounting</inlineHelpText>
        <label>Budgeted Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Labor_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Upon posting a Time Card. A debit entry will be made to this GL Account and a corresponding credit entry will be made to the Labor GL Account set in the Accounting Settings Tab for each Time Card Day.</inlineHelpText>
        <label>Expense GL Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Expense</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <inlineHelpText>Project the line item is associated with- Automatically fills in when the line item is created from the Project</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Sales Order</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>For Major Component reqs, enter the exact product you are ordering. For all other reqs match the product name to the Line Item/Cost Code.   If that cannot be found enter Miscellaneous.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Sales Order Line</relationshipLabel>
        <relationshipName>Sales_Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Project_Task__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Line Item/Cost Code where the cost should be allocated</inlineHelpText>
        <label>Project Task</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.AcctSeedERP__Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project_Task__c</referenceTo>
        <relationshipLabel>Sales Order Line</relationshipLabel>
        <relationshipName>Sales_Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Project the req is associated with- automatically filled in when creating the req from the Project</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Sales Order Line (Project)</relationshipLabel>
        <relationshipName>Sales_Order_Line1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Quantity_Ordered__c</fullName>
        <inlineHelpText>Quantity of the material needed
For Sub reqs, always enter 1</inlineHelpText>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Sales_Order__c</fullName>
        <inlineHelpText>Sales Order associated with the requisition
Automatically gets entered when creating a req from the Project</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
        <relationshipLabel>Sales Order Line</relationshipLabel>
        <relationshipName>Sales_Order_Line</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Con_Req_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Con Req Group</label>
        <referenceTo>Con_Req_Group__c</referenceTo>
        <relationshipLabel>Construction Requisitions</relationshipLabel>
        <relationshipName>Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Not_To_Exceed__c</fullName>
        <inlineHelpText>Indicates if the PO will be a Not To Exceed PO. Enter an estimated amount that will true up once the final invoice is received.</inlineHelpText>
        <label>Not To Exceed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Product__c</fullName>
        <description>Hidden field used by class file ConstructionReqControllerExt and VF page SalesOrderLine_new to help populate the real Product field.</description>
        <label>Opportunity Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Option 1</fullName>
                </value>
                <value>
                    <fullName>Option 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Requested_Delivery_Date__c</fullName>
        <inlineHelpText>Date the item is needed or date the work will be performed</inlineHelpText>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_Cost__c</fullName>
        <inlineHelpText>This is a editable unit cost to be the POLine unit cost.</inlineHelpText>
        <label>Unit Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Con_Req_Group__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Con Req Groups</relationshipLabel>
        <relationshipName>Con_Req_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Delivery_Date__c</fullName>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
        <relationshipLabel>Con Req Groups</relationshipLabel>
        <relationshipName>Con_Req_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Con Req Group</label>
    <nameField>
        <displayFormat>CRG-{000000}</displayFormat>
        <label>Con Req Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Con Req Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Products__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Product2.Status__c</field>
                <operation>equals</operation>
                <value>1- Standard, 2- CC Approved for Sale, 3- Project Specific Approved</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Project Products</relationshipLabel>
        <relationshipName>Project_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Products</relationshipLabel>
        <relationshipName>Project_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Product</label>
    <nameField>
        <displayFormat>PP-{000000000}</displayFormat>
        <label>Project Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testConReqGroupControllerExt.cls
@isTest(SeeAllData = true)
private class testConReqGroupControllerExt {
    
    /*
     *  Methods for testing ConReqGroupControllerExt.cls
     *
     */
     
     /* code deactivated on 3/22/2019 to push the changeset 'Error was Lastvieweddate' MG*/

   static testMethod void testConReqGroup1() {

        //Initialize all required objects base objects
        TestAllProjectRollUpTriggers.initalizeBaseObjects();
        
        Project_Products__c pp = new Project_Products__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Product__c = TestAllProjectRollUpTriggers.testProduct.Id
        );
        insert pp;

        Test.StartTest();
               
        //Create a new project task
        AcctSeed__Project_Task__c projectTask = new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123);
        insert projectTask;       
        
        //Create a Sales Order Line to use on the Project Task
        AcctSeedERP__Sales_Order_Line__c salesOrderLine = new AcctSeedERP__Sales_Order_Line__c(Unit_Cost__c= 1, AcctSeedERP__Product__c = TestAllProjectRollUpTriggers.testProduct.Id, Opportunity_Product__c = TestAllProjectRollUpTriggers.testProduct.Id, AcctSeedERP__Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id, AcctSeedERP__Quantity_Ordered__c = 1, AcctSeedERP__Project_Task__c = projectTask.Id, AcctSeedERP__Project__c = TestAllProjectRollUpTriggers.testProject.Id);
        insert salesOrderLine;
        
        // Create the Con Req Group object
        Con_Req_Group__c conReqGroup = new Con_Req_Group__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id
        );
        insert conReqGroup;
        salesOrderLine.Con_Req_Group__c = conReqGroup.Id;
        update salesOrderLine;
        
        //Instantiate a new controller
        ApexPages.StandardController std = new ApexPages.StandardController(conReqGroup);
        ConReqGroupControllerExt ctl = new ConReqGroupControllerExt(std);
        
        ctl.getProjProducts();
        ctl.editGroup();
        ctl.cancelGroup();
        ctl.editGroup();
        conReqGroup.Requested_Delivery_Date__c = system.today();
        ctl.saveGroup();
        
        //--------------------
        ctl.submitGroup();
        ctl.clearLock();
        ctl.recallApproved();
        ctl.deleteSolLine();
        
        //-----------------
        Test.stopTest();  
    }
    
    static testMethod void testConReqGroup2() {

        //Initialize all required objects base objects
        TestAllProjectRollUpTriggers.initalizeBaseObjects();
        
        Project_Products__c pp = new Project_Products__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Product__c = TestAllProjectRollUpTriggers.testProduct.Id
        );
        insert pp;

        Test.StartTest();
               
        //Create a new project task
        AcctSeed__Project_Task__c projectTask = new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123);
        insert projectTask;       
        
        //Create a Sales Order Line to use on the Project Task
        AcctSeedERP__Sales_Order_Line__c salesOrderLine = new AcctSeedERP__Sales_Order_Line__c(Unit_Cost__c= 1, AcctSeedERP__Product__c = TestAllProjectRollUpTriggers.testProduct.Id, Opportunity_Product__c = TestAllProjectRollUpTriggers.testProduct.Id, AcctSeedERP__Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id, AcctSeedERP__Quantity_Ordered__c = 1, AcctSeedERP__Project_Task__c = projectTask.Id, AcctSeedERP__Project__c = TestAllProjectRollUpTriggers.testProject.Id);
        insert salesOrderLine;
        
        // Create the Con Req Group object
        Con_Req_Group__c conReqGroup = new Con_Req_Group__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id
        );
        insert conReqGroup;
        salesOrderLine.Con_Req_Group__c = conReqGroup.Id;
        update salesOrderLine;
        
        //Instantiate a new controller
        ApexPages.StandardController std = new ApexPages.StandardController(conReqGroup);
        ConReqGroupControllerExt ctl = new ConReqGroupControllerExt(std);
        
        ctl.detailAllSolLines();
        ctl.cancelAllSolLines();
        ctl.editAllSolLines();
        salesOrderLine.Not_To_Exceed__c = 'Yes';
        ctl.saveAllSolLines();
        
        ApexPages.currentPage().getParameters().put('solId', salesOrderLine.Id);
        
        ctl.detailSolLine();
        ctl.editSolLine();
        ctl.cloneSolLine();
        
        Test.stopTest();  
    }
    
    static testMethod void testConReqGroup3() {

        //Initialize all required objects base objects
        TestAllProjectRollUpTriggers.initalizeBaseObjects();
        
        Project_Products__c pp = new Project_Products__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Product__c = TestAllProjectRollUpTriggers.testProduct.Id
        );
        insert pp;

        Test.StartTest();
               
        //Create a new project task
        AcctSeed__Project_Task__c projectTask = new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123);
        insert projectTask;       
        
        //Create a Sales Order Line to use on the Project Task
        AcctSeedERP__Sales_Order_Line__c salesOrderLine = new AcctSeedERP__Sales_Order_Line__c(Unit_Cost__c= 1, AcctSeedERP__Product__c = TestAllProjectRollUpTriggers.testProduct.Id, Opportunity_Product__c = TestAllProjectRollUpTriggers.testProduct.Id, AcctSeedERP__Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id, AcctSeedERP__Quantity_Ordered__c = 1, AcctSeedERP__Project_Task__c = projectTask.Id, AcctSeedERP__Project__c = TestAllProjectRollUpTriggers.testProject.Id);
        insert salesOrderLine;
        
        // Create the Con Req Group object
        Con_Req_Group__c conReqGroup = new Con_Req_Group__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id
        );
        insert conReqGroup;
        salesOrderLine.Con_Req_Group__c = conReqGroup.Id;
        update salesOrderLine;
        
        //Instantiate a new controller
        ApexPages.StandardController std = new ApexPages.StandardController(conReqGroup);
        ConReqGroupControllerExt ctl = new ConReqGroupControllerExt(std);
        
        ApexPages.currentPage().getParameters().put('solId', salesOrderLine.Id);
        
        ctl.saveSolLine();
        
        Test.stopTest();  
    }
    
    static testMethod void testConReqGroup4() {

        //Initialize all required objects base objects
        TestAllProjectRollUpTriggers.initalizeBaseObjects();
        
        Project_Products__c pp = new Project_Products__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Product__c = TestAllProjectRollUpTriggers.testProduct.Id
        );
        insert pp;

        Test.StartTest();
               
        //Create a new project task
        AcctSeed__Project_Task__c projectTask = new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123);
        insert projectTask;       
        
        //Create a Sales Order Line to use on the Project Task
        AcctSeedERP__Sales_Order_Line__c salesOrderLine = new AcctSeedERP__Sales_Order_Line__c(Unit_Cost__c= 1, AcctSeedERP__Product__c = TestAllProjectRollUpTriggers.testProduct.Id, Opportunity_Product__c = TestAllProjectRollUpTriggers.testProduct.Id, AcctSeedERP__Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id, AcctSeedERP__Quantity_Ordered__c = 1, AcctSeedERP__Project_Task__c = projectTask.Id, AcctSeedERP__Project__c = TestAllProjectRollUpTriggers.testProject.Id);
        insert salesOrderLine;
        
        // Create the Con Req Group object
        Con_Req_Group__c conReqGroup = new Con_Req_Group__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id
        );
        insert conReqGroup;
        salesOrderLine.Con_Req_Group__c = conReqGroup.Id;
        update salesOrderLine;
        
        //Instantiate a new controller
        ApexPages.StandardController std = new ApexPages.StandardController(conReqGroup);
        ConReqGroupControllerExt ctl = new ConReqGroupControllerExt(std);
        
        ApexPages.currentPage().getParameters().put('solId', salesOrderLine.Id);
        
        ctl.saveAndNewSolLine();
        
        Test.stopTest();  
    }
    
    static testMethod void testConReqGroup5() {

        //Initialize all required objects base objects
        TestAllProjectRollUpTriggers.initalizeBaseObjects();
        
        Project_Products__c pp = new Project_Products__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Product__c = TestAllProjectRollUpTriggers.testProduct.Id
        );
        insert pp;

        Test.StartTest();
               
        //Create a new project task
        AcctSeed__Project_Task__c projectTask = new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123);
        insert projectTask;       
        
        //Create a Sales Order Line to use on the Project Task
        AcctSeedERP__Sales_Order_Line__c salesOrderLine = new AcctSeedERP__Sales_Order_Line__c(Unit_Cost__c= 1, AcctSeedERP__Product__c = TestAllProjectRollUpTriggers.testProduct.Id, Opportunity_Product__c = TestAllProjectRollUpTriggers.testProduct.Id, AcctSeedERP__Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id, AcctSeedERP__Quantity_Ordered__c = 1, AcctSeedERP__Project_Task__c = projectTask.Id, AcctSeedERP__Project__c = TestAllProjectRollUpTriggers.testProject.Id);
        insert salesOrderLine;
        
        // Create the Con Req Group object
        Con_Req_Group__c conReqGroup = new Con_Req_Group__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id
        );
        insert conReqGroup;
        salesOrderLine.Con_Req_Group__c = conReqGroup.Id;
        update salesOrderLine;
        
        //Instantiate a new controller
        ApexPages.StandardController std = new ApexPages.StandardController(conReqGroup);
        ConReqGroupControllerExt ctl = new ConReqGroupControllerExt(std);
        
        ApexPages.currentPage().getParameters().put('solId', salesOrderLine.Id);
        ctl.cancelSolLine();
        
        List<SelectOption> options = ctl.getsolRecordTypes();
        ctl.addSolLine();
        ctl.setsolRTSelected(options[0].getValue());
        String rtSelected = ctl.getsolRTSelected();
        ctl.selectSolRecordType();
        ctl.cancelSolRecordType();
        
        Test.stopTest();  
    }
    
    static testMethod void testConReqGroup6() {

        //Initialize all required objects base objects
        TestAllProjectRollUpTriggers.initalizeBaseObjects();
        
        Project_Products__c pp = new Project_Products__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Product__c = TestAllProjectRollUpTriggers.testProduct.Id
        );
        insert pp;

        Test.StartTest();
               
        //Create a new project task
        AcctSeed__Project_Task__c projectTask = new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123);
        insert projectTask;       
        
        //Create a Sales Order Line to use on the Project Task
        AcctSeedERP__Sales_Order_Line__c salesOrderLine = new AcctSeedERP__Sales_Order_Line__c(Unit_Cost__c= 1, AcctSeedERP__Product__c = TestAllProjectRollUpTriggers.testProduct.Id, Opportunity_Product__c = TestAllProjectRollUpTriggers.testProduct.Id, AcctSeedERP__Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id, AcctSeedERP__Quantity_Ordered__c = 1, AcctSeedERP__Project_Task__c = projectTask.Id, AcctSeedERP__Project__c = TestAllProjectRollUpTriggers.testProject.Id);
        insert salesOrderLine;
        
        // Create the Con Req Group object
        Con_Req_Group__c conReqGroup = new Con_Req_Group__c(
            Project__c = TestAllProjectRollUpTriggers.testProject.Id,
            Sales_Order__c = TestAllProjectRollUpTriggers.testSalesOrder.Id
        );
        insert conReqGroup;
        salesOrderLine.Con_Req_Group__c = conReqGroup.Id;
        update salesOrderLine;
        
        Attachment att = new Attachment(
            Body = Blob.valueof('This is the body of the attachment'),
            Name = 'File Attachment',
            ParentId = conReqGroup.Id
        );
        insert att;
        delete att;
        
        Test.stopTest();  
    } 
}