objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Billing_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to configure formatting and display of fields in Billing PDF.</inlineHelpText>
        <label>Billing Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Billing</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Billing</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Project_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The organization you would like to pay you for your product or service. This is a filtered lookup to the Account where Accounting Status equals &quot;Customer&quot; or &quot;Customer &amp; Vendor&quot;.</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Customer, Customer and Vendor</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Date the Billing is issued to the customer.</inlineHelpText>
        <label>Billing Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Due_Date2__c</fullName>
        <inlineHelpText>The Due Date equals the Billing Date plus the Billing Days Due on the associated Account (Customer) record. Otherwise the Due Date defaults to the Billing Date.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Proprietary_Billing_Number__c</fullName>
        <inlineHelpText>For use when you feel salesforce&apos;s auto number will not be adequate for your organization&apos;s needs. Can be used for legacy Billings for loading history as well.</inlineHelpText>
        <label>Proprietary Billing Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Recurring_Billing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Billing</label>
        <referenceTo>AcctSeed__Recurring_Billing__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Number__c</fullName>
        <inlineHelpText>Customer Invoice number</inlineHelpText>
        <label>Application Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to Service Contract</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing_Line__c.object
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <fields>
        <fullName>AcctSeed__Billing__c</fullName>
        <inlineHelpText>Reference to parent object.</inlineHelpText>
        <label>Billing</label>
        <referenceTo>AcctSeed__Billing__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Project_Billing_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Date Product or Service was rendered.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Upon posting a credit entry will be made to this GL Account and a corresponding debit entry will be made to the AR Control Account set in the Accounting Settings Tab.</inlineHelpText>
        <label>Revenue GL Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Revenue</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Recurring_Billing__c.object
<CustomObject>
    <description>Captures information related to recurring billings associated with customers. A recurring billing is a template for creating billings on a periodic basis.</description>
    <fields>
        <fullName>AcctSeed__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Customer, Customer and Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recurring Billings</relationshipLabel>
        <relationshipName>Recurring_Billings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Next_Billing_Date__c</fullName>
        <label>Next Billing Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BillingDaysinCurrentEscalator__c</fullName>
        <description>used to determine billing rate</description>
        <formula>(CurrentPeriodEndDate__c-CurrentPeriodStartDate__c) 
- 
IF(CurrentPeriodEndDate__c&gt;Service_Contract__r.CurrentEscalatorEndDate__c, 
CurrentPeriodEndDate__c-Service_Contract__r.CurrentEscalatorEndDate__c, 0)
+1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Days in Current Escalator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BillingDaysinPreviousEscalator__c</fullName>
        <description>used for determining the rate on billings</description>
        <formula>IF((CurrentPeriodStartDate__c&lt;Service_Contract__r.CurrentEscalatorStartDate__c), 
(Service_Contract__r.CurrentEscalatorStartDate__c-CurrentPeriodStartDate__c),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Days in Previous Escalator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BillingDaysin__c</fullName>
        <description>used to calculate number of days to bill in next escalator period</description>
        <formula>IF(CurrentPeriodEndDate__c&gt;Service_Contract__r.CurrentEscalatorEndDate__c, 
CurrentPeriodEndDate__c-Service_Contract__r.CurrentEscalatorEndDate__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Billing Days in Next Escalator</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CurrentPeriodEndDate__c</fullName>
        <inlineHelpText>End date of the current billing period</inlineHelpText>
        <label>Current Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CurrentPeriodStartDate__c</fullName>
        <inlineHelpText>Date of the current billing period start</inlineHelpText>
        <label>Current Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Recurring Billings</relationshipLabel>
        <relationshipName>Recurring_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recurring Billing</label>
    <nameField>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Recurring_Billing_Line__c.object
<CustomObject>
    <description>Defines the line level detail of a recurring billing. Aggregation of recurring billing lines constitute a recurring billing.</description>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Recurring_Billing__c</fullName>
        <label>Recurring Billing</label>
        <referenceTo>AcctSeed__Recurring_Billing__c</referenceTo>
        <relationshipLabel>Recurring Billing Lines</relationshipLabel>
        <relationshipName>Recurring_Billing_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue GL Account</label>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Recurring Billing Lines</relationshipLabel>
        <relationshipName>Recurring_Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recurring Billing Line</label>
    <nameField>
        <displayFormat>RBL-{00000}</displayFormat>
        <label>Recurring Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related project that the service contract was created for.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EscalatorYearofContract__c</fullName>
        <formula>IF(ISPICKVAL(Escalator_Details__c, &quot;Increases on anniversary date of contract&quot;), Year_of_Contract__c,
(YEAR(TODAY()) - YEAR( Service_Contract_Start_Date__c ) + 1)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Escalator Year of Contract</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_due_days__c</fullName>
        <inlineHelpText>how many days the customer has to pay us</inlineHelpText>
        <label>Payment due (days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Paid</fullName>
        <active>true</active>
        <description>Paid O&amp;M Service Contracts</description>
        <label>Paid</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Service_Contract_Escalator__c.object
<CustomObject>
    <description>stores escalator values for each year of service contract</description>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <description>displays the related contract</description>
        <inlineHelpText>displays the related contract</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Contract Escalators</relationshipLabel>
        <relationshipName>Service_Contract_Escalators</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Contract Escalator</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Contract Escalator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Escalators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateBillingandBillingLine.cls
global class CreateBillingandBillingLine
{
     webservice static String createbilling(Id customerId, Id recurringbillingId, Id servicecontractId,String nextBillingDate) 
     {
     List <AcctSeed__Billing__c > createbilling= new List <AcctSeed__Billing__c>(); 
     List <AcctSeed__Billing_Line__c> createbillingline=new List<AcctSeed__Billing_Line__c >();
         system.debug('Date'+  nextBillingDate);
         //Date nextBillDate =  Date.valueOf(nextBillingDate.replace('/','-'));
         Date nextBillDate =  Date.parse(nextBillingDate);
         system.debug('Date typecaseted value'+  nextBillDate);
         
         AcctSeed__Billing__c bill = new AcctSeed__Billing__c();
         
         AcctSeed__Recurring_Billing__c recbill= new AcctSeed__Recurring_Billing__c(); 
         
         recbill = [SELECT Name,AcctSeed__Next_Billing_Date__c, BillingDaysinCurrentEscalator__c,BillingDaysinPreviousEscalator__c,BillingDaysin__c,CurrentPeriodStartDate__c,CurrentPeriodEndDate__c from AcctSeed__Recurring_Billing__c where id=:recurringbillingId];
         system.debug('Date' +recbill.CurrentPeriodStartDate__c);
         system.debug('Billing Days'+  recbill.BillingDaysinCurrentEscalator__c);
         system.debug('Prev Billing Days'+  recbill.BillingDaysinPreviousEscalator__c);
         system.debug('Billing Days in'+  recbill.BillingDaysin__c );
         
      Date d = recbill.CurrentPeriodStartDate__c;
      string dateStr = DateTime.newInstance(d.year(),d.month(),d.day()).format('MM/dd/yyyy');
         
      Date d1 = recbill.CurrentPeriodEndDate__c;
      string dateStr1 = DateTime.newInstance(d1.year(),d1.month(),d1.day()).format('MM/dd/yyyy');

         
         Contract con=new Contract();
         con = [SELECT EscalatorYearofContract__c,Payment_due_days__c,ASProject__c FROM Contract where id=:servicecontractId];
         
        
         
         bill.AcctSeed__Billing_Format__c='a1U34000003y3Ql';
         bill.AcctSeed__Customer__c=customerId;     
         bill.Service_Contract__c=servicecontractId;
         bill.AcctSeed__Recurring_Billing__c=recurringbillingId;
         bill.Application_Number__c=bill.Name;
         integer daysToAdd = 0;
         if(con.Payment_due_days__c!=null)
         {
             daysToAdd = integer.ValueOf(con.Payment_due_days__c);
         }       
         bill.AcctSeed__Date__c=nextBillDate;
         bill.AcctSeed__Due_Date2__c = bill.AcctSeed__Date__c.addDays(daysToAdd);
         system.debug('Next Due date'+bill.AcctSeed__Due_Date2__c);
         bill.AcctSeed__Proprietary_Billing_Number__c=String.Valueof(recbill.Name) +' ' +'Service' +' ' + String.ValueOf(dateStr) +' ' + ('-') + ' ' + String.ValueOf(dateStr1) ;
       
          createbilling.add(bill);
          insert createbilling;
          
          
          AcctSeed__Billing_Line__c recbillingline= new AcctSeed__Billing_Line__c();
         
          recbillingline.AcctSeed__Revenue_GL_Account__c='a1m80000000p2kE';
          recbillingline.AcctSeed__Date__c=System.today();
          recbillingline.AcctSeed__Project__c=con.ASProject__c;
          recbillingline.AcctSeed__GL_Account_Variable_1__c='a1O80000005KqHT';
          recbillingline.AcctSeed__Hours_Units__c=1;
          AcctSeed__Billing__c bi=[select Name,AcctSeed__Proprietary_Billing_Number__c from AcctSeed__Billing__c where id=:createbilling];
          recbillingline.AcctSeed__Billing__c=bi.id;
          recbillingline.Description__c = bi.AcctSeed__Proprietary_Billing_Number__c;
          system.debug('Escalator curr value' +con.EscalatorYearofContract__c);
          AcctSeed__Recurring_Billing_Line__c RecLineTax =  [SELECT Tax_Category__c FROM AcctSeed__Recurring_Billing_Line__c where  AcctSeed__Recurring_Billing__c=:recurringbillingId];
          recbillingline.Category__c = RecLineTax.Tax_Category__c;
          recbillingline.AcctSeed__Rate__c=1;
          string projectid1= string.valueOf(con.ASProject__c).substring(0,15);
          system.debug('Project Id' +projectid1);
          AcctSeed__Project_Task__c projecttask1=[select id from AcctSeed__Project_Task__c  where AcctSeed__Project__c=:projectid1 and Name='Paid Service-OM'];
          recbillingline.AcctSeed__Project_Task__c=projecttask1.id;
          decimal escalator = con.EscalatorYearofContract__c;
          decimal precontr=escalator - 1;
          decimal nextcontr=escalator + 1;
          
          Service_Contract_Escalator__c serescpre = new Service_Contract_Escalator__c ();
          
          Service_Contract_Escalator__c serescnext = new Service_Contract_Escalator__c ();
          Service_Contract_Escalator__c seresc = new Service_Contract_Escalator__c ();
          
          List<Service_Contract_Escalator__c> liCurr = new List<Service_Contract_Escalator__c>();
          List<Service_Contract_Escalator__c> liNext = new List<Service_Contract_Escalator__c>();
          List<Service_Contract_Escalator__c> liPrev = new List<Service_Contract_Escalator__c>();
            
          liPrev=[select Contract_Value_Per_Day__c from Service_Contract_Escalator__c where Year__c=:precontr and Service_Contract__c=:servicecontractId];
          liNext=[select Contract_Value_Per_Day__c from Service_Contract_Escalator__c where Year__c=:nextcontr and Service_Contract__c=:servicecontractId];
          liCurr=[select Contract_Value_Per_Day__c from Service_Contract_Escalator__c where Year__c=:escalator and Service_Contract__c=:servicecontractId];
          
          decimal calcprevvalue = 0;
          decimal calcnextvalue =0;
          decimal calccurrvalue=0;
          if(liPrev.size() > 0){
              serescpre = liPrev[0];
              system.debug('value per day prev' +serescpre.Contract_Value_Per_Day__c);
              calcprevvalue=serescpre.Contract_Value_Per_Day__c  *  recbill.BillingDaysinPreviousEscalator__c; 
          }
          if(liNext.size() > 0){
              serescnext= liNext[0];
              system.debug('value per day next' +serescnext.Contract_Value_Per_Day__c);
              calcnextvalue = serescnext.Contract_Value_Per_Day__c * recbill.BillingDaysin__c;
          }
          if(liCurr.size() > 0)
          {
              seresc= liCurr[0];
              system.debug('value per day current' +seresc.Contract_Value_Per_Day__c);
              calccurrvalue= seresc.Contract_Value_Per_Day__c * recbill.BillingDaysinCurrentEscalator__c;
              //calccurrvalue=0;
          }
          
          recbillingline.AcctSeed__Rate__c=calcprevvalue+calcnextvalue+calccurrvalue;
          system.debug('prev'+calcprevvalue+ ' Curr' +calccurrvalue + ' next' +calcnextvalue+ ' total' +recbillingline.AcctSeed__Rate__c);
          
          createbillingline.add(recbillingline);
          insert createbillingline; 
          return 'Billing and BillingLine Created';
              
         }
}