objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Budgeted_Revenue__c</fullName>
        <description>Summary of Revenue budgeted at the Project Task Level.</description>
        <inlineHelpText>Total amount of Billing Line Items</inlineHelpText>
        <label>Budgeted Revenue</label>
        <summarizedField>AcctSeed__Project_Task__c.AcctSeed__Budgeted_Revenue__c</summarizedField>
        <summaryForeignKey>AcctSeed__Project_Task__c.AcctSeed__Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PM_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used by Project Managers- Locks PM estimate</inlineHelpText>
        <label>Projection Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <fields>
        <fullName>AcctSeed__Budgeted_Revenue__c</fullName>
        <inlineHelpText>Budgeted Revenue for a Project Task. Amount should be a positive value.
Amount of the line item on the SOV, entered by Accounting</inlineHelpText>
        <label>Budgeted Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Labor_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Upon posting a Time Card. A debit entry will be made to this GL Account and a corresponding credit entry will be made to the Labor GL Account set in the Accounting Settings Tab for each Time Card Day.</inlineHelpText>
        <label>Expense GL Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Expense</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <inlineHelpText>Project the line item is associated with- Automatically fills in when the line item is created from the Project</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <formula>Cost_Code__r.Category__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>References the category of the Cost Code listed</inlineHelpText>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Cost code of the line item. Lookup to the Cost Code Object- Must be equal to the Line Item Name</inlineHelpText>
        <label>Cost Code</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.Not_In_Rollup__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Cost_Code__c.Old__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Not_In_Rollup__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Cost_Code__c.Old__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Cost_Code__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Old__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used for CC migration</inlineHelpText>
        <label>Old</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cost_Code__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grouping__c</fullName>
        <label>Grouping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Civil Subcontracting</fullName>
                </value>
                <value>
                    <fullName>Electrical Materials - Borrego</fullName>
                </value>
                <value>
                    <fullName>Electrical Subcontracting</fullName>
                </value>
                <value>
                    <fullName>Engineering Subcontracting</fullName>
                </value>
                <value>
                    <fullName>ESD</fullName>
                </value>
                <value>
                    <fullName>Materials</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Other Subcontracting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Old__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Old</label>
        <type>Checkbox</type>
    </fields>
    <label>Cost Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testUpdateBudgetsCls.cls
@isTest (SeeAllData = true) 
private class testUpdateBudgetsCls {

    public static testmethod void budgetTest1() { 
		
		//Initialize all required objects base objects
		TestAllProjectRollUpTriggers.initalizeBaseObjects();
		
		//Create a new project task
		AcctSeed__Project_Task__c projectTask = new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123);
		insert projectTask;
		/*
		TestAllProjectRollUpTriggers.testProject.PM_Lock__c = false;
		update TestAllProjectRollUpTriggers.testProject;
		*/
		ApexPages.StandardController stdController = new ApexPages.Standardcontroller(TestAllProjectRollUpTriggers.testProject);
		
		UpdateBudgetsCls theController = new UpdateBudgetsCls(stdController);
		
		List<String> Profiless = new List<String> {'Sys Admin w/o HR','System Administrator'};
		List<profile> profiles = [select id from profile where id=:Userinfo.getProfileId() and name in: Profiless];
		
		if (profiles.isEmpty()) {
			System.assert(!theController.getAmISysAdmin() );
		} else {
			System.assert(theController.getAmISysAdmin() );
		}
		
		List<String> PMProfiles = new List<String> {'Sys Admin w/o HR','System Administrator','Borrego - PM','Borrego - COO','Borrego-Dir of Ops'};
		profiles = [select id from profile where id=:Userinfo.getProfileId() and  name in: PMProfiles];
		
		if (profiles.isEmpty()) {
			System.assert(!theController.getAmIPM() );
		} else {
			System.assert(theController.getAmIPM() );
		}
		theController.getAmIApps();
		
		System.assert(!theController.theProject.PM_Lock__c);
		theController.getUnlock();
		theController.PMsave();
		theController.SaveIt();
		/*
		theController.LockIt();

		System.assert(theController.theProject.PM_Lock__c);
		
		theController.unLockIt();
		System.assert(!theController.theProject.PM_Lock__c);
		
		theController.Cancel();
		
		ApexPages.currentPage().getParameters().put('columnSort', 'Name');
		theController.sortLineItems();
		theController.sortLineItems();
		ApexPages.currentPage().getParameters().put('columnSort', 'Category');
		theController.sortLineItems();
		theController.sortLineItems();
		ApexPages.currentPage().getParameters().put('columnSort', 'Grouping');
		theController.sortLineItems();
		theController.sortLineItems();
		*/
    }
    
    public static testmethod void budgetTest2() { 
		
		//Initialize all required objects base objects
		TestAllProjectRollUpTriggers.initalizeBaseObjects();
		/*
		//Create a new project task
		AcctSeed__Project_Task__c projectTask = new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123);
		insert projectTask;
		
		TestAllProjectRollUpTriggers.testProject.PM_Lock__c = false;
		update TestAllProjectRollUpTriggers.testProject;
		*/
		ApexPages.StandardController stdController = new ApexPages.Standardcontroller(TestAllProjectRollUpTriggers.testProject);
		
		UpdateBudgetsCls theController = new UpdateBudgetsCls(stdController);
		/*
		List<String> Profiless = new List<String> {'Sys Admin w/o HR','System Administrator'};
		List<profile> profiles = [select id from profile where id=:Userinfo.getProfileId() and name in: Profiless];
		
		if (profiles.isEmpty()) {
			System.assert(!theController.getAmISysAdmin() );
		} else {
			System.assert(theController.getAmISysAdmin() );
		}
		
		List<String> PMProfiles = new List<String> {'Sys Admin w/o HR','System Administrator','Borrego - PM','Borrego - COO','Borrego-Dir of Ops'};
		profiles = [select id from profile where id=:Userinfo.getProfileId() and  name in: PMProfiles];
		
		if (profiles.isEmpty()) {
			System.assert(!theController.getAmIPM() );
		} else {
			System.assert(theController.getAmIPM() );
		}
		
		System.assert(!theController.theProject.PM_Lock__c);
		theController.getUnlock();
		theController.PMsave();
		theController.SaveIt();
		*/
		theController.LockIt();

		System.assert(theController.theProject.PM_Lock__c);
		
		theController.unLockIt();
		System.assert(!theController.theProject.PM_Lock__c);
		
		theController.getLock();
		theController.Cancel();
		/*
		ApexPages.currentPage().getParameters().put('columnSort', 'Name');
		theController.sortLineItems();
		theController.sortLineItems();
		ApexPages.currentPage().getParameters().put('columnSort', 'Category');
		theController.sortLineItems();
		theController.sortLineItems();
		ApexPages.currentPage().getParameters().put('columnSort', 'Grouping');
		theController.sortLineItems();
		theController.sortLineItems();
		*/
    }
    
    public static testmethod void budgetTest3() { 
		
		//Initialize all required objects base objects
		TestAllProjectRollUpTriggers.initalizeBaseObjects();
		
		//Create a new project task records
		List<Cost_Code__c> ccList = new List<Cost_Code__c>();
		ccList = [select Id, Category__c, Grouping__c from Cost_Code__c where (Category__c = 'L' or Category__c = 'M' or Category__c = 'S') and Grouping__c != null and Old__c = false and Active__c = true];
		Id cc1Id = null;
		Id cc2Id = null;
		Id cc3Id = null;
		for (Cost_Code__c cc :ccList) {
			if (cc.Category__c == 'M' && cc1Id == null) {
				cc1Id = cc.Id;
			}
			if (cc.Category__c == 'L' && cc2Id == null) {
				cc2Id = cc.Id;
			}
			if (cc.Category__c == 'S' && cc3Id == null) {
				cc3Id = cc.Id;
			}
		}
		List<AcctSeed__Project_Task__c> projectTasks = new List<AcctSeed__Project_Task__c>();
		projectTasks.add(new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task3', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123, Cost_Code__c = cc1Id));
		projectTasks.add(new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task2', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123, Cost_Code__c = cc2Id));
		projectTasks.add(new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task1', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123, Cost_Code__c = cc3Id));
		insert projectTasks;
		/*
		TestAllProjectRollUpTriggers.testProject.PM_Lock__c = false;
		update TestAllProjectRollUpTriggers.testProject;
		*/
		ApexPages.StandardController stdController = new ApexPages.Standardcontroller(TestAllProjectRollUpTriggers.testProject);
		
		UpdateBudgetsCls theController = new UpdateBudgetsCls(stdController);
		/*
		List<String> Profiless = new List<String> {'Sys Admin w/o HR','System Administrator'};
		List<profile> profiles = [select id from profile where id=:Userinfo.getProfileId() and name in: Profiless];
		
		if (profiles.isEmpty()) {
			System.assert(!theController.getAmISysAdmin() );
		} else {
			System.assert(theController.getAmISysAdmin() );
		}
		
		List<String> PMProfiles = new List<String> {'Sys Admin w/o HR','System Administrator','Borrego - PM','Borrego - COO','Borrego-Dir of Ops'};
		profiles = [select id from profile where id=:Userinfo.getProfileId() and  name in: PMProfiles];
		
		if (profiles.isEmpty()) {
			System.assert(!theController.getAmIPM() );
		} else {
			System.assert(theController.getAmIPM() );
		}
		
		System.assert(!theController.theProject.PM_Lock__c);
		theController.getUnlock();
		theController.PMsave();
		theController.SaveIt();
		
		theController.LockIt();

		System.assert(theController.theProject.PM_Lock__c);
		
		theController.unLockIt();
		System.assert(!theController.theProject.PM_Lock__c);
		
		theController.Cancel();
		*/
		ApexPages.currentPage().getParameters().put('columnSort', 'Name');
		theController.sortLineItems();
		theController.sortLineItems();
		ApexPages.currentPage().getParameters().put('columnSort', 'Category');
		theController.sortLineItems();
		theController.sortLineItems();
		ApexPages.currentPage().getParameters().put('columnSort', 'Grouping');
		theController.sortLineItems();
		theController.sortLineItems();
		
		theController.LockSalesBudget();
		theController.unLockSalesBudget();
		
    }
}