objects/AcctSeed__Billing_Format__c.object
<CustomObject>
    <description>Used to store configuration and default settings related to the pdf generation of a record.</description>
    <fields>
        <fullName>AcctSeed__Default_Email_Template__c</fullName>
        <inlineHelpText>This is the email template used when emailing Billing PDF Invoices. Use the Template Unique Name NOT the Template Name when populating this field.</inlineHelpText>
        <label>Default Email Template</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>The type of record this PDF Format is associated.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Purchase Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Visualforce_PDF_Page__c</fullName>
        <inlineHelpText>The API name of the Visualforce page that is used to display the PDF rendition of the Billing.</inlineHelpText>
        <label>Visualforce PDF Page</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PDF Format</label>
    <nameField>
        <label>PDF Format Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PDF Formats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Ledger__c.object
<CustomObject>
    <description>Used to associate and aggregate financial transaction or budget entries with a specific entity.</description>
    <fields>
        <fullName>AcctSeed__Billing_Activity_Statement_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the billing activity statement format here. The billing activity statement format is the PDF format used to send billing activity statements to a customer.</inlineHelpText>
        <label>Billing Activity Statement Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Activity Statement</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Activity Statement</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Ledgers (Billing Activity Statement Format)</relationshipLabel>
        <relationshipName>Billing_Activity_Statement_Formats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Billing_Outstanding_Statement_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the billing outstanding statement format here. The billing outstanding statement format is the PDF format used to send billing outstanding statements to a customer.</inlineHelpText>
        <label>Billing Outstanding Statement Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Outstanding Statement</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Outstanding Statement</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Ledgers (Billing Outstanding Statement Format)</relationshipLabel>
        <relationshipName>Billing_Outstanding_Statement_Formats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Default_Bank_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the account that the majority of payments are made from and that deposits are made to. When entering a cash receipt it will default to this bank account. When creating a cash disbursement batch it will default to this account.</inlineHelpText>
        <label>Default Bank Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Only GL Accounts with Bank checked are allowed.</errorMessage>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Bank__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Ledgers</relationshipLabel>
        <relationshipName>Default_Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Default_Billing_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select your primary billing format here. When you create a billing and leave this field blank, the default billing format will be selected after you press save.</inlineHelpText>
        <label>Default Billing Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Billing</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Billing</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Ledgers</relationshipLabel>
        <relationshipName>Default_Billing_Formats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Default_Packing_Slip_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select your primary packing slip format here. When you create a shipment record and leave this field blank, the default packing slip format will be selected after you press save.</inlineHelpText>
        <label>Default Packing Slip Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Packing Slip</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Packing Slip</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Ledgers (Default Packing Slip Format)</relationshipLabel>
        <relationshipName>Default_Packing_Slip_Formats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Default_Purchase_Order_Format__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select your primary purchase order format here. When you create a purchase order and leave this field blank, the default purchase order format will be selected after you press save.</inlineHelpText>
        <label>Default Purchase Order Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Purchase Order</value>
            </filterItems>
            <infoMessage>The type on the PDF Format must be Purchase Order</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Ledgers (Default Purchase Order Format)</relationshipLabel>
        <relationshipName>Default_Purchase_Order_Formats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget</fullName>
                    <default>true</default>
                    <label>Budget</label>
                </value>
                <value>
                    <fullName>Transactional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Ledger__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Denotes the associated ledger.</inlineHelpText>
        <label>Ledger</label>
        <referenceTo>AcctSeed__Ledger__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order_Format__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Purchase Order Format</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Purchase Order</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order__c</fullName>
        <inlineHelpText>Purchase Order the PO Line Is associated with</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/testVendorPOwPOLNotification.cls
@isTest
private class testVendorPOwPOLNotification {
    
    /*
     *  Test methods for class file VendorPOwPOLNotification.
     *
     */
     
    static testMethod void myUnitTest() {
        
        // Create test data
        AcctSeed__Billing_Format__c pdfFormat = new AcctSeed__Billing_Format__c(Name = 'Other2', AcctSeed__Default_Email_Template__c = 'Billing_Email_Template', AcctSeed__Visualforce_PDF_Page__c = 'Billing_InvoicePDF', AcctSeed__Type__c = 'Purchase Order');
        insert pdfFormat;
        
         List<AcctSeed__Ledger__c> ledgers = new List<AcctSeed__Ledger__c>();

        ledgers.add(
            new AcctSeed__Ledger__c(
                Name = 'Actual',
                AcctSeed__Type__c = 'Transactional',
                AcctSeed__Billing_Activity_Statement_Format__c='a1U34000003y3Ql',
                AcctSeed__Billing_Outstanding_Statement_Format__c='a1U80000000COOs',
                AcctSeed__Default_Bank_Account__c= 'a1m80000000p2ic',
                AcctSeed__Default_Billing_Format__c='a1U80000000AbRO',
                AcctSeed__Default_Purchase_Order_Format__c='a1U80000000COQ8',
                AcctSeed__Default_Packing_Slip_Format__c='a1U34000004Abf2'
                
            )
        );
        
        insert ledgers;
        
        AcctSeedERP__Purchase_Order__c po = new AcctSeedERP__Purchase_Order__c(AcctSeedERP__Purchase_Order_Format__c = pdfFormat.Id,AcctSeedERP__Ledger__c=ledgers[0].Id);
        insert po;
        
        // Test the class file
        VendorPOwPOLNotification ctl = new VendorPOwPOLNotification();
        ctl.poId = po.Id;
        AcctSeedERP__Purchase_Order__c ctlPO = ctl.getPurchaseOrder();
        List<AcctSeedERP__Purchase_Order_Line__c> ctlPOLines = ctl.getPOLines();
    }
}