objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AcctSeedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The service contract associated with the Asset</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the case to a Project
Used in Diaspark Integration</description>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pending_Work__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. The Project on the Asset must match the Project on the Pending Work.</errorMessage>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Asset.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Associated_Case_to_Close__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Case in which the pending work item was addressed</inlineHelpText>
        <label>Associated Case to Close</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Pending Work (Associated Case to Close)</relationshipLabel>
        <relationshipName>Pending_Work1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Contract must be associated with the same Project as the Pending Work</errorMessage>
            <filterItems>
                <field>Contract.ASProject__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description_of_Pending_Work__c</fullName>
        <label>Description of Pending Work</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Display the Status of the Pending Work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WOLI_to_Close__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WOLI to Close</label>
        <referenceTo>WorkOrderLineItem</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order_To_Close__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order To Close</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Pending Work (Work Order To Close)</relationshipLabel>
        <relationshipName>Pending_Work1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pending Work</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Pending Work Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pending Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Project__c.object
<CustomObject>
    <description>Project Management</description>
    <label>SFDCProject</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFDCProjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used with Lookup Helper to associate the WOLI to the Case for reporting</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PendingWorkController.cls
public without sharing class PendingWorkController {
  @TestVisible private static list<String> WORKORDER_STATUS = new list<String>{'New', 'In Progress', 'On Hold'};
  @TestVisible private static list<String> PENDINGWORK_STATUS = new list<String>{'Open'};
  @AuraEnabled
  public static list<Pending_Work__c> getCaseRelatedWork(String caseId) {
    return [
      Select Id, Name, Asset__c, Asset__r.Name, Project__c, Project__r.Name, Contract__c, Contract__r.ContractNumber, Description_of_Pending_Work__c 
      From Pending_Work__c where Project__c in (select Project__c from case where id= :caseId) and status__c in :PENDINGWORK_STATUS order by Name Asc
    ];
  }
  @AuraEnabled
  public static list<WorkOrder> getCaseRelatedWorkOrders(String caseId) {
    return [
      Select Id, WorkOrderNumber, Status 
      From WorkOrder where CaseId = :caseId and Status in :WORKORDER_STATUS order by createddate Desc
    ];
  }
  @AuraEnabled
  public static string createWorkOrderLineItems(String caseId, String workOrderId, list<String> pendingWorkIds){
    list<WorkOrderLineItem> newWorkOrderLineItems = new list<WorkOrderLineItem>();
    list<Pending_Work__c> updatePendingWorkList = new list<Pending_Work__c>();
    //SELECT Id, LineItemNumber, WorkOrderId, Product2Id, AssetId, OrderId, Description, StartDate, EndDate, Status FROM WorkOrderLineItem
    /* rcdSV.Asset__c = pw.pwrk.Asset__c ;
                     rcdSV.Project__c = pw.pwrk.Project__c ;
                     rcdSV.Case__c = rcdCase.id ; //pw.pwrk.Case__c ;  -- 15-08-2018 Updated as per email from Kumar           
                     rcdSV.Contract__c = pw.pwrk.Contract__c; 
                     rcdSV.Account__c = rcdCase.AccountId ; */
    for (Pending_Work__c currentWork : [Select Id, Name, Asset__c, Project__c, Contract__c, Description_of_Pending_Work__c From Pending_Work__c where Id in :pendingWorkIds AND Project__c in (select Project__c from case where id= :caseId) and status__c in :PENDINGWORK_STATUS]) {
      newWorkOrderLineItems.add(new WorkOrderLineItem(
        WorkOrderId = workOrderId,
        AssetId = currentWork.Asset__c,
        description = currentWork.Description_of_Pending_Work__c,
        External_Id__c = currentWork.Id
      ));
      currentWork.Associated_Case_to_Close__c = caseId;
      currentWork.Work_Order_To_Close__c = workOrderId;
      currentWork.Status__c = 'Assigned';
      currentWork.WOLI_To_Close__r = new WorkOrderLineItem(External_Id__c = currentWork.Id);
      updatePendingWorkList.add(currentWork);
    }
    insert newWorkOrderLineItems;
    update updatePendingWorkList;
    return 'success';
  }
}