objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Rebate__c</fullName>
        <description>Automatically populated from the associated Opportunity record Expected Rebate field.</description>
        <formula>AcctSeed__Opportunity__r.Expected_Rebate__c</formula>
        <inlineHelpText>Automatically populated from the associated Opportunity record Expected Rebate field.</inlineHelpText>
        <label>Expected Rebate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <formula>IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;Cash&quot;), &quot;Cash &quot;, NULL) +
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;PPA&quot;), &quot;PPA &quot;, NULL) + 
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;Lease&quot;), &quot;Lease &quot;, NULL) +
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;PACE&quot;), &quot;PACE &quot;, NULL) +  
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;TEML (tax -exempt municipal lease)&quot;), &quot;TEML (tax -exempt municipal lease) &quot;, NULL) + 
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;GO Bond&quot;), &quot;GO Bond &quot;, NULL) +
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;Other&quot;), &quot;Other &quot;, NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>How the project is financed- designated on the Opportunity</inlineHelpText>
        <label>Financing Options Provided</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inverter_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Inverter delivery</inlineHelpText>
        <label>Inverter Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Module_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Module delivery</inlineHelpText>
        <label>Module Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prevailing_Wage__c</fullName>
        <formula>TEXT(AcctSeed__Opportunity__r.Prevailing_Wage__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prevailing Wage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Racking_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Racking delivery</inlineHelpText>
        <label>Racking Delivery Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <businessProcess>Project</businessProcess>
        <description>One-off projects such as due diligence visits, retrofits/rebuilds, DAS replacements</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approximate_Install_Date__c</fullName>
        <description>This is the approximate date that customer expects that installation will begin.</description>
        <inlineHelpText>Required at Project Awarded- This is the approximate date that customer expects that installation will begin.</inlineHelpText>
        <label>Approximate Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Rebate__c</fullName>
        <description>This is the dollar value of the rebate we expect project to be eligable for.</description>
        <inlineHelpText>Expected Rebate Amount- required at Project Awarded. Enter $0 if rebate is not applicable</inlineHelpText>
        <label>Expected Rebate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <inlineHelpText>Denotes the Financing that was selected when the contract was signed.</inlineHelpText>
        <label>Final Financing Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PPA – Borrego</fullName>
                </value>
                <value>
                    <fullName>PPA - 3rd Party</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>HELOC</fullName>
                </value>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PPA</fullName>
                </value>
                <value>
                    <fullName>PACE</fullName>
                </value>
                <value>
                    <fullName>TEML (tax-exempt municipal lease)</fullName>
                </value>
                <value>
                    <fullName>GO Bond</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inverter_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Date of Inverter Delivery</inlineHelpText>
        <label>Inverter Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Module_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Module Delivery Date</inlineHelpText>
        <label>Module Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Contract_System_Size__c</fullName>
        <inlineHelpText>Original Contract System Size in watts- Proposed or executed Contract System Size</inlineHelpText>
        <label>PV System Size - DC (W)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prevailing_Wage__c</fullName>
        <inlineHelpText>Does the contract include Prevailing Wage? Required at Contract Signing</inlineHelpText>
        <label>Prevailing Wage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal_Submitted_Date__c</fullName>
        <label>First Proposal Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_System_Size__c</fullName>
        <inlineHelpText>Current proposed system size in watts</inlineHelpText>
        <label>Proposed System Size (watts)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Racking_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Racking Delivery Date</inlineHelpText>
        <label>Racking Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The individual or entity that will own the system.</inlineHelpText>
        <label>System Owner-Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (System Owner)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Rate__c</fullName>
        <inlineHelpText>What is the host customer&apos;s or offtaker&apos;s current utility rate? You can find this on their bill.</inlineHelpText>
        <label>Current Utility Rate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E A</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E AL-TOU</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E AL-TOU DGR</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E PA</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E PA-T-1</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A6</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A-10</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A-10 TOU</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E E-19</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E E-20</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-1</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-4</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-5</fullName>
                </value>
                <value>
                    <fullName>SCE GS-1</fullName>
                </value>
                <value>
                    <fullName>SCE GS-2</fullName>
                </value>
                <value>
                    <fullName>SCE GS-2 TOU</fullName>
                </value>
                <value>
                    <fullName>SCE GS-3-A</fullName>
                </value>
                <value>
                    <fullName>SCE-GS-3-B</fullName>
                </value>
                <value>
                    <fullName>SCE-GS-3-R</fullName>
                </value>
                <value>
                    <fullName>SCE TOU-8-A</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-B</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-CPP</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-R</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-1</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-2</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-3</fullName>
                </value>
                <value>
                    <fullName>LADWP A1A</fullName>
                </value>
                <value>
                    <fullName>LADWP A2A</fullName>
                </value>
                <value>
                    <fullName>NSTAR B7-TOU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MB_ContentVersionScriptTest.cls
@IsTest
private class MB_ContentVersionScriptTest {
    @IsTest
    static void testBehavior() {

        ASeedAccountingSettingsSetupTest.testDataSetup();
        Account acc = new Account(Name = 'nsvAccount');

        insert acc;
        Contact con = new Contact(FirstName = 'Generic', LastName = 'Technician', Title = 'Solar Tech', AccountId = acc.Id);
        insert con;
        Opportunity testOpportunity = new Opportunity(Name = 'Test test', AccountId = acc.Id, CloseDate = System.today(), Module_Delivery_Date__c =system.now().Date(),
                Inverter_Delivery_Date__c =system.now().Date(), Racking_Delivery_Date__c =system.now().Date(), StageName = 'Project Awarded', Amount = 500000, Proposed_System_Size__c = 10000,
                System_Owner__c = con.Id, Expected_Rebate__c = 0,Utility_Rate__c = 'N/A', Prevailing_Wage__c = 'No', Original_Contract_System_Size__c = 1000,
                Type = 'Turnkey System', Approximate_Install_Date__c = System.today(), Proposal_Submitted_Date__c = System.today(), Financing__c = 'Cash',
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Opportunity').getRecordTypeId());
        insert testOpportunity;
        AcctSeed__Project__c testProject = new AcctSeed__Project__c(Name = 'Knight - 2456',AcctSeed__Account__c = acc.Id, AcctSeed__Opportunity__c = testOpportunity.Id, Branch__c = 'San Diego',PC_Code__c = 10);  // ,PC_Code__c = '10''
        insert testProject;
        Case testNewCase = new Case(AccountId=acc.id,Project__c= testProject.Id);
        insert testNewCase;
        WorkOrder testWorkOrder = new WorkOrder(CaseId=testNewCase.Id,WorkTypeId='08q2H0000008OIjQAM');
        insert testWorkOrder;
        system.debug('work order' +testWorkOrder);
        workorderlineitem testwolineitem = new workorderlineitem(WorkOrderId =testWorkOrder.Id);
        insert testwolineitem;
        Checklist__c checklst = new Checklist__c(Work_Order_Line_Item__c = testwolineitem.Id );
        insert checklst;

        //testwolineitem.Checklist__c=checklst.Id;
        //update testwolineitem;

        RecordType ContentRT = [select Id FROM RecordType WHERE name='Standard Work/SOP'];

        ContentVersion ContentDoc = new ContentVersion();
        ContentDoc.Title = 'My Doc';
        ContentDoc.Description ='test';
        ContentDoc.RecordTypeId = ContentRT.Id; //'01234000000GGcgAAG';
        ContentDoc.ContentUrl= 'test.com';
        Insert ContentDoc;

         List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
         //create ContentDocumentLink  record

         ContentDocumentLink cdl = New ContentDocumentLink();
         cdl.LinkedEntityId = checklst.id;
         cdl.ContentDocumentId = documents[0].Id;
         cdl.shareType = 'V';
         insert cdl;
        //     workorderlineitem testwolineitem = new workorderlineitem(Checklist__c =  );
        testwolineitem.Checklist__c = checklst.Id;
        update testwolineitem;

        Test.startTest();
        MB_ContentVersionScript c = new MB_ContentVersionScript();
        Database.executeBatch(c);
        Test.stopTest();


    }
}