objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Sales Order</relationshipLabel>
        <relationshipName>Sales_Order</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Service Case</businessProcess>
        <description>used to log all reactive service cases and is default case type for email to case settings</description>
        <label>Reactive</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Con_Req_Group__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Con Req Groups</relationshipLabel>
        <relationshipName>Con_Req_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
        <relationshipLabel>Con Req Groups</relationshipLabel>
        <relationshipName>Con_Req_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Con Req Group</label>
    <nameField>
        <displayFormat>CRG-{000000}</displayFormat>
        <label>Con Req Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Con Req Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateConreqfromcaseController.cls
public class CreateConreqfromcaseController {
    
    @Auraenabled
    public static List<Con_Req_Group__c> createconreq(Id caseid){
        List<Con_Req_Group__c>  newlist = new Con_Req_Group__c[]{};
        Con_Req_Group__c finallist = new  Con_Req_Group__c();    
        
        RecordType getrectypeid =[SELECT Id, Name FROM RecordType where Name ='Service Visit' AND SobjectType = 'Con_Req_Group__c'] ;
        string rectype = getrectypeid.id;
        
        case getcasefldvalues = [select id,CaseNumber,Project__c from case where id=:caseid];
        list<AcctSeedERP__Sales_Order__c> listsovalue = new list<AcctSeedERP__Sales_Order__c>();
        listsovalue =   [SELECT Id, Name, Project__c FROM AcctSeedERP__Sales_Order__c where Project__c = :getcasefldvalues.Project__c limit 1];
        if (listsovalue.size()>0){
            
            AcctSeedERP__Sales_Order__c  getsovalues  = new AcctSeedERP__Sales_Order__c();
            getsovalues = listsovalue.get(0); 
            string salesordername = getsovalues.id;
            
            AcctSeed__Project__c getprojectvalues =    [SELECT Id, Name, Owner.Name FROM AcctSeed__Project__c where Id =:getcasefldvalues.Project__c limit 1];
            string ownername = getprojectvalues.Owner.Name;
            
            
            
            finallist.Project__c = getcasefldvalues.Project__c;
            finallist.RecordTypeId = rectype;
            finallist.Sales_Order__c = salesordername;
          //  newlist.Ownerid = ownername;
            
            newlist.add(finallist);
            
            
        }
        system.debug('this is list-->' +newlist);
        return newlist;
        
    }
    
}