objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Hand_off_Date__c</fullName>
        <inlineHelpText>Date Project was handed off to Operations</inlineHelpText>
        <label>Hand off Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interconn_Date__c</fullName>
        <label>Interconnection Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Overall_Project_Status__c</fullName>
        <inlineHelpText>Defaults to &quot;Pre-Contract&quot; until Contract is signed- controlled by the PM</inlineHelpText>
        <label>Overall Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Contract</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Construction Completed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Delayed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rebate_Date__c</fullName>
        <label>Rebate Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SFDC_Project_End_Date__c</fullName>
        <inlineHelpText>Date Construction completed</inlineHelpText>
        <label>Mechanical Completion Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Con_Req__c.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Project the CO is related to</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Change Orders</relationshipLabel>
        <relationshipName>Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_PM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Project Manager
Automatically pulls from the Owner listed on the Project</inlineHelpText>
        <label>Project PM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N80000002yrRJEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the CO
Controlled by the approval process and recall button</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed by Customer</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Borrego Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>X - Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved By Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Change Order</label>
    <nameField>
        <displayFormat>SF-CR-{000000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Project__c.object
<CustomObject>
    <description>Project Management</description>
    <fields>
        <fullName>Hand_off_Date__c</fullName>
        <label>Hand off Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interconn_Date__c</fullName>
        <label>Interconnection Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rebate_Date__c</fullName>
        <label>Rebate Status Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SFDC_Project_End_Date__c</fullName>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <label>SFDCProject</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFDCProjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FieldUpdate.cls
public class FieldUpdate { 
    
    public static void addHandOffDate(SFDC_Project__c[] pros){
    } 
    public static void addEndDate(SFDC_Project__c[] pros) {
    }
    public static void addRebateDate(SFDC_Project__c[] pros) {
    }
    public static void addInterconnectionDate(SFDC_Project__c[] pros) {
    }
     public static void addCompleteStatus(SFDC_Project__c[] pros) {
    }
    public static void ownerUpdate(Map<Id, SFDC_Project__c> updatedProjs) {
    }
    
    public static void addHandOffDate(AcctSeed__Project__c[] pros){
       for (AcctSeed__Project__c p:pros){
            if(p.Hand_off_Date__c == null){
               p.Hand_off_Date__c = System.today();
            }
        }
    } 
    public static void addEndDate(AcctSeed__Project__c[] pros) {
        for (AcctSeed__Project__c p:pros) {
            if (p.SFDC_Project_End_Date__c == null){
                p.SFDC_Project_End_Date__c = System.today();
            }
        }
    }
    public static void addRebateDate(AcctSeed__Project__c[] pros) {
        for (AcctSeed__Project__c p:pros) {
            p.Rebate_Date__c = System.today();
        }
    }
    public static void addInterconnectionDate(AcctSeed__Project__c[] pros) {
        for (AcctSeed__Project__c p:pros) {
            p.Interconn_Date__c = System.today();
        }
    }
     public static void addCompleteStatus(AcctSeed__Project__c[] pros) {
        for (AcctSeed__Project__c p:pros) {
            if (p.Overall_Project_Status__c != 'Completed'){
                p.Overall_Project_Status__c = 'Completed';
            }
        }
    }
    public static void ownerUpdate(Map<Id, AcctSeed__Project__c> updatedProjs) {
        List<Con_Req__c> upReqs = new List<Con_Req__c>();
        for (Con_Req__c r : [SELECT Project_PM__c, ASProject__c, Status__c FROM Con_Req__c WHERE ASProject__c in :updatedProjs.keySet() and 
                             Status__c != 'Approved']) {
            AcctSeed__Project__c parentProj = updatedProjs.get(r.ASProject__c);
            r.Project_PM__c = parentProj.OwnerId;           
            upReqs.add(r);
        }
        update upReqs; 
    }
    public static testMethod void FieldUpdateTest(){
        ProjectTest.FieldUpdate();
        
        
        
        FieldUpdate.addHandOffDate(new SFDC_Project__c[]{}); 
        FieldUpdate.addEndDate(new SFDC_Project__c[]{}); 
        FieldUpdate.addRebateDate(new SFDC_Project__c[]{}); 
        FieldUpdate.addInterconnectionDate(new SFDC_Project__c[]{}); 
        FieldUpdate.addCompleteStatus(new SFDC_Project__c[]{}); 
        FieldUpdate.ownerUpdate(new Map<Id, SFDC_Project__c>() ); 
        
        
        
        
        
    }
}