objects/AcctSeed__Cash_Disbursement__c.object
<CustomObject>
    <description>Used to document the payment made to an outside vendor, contact, or employee typically recorded as an payable. The aggregation of multiple cash disbursements constitute a cash disbursement batch.</description>
    <fields>
        <fullName>OK_To_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OK To Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Cash Disbursement</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>Cash Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>should define the role this contact is playing in their relationship with Borrego.</inlineHelpText>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Service Contact</fullName>
                </value>
                <value>
                    <fullName>Host Contact</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Owner Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Contact</fullName>
                </value>
                <value>
                    <fullName>Sales Contact</fullName>
                </value>
                <value>
                    <fullName>Sales Decision-Maker</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Not Yet Identified</fullName>
                </value>
                <value>
                    <fullName>Portal User</fullName>
                </value>
                <value>
                    <fullName>Primary O&amp;M Contact</fullName>
                </value>
                <value>
                    <fullName>Technical Contact</fullName>
                </value>
                <value>
                    <fullName>Primary Technical Contact</fullName>
                </value>
                <value>
                    <fullName>O&amp;M Billing Contact</fullName>
                </value>
                <value>
                    <fullName>O&amp;M Service Billing Contact</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>O&amp;M Performance Report Contact</fullName>
                </value>
                <value>
                    <fullName>O&amp;M Case Closure Report Contact</fullName>
                </value>
                <value>
                    <fullName>Amex Contact</fullName>
                </value>
                <value>
                    <fullName>Waiver Contact</fullName>
                </value>
                <value>
                    <fullName>O&amp;M Purchasing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/testCashDisbursementCtlExt.cls
@isTest(seeAllData=true)
private class testCashDisbursementCtlExt {
  
  /*
   *  Test methods for class file CaseDisbursementCtlExt
   *
   */
  
  static testMethod void testCDCtlExt1() {
    
    // Create the test data we need
    TestDataSuite.initialize();
    
    TestDataSuite.contacts[0].Contact_Type__c = 'Billing Contact';
    TestDataSuite.contacts[0].Email = 'testCDCtlExt1=borregosolar.com@example.com';
    update TestDataSuite.contacts[0];
    
    TestDataSuite.cashDisbursements[0].OK_To_Email__c = true;
    update TestDataSuite.cashDisbursements[0];
    
    // Test the CashDisbursement controller extension
    List<AcctSeed__Cash_Disbursement__c> cdList = new List<AcctSeed__Cash_Disbursement__c>();
    cdList.add(TestDataSuite.cashDisbursements[0]);
    ApexPages.StandardSetController setCon = new ApexPages.StandardSetController(cdList);
    setcon.setSelected(cdList);
    CashDisbursementCtlExt ext = new CashDisbursementCtlExt(setcon);

    ext.sendACHEmail();
  }
  }