objects/AcctSeed__Account_Payable__c.object
<CustomObject>
    <description>Used to document liabilities to outside vendor, contact, or employee.</description>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Used to record vendor invoice or credit memo date.</inlineHelpText>
        <label>Issue Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Payable</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/AcctSeed__Account_Payable_Line__c.object
<CustomObject>
    <description>Line item expense associated with an payable. The aggregation of multiple payable lines constitute a payable record.</description>
    <fields>
        <fullName>AcctSeed__Account_Payable__c</fullName>
        <inlineHelpText>Reference to Accounts Payable the line is associated with</inlineHelpText>
        <label>Payable</label>
        <referenceTo>AcctSeed__Account_Payable__c</referenceTo>
        <relationshipName>Project_Account_Payable_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Amount__c</fullName>
        <inlineHelpText>Currency field to record amount of line.</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Optional Date used to override the date on the Accounts Payable parent object when posting to the transaction object. Most useful in the Time &amp; Material Billing process to provide date information for the related billing line.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Expense_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Upon posting a debit entry will be made to this account and a corresponding credit entry will be made to the AP Control account set in the Accounting Settings Tab or the AP Control Override indicated in the Account Payable Parent.</inlineHelpText>
        <label>Expense GL Account</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Expense</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Payable Lines</relationshipLabel>
        <relationshipName>Project_Payable_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Work break down structure for projects, such as: Phases, Deliverables or Roles.</inlineHelpText>
        <label>Project Task</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.AcctSeed__Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project_Task__c</referenceTo>
        <relationshipLabel>Payable Lines</relationshipLabel>
        <relationshipName>Project_Payable_Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Project or Job for allocation of cost.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Payable Lines</relationshipLabel>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tax Group (B)</label>
        <referenceTo>Tax_Group__c</referenceTo>
        <relationshipName>Account_Payable_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payable Line</label>
    <nameField>
        <displayFormat>APL-{00000}</displayFormat>
        <label>Payable Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payable Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Date the Billing is issued to the customer.</inlineHelpText>
        <label>Billing Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tax_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the Tax Group</inlineHelpText>
        <label>Tax Group</label>
        <referenceTo>Tax_Group__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing_Line__c.object
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <fields>
        <fullName>AcctSeed__Billing__c</fullName>
        <inlineHelpText>Reference to parent object.</inlineHelpText>
        <label>Billing</label>
        <referenceTo>AcctSeed__Billing__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Project_Billing_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Date Product or Service was rendered.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Expense_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Overrides the expense GL account set on the product in the posting process if populated. This feature requires product costing on the Accounting Settings tab to be enabled.</inlineHelpText>
        <label>Expense GL Account</label>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Billing Lines (Expense GL Account)</relationshipLabel>
        <relationshipName>Billing_Lines1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Hours_Units__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Quantity for Product Pricing, Hours for Service pricing.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project_Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Work break down structure for projects, such as: Phases, Deliverables or Roles. Drives Revenue GL Account and GL Account Variables when Posting to the Transaction object if populated.</inlineHelpText>
        <label>Project Task</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.AcctSeed__Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project_Task__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Project_Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the Project the Billing Line is related to</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Rate__c</fullName>
        <inlineHelpText>Required- Product or Service Rate</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AcctSeedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Budgeted_Revenue__c</fullName>
        <description>Summary of Revenue budgeted at the Project Task Level.</description>
        <inlineHelpText>Total amount of Billing Line Items</inlineHelpText>
        <label>Budgeted Revenue</label>
        <summarizedField>AcctSeed__Project_Task__c.AcctSeed__Budgeted_Revenue__c</summarizedField>
        <summaryForeignKey>AcctSeed__Project_Task__c.AcctSeed__Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Project_Task__c.object
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <fields>
        <fullName>AcctSeed__Budgeted_Revenue__c</fullName>
        <inlineHelpText>Budgeted Revenue for a Project Task. Amount should be a positive value.
Amount of the line item on the SOV, entered by Accounting</inlineHelpText>
        <label>Budgeted Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Labor_GL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Upon posting a Time Card. A debit entry will be made to this GL Account and a corresponding credit entry will be made to the Labor GL Account set in the Accounting Settings Tab for each Time Card Day.</inlineHelpText>
        <label>Expense GL Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
                <operation>equals</operation>
                <value>Expense</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__GL_Account__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <inlineHelpText>Project the line item is associated with- Automatically fills in when the line item is created from the Project</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related account for the Service Contract.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestBillingLineTrigger.cls
/* Auther: Madan(Forcebrain Developer)
/* Date: Sept 18, 2017
/* Description: To increase code coverage of Billing Line Trigger and Handler class
*/
@isTest (SeeAllData = true) 
private class TestBillingLineTrigger {

    static testMethod void myUnitTest() {
        //Initialize all required objects
        TestAllProjectRollUpTriggers.initalizeBaseObjects(); 
        
        //Create a new project task
        AcctSeed__Project_Task__c projectTask = new AcctSeed__Project_Task__c(RecordTypeId = Schema.SObjectType.AcctSeed__Project_Task__c.getRecordTypeInfosByName().get('Budget Line Item').getRecordTypeId(), Name = 'Test Project Task', AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Labor_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Budgeted_Revenue__c = 123);
        insert projectTask; 
        
        Test.StartTest();   
                
        //Create a new Billing Line on the Project Task
        AcctSeed__Billing_Line__c billingLine = new AcctSeed__Billing_Line__c(AcctSeed__Billing__c = TestAllProjectRollUpTriggers.testBilling.Id, AcctSeed__Hours_Units__c = 1, AcctSeed__Rate__c = 10.0, AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Project_Task__c = projectTask.Id);

        insert billingLine;
        
        //Create an Account Payable Line on the Project Task
        AcctSeed__Account_Payable_Line__c accountPayableLine = new AcctSeed__Account_Payable_Line__c(AcctSeed__Date__c = date.today(), AcctSeed__Account_Payable__c = TestAllProjectRollUpTriggers.testAccountsPayable.Id, AcctSeed__Amount__c = 100.00, AcctSeed__Expense_GL_Account__c = TestAllProjectRollUpTriggers.testGLAccount.Id, AcctSeed__Project__c = TestAllProjectRollUpTriggers.testProject.Id, AcctSeed__Project_Task__c = projectTask.Id);
        insert accountPayableLine;
        
        //accountPayableLine.AcctSeed__Amount__c = 200;
        //update accountPayableLine;
        
        delete accountPayableLine;
        
        Tax_Group__c taxgroup = new Tax_Group__c();
        taxgroup.name = 'Test';
        insert taxgroup;
        
        // Added By Madan - Sept 18, 2017(To Increase main class code coverage)
        TestAllProjectRollUpTriggers.testBilling.Tax_Group__c = taxgroup.Id;
        
        AcctSeed__Billing_Format__c billpdf = new AcctSeed__Billing_Format__c();
        billpdf.Name = 'O&M';
        billpdf.AcctSeed__Default_Email_Template__c = ' Billing_Approved ';
        billpdf.AcctSeed__Visualforce_PDF_Page__c = 'ProjectBillingPDF';
        insert billpdf;
        
        TestAllProjectRollUpTriggers.testBilling.AcctSeed__Billing_Format__c = billpdf.Id;
        update TestAllProjectRollUpTriggers.testBilling;
        
        Account acc = new Account(Name = 'asvAccount');
        insert acc;
        
        Contract cntrct = new Contract(Name = 'asvContract', AccountId = acc.Id, Type__c = 'O&M');
        insert cntrct;
        
        SV__c sv = new SV__c(Account__c = acc.Id, Contract__c = cntrct.Id);
        insert sv;
        
        billingLine.Category__c = 'Labor - Internal'; //'Labor';
        billingLine.Service_Visit__c = sv.Id;
        update billingLine;

        delete billingLine;
        
        Test.stopTest();
    }
}