objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_Supplied_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Owner Supplied Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Spare</fullName>
                </value>
                <value>
                    <fullName>Installed Spare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/ProjectOpportunityProducts.cls
public with sharing class ProjectOpportunityProducts {

/* deactivate as per emily 12/141/18 -- MG
    AcctSeed__Project__c theProject;

    public List<OpportunityLineItem> oppProducts{get;set;}

    public ProjectOpportunityProducts(ApexPages.StandardController stdController) {
        theProject = (AcctSeed__Project__c)stdController.getRecord(); 
        
        
       initOppProduct();
    }
    
    private void initOppProduct(){
        
        oppProducts = [select PricebookEntryId,PricebookEntry.Name, type__c,Quantity,TotalPrice,Owner_Supplied_Product__c from OpportunityLineItem where OpportunityId =: theProject.AcctSeed__Opportunity__c ];
        
    }
    
   deactivate as per emily 12/141/18 -- MG */ 
    

}