objects/AcctSeed__Accounting_Period__c.object
<CustomObject>
    <customHelpPage>AcctSeed__AccountingPeriodHelp</customHelpPage>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>&quot;Open&quot; allows new transactions to be saved to this period. &quot;Closed&quot; prevents new records from being saved to this period.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Accounting_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to specify accounting period for financial reporting. Accounting period must have a value of &quot;Open&quot; in order to be selected.</inlineHelpText>
        <label>Accounting  Period</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
                <operation>equals</operation>
                <value>Open</value>
            </filterItems>
            <infoMessage>The accounting period status must be open</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Project_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Billing_Cycle_End_Date__c</fullName>
        <inlineHelpText>Used Primarily in Time &amp; Material Billings. Used to show range in which products or services were sold.</inlineHelpText>
        <label>Billing Cycle End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Billing_Cycle_Start_Date__c</fullName>
        <inlineHelpText>Used Primarily in Time &amp; Material Billings. Used to show range in which products or services were sold.</inlineHelpText>
        <label>Billing Cycle Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The organization you would like to pay you for your product or service. This is a filtered lookup to the Account where Accounting Status equals &quot;Customer&quot; or &quot;Customer &amp; Vendor&quot;.</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Customer, Customer and Vendor</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Date the Billing is issued to the customer.</inlineHelpText>
        <label>Billing Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Due_Date2__c</fullName>
        <inlineHelpText>The Due Date equals the Billing Date plus the Billing Days Due on the associated Account (Customer) record. Otherwise the Due Date defaults to the Billing Date.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Recurring_Billing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Billing</label>
        <referenceTo>AcctSeed__Recurring_Billing__c</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in approvals of billing records and therefore related detail lines. A value of &quot;Posted&quot; indicates the record is final and a debit and credit line have been entered into the transaction object for each billing line.</inlineHelpText>
        <label>Posting Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>New- No AP</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Waiting for Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to Service Contract</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing_Line__c.object
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <fields>
        <fullName>AcctSeed__Billing__c</fullName>
        <inlineHelpText>Reference to parent object.</inlineHelpText>
        <label>Billing</label>
        <referenceTo>AcctSeed__Billing__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Project_Billing_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Date Product or Service was rendered.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Hours_Units__c</fullName>
        <defaultValue>1</defaultValue>
        <inlineHelpText>Quantity for Product Pricing, Hours for Service pricing.</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the Project the Billing Line is related to</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Rate__c</fullName>
        <inlineHelpText>Required- Product or Service Rate</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <inlineHelpText>Used in filtered look ups to limit the selection of inactive projects.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Recurring_Billing__c.object
<CustomObject>
    <description>Captures information related to recurring billings associated with customers. A recurring billing is a template for creating billings on a periodic basis.</description>
    <fields>
        <fullName>AcctSeed__Billing_Frequency__c</fullName>
        <inlineHelpText>shared picklist should should match values of Payment Options in contract as well as Payment Options in Opportunity</inlineHelpText>
        <label>Billing Frequency</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lump Sum</fullName>
                    <label>Anniversary in Advance</label>
                </value>
                <value>
                    <fullName>Anniversary Semi-Annual in Arrears</fullName>
                </value>
                <value>
                    <fullName>Annual in Advance</fullName>
                    <label>Annual in Advance-Jan to Dec</label>
                </value>
                <value>
                    <fullName>Arrears Per % of visits completed</fullName>
                </value>
                <value>
                    <fullName>Long Term</fullName>
                    <label>Long Term in Advance</label>
                </value>
                <value>
                    <fullName>Mid Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Monthly in Advance</fullName>
                </value>
                <value>
                    <fullName>Monthly in Arrears</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Advance</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Advance Equal Installments</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Arrears</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Arrears Equal Installments</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual In Advance</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual in Arrears</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Customer, Customer and Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recurring Billings</relationshipLabel>
        <relationshipName>Recurring_Billings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Last_Billing_Date__c</fullName>
        <label>Last Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Recurring Billings</relationshipLabel>
        <relationshipName>Recurring_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recurring Billing</label>
    <nameField>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateBillingdatesTestClass.cls
@isTest(seealldata=True)
public class UpdateBillingdatesTestClass 
{
  /*   @testSetup
    public static void setup() {
      ASeedAccountingSettingsSetupTest.testDataSetup(); 
    } */
    
    
 {
 
  //ASeedAccountingSettingsSetupTest.testDataSetup();
  
  
 test.starttest();
     AcctSeed__Billing__c[] billings = new List <AcctSeed__Billing__c> ();
     billings.add(
     new AcctSeed__Billing__c(
        AcctSeed__Billing_Cycle_Start_Date__c = System.today(),
        AcctSeed__Billing_Cycle_End_Date__c = System.today() + 30,
        AcctSeed__Date__c = System.today(),
        AcctSeed__Customer__c = '0013400001KBNN4', //[select id from Account Limit 1].id,//'0013400001KBNN4',
        AcctSeed__Status__c = 'Approved',
        AcctSeed__Accounting_Period__c='a1M2H00000Dn181',
        AcctSeed__Due_Date2__c = System.today() + 30,
        Service_Contract__c='80034000002EC1M',//[select id from contract Limit 1].id,//80034000002EC1M
        AcctSeed__Recurring_Billing__c=[select Id from AcctSeed__Recurring_Billing__c where AcctSeed__Billing_Frequency__c='Quarterly in Arrears' limit 1].Id //'a3234000003LIVq'
    )
);


insert billings;

AcctSeed__Billing_Line__c[] bLines = new List <AcctSeed__Billing_Line__c> ();
for (AcctSeed__Billing__c bill : billings) {
    AcctSeed__Billing_Line__c objBillingLine = new AcctSeed__Billing_Line__c();
    objBillingLine.AcctSeed__Billing__c = bill.id;
    objBillingLine.AcctSeed__Date__c = System.today();
    //objBillingLine.AcctSeed__Last_Billing_Date__c = Date.newinstance(2018, 11, 08);
    objBillingLine.AcctSeed__Rate__c = 25;
    objBillingLine.AcctSeed__Hours_Units__c = 1;
    objBillingLine.AcctSeed__Project__c=[select id from AcctSeed__Project__c Limit 1].Id;
    
    bLines.add(objBillingLine);

 
}

  insert bLines;

   AcctSeed.PostResult[] postResults = AcctSeed.BillingPostService.postBillings(billings);
 test.stoptest();
 }

////
static testMethod void testMethod2() {
test.starttest();
 AcctSeed__Billing__c[] billings1 = new List <AcctSeed__Billing__c> ();
billings1.add(
    new AcctSeed__Billing__c(
        AcctSeed__Billing_Cycle_Start_Date__c = System.today(),
        AcctSeed__Billing_Cycle_End_Date__c = System.today() + 30,
        AcctSeed__Date__c = System.today(),
        AcctSeed__Customer__c = [select Id from account limit 1].Id, // '0013400001MvI72',
        AcctSeed__Status__c = 'Approved',
        AcctSeed__Due_Date2__c = System.today() + 30,
        AcctSeed__Accounting_Period__c='a1M2H00000Dn181',
        Service_Contract__c= '80034000002EC1M', //[select id from contract Limit 1].id,'80034000001zvoI',
        AcctSeed__Recurring_Billing__c=[select Id from AcctSeed__Recurring_Billing__c where AcctSeed__Billing_Frequency__c='lump sum' order by id desc limit 1].Id //'a3234000003YJOU'
    )
);

insert billings1;
system.debug('Lump Look here' + billings1);

AcctSeed__Billing_Line__c[] bLines1 = new List <AcctSeed__Billing_Line__c> ();
for (AcctSeed__Billing__c bill1 : billings1) {
    AcctSeed__Billing_Line__c objBillingLine = new AcctSeed__Billing_Line__c();
    objBillingLine.AcctSeed__Billing__c = bill1.id;
    objBillingLine.AcctSeed__Date__c = System.today();
    //objBillingLine.AcctSeed__Last_Billing_Date__c = Date.newinstance(2018, 11, 08);
    objBillingLine.AcctSeed__Rate__c = 25;
    objBillingLine.AcctSeed__Hours_Units__c = 1;
    objBillingLine.AcctSeed__Project__c=[select id from AcctSeed__Project__c Limit 1].Id;
    
    bLines1.add(objBillingLine);

  }

insert bLines1;

    
   AcctSeed.PostResult[] postResults1 = AcctSeed.BillingPostService.postBillings(billings1);
   test.stoptest();
   }
////

static testMethod void testMethod3() {
test.starttest();

AcctSeed__Billing__c[] billings2 = new List <AcctSeed__Billing__c> ();
billings2.add(
    new AcctSeed__Billing__c(
        AcctSeed__Billing_Cycle_Start_Date__c = System.today(),
        AcctSeed__Billing_Cycle_End_Date__c = System.today() + 30,
        AcctSeed__Date__c = System.today(),
        AcctSeed__Customer__c =[select Id from account limit 1].Id,
        AcctSeed__Status__c = 'Approved',
        AcctSeed__Accounting_Period__c='a1M2H00000Dn181',
        AcctSeed__Due_Date2__c = System.today() + 30,
        Service_Contract__c='80034000002EC1M', //[select id from contract Limit 1].id,'800340000026esN',
        AcctSeed__Recurring_Billing__c=[select Id from AcctSeed__Recurring_Billing__c where AcctSeed__Billing_Frequency__c='Annual in Advance' limit 1].Id)
);


insert billings2;

AcctSeed__Billing_Line__c[] bLines2 = new List <AcctSeed__Billing_Line__c> ();
for (AcctSeed__Billing__c bill2 : billings2) {
    AcctSeed__Billing_Line__c objBillingLine2 = new AcctSeed__Billing_Line__c();
    objBillingLine2.AcctSeed__Billing__c = bill2.id;
    objBillingLine2.AcctSeed__Date__c = System.today();
    objBillingLine2.AcctSeed__Rate__c = 25;
    objBillingLine2.AcctSeed__Hours_Units__c = 1;
    objBillingLine2.AcctSeed__Project__c=[select id from AcctSeed__Project__c Limit 1].Id;
    
    bLines2.add(objBillingLine2);

}

insert bLines2;

    
   AcctSeed.PostResult[] postResults2 = AcctSeed.BillingPostService.postBillings(billings2);
     
  test.stoptest();   
  }
    
     
static testMethod void testMethod4() {
test.starttest();

AcctSeed__Billing__c[] billings3 = new List <AcctSeed__Billing__c> ();
billings3.add(
    new AcctSeed__Billing__c(
        AcctSeed__Billing_Cycle_Start_Date__c = System.today(),
        AcctSeed__Billing_Cycle_End_Date__c = System.today() + 30,
        AcctSeed__Date__c = System.today(),
        AcctSeed__Customer__c = [select Id from account limit 1].Id,
        AcctSeed__Status__c = 'Approved',
        AcctSeed__Accounting_Period__c='a1M2H00000Dn181',
        AcctSeed__Due_Date2__c = System.today() + 30,
        Service_Contract__c='80034000002EC1M', //'[select id from contract Limit 1].id, '80080000000pMWSAA2',
        AcctSeed__Recurring_Billing__c= [select Id from AcctSeed__Recurring_Billing__c where AcctSeed__Billing_Frequency__c='Mid Semi-Annual' limit 1].Id //'a3234000003D5lP'
    )
);


insert billings3;

AcctSeed__Billing_Line__c[] bLines3 = new List <AcctSeed__Billing_Line__c> ();
for (AcctSeed__Billing__c bill3 : billings3) {
    AcctSeed__Billing_Line__c objBillingLine3 = new AcctSeed__Billing_Line__c();
    objBillingLine3.AcctSeed__Billing__c = bill3.id;
    objBillingLine3.AcctSeed__Date__c = System.today();
    objBillingLine3.AcctSeed__Rate__c = 25;
    objBillingLine3.AcctSeed__Hours_Units__c = 1;
    objBillingLine3.AcctSeed__Project__c=[select id from AcctSeed__Project__c Limit 1].Id;
    
    bLines3.add(objBillingLine3);

}

insert bLines3;

    
   AcctSeed.PostResult[] postResults3 = AcctSeed.BillingPostService.postBillings(billings3);
     
  test.stoptest();   
  }
  
  static testMethod void testMethod5() 
 {
 
  //ASeedAccountingSettingsSetupTest.testDataSetup();
  
  
 test.starttest();
     AcctSeed__Billing__c[] billings = new List <AcctSeed__Billing__c> ();
     billings.add(
     new AcctSeed__Billing__c(
        AcctSeed__Billing_Cycle_Start_Date__c = System.today(),
        AcctSeed__Billing_Cycle_End_Date__c = System.today() + 30,
        AcctSeed__Date__c = Date.newinstance(2025, 12, 31),
        AcctSeed__Customer__c ='0013400001KBNN4', // [select Id from account limit 1].Id,
        AcctSeed__Status__c = 'Approved',
         AcctSeed__Accounting_Period__c='a1M2H00000Dn181',
        AcctSeed__Due_Date2__c = System.today() + 30,
        Service_Contract__c='80034000002EC1M', // [select id from contract Limit 1].id, '80034000002EC1M',
        AcctSeed__Recurring_Billing__c='a3234000003LIVq' //[select Id from AcctSeed__Recurring_Billing__c where AcctSeed__Billing_Frequency__c='Quarterly in Advance' limit 1].Id //'a3234000003LIVq'
    )
);


insert billings;

AcctSeed__Billing_Line__c[] bLines = new List <AcctSeed__Billing_Line__c> ();
for (AcctSeed__Billing__c bill : billings) {
    AcctSeed__Billing_Line__c objBillingLine = new AcctSeed__Billing_Line__c();
    objBillingLine.AcctSeed__Billing__c = bill.id;
    objBillingLine.AcctSeed__Date__c = System.today();
    //objBillingLine.AcctSeed__Last_Billing_Date__c = Date.newinstance(2018, 11, 08);
    objBillingLine.AcctSeed__Rate__c = 25;
    objBillingLine.AcctSeed__Hours_Units__c = 1;
    objBillingLine.AcctSeed__Project__c=[select id from AcctSeed__Project__c Limit 1].Id;
    
    bLines.add(objBillingLine);

 
}

  insert bLines;

   AcctSeed.PostResult[] postResults = AcctSeed.BillingPostService.postBillings(billings);
 test.stoptest();
 }
     
  static testMethod void testMethod6() 
 {
 
  //ASeedAccountingSettingsSetupTest.testDataSetup();
  
  
 test.starttest();
     AcctSeed__Billing__c[] billings = new List <AcctSeed__Billing__c> ();
     billings.add(
     new AcctSeed__Billing__c(
        AcctSeed__Billing_Cycle_Start_Date__c = System.today(),
        AcctSeed__Billing_Cycle_End_Date__c = System.today() + 30,
        AcctSeed__Date__c = Date.newinstance(2025, 09, 30),
        AcctSeed__Customer__c = '0013400001KBNN4', //[select Id from account limit 1].Id,
        AcctSeed__Status__c = 'Approved',
         AcctSeed__Accounting_Period__c='a1M2H00000Dn181',
        AcctSeed__Due_Date2__c = System.today() + 30,
        Service_Contract__c='80034000002EC1M', //[select id from contract Limit 1].id, '80034000002EC1M',
        AcctSeed__Recurring_Billing__c='a3234000003LIVq' //[select Id from AcctSeed__Recurring_Billing__c where AcctSeed__Billing_Frequency__c='Quarterly in Arrears Equal Installments' limit 1].Id //'a3234000003LIVq'
    )
);


insert billings;

AcctSeed__Billing_Line__c[] bLines = new List <AcctSeed__Billing_Line__c> ();
for (AcctSeed__Billing__c bill : billings) {
    AcctSeed__Billing_Line__c objBillingLine = new AcctSeed__Billing_Line__c();
    objBillingLine.AcctSeed__Billing__c = bill.id;
    objBillingLine.AcctSeed__Date__c = System.today();
    //objBillingLine.AcctSeed__Last_Billing_Date__c = Date.newinstance(2018, 11, 08);
    objBillingLine.AcctSeed__Rate__c = 25;
    objBillingLine.AcctSeed__Hours_Units__c = 1;
    objBillingLine.AcctSeed__Project__c=[select id from AcctSeed__Project__c Limit 1].Id;
    
    bLines.add(objBillingLine);

 
}

  insert bLines;

   AcctSeed.PostResult[] postResults = AcctSeed.BillingPostService.postBillings(billings);
 test.stoptest();
 }
 
 static testMethod void testMethod7() {
test.starttest();

AcctSeed__Billing__c[] billings3 = new List <AcctSeed__Billing__c> ();
billings3.add(
    new AcctSeed__Billing__c(
        AcctSeed__Billing_Cycle_Start_Date__c = System.today(),
        AcctSeed__Billing_Cycle_End_Date__c = System.today() + 30,
        AcctSeed__Date__c = System.today(),
        AcctSeed__Customer__c = [select Id from account limit 1].Id,
        AcctSeed__Status__c = 'Approved',
        AcctSeed__Accounting_Period__c='a1M2H00000Dn181',
        AcctSeed__Due_Date2__c = System.today() + 30,
        Service_Contract__c='80034000002EC1M', // [select id from contract Limit 1].id, '8001g0000001AuL',
        AcctSeed__Recurring_Billing__c= [select Id from AcctSeed__Recurring_Billing__c where AcctSeed__Billing_Frequency__c='Monthly in Advance' limit 1].Id //'a3234000003D5lP'
        
    )
);


insert billings3;
system.debug('Monthly Look here' + billings3);

AcctSeed__Billing_Line__c[] bLines3 = new List <AcctSeed__Billing_Line__c> ();
for (AcctSeed__Billing__c bill3 : billings3) {
    AcctSeed__Billing_Line__c objBillingLine3 = new AcctSeed__Billing_Line__c();
    objBillingLine3.AcctSeed__Billing__c = bill3.id;
    objBillingLine3.AcctSeed__Date__c = System.today();
    objBillingLine3.AcctSeed__Rate__c = 25;
    objBillingLine3.AcctSeed__Hours_Units__c = 1;
    objBillingLine3.AcctSeed__Project__c=[select id from AcctSeed__Project__c Limit 1].Id;
    
    bLines3.add(objBillingLine3);

}

insert bLines3;

    
   AcctSeed.PostResult[] postResults3 = AcctSeed.BillingPostService.postBillings(billings3);
     
  test.stoptest();   
  }
  static testMethod void testMethod8() {
test.starttest();

AcctSeed__Billing__c[] billings3 = new List <AcctSeed__Billing__c> ();
billings3.add(
    new AcctSeed__Billing__c(
        AcctSeed__Billing_Cycle_Start_Date__c = System.today(),
        AcctSeed__Billing_Cycle_End_Date__c = System.today() + 30,
        AcctSeed__Date__c = System.today(),
        AcctSeed__Customer__c = [select Id from account limit 1].Id,
        AcctSeed__Status__c = 'Approved',
        AcctSeed__Accounting_Period__c='a1M2H00000Dn181',
        AcctSeed__Due_Date2__c = System.today() + 30,
        Service_Contract__c= '80034000002EC1M', //[select id from contract Limit 1].id, '800340000026guJ',
        AcctSeed__Recurring_Billing__c= [select Id from AcctSeed__Recurring_Billing__c where AcctSeed__Billing_Frequency__c='Semi-Annual In Advance' limit 1].Id //'a3234000003D5lP'
    )
);


insert billings3;

AcctSeed__Billing_Line__c[] bLines3 = new List <AcctSeed__Billing_Line__c> ();
for (AcctSeed__Billing__c bill3 : billings3) {
    AcctSeed__Billing_Line__c objBillingLine3 = new AcctSeed__Billing_Line__c();
    objBillingLine3.AcctSeed__Billing__c = bill3.id;
    objBillingLine3.AcctSeed__Date__c = System.today();
    objBillingLine3.AcctSeed__Rate__c = 25;
    objBillingLine3.AcctSeed__Hours_Units__c = 1;
    objBillingLine3.AcctSeed__Project__c=[select id from AcctSeed__Project__c Limit 1].Id;
    
    bLines3.add(objBillingLine3);

}

insert bLines3;

    
   AcctSeed.PostResult[] postResults3 = AcctSeed.BillingPostService.postBillings(billings3);
     
  test.stoptest();   
  }
  
 
        }