objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract</relationshipLabel>
        <relationshipName>Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Cost_Code__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cost Code</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <inlineHelpText>Cost of the product, filled out by Procurement</inlineHelpText>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Subcontractor</fullName>
        <active>true</active>
        <label>Subcontractor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Construction_Requisition__c.object
<CustomObject>
    <description>For creating a Service Con Req (and Service PO) from within the Service Visit obj__c (R.L.) from within a Service Contract. This is unique from the ConReqs, i.e., Major, Minor, etc.</description>
    <fields>
        <fullName>Cost_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cost Code</label>
        <referenceTo>Cost_Code__c</referenceTo>
        <relationshipLabel>Service Construction Requisitions</relationshipLabel>
        <relationshipName>Service_Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Unit Cost</label>
        <precision>17</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Needed__c</fullName>
        <label>Date Needed</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Service Construction Requisitions</relationshipLabel>
        <relationshipName>Service_Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service_PO__c</fullName>
        <label>Service PO</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will point to Service purchase order</description>
        <label>Service Purchase Order</label>
        <referenceTo>Service_PO__c</referenceTo>
        <relationshipLabel>Service Construction Requisitions</relationshipLabel>
        <relationshipName>Service_Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Visit__c</fullName>
        <label>Service Visit</label>
        <referenceTo>SV__c</referenceTo>
        <relationshipLabel>Service Construction Requisitions</relationshipLabel>
        <relationshipName>Service_Construction_Requisitions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Construction Requisitions (Ship To Account)</relationshipLabel>
        <relationshipName>Service_Construction_Requisitions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vendor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Construction Requisitions</relationshipLabel>
        <relationshipName>Service_Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Construction Requisitions</relationshipLabel>
        <relationshipName>Service_Construction_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Construction Requisition</label>
    <nameField>
        <displayFormat>SCR-{00000000}</displayFormat>
        <label>Service Construction Requisition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Construction Requisitions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_PO__c.object
<CustomObject>
    <fields>
        <fullName>SCR_Cost_Code_Cat__c</fullName>
        <label>Cost Code/Category</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCR_Date__c</fullName>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SCR_Description__c</fullName>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SCR_Item_Code__c</fullName>
        <label>Item Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCR_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Service_Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SCR_Project_Name__c</fullName>
        <label>Service Visit Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCR_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SCR_Requested_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SCR_Requisition_Number__c</fullName>
        <label>Service Req Number</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SCR_Ship_Address__c</fullName>
        <label>Ship To Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SCR_Ship_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Service_Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SCR_Shipping__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Shipping</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SCR_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Approved by Aaron</fullName>
                </value>
                <value>
                    <fullName>Director Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Vendor</fullName>
                </value>
                <value>
                    <fullName>Vendor Received PO</fullName>
                </value>
                <value>
                    <fullName>Vendor Shipped Material</fullName>
                </value>
                <value>
                    <fullName>Material Received</fullName>
                </value>
                <value>
                    <fullName>Work Complete</fullName>
                </value>
                <value>
                    <fullName>Invoice Received</fullName>
                </value>
                <value>
                    <fullName>Invoice Attached</fullName>
                </value>
                <value>
                    <fullName>Invoice Approved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SCR_Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>6</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SCR_Unit_Cost__c</fullName>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SCR_Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SCR_Vendor_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>SCR_Con_PO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SCR_Vendor_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Service_Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Construction_Requisition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Construction Requisition</label>
        <referenceTo>Service_Construction_Requisition__c</referenceTo>
        <relationshipLabel>Service Construction Purchase Orders</relationshipLabel>
        <relationshipName>Service_Construction_Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Purchase Order</label>
    <nameField>
        <displayFormat>SVC-PO-{00000000}</displayFormat>
        <label>SVC PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Construction Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Approximate Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_Rate__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>9</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Tax Rate</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Tax Rate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateServicePO.cls
public with sharing class CreateServicePO {
      
    /***** Begin Service Purchase Order *****/
    public static void addserPO(Service_Construction_Requisition__c[] reqs,boolean IsUpdate){

        system.debug('Test--');
        List<Id> ListOfServiceVisitIds = new List<Id>();
        List<Id> ccId = new List<Id>();         
        List<Id> accId = new List<Id>();
        Map<Id, Id> reqSV = new Map<Id, Id>();
        Map<Id, Id> ccReq = new Map<Id, Id>();
        Map<Id, SV__c> svMap = new Map<Id, SV__c>();
        Map<Id, Cost_Code__c> ccMap = new Map<Id, Cost_Code__c>();                        
        Map<Id, Account> accMap = new Map<Id, Account>();
        
        
        Map<id,Service_PO__c> MapOfServicePurchaseOrder=new Map<id,Service_PO__c>();
        
        //Query BLIs from ConReqs, add BLIs to reqID list, put Req Id and BLI Id into conBli
        Service_Construction_Requisition__c[] req = [SELECT Id, Service_Visit__c, Cost_Code__c
                                , Ship_To_Account__c FROM Service_Construction_Requisition__c WHERE Id in :reqs];
        for (Integer i = 0; i <req.size(); i++) {
            ListOfServiceVisitIds.add(req[i].Service_Visit__c);
            reqSV.put(req[i].Id, req[i].Service_Visit__c);
            ccId.add(req[i].Cost_Code__c);
            ccReq.put(req[i].Cost_Code__c, req[i].Id);
            accId.add(req[i].Ship_To_Account__c);
        }
        SV__c[] svs = [SELECT Id, Cost__c, Name, Contract__c FROM SV__c WHERE Id in :ListOfServiceVisitIds];
        for (Integer i = 0; i <svs.size(); i++) {
            svMap.put(svs[i].Id, svs[i]);
        }
        Cost_Code__c[] ccs = [SELECT Id, Number__c, Category__c FROM Cost_Code__c WHERE Id in :ccId];
        for (Integer i = 0; i <ccs.size(); i++) {
            ccMap.put(ccReq.get(ccs[i].Id), ccs[i]);
        }
        Account[] accs = [SELECT Id, Name, ShippingStreet, ShippingState, ShippingCity, ShippingPostalCode FROM Account WHERE Id in :accId];
        for (Integer i = 0; i <accs.size(); i++) {
            accMap.put(accs[i].Id, accs[i]);
        }
        
        List<SV__c> updatesv = new List<SV__c>();   //List of SVs to be updated         
        
        //Begin to Create POs - includes removing Req Amount from Pending PO and adding to Approved PO (PO_Total__c)
        for (Service_Construction_Requisition__c ServiceConstructionRequisition:reqs){
            //if (r.RecordTypeId == Utilities.getRecordType('Minor Component Requisition').Id) {
            String ShipingAddress;
             if (accMap.size()>0 && ServiceConstructionRequisition.Ship_To_Account__c!=null)
                    ShipingAddress = accMap.get(ServiceConstructionRequisition.Ship_To_Account__c).ShippingStreet + '\n' + accMap.get(ServiceConstructionRequisition.Ship_To_Account__c).ShippingCity + ', ' 
                                        + accMap.get(ServiceConstructionRequisition.Ship_To_Account__c).ShippingState + ' ' + accMap.get(ServiceConstructionRequisition.Ship_To_Account__c).ShippingPostalCode;
                Service_PO__c ServicePurchaseOrder = new Service_PO__c(
                    SCR_Vendor_Account__c = ServiceConstructionRequisition.Vendor_Account__c,
                    SCR_Vendor_Contact__c = ServiceConstructionRequisition.Vendor_Contact__c,
                    SCR_Ship_To__c = ServiceConstructionRequisition.Ship_To_Account__c,
                    SCR_Ship_Address__c =ShipingAddress,
                    SCR_Date__c = ServiceConstructionRequisition.Date_Needed__c,
                    SCR_Quantity__c = ServiceConstructionRequisition.Quantity__c,
                    SCR_Unit_Price__c = ServiceConstructionRequisition.Cost__c,
                    //OwnerId = ServiceConstructionRequisition.Service_Visit__r.Contract__r.OwnerId,
                    SCR_Requested_By__c = ServiceConstructionRequisition.Service_Visit__r.Contract__r.Account.Ownership ,
                    SCR_Product__c = ServiceConstructionRequisition.Product__c,                    
                    SCR_Item_Code__c = ServiceConstructionRequisition.Product__r.ProductCode,
                    SCR_Description__c = ServiceConstructionRequisition.Product__r.Description,
                    SCR_Tax_Rate__c = ServiceConstructionRequisition.Tax_Rate__c,
                    //SCR_Shipping__c = ServiceConstructionRequisition.Shipping__c,
                    SCR_Requisition_Number__c = ServiceConstructionRequisition.Name,
                    Service_Construction_Requisition__c=ServiceConstructionRequisition.Id,
                    SCR_Unit_Cost__c=ServiceConstructionRequisition.Cost__c,
                    SCR_Status__c='New',
                    SCR_Project_Name__c = svMap.get(reqSV.get(ServiceConstructionRequisition.Id)).Name,
                    SCR_Cost_Code_Cat__c = ccMap.get(ServiceConstructionRequisition.Id).Number__c + ' ' +ccMap.get(ServiceConstructionRequisition.Id).Category__c);
                     
                    MapOfServicePurchaseOrder.Put(ServiceConstructionRequisition.id,ServicePurchaseOrder);
                    
                //insert ServicePurchaseOrder;
               
            
        }
            Insert MapOfServicePurchaseOrder.Values();
            
            List<id> ListOfServicePurchaseOrderIds =new List<id>();
            
            for (Service_PO__c ServicePurchaseOrder:MapOfServicePurchaseOrder.Values()){
                ListOfServicePurchaseOrderIds.add(ServicePurchaseOrder.ID);
            }
            
            Map<id,Service_PO__c> MapOfServicePurchaseOrders =new Map<id,Service_PO__c>([Select id,Name from Service_PO__c Where id in :ListOfServicePurchaseOrderIds ]);
            Map<id,Service_Construction_Requisition__c > MapOfService_Construction_Requisition =new Map<id,Service_Construction_Requisition__c >
            ([Select id,Name from Service_Construction_Requisition__c Where id in :reqs]);
            
         for (Service_Construction_Requisition__c ServiceConstructionRequisition:reqs){
            
            Service_PO__c ServicePurchaseOrder =MapOfServicePurchaseOrders.get(MapOfServicePurchaseOrder.get(ServiceConstructionRequisition.id).id);
            
            Service_Construction_Requisition__c TempServiceConstructionRequisition = MapOfService_Construction_Requisition .get(ServiceConstructionRequisition.id);
            
            if (IsUpdate==true){
                 ServiceConstructionRequisition.Service_PO__c = ServicePurchaseOrder.Name;
                 ServiceConstructionRequisition.Service_Purchase_Order__c = ServicePurchaseOrder.id;
             }
             else{
                 TempServiceConstructionRequisition.Service_PO__c = ServicePurchaseOrder.Name;
                 TempServiceConstructionRequisition.Service_Purchase_Order__c = ServicePurchaseOrder.id;           
             }
             
             System.debug(ServiceConstructionRequisition.Service_PO__c);
             
                if(svMap.get(reqSV.get(ServiceConstructionRequisition.Id)).Cost__c == null) {
                    svMap.get(reqSV.get(ServiceConstructionRequisition.Id)).Cost__c = 0;
                }
                //Add Req Total to PO_Total
                //svMap.get(reqSV.get(r.Id)).Cost__c += r.Total_Cost_Tax__c;
                
                //Add updated BLIs to updatebli to be mass updated below
                updatesv.add(svMap.get(reqSV.get(ServiceConstructionRequisition.Id)));                           
            //}
            //Subcontractor
            
            //Major Component
         }
         
         if (IsUpdate==false){
             Update MapOfService_Construction_Requisition.values();
         }
        
        if (updatesv.size() > 0){
            update updatesv;
        } 
    }
    /***** End Service Purchase Order *****/ 
    
      
}