objects/AcctSeed__AP_Disbursement__c.object
<CustomObject>
    <description>Used to document the relationship an payable has with a cash disbursement.</description>
    <fields>
        <fullName>AcctSeed__Cash_Disbursement__c</fullName>
        <label>Cash Disbursement</label>
        <referenceTo>AcctSeed__Cash_Disbursement__c</referenceTo>
        <relationshipLabel>Invoices Applied To</relationshipLabel>
        <relationshipName>Account_Payable_Cash_Disbursements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Paid_Amount__c</fullName>
        <label>Applied Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Payee_Reference__c</fullName>
        <formula>AcctSeed__Account_Payable__r.AcctSeed__Payee_Reference__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payee Reference</label>
        <type>Text</type>
    </fields>
    <label>AP Disbursement</label>
    <nameField>
        <displayFormat>APD-{00000}</displayFormat>
        <label>AP Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Cash_Disbursement__c.object
<CustomObject>
    <description>Used to document the payment made to an outside vendor, contact, or employee typically recorded as an payable. The aggregation of multiple cash disbursements constitute a cash disbursement batch.</description>
    <fields>
        <fullName>ACH_Payment_Date_RW__c</fullName>
        <description>Records when an ACH payment was made for this CD</description>
        <label>ACH Payment Date RW</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Payee__c</fullName>
        <formula>IF( NOT(ISBLANK(AcctSeed__Alternate_Payee_Name__c)), AcctSeed__Alternate_Payee_Name__c,
IF( NOT(ISBLANK(AcctSeed__Vendor__c)) , AcctSeed__Vendor__r.Name,
IF( NOT(ISBLANK(AcctSeed__Contact__c)) , AcctSeed__Contact__r.FirstName &amp; &quot; &quot; &amp; AcctSeed__Contact__r.LastName, 
IF( NOT(ISBLANK(AcctSeed__Employee__c)) , AcctSeed__Employee__r.FirstName &amp; &quot; &quot; &amp; AcctSeed__Employee__r.LastName, 
&quot;&quot; ))))</formula>
        <inlineHelpText>Formula field that lists either the vendor, contact or the employee as the Payee. Used in reporting and as a convenient reference to the source record for the Payee.</inlineHelpText>
        <label>Payee</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Vendor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>A Cash Disbursement can have either the Account (Vendor), Contact or User (Employee) as the Payee. One object must be chosen.</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Vendor, Customer and Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cash Disbursements</relationshipLabel>
        <relationshipName>Cash_Disbursements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cash Disbursement</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>Cash Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AE_SmartConfiguration__c.object
<CustomObject>
    <fields>
        <fullName>ACH_Key__c</fullName>
        <label>ACH Key</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ACH_URL__c</fullName>
        <label>ACH URL</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <label>DocumentType</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>AE_SmartConfiguration</label>
    <nameField>
        <label>AE_SmartConfiguration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AE_SmartConfigurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AS_ACH__c.object
<CustomObject>
    <description>ACH data for a Cash Disbursement Payee</description>
    <fields>
        <fullName>BankAccountNumber__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>BankAccountNumber</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BankRoutingNumber__c</fullName>
        <defaultValue>&apos;0&apos;</defaultValue>
        <label>BankRoutingNumber</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TransactionCode__c</fullName>
        <formula>CASE(Bank_Account_Type__c,
&quot;Checking&quot;, &quot;22&quot;,
&quot;Savings&quot;, &quot;32&quot;,
&quot;00&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TransactionCode</label>
        <type>Text</type>
    </fields>
    <label>AS_ACH</label>
    <nameField>
        <displayFormat>ACH-{00000}</displayFormat>
        <label>AS_ACH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AS_ACHs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AS_ACHConfig__c.object
<CustomObject>
    <description>Common configuration information for ACH</description>
    <fields>
        <fullName>CompanyDiscretionaryData__c</fullName>
        <label>CompanyDiscretionaryData</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyEntryDescription__c</fullName>
        <label>CompanyEntryDescription</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyIdentification__c</fullName>
        <label>CompanyIdentification</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyName__c</fullName>
        <label>CompanyName</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImmediateDestinationName__c</fullName>
        <label>ImmediateDestinationName</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImmediateDestination__c</fullName>
        <label>ImmediateDestination</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImmediateOriginName__c</fullName>
        <label>ImmediateOriginName</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ImmediateOrigin__c</fullName>
        <label>ImmediateOrigin</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StandardEntryClassCode__c</fullName>
        <label>StandardEntryClassCode</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AS_ACHConfig</label>
    <nameField>
        <label>AS_ACHConfig Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AS_ACHConfigs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AS_ACH.cls
global with sharing class AS_ACH
{
    private static String endpointURL;
    private static String achKey;
    private static String AE_DbgMsg = 'AS: A ';
    private static String statusMessage;
    private static Integer statusCode;
    // private static String cookies;

    @future(callout=true)
    public static void sendACH(String cdsString)
    {
        Boolean errorExists;
        JSONGenerator result;
        AcctSeed__AP_Disbursement__c[] apds;

        System.debug(AE_DbgMsg + 'cdsString is `' + cdsString + '\'');
        AS_ACHConfig__c achConfig = [SELECT CompanyDiscretionaryData__c, CompanyEntryDescription__c, CompanyIdentification__c,
                        CompanyName__c, ImmediateDestinationName__c, ImmediateDestination__c, ImmediateOriginName__c,
                        ImmediateOrigin__c, StandardEntryClassCode__c FROM AS_ACHConfig__c LIMIT 1];
        AE_SmartConfiguration__c config = [SELECT Customer__c,DocumentType__c,ACH_Key__c,ACH_URL__c
          FROM AE_SmartConfiguration__c
          LIMIT 1];
        apds = AE_WS_Utilities.getApdValues(cdsString);
        endpointURL = config.ACH_URL__c;
        achKey = config.ACH_Key__c;
        HttpRequest reqData = new HttpRequest();
        // Http http = new Http();      
        // reqData.setHeader('Content-Type','application/x-www-form-urlencoded');
        reqData.setHeader('Content-Type','application/json');
        // reqData.setHeader('Connection','keep-alive');
        // reqData.setHeader('Content-Length','0');
        // reqData.setHeader('Cookie', cookies);
        reqData.setTimeout(60000); // 60,000 millisecs
        reqData.setEndpoint(endpointURL);
        // String targetString = 'key='+ EncodingUtil.URLENCODE(achKey,'UTF-8');
        result = JSON.createGenerator(true);

        result.writeStartObject();
        result.writeStringField('key', achKey);
        result.writeFieldName('achData');
        result.writeStartArray();
        for(AcctSeed__AP_Disbursement__c apd : apds)
        {
          AcctSeed__Cash_Disbursement__c cd 
            = AE_WS_Utilities.cdsMap.get(apd.AcctSeed__Cash_Disbursement__c);
          System.debug(AE_DbgMsg + 'cd is `' + cd + '\'');
          AS_ACH__c ach = AE_WS_Utilities.achMap.get(cd.AcctSeed__Vendor__c);
          System.debug(AE_DbgMsg + 'ach is `' + ach + '\'');
          result.writeStartObject();
          result.writeStringField('cdReferenceNumber', apd.Id);
          result.writeStringField('immediateOriginName', achConfig.immediateOriginName__c);
          result.writeStringField('companyName', achConfig.CompanyName__c);
          result.writeStringField('companyDiscData', achConfig.CompanyDiscretionaryData__c);
          result.writeStringField('standardEntryClassCode', achConfig.StandardEntryClassCode__c);
          result.writeStringField('companyEntryDescription', achConfig.CompanyEntryDescription__c);
          result.writeStringField('transactionCode', ach.TransactionCode__c);
          result.writeStringField('dfiRoutingNumber', ach.BankRoutingNumber__c);
          result.writeStringField('dfiAccountNumber', ach.BankAccountNumber__c);
          // use Paid Amount from AP Disbursement
          Integer amount = Integer.valueOf(apd.AcctSeed__Paid_Amount__c * 100);
          String amountString = String.valueOf(amount);
          result.writeStringField('amountCents', amountString);
          result.writeStringField('individualIdentificationNumber',cd.AcctSeed__Payee__c);
          result.writeStringField('individualName',apd.AcctSeed__Payee_Reference__c);
          result.writeEndObject();
        }
        result.writeEndArray();
        System.debug(AE_DbgMsg + 'result is `' + result.getAsString() + '\'');
        reqData.setBody(result.getAsString());   
        reqData.setMethod('POST');    
        HTTPResponse res;
        res = new Http().send(reqData);
        statusMessage = res.getStatus();
        System.debug(AE_DbgMsg + 'statusMessage is `' + statusMessage + '\'');
        statusCode = res.getStatusCode();
        System.debug(AE_DbgMsg + 'statusCode is `' + statusCode + '\'');
        if(statusCode == 200)
        { for(AcctSeed__Cash_Disbursement__c cd : AE_WS_Utilities.cdsMap.values())
          {
            cd.ACH_Payment_Date_RW__c = System.now().format(); // stores local time in database
            update cd;
          }
        }
    }

/*    
    private static void getAuthToken()
    {
        HttpRequest reqData = new HttpRequest();
        Http http = new Http();
        reqData.setMethod('HEAD');
        reqData.setTimeout(20000);
        reqData.setEndpoint(endpointURL);
        try
        {
            HTTPResponse res = http.send(reqData);
            cookies = res.getHeader('Set-Cookie');
            // System.debug(AE_DbgMsg + 'cookies is `' + cookies + '\'');
            statusMessage = res.getBody(); 
            // System.debug(AE_DbgMsg + 'statusMessage is `' + statusMessage + '\'');
        }
        catch(Exception exp)
        {
            System.debug(AE_DbgMsg + 'exception ' + exp);
        }
    }
*/
}