objects/AcctSeed__Billing__c.object
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <fields>
        <fullName>AcctSeed__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The organization you would like to pay you for your product or service. This is a filtered lookup to the Account where Accounting Status equals &quot;Customer&quot; or &quot;Customer &amp; Vendor&quot;.</inlineHelpText>
        <label>Customer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Customer, Customer and Vendor</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Date the Billing is issued to the customer.</inlineHelpText>
        <label>Billing Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Due_Date2__c</fullName>
        <inlineHelpText>The Due Date equals the Billing Date plus the Billing Days Due on the associated Account (Customer) record. Otherwise the Due Date defaults to the Billing Date.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Shipping_City__c</fullName>
        <label>Shipping City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Shipping_PostalCode__c</fullName>
        <label>Shipping Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Shipping_State__c</fullName>
        <label>Shipping State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Total__c</fullName>
        <inlineHelpText>Grand Total for Billing.</inlineHelpText>
        <label>Total</label>
        <summarizedField>AcctSeed__Billing_Line__c.AcctSeed__Total__c</summarizedField>
        <summaryForeignKey>AcctSeed__Billing_Line__c.AcctSeed__Billing__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <formula>IF(AcctSeed__Total__c &lt; 0, &apos;Credit Memo&apos;,&apos;Invoice&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Type of Billing- either Invoice or Credit Memo
If Total &gt;0 = Invoice
If Total &lt;0 = Credit Memo</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Number__c</fullName>
        <inlineHelpText>Customer Invoice number</inlineHelpText>
        <label>Application Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AvaAcctSeed__Sales_Tax_Amount__c</fullName>
        <description>Avalara Sales Tax Field</description>
        <inlineHelpText>Avalara Sales Tax Amount</inlineHelpText>
        <label>Sales Tax</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BS_Due_Date__c</fullName>
        <description>Exact copy of field AcctSeed__Due_Date__c.</description>
        <formula>IF(!ISBLANK(AcctSeed__Due_Date2__c), AcctSeed__Due_Date2__c, AcctSeed__Date__c + AcctSeed__Billing_Format__r.AcctSeed__Billing_Days_Offset__c)</formula>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Reference_Number__c</fullName>
        <description>Optional Customer Reference or Customer PO number to assist customers in locating POs or Payment Authorizations for Borrego Invoices</description>
        <inlineHelpText>Optional Customer Reference or Customer PO number to assist customers in locating POs or Payment Authorizations for Borrego Invoices</inlineHelpText>
        <label>Customer Reference Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAyment_Due__c</fullName>
        <inlineHelpText>Amount Due on the Billing</inlineHelpText>
        <label>Payment Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SalesTaxPercent__c</fullName>
        <description>sales tax percent used on billing printout for O&amp;M</description>
        <label>Sales Tax Percent</label>
        <summarizedField>AcctSeed__Billing_Line__c.SalesTaxRateFormula__c</summarizedField>
        <summaryForeignKey>AcctSeed__Billing_Line__c.AcctSeed__Billing__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Link to Service Contract</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Billings</relationshipLabel>
        <relationshipName>Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SolarFund__c</fullName>
        <formula>Service_Contract__r.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solar Fund</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubTotal__c</fullName>
        <formula>AcctSeed__Total__c-SalesTaxDollars__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub-Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Billing_Line__c.object
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <fields>
        <fullName>AcctSeed__Billing__c</fullName>
        <inlineHelpText>Reference to parent object.</inlineHelpText>
        <label>Billing</label>
        <referenceTo>AcctSeed__Billing__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Project_Billing_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <inlineHelpText>Date Product or Service was rendered.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the Project the Billing Line is related to</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Total__c</fullName>
        <formula>AcctSeed__Sub_Total__c +  AcctSeed__Tax_Amount2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Billing Line Total: Hours * Units + Tax</inlineHelpText>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Enter a description of the Billing Line</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Taxable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is the Billing Line Taxable? Checked = Yes, Not Checked = NO</inlineHelpText>
        <label>Taxable</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__GL_Account__c.object
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <fields>
        <fullName>AcctSeed__Type__c</fullName>
        <inlineHelpText>Denotes the major grouping for financial reporting.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Revenue</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                    <default>true</default>
                    <label>Expense</label>
                </value>
                <value>
                    <fullName>Balance Sheet</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <description>For use in Brendan&apos;s BtoA Reports</description>
        <label>Subtotal</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1. Direct Margin Total</fullName>
                </value>
                <value>
                    <fullName>2. Commissions</fullName>
                </value>
                <value>
                    <fullName>3. ICOGS Total</fullName>
                </value>
                <value>
                    <fullName>1. O&amp;M Direct Margin Total</fullName>
                </value>
                <value>
                    <fullName>3. O&amp;M ICOGS Total</fullName>
                </value>
                <value>
                    <fullName>1. Revenue</fullName>
                </value>
                <value>
                    <fullName>2. Cost of Revenue- Direct</fullName>
                </value>
                <value>
                    <fullName>4. Cost of Revenue- Commissions</fullName>
                </value>
                <value>
                    <fullName>3. Cost of Revenue- Indirect</fullName>
                </value>
                <value>
                    <fullName>5. Marketing and Sales Expenses</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related project that the service contract was created for.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_M_Client_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Personnel at client who manages contract terms</description>
        <inlineHelpText>Personnel at client who manages contract terms</inlineHelpText>
        <label>O&amp;M Client Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>O&amp;M Contracts</relationshipLabel>
        <relationshipName>OMContracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_due_days__c</fullName>
        <inlineHelpText>how many days the customer has to pay us</inlineHelpText>
        <label>Payment due (days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Performance_Guarantee__c.object
<CustomObject>
    <description>NO LONGER IN USE _ THESE FIELDS HAVE BEEN MOVED TO THE OPPORTUNITY</description>
    <fields>
        <fullName>service_contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>used with Lookup Helper</description>
        <inlineHelpText>auto-updates contract associated with project</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Performance Guarantees</relationshipLabel>
        <relationshipName>service_contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Performance Guarantee</label>
    <nameField>
        <displayFormat>PG-{000}</displayFormat>
        <label>Production Guarantee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance Guarantees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Billing_InvoiceCtlExt.cls
public with sharing class Billing_InvoiceCtlExt {
        
        /*
         *      Methods to support the Billing Invoice PDF.
         *
         */
        
        ApexPages.StandardController stdController;
        
        public AcctSeed__Billing__c billing {get; set;}
        public List<AcctSeed__Project__c> projectList {get; set;}
        public AcctSeed__Project__c svConProject {get; set;}
        public String invoiceDate {get; set;}
        public String dueDate {get; set;}
        public String dueDateOM {get; set;}
        public String attentionNames {get; set;}
        public String attentionNamesOM {get; set;}
        public String solarFund {get; set;}
        //public String salesTaxTotal {get; set;}
        public String omBillLineTotal {get; set;}
        public List<OMBillingLines> omBillLines {get; set;}
        public List<AcctSeed__Billing_Line__c> billLines {get; set;}
        public Decimal subTotal {get;set;}
        
        public Billing_InvoiceCtlExt(ApexPages.StandardController stdController) {
                
                this.billing = new AcctSeed__Billing__c();
                this.billing = (AcctSeed__Billing__c)stdController.getRecord();
                this.billing = [select Id, Name, Application_Number__c, AcctSeed__Date__c, AcctSeed__Due_Date2__c, BS_Due_Date__c, 
                                SalesTaxPercent__c, AvaAcctSeed__Sales_Tax_Amount__c, SubTotal__c,
                                AcctSeed__Type__c, PAyment_Due__c, Customer_Reference_Number__c, SolarFund__c, AcctSeed__Shipping_Street__c, 
                                AcctSeed__Shipping_City__c, AcctSeed__Shipping_State__c, AcctSeed__Shipping_PostalCode__c, AcctSeed__Total__c, 
                                AcctSeed__Customer__c, AcctSeed__Customer__r.Name, AcctSeed__Customer__r.BillingStreet, AcctSeed__Customer__r.BillingCity, 
                                AcctSeed__Customer__r.BillingState, AcctSeed__Customer__r.BillingPostalCode, 
                                Service_Contract__c, Service_Contract__r.ContractNumber, Service_Contract__r.ASProject__c, Service_Contract__r.BillingStreet, 
                                Service_Contract__r.BillingCity, Service_Contract__r.BillingState, Service_Contract__r.BillingPostalCode, 
                                Service_Contract__r.Payment_due_days__c, Service_Contract__r.O_M_Client_Contact__r.Name 
                                from AcctSeed__Billing__c where Id = :this.billing.Id];
                
                invoiceDate = (billing.AcctSeed__Date__c == null) ? ' ' : String.valueOf(billing.AcctSeed__Date__c);
                dueDate = (billing.AcctSeed__Due_Date2__c == null) ? ' ' : String.valueOf(billing.AcctSeed__Due_Date2__c);
                dueDateOM = (billing.BS_Due_Date__c == null) ? ' ' : String.valueOf(billing.BS_Due_Date__c);
                solarFund = (String.isBlank(billing.SolarFund__c)) ? 'N/A' : billing.SolarFund__c;
                
                // Added By Madan - Jan 31, 2018(to show Sub Total on PDF page)
                if(billing.AcctSeed__Total__c != null) {
                    if(billing.AvaAcctSeed__Sales_Tax_Amount__c != null) {
                        String salesTaxAmt = billing.AvaAcctSeed__Sales_Tax_Amount__c;
                        
                        System.debug('===salesTaxAmt: ' + salesTaxAmt);
                        salesTaxAmt = salesTaxAmt.replace('$','').replace(' ','').replace(',', '');
                        
                        System.debug('===salesTaxAmt: ' + salesTaxAmt);
                        subTotal = billing.AcctSeed__Total__c - Decimal.valueOf(salesTaxAmt);
                        System.debug('===billing.AcctSeed__Total__c: ' + billing.AcctSeed__Total__c);
                        System.debug('===subTotal: ' + subTotal);
                    } else {
                        subTotal = billing.AcctSeed__Total__c;
                    }
                    
                    //subTotal = billing.AcctSeed__Total__c - (billing.AvaAcctSeed__Sales_Tax_Amount__c!=null?Decimal.valueOf(billing.AvaAcctSeed__Sales_Tax_Amount__c):0);
                } else {
                    subTotal = 0.00;
                }
                subTotal.setScale(0);
                
                //salesTaxTotal = (String.isBlank(billing.AvaAcctSeed__Sales_Tax_Amount__c)) ? ' ' : '$' + billing.AvaAcctSeed__Sales_Tax_Amount__c;
                
                List<AcctSeed__Billing_Line__c> billingLineList = new List<AcctSeed__Billing_Line__c>();
                billingLineList = [select Id, AcctSeed__Billing__c, AcctSeed__Project__c, Description__c, AcctSeed__Total__c, 
                                Taxable__c, Case__c, Case__r.CaseNumber, Service_Visit__r.Work_Ended__c, Category__c, AcctSeed__Hours_Units__c, 
                                AcctSeed__Rate__c, AvaAcctSeed__Rate__c, AcctSeed__Revenue_GL_Account__c, AcctSeed__Revenue_GL_Account__r.Name,
                                SalesTaxRateFormula__c  
                                from AcctSeed__Billing_Line__c where AcctSeed__Billing__c = :billing.Id];
                
                billLines = new List<AcctSeed__Billing_Line__c>();
                omBillLines = new List<OMBillingLines>();
                Decimal omBLTotal = 0;
                for (AcctSeed__Billing_Line__c bl :billingLineList) {
                        if (bl.AcctSeed__Revenue_GL_Account__r.Name.startsWith('22') || bl.AcctSeed__Revenue_GL_Account__r.Name.startsWith('3102')) {
                                omBillLines.add(new OMBillingLines(bl));
                        }
                        if (!bl.AcctSeed__Revenue_GL_Account__r.Name.startsWith('2204')) {
                                billLines.add(bl);
                        }
                        
                        if (bl.AcctSeed__Total__c != null) {
                                omBLTotal += bl.AcctSeed__Total__c;
                        }
                        
                }
                omBillLineTotal = '$' + String.valueOf(omBLTotal);
                
                Set<Id> pIds = new Set<Id>();
                Id pSvConId = null;
                if (billing.Service_Contract__r.ASProject__c != null) {
                        pSvConId = billing.Service_Contract__r.ASProject__c;
                }
                for (AcctSeed__Billing_Line__c bl :billLines) {
                        if (bl.AcctSeed__Project__c != null) {
                                pIds.add(bl.AcctSeed__Project__c);
                        }
                }
                
                projectList = new List<AcctSeed__Project__c>();
                List<AcctSeed__Project__c> pList = new List<AcctSeed__Project__c>();
                svConProject = new AcctSeed__Project__c();
                if (!pIds.isEmpty() || pSvConId != null) {
                        pList = [select Id, Name, Customer_Project_Name__c, O_M_Manager__c, O_M_Manager__r.Name, 
                                        Site_Address__c, Site_City__c, Site_State__c, Site_Zip__c 
                                        from AcctSeed__Project__c where Id in :pIds or Id = :pSvConId];
                }
                for (AcctSeed__Project__c p :pList) {
                        if (pSvConId == p.Id) {
                                svConProject = p;
                        }
                        if (pIds.contains(p.Id)) {
                                projectList.add(p);
                        }
                }
                
                //attentionNames = (String.isBlank(billing.Service_Contract__r.O_M_Client_Contact__r.Name)) ? ' ' : billing.Service_Contract__r.O_M_Client_Contact__r.Name;
                attentionNames = '';
                attentionNamesOM = '';
                List<ContractContactRole> ccrList = new List<ContractContactRole>();
                ccrList = [select Id, ContactId, Contact.Name, Role from ContractContactRole 
                                where ContractId = :billing.Service_Contract__c and (Role = 'O&M Billing Contact' or Role = 'O&M Service Billing Contact')];
                
                if (!ccrList.isEmpty()) {
                        for (ContractContactRole ccr :ccrList) {
                                attentionNames += (ccr.Role == 'O&M Service Billing Contact') ? ccr.Contact.Name + ', ' : '';
                                attentionNamesOM += (ccr.Role == 'O&M Billing Contact') ? ccr.Contact.Name + ', ' : '';
                        }
                }
                if (String.isBlank(attentionNames)) {
                        attentionNames = ' ';
                } else {
                        attentionNames = attentionNames.removeEnd(', ');
                }
                if (String.isBlank(attentionNamesOM)) {
                        attentionNamesOM = ' ';
                } else {
                        attentionNamesOM = attentionNamesOM.removeEnd(', ');
                }
        }
        
        public class OMBillingLines {
                public AcctSeed__Billing_Line__c billingLine {get; set;}
                public String endDate {get; set;}
                public String quantity {get; set;}
                public String unitMeasure {get; set;}
                public String unitCost {get; set;}
                
                public OMBillingLines(AcctSeed__Billing_Line__c bl) {
                        this.billingLine = bl;
                        this.endDate = (bl.Service_Visit__r.Work_Ended__c == null) ? '' : String.valueOf(bl.Service_Visit__r.Work_Ended__c.date());
                        this.quantity = (bl.AcctSeed__Hours_Units__c == null) ? '' : bl.AcctSeed__Hours_Units__c.setscale(2).toPlainString();
                        this.unitMeasure = (bl.Category__c == 'Labor' || bl.Category__c == 'Drive Time/Travel') ? 'Hours' : '';
                        this.unitCost = (bl.AcctSeed__Rate__c == null) ? '' : '$' + bl.AcctSeed__Rate__c.setscale(2).toPlainString();
                }
        }
}