objects/AcctSeedERP__Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Vendor of the material or the Subcontractor performing the work
Must be an account in Salesforce</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>equals</operation>
                <value>Vendor, Customer and Vendor</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Purchase_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Product on the PO Line
Defaults as the Product listed on the Requisition
PRINTS ON THE PO</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order__c</fullName>
        <inlineHelpText>Purchase Order the PO Line Is associated with</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PO_Line_Status__c</fullName>
        <label>PO Line Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Aaron Approved</fullName>
                </value>
                <value>
                    <fullName>PM Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Vendor</fullName>
                </value>
                <value>
                    <fullName>Vendor Received PO</fullName>
                </value>
                <value>
                    <fullName>Shipment Scheduled</fullName>
                </value>
                <value>
                    <fullName>Vendor Shipped Material</fullName>
                </value>
                <value>
                    <fullName>Shipment On Hold</fullName>
                </value>
                <value>
                    <fullName>Partially Received: Warehouse</fullName>
                </value>
                <value>
                    <fullName>Partially Received: Job Site</fullName>
                </value>
                <value>
                    <fullName>Received In-Full: Warehouse</fullName>
                </value>
                <value>
                    <fullName>Received In-Full: Job Site</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Partially Received</fullName>
                    <label>Partially Received - O&amp;M</label>
                </value>
                <value>
                    <fullName>Received In-Full</fullName>
                    <label>Received In-Full - O&amp;M</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProductRequest.object
<CustomObject>
    <fields>
        <fullName>Mass_Transfer_Alert__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mass Transfer Alert</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Requests</relationshipLabel>
        <relationshipName>Product_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductTransfer.object
<CustomObject>
    <fields>
        <fullName>Ship_To_City__c</fullName>
        <label>Ship To City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_State__c</fullName>
        <label>Ship To State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Street__c</fullName>
        <label>Ship To Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Zip__c</fullName>
        <label>Ship To Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Company__c</fullName>
        <label>Shipping Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_URL__c</fullName>
        <label>Tracking URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Vendor_PO_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor PO Line</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeedERP__Purchase_Order_Line__c.AcctSeedERP__Purchase_Order__r.AcctSeedERP__Vendor__c</field>
                <operation>equals</operation>
                <valueField>$Source.Vendor__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>Product Transfers</relationshipLabel>
        <relationshipName>Product_Transfers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Vendor- Material, Vendor- Corporate, Vendor- Subcontractor/Non-Material</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Product Transfers</relationshipLabel>
        <relationshipName>Product_Transfers</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MassCreateProductTransferController.cls
public with sharing class MassCreateProductTransferController {
    @AuraEnabled (cacheable=true)
    public static String getProductTransferRecordTypes() {
        List<Schema.RecordTypeInfo> recordTypes = Schema.SObjectType.ProductTransfer.getRecordTypeInfos();
        List<Map<String, String>> recordTypeOptions = new List<Map<String, String>>();

        for (Schema.RecordTypeInfo recordType : recordTypes) {
            if (!recordType.isMaster()) {
                recordTypeOptions.add(new Map<String, String> {
                    'label' => recordType.getName(),
                    'value' => recordType.getRecordTypeId()
                });
            }
        }

        return JSON.serialize(recordTypeOptions);
    }

    @AuraEnabled(Cacheable=true)
    public static ProductRequest getProductRequest(String productRequestId) {
        return [SELECT Id, SourceLocationId, SourceLocation.Name, DestinationLocationId, DestinationLocation.Name, Vendor__c, Vendor__r.Name, ShipToStreet, ShipToCity, ShipToState, ShipToPostalCode FROM ProductRequest WHERE Id = :productRequestId];
    }

    @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> getLocations(String searchTerm, List<String> selectedIds) {
        searchTerm = '%' + searchTerm + '%';

        List<Schema.Location> locations = [SELECT Id, Name FROM Location WHERE Name LIKE :searchTerm LIMIT 5];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String locationIcon = 'standard:location';
        for (Schema.Location location : locations) {
            results.add(
                new LookupSearchResult(
                    location.Id,
                    'Location',
                    locationIcon,
                    location.Name,
                    ''
                )
            );
        }

        return results;
    }

    @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> getVendors(String searchTerm, List<String> selectedIds) {
        searchTerm = '%' + searchTerm + '%';

        List<Account> accounts = [SELECT Id, Name FROM Account WHERE Name LIKE :searchTerm LIMIT 5];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String accountIcon = 'standard:account';
        for (Account account : accounts) {
            results.add(
                new LookupSearchResult(
                    account.Id,
                    'Account',
                    accountIcon,
                    account.Name,
                    ''
                )
            );
        }

        return results;
    }

    @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> getSourceProductItem(String searchTerm, List<String> selectedIds, String locationId) {
        searchTerm = '%' + searchTerm + '%';

        List<ProductItem> productItems = [SELECT Id, Product2Id, Product2.Name FROM ProductItem WHERE Product2.Name LIKE :searchTerm AND LocationId = :locationId LIMIT 5];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String productItemIcon = 'standard:product_item';

        for (ProductItem productItem : productItems) {
            results.add(
                new LookupSearchResult(
                    productItem.Id,
                    'ProductItem',
                    productItemIcon,
                    productItem.Product2.Name,
                    productItem.Product2.Id
                )
            );
        }

        return results;
    }

    @AuraEnabled(Cacheable=true)
    public static List<LookupSearchResult> getVendorPOLineItems(String searchTerm, List<String> selectedIds, String locationId) {
        searchTerm = '%' + searchTerm + '%';

        List<AcctSeedERP__Purchase_Order_Line__c> purchaseOrderLineItems = [SELECT Id, AcctSeedERP__Product__c, AcctSeedERP__Product__r.Name FROM AcctSeedERP__Purchase_Order_Line__c WHERE AcctSeedERP__Product__r.Name LIKE :searchTerm AND PO_Line_Status__c != 'Closed' AND AcctSeedERP__Purchase_Order__r.AcctSeedERP__Vendor__c = :locationId LIMIT 5];

        List<LookupSearchResult> results = new List<LookupSearchResult>();

        String purchaseOrderLineItemIcon = 'standard:product';

        for (AcctSeedERP__Purchase_Order_Line__c purchaseOrderLineItem : purchaseOrderLineItems) {
            results.add(
                new LookupSearchResult(
                    purchaseOrderLineItem.Id,
                    'ProductItem',
                    purchaseOrderLineItemIcon,
                    purchaseOrderLineItem.AcctSeedERP__Product__r.Name,
                    purchaseOrderLineItem.AcctSeedERP__Product__c
                )
            );
        }

        return results;
    }

    @AuraEnabled
    public static ProductItem getDefaultProductItem(String productId, String locationId) {
        return [SELECT Id, Product2Id, Product2.Name FROM ProductItem WHERE Product2Id = :productId AND LocationId = :locationId LIMIT 1];
    }

    @AuraEnabled
    public static AcctSeedERP__Purchase_Order_Line__c getDefaultVendorPOLineItem(String productId, String vendorId) {
        return [SELECT Id, AcctSeedERP__Product__c, AcctSeedERP__Product__r.Name FROM AcctSeedERP__Purchase_Order_Line__c WHERE AcctSeedERP__Product__c =: productId AND AcctSeedERP__Purchase_Order__r.AcctSeedERP__Vendor__c = :vendorId AND PO_Line_Status__c != 'Closed' LIMIT 1];
    }

    @AuraEnabled(Cacheable=true)
    public static List<ProductRequestLineItem> getProductRequestLineItems(String productRequestId) {
        return [SELECT Id, QuantityRequested, Product2Id, Product2.Name FROM ProductRequestLineItem WHERE ParentId = :productRequestId AND Status != 'Fulfilled'];
        // return [SELECT Id, QuantityRequested, Product2Id, Product2.Name FROM ProductRequestLineItem WHERE ParentId = :productRequestId];
    }

    @AuraEnabled
    public static void createProductTransfers(String productRequestId, String productTransfersString) {
        List<ProductTransferWrapper> productTransferWrappers = (List<ProductTransferWrapper>) JSON.deserialize(productTransfersString.replaceAll('__c', '').replaceAll('__r', 'rrr').replace('AcctSeedERP__Productrrr', 'Product2'), List<ProductTransferWrapper>.class);
        List<ProductTransfer> productTransfers = new List<ProductTransfer>();
        for (ProductTransferWrapper tempProductTransferWrapper : productTransferWrappers) {
            productTransfers.add(tempProductTransferWrapper.createProductTransfer());
        }
        insert productTransfers;

        ProductRequest productRequest = [SELECT Id, Mass_Transfer_Alert__c FROM ProductRequest WHERE Id = :productRequestId];
        productRequest.Mass_Transfer_Alert__c = true;
        update productRequest;
    }

    public class ProductTransferWrapper {
        public String Id {get; set;}
        public Decimal QuantityRequested {get; set;}
        public String Product2Id {get; set;}
        public String DestinationLocationId {get; set;}
        public String RecordTypeId {get; set;}
        public String SourceLocationId {get; set;}
        public String Shipping_Company {get; set;}
        public String Tracking_Number {get; set;}
        public String Tracking_URL {get; set;}
        public Date ExpectedPickupDate {get; set;}
        public String ShipToStreet {get; set;}
        public String ShipToCity {get; set;}
        public String ShipToState {get; set;}
        public String ShipToPostalCode {get; set;}
        public String SourceProductItemId {get; set;}
        public SourceProductItemWrapper SourceProductItem {get; set;}
        public String Vendor_PO_Line {get; set;}
        public VendorPOLineWrapper Vendor_PO_Linerrr {get; set;}

        public ProductTransfer createProductTransfer() {
            if (this.SourceProductItemId != null) {
                return new ProductTransfer(
                    ProductRequestLineItemId = this.Id,
                    RecordTypeId = this.RecordTypeId,
                    QuantitySent = this.QuantityRequested,
                    Product2Id = this.SourceProductItem.Product2.Id,
                    SourceProductItemId = this.SourceProductItemId,
                    DestinationLocationId = this.DestinationLocationId,
                    SourceLocationId = this.SourceLocationId,
                    Shipping_Company__c = this.Shipping_Company,
                    Tracking_Number__c = this.Tracking_Number,
                    Tracking_URL__c = this.Tracking_URL,
                    ExpectedPickupDate = this.ExpectedPickupDate,
                    Ship_To_Street__c = this.ShipToStreet,
                    Ship_To_City__c = this.ShipToCity,
                    Ship_To_State__c = this.ShipToState,
                    Ship_To_Zip__c = this.ShipToPostalCode
                );
            } else if (this.Vendor_PO_Line != null) {
                return new ProductTransfer(
                    ProductRequestLineItemId = this.Id,
                    RecordTypeId = this.RecordTypeId,
                    QuantitySent = this.QuantityRequested,
                    Product2Id = this.Vendor_PO_Linerrr.Product2.Id,
                    Vendor_PO_Line__c = this.Vendor_PO_Line,
                    DestinationLocationId = this.DestinationLocationId,
                    SourceLocationId = this.SourceLocationId,
                    Shipping_Company__c = this.Shipping_Company,
                    Tracking_Number__c = this.Tracking_Number,
                    Tracking_URL__c = this.Tracking_URL,
                    ExpectedPickupDate = this.ExpectedPickupDate,
                    Ship_To_Street__c = this.ShipToStreet,
                    Ship_To_City__c = this.ShipToCity,
                    Ship_To_State__c = this.ShipToState,
                    Ship_To_Zip__c = this.ShipToPostalCode
                );
            } else {
                return new ProductTransfer(
                    ProductRequestLineItemId = this.Id,
                    RecordTypeId = this.RecordTypeId,
                    QuantitySent = this.QuantityRequested,
                    Product2Id = this.Product2Id,
                    DestinationLocationId = this.DestinationLocationId,
                    SourceLocationId = this.SourceLocationId,
                    Shipping_Company__c = this.Shipping_Company,
                    Tracking_Number__c = this.Tracking_Number,
                    Tracking_URL__c = this.Tracking_URL,
                    ExpectedPickupDate = this.ExpectedPickupDate,
                    Ship_To_Street__c = this.ShipToStreet,
                    Ship_To_City__c = this.ShipToCity,
                    Ship_To_State__c = this.ShipToState,
                    Ship_To_Zip__c = this.ShipToPostalCode
                );
            }
        }
    }

    public class SourceProductItemWrapper {
        public Product2Wrapper Product2 {get; set;}
    }

    public class VendorPOLineWrapper {
        public Product2Wrapper Product2 {get; set;}
    }

    public class Product2Wrapper {
        public String Id {get; set;}
        public String Name {get; set;}
    }
}