objects/AcctSeed__Account_Payable_Line__c.object
<CustomObject>
    <description>Line item expense associated with an payable. The aggregation of multiple payable lines constitute a payable record.</description>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related PO Line for allocation of cost.</inlineHelpText>
        <label>Purchase Order Line</label>
        <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>Account Payable Lines</relationshipLabel>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Account__c</fullName>
        <formula>AcctSeed__Project__r.AcctSeed__Account__r.Name</formula>
        <inlineHelpText>The account for which the project is related to. Pulls through from the Project listed.</inlineHelpText>
        <label>Project Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Project or Job for allocation of cost.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Payable Lines</relationshipLabel>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Account_Payable_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payable Line</label>
    <nameField>
        <displayFormat>APL-{00000}</displayFormat>
        <label>Payable Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payable Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Billing_Line__c.object
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <fields>
        <fullName>AcctSeedERP__Sales_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order Line</label>
        <referenceTo>AcctSeedERP__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the Project the Billing Line is related to</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Reference to Credit side of related transaction created in the posting process.</inlineHelpText>
        <label>zDep-Transaction</label>
        <referenceTo>AcctSeed__Transaction__c</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Project_Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Billing Lines</relationshipLabel>
        <relationshipName>Billing_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Journal_Entry_Line__c.object
<CustomObject>
    <description>Line level entry associated with a journal entry. The aggregation of multiple journal entry lines constitute a journal entry record.</description>
    <fields>
        <fullName>AcctSeed__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Related Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Journal Entry Lines</relationshipLabel>
        <relationshipName>Journal_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Project or Job for allocation of cost.</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Status__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Journal Entry Lines</relationshipLabel>
        <relationshipName>Journal_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>related Case from SOL/POL, usually filled in via an upload of JEL</description>
        <inlineHelpText>related Case from SOL/POL</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Journal Entry Lines</relationshipLabel>
        <relationshipName>Journal_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Work Order</description>
        <inlineHelpText>Lookup to Work Order</inlineHelpText>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Journal Entry Lines</relationshipLabel>
        <relationshipName>Journal_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Journal Entry Line</label>
    <nameField>
        <displayFormat>JEL-{00000}</displayFormat>
        <label>Journal Entry Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AcctSeed__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>O_M_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>O&amp;M Manager based on the project branch.</inlineHelpText>
        <label>O&amp;M Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects8</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeed__Transaction__c.object
<CustomObject>
    <description>Used to document a specific entry to a ledger. Transaction records are created when a source record is posted i.e. payable, billing, cash disbursement, cash receipt, journal entry, scheduled revenue expense, and time card.</description>
    <fields>
        <fullName>AcctSeed__Account_Payable_Line__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Reference to source transaction.</inlineHelpText>
        <label>Payable Line</label>
        <referenceTo>AcctSeed__Account_Payable_Line__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Project_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This field is populated based on the transaction source record. The mapping is Journal Entry Line Account field, Billing Customer, Accounts Payable Payee field, Cash Receipt Account field, or Cash Disbursement Payee field.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Billing_Line__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Reference to source transaction.</inlineHelpText>
        <label>Billing Line</label>
        <referenceTo>AcctSeed__Billing_Line__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Project_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Journal_Entry_Line__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Reference to source transaction.</inlineHelpText>
        <label>Journal Entry Line</label>
        <referenceTo>AcctSeed__Journal_Entry_Line__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Project or Job for allocation of cost or revenue.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Project_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SV__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SV#</label>
        <referenceTo>SV__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PO Line created from the req
This is filled in when the req is converted to a PO</inlineHelpText>
        <label>Purchase Order Line</label>
        <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>Sales Order Line</relationshipLabel>
        <relationshipName>Sales_Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Sales Order Line</relationshipLabel>
        <relationshipName>Sales_Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <description>For Service Construction Requisitions</description>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The case on which the service visit was scheduled.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TransactionService.cls
public class TransactionService {
    
    /*
     *  Service methods for TransactionTrigger_BS.trigger
     *
     */
    
    // Set various fields on Transaction records from related records
    // - before insert, before update
    public static void relatedRecordFields(List<AcctSeed__Transaction__c> newList, Map<Id, AcctSeed__Transaction__c> oldMap, Boolean isInsert) {
        Set<Id> aplIds = new Set<Id>();
        Set<Id> projIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Set<Id> jelIds = new Set<Id>();
        Set<Id> bilIds = new Set<Id>();
        system.debug('this is newlist--->'  +newlist);
       
        for (AcctSeed__Transaction__c t :newList) {
         system.debug('this is bill id start-->' +t.AcctSeed__Billing_Line__c);
        if (t.AcctSeed__Journal_Entry_Line__c != null) {
           /*     if (isInsert) {
                    jelIds.add(t.AcctSeed__Journal_Entry_Line__c);
                } else {
                    if (t.AcctSeed__Journal_Entry_Line__c != oldMap.get(t.Id).AcctSeed__Journal_Entry_Line__c) {
                        jelIds.add(t.AcctSeed__Journal_Entry_Line__c);
                    }
                } */
             jelIds.add(t.AcctSeed__Journal_Entry_Line__c);
            }
            system.debug('jelids look-->' +jelids);
            if (t.AcctSeed__Billing_Line__c!= null) {
          /*      if (isInsert) {
                    bilIds.add(t.AcctSeed__Billing_Line__c);
                } else {
                    if (t.AcctSeed__Billing_Line__c!= oldMap.get(t.Id).AcctSeed__Billing_Line__c) {
                        bilIds.add(t.AcctSeed__Billing_Line__c);
                    }
                } */
              bilIds.add(t.AcctSeed__Billing_Line__c);  
            }
            system.debug('this is bill id-->' +bilIds);
            if (t.AcctSeed__Account_Payable_Line__c != null) {
                if (isInsert) {
                    aplIds.add(t.AcctSeed__Account_Payable_Line__c);
                } else {
                    if (t.AcctSeed__Account_Payable_Line__c != oldMap.get(t.Id).AcctSeed__Account_Payable_Line__c) {
                        aplIds.add(t.AcctSeed__Account_Payable_Line__c);
                    }
                }
            }
            
            if (t.AcctSeed__Project__c != null) {
                if (isInsert) {
                    projIds.add(t.AcctSeed__Project__c);
                } else {
                    if (t.AcctSeed__Project__c != oldMap.get(t.Id).AcctSeed__Project__c) {
                        projIds.add(t.AcctSeed__Project__c);
                    }
                }
            }
            
            if (t.AcctSeed__Account__c != null) {
                if (isInsert) {
                    accIds.add(t.AcctSeed__Account__c);
                } else {
                    if (t.AcctSeed__Account__c != oldMap.get(t.Id).AcctSeed__Account__c) {
                        accIds.add(t.AcctSeed__Account__c);
                    }
                }
            }
        }
        
        Map<Id, AcctSeed__Project__c> projMap;
        if (!projIds.isEmpty()) {
            projMap = new Map<Id, AcctSeed__Project__c>([select Id, O_M_Manager__c from AcctSeed__Project__c where Id in :projIds]);
        } else {
            projMap = new Map<Id, AcctSeed__Project__c>();
        }
        
        Map<Id, Account> accMap;
        if (!accIds.isEmpty()) {
            accMap = new Map<Id, Account>([select Id, ParentId from Account where Id in :accIds]);
        } else {
            accMap = new Map<Id, Account>();
        }
        
        Map<Id, AcctSeed__Account_Payable_Line__c> aplMap;
        Map<Id, AcctSeedERP__Purchase_Order_Line__c> polMap;
        Map<Id, AcctSeedERP__Sales_Order_Line__c> solMap;
        Map<Id, SV__c> svMap;
        Map<Id, Workorder> WoMap;
        Map<Id, Case> caseMap;
        Map<Id, AcctSeed__Journal_Entry_Line__c> jelmap;
        Map<Id, AcctSeed__Billing_Line__c> bilmap;
         if (!bilIds.isEmpty()) {
            bilmap= new Map<Id, AcctSeed__Billing_Line__c>([select Id, Case__c,WorkOrder__c  from AcctSeed__Billing_Line__c where Id in :bilIds]);
            Set<Id> caseids1= new Set<Id>();
            Set<Id> workorderids1= new Set<Id>();
            for (AcctSeed__Billing_Line__c bil :bilmap.values()) {
                if (bil.Case__c != null) {
                    caseids1.add(bil.Case__c );
                }
                if (bil.WorkOrder__c!= null) {
                    workorderids1.add(bil.WorkOrder__c);
                }
            }
            }
            else
            {
            aplMap = new Map<Id, AcctSeed__Account_Payable_Line__c>();
            polMap = new Map<Id, AcctSeedERP__Purchase_Order_Line__c>();
            solMap = new Map<Id, AcctSeedERP__Sales_Order_Line__c>();
            svMap = new Map<Id, SV__c>();
            WoMap = new Map<Id, WorkOrder>();
            caseMap = new Map<Id, Case>();
                if (test.isRunningTest()){
                    jelmap=new Map<Id,AcctSeed__Journal_Entry_Line__c>();
                }
            //
            }
            system.debug('this is bilmap-->' +bilmap );
        
        if (!jelIds.isEmpty()) {
            jelmap = new Map<Id, AcctSeed__Journal_Entry_Line__c>([select Id, Case__c,WorkOrder__c from AcctSeed__Journal_Entry_Line__c where Id in :jelIds]);
            Set<Id> caseids= new Set<Id>();
            Set<Id> workorderids= new Set<Id>();
            for (AcctSeed__Journal_Entry_Line__c jel :jelMap.values()) {
                if (jel.Case__c != null) {
                    caseids.add(jel.Case__c );
                }
                if (jel.WorkOrder__c!= null) {
                    workorderids.add(jel.WorkOrder__c);
                }
            }
            }else{
            aplMap = new Map<Id, AcctSeed__Account_Payable_Line__c>();
            polMap = new Map<Id, AcctSeedERP__Purchase_Order_Line__c>();
            solMap = new Map<Id, AcctSeedERP__Sales_Order_Line__c>();
            svMap = new Map<Id, SV__c>();
            WoMap = new Map<Id, WorkOrder>();
            caseMap = new Map<Id, Case>();
                if (test.isRunningTest()){
                    bilmap=new Map<Id,AcctSeed__Billing_Line__c>();
                }
            //bilmap=new Map<Id,AcctSeed__Billing_Line__c>();
        }
        
            
        if (!aplIds.isEmpty()) {
            aplMap = new Map<Id, AcctSeed__Account_Payable_Line__c>([select Id, AcctSeedERP__Purchase_Order_Line__c from AcctSeed__Account_Payable_Line__c where Id in :aplIds]);
            Set<Id> polIds = new Set<Id>();
            for (AcctSeed__Account_Payable_Line__c apl :aplMap.values()) {
                if (apl.AcctSeedERP__Purchase_Order_Line__c != null) {
                    polIds.add(apl.AcctSeedERP__Purchase_Order_Line__c);
                }
            }
            
            if (!polIds.isEmpty()) {
                polMap = new Map<Id, AcctSeedERP__Purchase_Order_Line__c>([select Id, Construction_Req__c from AcctSeedERP__Purchase_Order_Line__c where Id in :polIds]);
                Set<Id> solIds = new Set<Id>();
                for (AcctSeedERP__Purchase_Order_Line__c pol :polMap.values()) {
                    if (pol.Construction_Req__c != null) {
                        solIds.add(pol.Construction_Req__c);
                    }
                }
                
                if (!solIds.isEmpty()) {
                    solMap = new Map<Id, AcctSeedERP__Sales_Order_Line__c>([select Id, Service_Visit__c,WorkOrder__c from AcctSeedERP__Sales_Order_Line__c where Id in :solIds]);
                    Set<Id> svIds = new Set<Id>();
                    Set<Id> woIds = new Set<Id>();
                    for (AcctSeedERP__Sales_Order_Line__c sol :solMap.values()) {
                        if (sol.Service_Visit__c != null) {
                            svIds.add(sol.Service_Visit__c);
                        }
                        
                        if (sol.WorkOrder__c !=null){
                             woIds.add(sol.WorkOrder__c);
                        }
                    }
                    
                    if (!svIds.isEmpty()) {
                        svMap = new Map<Id, SV__c>([select Id, Case__c, Contract__c from SV__c where Id in :svIds]);
                        Set<Id> cIds = new Set<Id>();
                        for (SV__c sv :svMap.values()) {
                            if (sv.Case__c != null) {
                                cIds.add(sv.Case__c);
                            }
                        }
                        
                        if (!cIds.isEmpty()) {
                            caseMap = new Map<Id, Case>([select Id, Status, ClosedDate from Case where Id in :cIds]);
                        } else {
                            caseMap = new Map<Id, Case>();
                        }
                    }
                    /// Adding the logic for Workorder to add in transaction (MG 6/20/2019)//// 
                    
                    if (!woIds.isEmpty()) {
                        woMap = new Map<Id, WorkOrder>([select Id, CaseId, Contract__c from WorkOrder where Id in :woIds]);
                        Set<Id> cIds = new Set<Id>();
                        for (WorkOrder wo :woMap.values()) {
                            if (wo.CaseId != null) {
                                cIds.add(wo.CaseId);
                            }
                        }
                        
                        if (!cIds.isEmpty()) {
                            caseMap = new Map<Id, Case>([select Id, Status, ClosedDate from Case where Id in :cIds]);
                        } else {
                            caseMap = new Map<Id, Case>();
                        }
                    }
                 ///////   
                     else {
                        svMap = new Map<Id, SV__c>();
                        WoMap = new Map<Id, WorkOrder>();
                        caseMap = new Map<Id, Case>();
                    }
                } else {
                    solMap = new Map<Id, AcctSeedERP__Sales_Order_Line__c>();
                    svMap = new Map<Id, SV__c>();
                    WoMap = new Map<Id, WorkOrder>();
                    caseMap = new Map<Id, Case>();
                }
            } else {
                polMap = new Map<Id, AcctSeedERP__Purchase_Order_Line__c>();
                solMap = new Map<Id, AcctSeedERP__Sales_Order_Line__c>();
                svMap = new Map<Id, SV__c>();
                WoMap = new Map<Id, WorkOrder>();
                caseMap = new Map<Id, Case>();
            }
        } else {
            aplMap = new Map<Id, AcctSeed__Account_Payable_Line__c>();
            polMap = new Map<Id, AcctSeedERP__Purchase_Order_Line__c>();
            solMap = new Map<Id, AcctSeedERP__Sales_Order_Line__c>();
            svMap = new Map<Id, SV__c>();
            WoMap = new Map<Id, WorkOrder>();
            caseMap = new Map<Id, Case>();
        }
        
        
        
        // Update all of the new/changed values
        for (AcctSeed__Transaction__c t :newList) {
        system.debug('entering loop1');
            
            if (projMap.containsKey(t.AcctSeed__Project__c)) {
                t.O_M_Mgr__c = projMap.get(t.AcctSeed__Project__c).O_M_Manager__c;
            }
            
            if (accMap.containsKey(t.AcctSeed__Account__c)) {
                t.Parent_Account__c = accMap.get(t.AcctSeed__Account__c).ParentId;
            }
            system.debug('entering loop2' +t.AcctSeed__Journal_Entry_Line__c);
            
            if(t.AcctSeed__Journal_Entry_Line__c!=null)
            {
            
            
                        
             if (jelMap.containsKey(t.AcctSeed__Journal_Entry_Line__c)) {
                        t.Case__c = jelMap.get(t.AcctSeed__Journal_Entry_Line__c).Case__c;
                        t.WorkOrder__c=jelMap.get(t.AcctSeed__Journal_Entry_Line__c).WorkOrder__c;
                        }
                        }
                        
                        SYSTEM.DEBUG('THIS IS CASE' +t.Case__c);
                        SYSTEM.DEBUG('THIS IS WO' + t.WorkOrder__c);
                        
                        
                        system.debug('entering loop3' +t.AcctSeed__Billing_Line__c);
                        system.debug('entering loop4' +bilMap);
                        
                        
                       if(t.AcctSeed__Billing_Line__c!=null)
                       {
                           system.debug(bilMap.containsKey(t.AcctSeed__Billing_Line__c));
                   if (bilMap.containsKey(t.AcctSeed__Billing_Line__c)) {
                        system.debug('entering loop');
                        t.Case__c = bilMap.get(t.AcctSeed__Billing_Line__c).Case__c;
                        system.debug('case' +t.Case__c);
                        t.WorkOrder__c=bilMap.get(t.AcctSeed__Billing_Line__c).WorkOrder__c  ;
                        }
                       }
                       
                        SYSTEM.DEBUG('THIS IS CASE' +t.Case__c);
                        SYSTEM.DEBUG('THIS IS WO' + t.WorkOrder__c);
                        
            
            if (aplMap.containsKey(t.AcctSeed__Account_Payable_Line__c)) {
                t.POL__c = aplMap.get(t.AcctSeed__Account_Payable_Line__c).AcctSeedERP__Purchase_Order_Line__c;
                
                if (polMap.containsKey(t.POL__c)) {
                    t.SOL__c = polMap.get(t.POL__c).Construction_Req__c;
                    
                    if (solMap.containsKey(t.SOL__c)) {
                        t.SV__c = solMap.get(t.SOL__c).Service_Visit__c;
                        t.WorkOrder__c = solMap.get(t.SOL__c).WorkOrder__c;
                        
                        
                        
                    /*    if (bilMap.containsKey(t.AcctSeed__Billing_Line__c)) {
                        system.debug('entering loop');
                        t.Case__c = bilMap.get(t.AcctSeed__Billing_Line__c).Case__c;
                        system.debug('case' +t.Case__c);
                        t.WorkOrder__c=bilMap.get(t.AcctSeed__Billing_Line__c).Work_Order__c ;
                        } */
               /*         if (svMap.containsKey(t.SV__c)) {
                            t.Case__c = svMap.get(t.SV__c).Case__c;
                            t.Contract__c = svMap.get(t.SV__c).Contract__c;
                            
                            if (caseMap.containsKey(t.Case__c)) {
                                t.Case_Status__c = caseMap.get(t.Case__c).Status;
                                t.Case_Closed_Date__c = caseMap.get(t.Case__c).ClosedDate;
                            }
                        }   Commenting line since no SV and throwing null exceptions */
                        
                        ///updatin Logic to add Work order and related case and Contract (MG 6/20/2019)
                        
                        if (woMap.containsKey(t.WorkOrder__c )) {
                            t.Case__c = WoMap.get(t.WorkOrder__c ).CaseId;
                            t.Contract__c = WoMap.get(t.WorkOrder__c ).Contract__c;
                            
                            if (caseMap.containsKey(t.Case__c)) {
                                t.Case_Status__c = caseMap.get(t.Case__c).Status;
                                t.Case_Closed_Date__c = caseMap.get(t.Case__c).ClosedDate;
                            }
                            }
                       
                        
                        
                        
                        ////
                        
                    }
                    
                    
                }
            }
            
            // If any of the lookup fields are null, set the dependent fields null
            if (t.AcctSeed__Project__c == null) {
                t.O_M_Mgr__c = null;
            }
            
            if (t.AcctSeed__Account__c == null) {
                t.Parent_Account__c = null;
            }
            
            if (t.AcctSeed__Account_Payable_Line__c == null) {
                t.POL__c = null;
                t.SOL__c = null;
                t.SV__c = null;
               // t.workorder__c=null;
               // t.Case__c = null;
                t.Case_Status__c = '';
                t.Case_Closed_Date__c = null;
                t.Contract__c = null;
            } else {
                if (t.POL__c == null) {
                    t.SOL__c = null;
                    t.SV__c = null;
                 //   t.workorder__c=null;
                 //   t.Case__c = null;
                    t.Case_Status__c = '';
                    t.Case_Closed_Date__c = null;
                    t.Contract__c = null;
                } else {
                    if (t.SOL__c == null) {
                        t.SV__c = null;
                     //   t.workorder__c=null;
                      //  t.Case__c = null;
                        t.Case_Status__c = '';
                        t.Case_Closed_Date__c = null;
                        t.Contract__c = null;
                    } else {
                        if (t.SV__c == null) {
                       //     t.Case__c = null;
                              t.Case_Status__c = '';
                              t.Case_Closed_Date__c = null;
                              t.Contract__c = null;
                        } else {
                            if (t.Case__c == null) {
                                t.Case_Status__c = '';
                                t.Case_Closed_Date__c = null;
                            }
                        }
                    }
                }
            }
        }
    }
}