objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>AcctSeedProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expected_Rebate__c</fullName>
        <description>Automatically populated from the associated Opportunity record Expected Rebate field.</description>
        <formula>AcctSeed__Opportunity__r.Expected_Rebate__c</formula>
        <inlineHelpText>Automatically populated from the associated Opportunity record Expected Rebate field.</inlineHelpText>
        <label>Expected Rebate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <formula>IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;Cash&quot;), &quot;Cash &quot;, NULL) +
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;PPA&quot;), &quot;PPA &quot;, NULL) + 
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;Lease&quot;), &quot;Lease &quot;, NULL) +
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;PACE&quot;), &quot;PACE &quot;, NULL) +  
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;TEML (tax -exempt municipal lease)&quot;), &quot;TEML (tax -exempt municipal lease) &quot;, NULL) + 
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;GO Bond&quot;), &quot;GO Bond &quot;, NULL) +
IF(INCLUDES( AcctSeed__Opportunity__r.Financing_Options_Provided__c , &quot;Other&quot;), &quot;Other &quot;, NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>How the project is financed- designated on the Opportunity</inlineHelpText>
        <label>Financing Options Provided</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inverter_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Inverter delivery</inlineHelpText>
        <label>Inverter Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Module_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Module delivery</inlineHelpText>
        <label>Module Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prevailing_Wage__c</fullName>
        <formula>TEXT(AcctSeed__Opportunity__r.Prevailing_Wage__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prevailing Wage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Racking_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Racking delivery</inlineHelpText>
        <label>Racking Delivery Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prevailing_Wage__c</fullName>
        <description>NO LONGER IN USE replaced by field Prevailing Wage Included.</description>
        <formula>TEXT(ASProject__r.AcctSeed__Opportunity__r.Prevailing_Wage__c)</formula>
        <inlineHelpText>pulls value from prevailing wage field on the opportunity</inlineHelpText>
        <label>Prevailing Wage DO NOT USE</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approximate_Install_Date__c</fullName>
        <description>This is the approximate date that customer expects that installation will begin.</description>
        <inlineHelpText>Required at Project Awarded- This is the approximate date that customer expects that installation will begin.</inlineHelpText>
        <label>Approximate Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Rebate__c</fullName>
        <description>This is the dollar value of the rebate we expect project to be eligable for.</description>
        <inlineHelpText>Expected Rebate Amount- required at Project Awarded. Enter $0 if rebate is not applicable</inlineHelpText>
        <label>Expected Rebate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <inlineHelpText>Denotes the Financing that was selected when the contract was signed.</inlineHelpText>
        <label>Final Financing Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PPA – Borrego</fullName>
                </value>
                <value>
                    <fullName>PPA - 3rd Party</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>HELOC</fullName>
                </value>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PPA</fullName>
                </value>
                <value>
                    <fullName>PACE</fullName>
                </value>
                <value>
                    <fullName>TEML (tax-exempt municipal lease)</fullName>
                </value>
                <value>
                    <fullName>GO Bond</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inverter_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Date of Inverter Delivery</inlineHelpText>
        <label>Inverter Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Module_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Module Delivery Date</inlineHelpText>
        <label>Module Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Contract_System_Size__c</fullName>
        <inlineHelpText>Original Contract System Size in watts- Proposed or executed Contract System Size</inlineHelpText>
        <label>PV System Size - DC (W)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prevailing_Wage__c</fullName>
        <inlineHelpText>Does the contract include Prevailing Wage? Required at Contract Signing</inlineHelpText>
        <label>Prevailing Wage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal_Submitted_Date__c</fullName>
        <label>First Proposal Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_System_Size__c</fullName>
        <inlineHelpText>Current proposed system size in watts</inlineHelpText>
        <label>Proposed System Size (watts)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Racking_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Racking Delivery Date</inlineHelpText>
        <label>Racking Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The individual or entity that will own the system.</inlineHelpText>
        <label>System Owner-Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (System Owner)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Rate__c</fullName>
        <inlineHelpText>What is the host customer&apos;s or offtaker&apos;s current utility rate? You can find this on their bill.</inlineHelpText>
        <label>Current Utility Rate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E A</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E AL-TOU</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E AL-TOU DGR</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E PA</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E PA-T-1</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A6</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A-10</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A-10 TOU</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E E-19</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E E-20</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-1</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-4</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-5</fullName>
                </value>
                <value>
                    <fullName>SCE GS-1</fullName>
                </value>
                <value>
                    <fullName>SCE GS-2</fullName>
                </value>
                <value>
                    <fullName>SCE GS-2 TOU</fullName>
                </value>
                <value>
                    <fullName>SCE GS-3-A</fullName>
                </value>
                <value>
                    <fullName>SCE-GS-3-B</fullName>
                </value>
                <value>
                    <fullName>SCE-GS-3-R</fullName>
                </value>
                <value>
                    <fullName>SCE TOU-8-A</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-B</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-CPP</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-R</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-1</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-2</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-3</fullName>
                </value>
                <value>
                    <fullName>LADWP A1A</fullName>
                </value>
                <value>
                    <fullName>LADWP A2A</fullName>
                </value>
                <value>
                    <fullName>NSTAR B7-TOU</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related account for the Service Contract.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prevailing_Wage__c</fullName>
        <description>indicates if prevailing wage is included Y/N from related contract field of same name</description>
        <formula>Contract__r.Prevailing_Wage_Included__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>indicates if prevailing wage is included Y/N from related contract field of same name</inlineHelpText>
        <label>Prevailing Wage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <recordTypes>
        <fullName>Other</fullName>
        <active>true</active>
        <description>used for all Non-Reactive, Non-PM Service Visits</description>
        <label>Other</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/testServiceVist_ProjectCtlExt.cls
@isTest
private class testServiceVist_ProjectCtlExt {

@testSetup
    public static void setup() {
      ASeedAccountingSettingsSetupTest.testDataSetup(); 
    }
    
    /*
     *  Test methods for ServiceVisit_ProjectCtlExt.cls
     *
     */
    
    // Create test data
    @testSetup static void svpTestData() {
        
        Account acc = new Account(Name = 'svpAccount');
        insert acc;
        
        Contact con = new Contact(FirstName = 'Generic', LastName = 'Technician', Title = 'Solar Tech', AccountId = acc.Id);
        insert con;
        
         user userid = [select id from user where isactive=true  and department ='o&m' and title like '%Manager%' limit 1];
        
        Opportunity testOpportunity = new Opportunity(Name = 'Test test', AccountId = acc.Id, CloseDate = System.today(), Module_Delivery_Date__c =system.now().Date(),         
                Inverter_Delivery_Date__c =system.now().Date(), Racking_Delivery_Date__c =system.now().Date(), StageName = 'Project Awarded', Amount = 500000, Proposed_System_Size__c = 10000,
                System_Owner__c = con.Id, Expected_Rebate__c = 0,Utility_Rate__c = 'N/A', Prevailing_Wage__c = 'No', Original_Contract_System_Size__c = 1000, 
                Type = 'Turnkey System', Approximate_Install_Date__c = System.today(), Proposal_Submitted_Date__c = System.today(), Financing__c = 'Cash', 
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Standard Opportunity').getRecordTypeId());
        insert testOpportunity;
        
        AcctSeed__Project__c testProject = new AcctSeed__Project__c(Name = 'Knight - 2456',AcctSeed__Account__c = acc.Id, AcctSeed__Opportunity__c = testOpportunity.Id, Branch__c = 'San Diego',PC_Code__c = 10);
        insert testProject;
        
        Contract cntrct = new Contract(Name = 'nsvContract', AccountId = acc.Id, Type__c = 'Other', ASProject__c = testProject.Id, Contract_Status__c = 'Active',Area_Supervisor__c=userid.id,Regional_Manager_User__c=userid.id);
        insert cntrct;
        
        Map<String, Schema.RecordTypeInfo> rtSVMap = Schema.SObjectType.SV__c.getRecordTypeInfosByName();
        SV__c testSV = new SV__c(Account__c = acc.Id, Project__c = testProject.Id, Contract__c = cntrct.Id, RecordTypeId = rtSVMap.get('Admin Service Visit').getRecordTypeId());
        insert testSV;
    }
    
    static testMethod void svpTest1() {
        SV__c testSV = [select Id from SV__c];
        
        ApexPages.StandardController std = new ApexPages.StandardController(testSV);
        ServiceVisit_ProjectCtlExt ctl = new ServiceVisit_ProjectCtlExt(std);
        
        ctl.getcontracts();
        String selContract = ctl.getselectedContract();
        ctl.projectChanged();
        ctl.setselectedContract(selContract);
        ctl.saveServiceVisit();
    }
}