objects/AcctSeed__Recurring_Billing__c.object
<CustomObject>
    <description>Captures information related to recurring billings associated with customers. A recurring billing is a template for creating billings on a periodic basis.</description>
    <fields>
        <fullName>AcctSeed__Billing_Frequency__c</fullName>
        <inlineHelpText>shared picklist should should match values of Payment Options in contract as well as Payment Options in Opportunity</inlineHelpText>
        <label>Billing Frequency</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lump Sum</fullName>
                    <label>Anniversary in Advance</label>
                </value>
                <value>
                    <fullName>Anniversary Semi-Annual in Arrears</fullName>
                </value>
                <value>
                    <fullName>Annual in Advance</fullName>
                    <label>Annual in Advance-Jan to Dec</label>
                </value>
                <value>
                    <fullName>Arrears Per % of visits completed</fullName>
                </value>
                <value>
                    <fullName>Long Term</fullName>
                    <label>Long Term in Advance</label>
                </value>
                <value>
                    <fullName>Mid Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Monthly in Advance</fullName>
                </value>
                <value>
                    <fullName>Monthly in Arrears</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Advance</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Advance Equal Installments</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Arrears</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Arrears Equal Installments</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual In Advance</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual in Arrears</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AcctSeed__Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>contains</operation>
                <value>Customer, Customer and Vendor</value>
            </filterItems>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recurring Billings</relationshipLabel>
        <relationshipName>Recurring_Billings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Next_Billing_Date__c</fullName>
        <label>Next Billing Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AcctSeed__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Recurring Billings</relationshipLabel>
        <relationshipName>Recurring_Billings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Recurring Billing</label>
    <nameField>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Testrecurringbillinglistview.cls
@isTest(seealldata=TRUE) 
public class Testrecurringbillinglistview
{
 static testMethod void testMethod1() 
 {
   AcctSeed__Recurring_Billing__c[] Rbillings = new List <AcctSeed__Recurring_Billing__c> ();
     Rbillings.add(
     new AcctSeed__Recurring_Billing__c(
        Name = 'test 1',
        AcctSeed__Customer__c = '0018000000xpgUZ',
        AcctSeed__Status__c= 'Active',
        Service_Contract__c='80034000001FWQk',
       
        AcctSeed__Billing_Frequency__c= 'Monthly in Advance',
        AcctSeed__Next_Billing_Date__c=Date.newinstance(2018, 11, 08)
    )
);

insert Rbillings;
  Test.startTest();
  Test.setCurrentPage(Page.createbilling);
  ApexPages.StandardSetController stdSetController= new ApexPages.StandardSetController(Rbillings);
  stdSetController.setSelected(Rbillings);
  
  recurringbillinglistview_createbilling ext = new recurringbillinglistview_createbilling(stdSetController);
  
  
 
  
  
 Test.stopTest();
 }
 
 static testMethod void testMethod2()
 {
 AcctSeed__Recurring_Billing__c Rbillings = new  AcctSeed__Recurring_Billing__c ();
     Rbillings.Name = 'test 1';
       Rbillings.AcctSeed__Customer__c = '0018000000xpgUZ';
        Rbillings.AcctSeed__Status__c= 'Active';
        Rbillings.Service_Contract__c='80034000001FWQk';
       
        Rbillings.AcctSeed__Billing_Frequency__c= 'Monthly in Advance';
        Rbillings.AcctSeed__Next_Billing_Date__c=Date.newinstance(2018, 11, 08);

insert Rbillings;
system.debug('RB' +Rbillings);


Test.StartTest(); 
  ApexPages.StandardController sc = new ApexPages.standardController(Rbillings);
  recurringbillinglistview_createbilling testAccPlan = new recurringbillinglistview_createbilling(sc);

  PageReference pageRef = Page.createbilling;
   // Add your VF page Name here
  //pageRef.getParameters().put('id','a3234000004654G');
  Test.setCurrentPage(pageRef);
  testAccPlan.RBId='a3234000004654G';
  testAccPlan.RBSC='80034000002LoiF';
  testAccPlan.RBName='0013400001KBNN4';

   testAccPlan .processSelected();
 Test.StopTest();
 }
 }