objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <description>for Diaspark
only visible to Admins</description>
        <formula>AcctSeed__Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AccountID</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/creatependingworklightning.cls
public with sharing class creatependingworklightning {
    @AuraEnabled
   
    //This is the apex class to convert the creatependingwork button on O&M project Related list to work in ligthing.
    public  static string Projupdate(Id ProId1) 
    {
         String result;
         AcctSeed__Project__c Projvalues=new AcctSeed__Project__c ();
        List<AcctSeed__Project__c>projectrecord=[select Name,AccountID__c from AcctSeed__Project__c where id=:ProId1];
        if(projectrecord.size()>0)
        {
            Projvalues=projectrecord.get(0);
           result=Projvalues.AccountID__c;
            
        }
         system.debug('Account' +result);
        return result;
        
       
}
}