objects/AcctSeed__Project__c.object
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <fields>
        <fullName>Branch__c</fullName>
        <inlineHelpText>Regional office responsible for Project</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>North Carolina</fullName>
                </value>
                <value>
                    <fullName>Oregon</fullName>
                </value>
                <value>
                    <fullName>Rhode Island</fullName>
                </value>
                <value>
                    <fullName>South Carolina</fullName>
                </value>
                <value>
                    <fullName>Texas</fullName>
                </value>
                <value>
                    <fullName>Washington</fullName>
                </value>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Branch__c.object
<CustomObject>
    <description>Branches and their addresses.</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Determines what branch needs to address the case.</description>
        <inlineHelpText>brought over from the related service contract</inlineHelpText>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Berkeley</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>Oakland</fullName>
                </value>
                <value>
                    <fullName>San Diego</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related project that the service contract was created for.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ContractTypeCaseRecordTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A mapping of Contract Type__c to allowable Case record types.</description>
    <fields>
        <fullName>Case_Record_Types__c</fullName>
        <label>Case Record Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ContractTypeCaseRecordTypes</label>
</CustomObject>

objects/Dynamic_Field_Id_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Case_Branch__c</fullName>
        <label>Case.Branch</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_ContractType__c</fullName>
        <label>Case.ContractType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Project__c</fullName>
        <label>Case.Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_ServiceContractCase__c</fullName>
        <label>Case.ServiceContractCase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dynamic Field Id Setting</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Case_ContractCtlExt.cls
public with sharing class Case_ContractCtlExt {
	
	/*
	 *	Case controller for case creation from a contract - creates list of allowable record types
	 *	for selection and pre-populates several fields.
	 *
	 */
	
	public List<SelectOption> recordTypeList {get; set;}
    public String selectedRecordTypeId {get; set;}
	public Boolean fatalError {get; set;}
	public Boolean showRecordTypes {get; set;}
	
	Contract svCon;
	String contractId;
	String caseRecordTypeId;
	String retURL;
	
	public Case_ContractCtlExt(ApexPages.StandardController stdController) {
		
		contractId = ApexPages.currentPage().getParameters().get('contractId');
		caseRecordTypeId = ApexPages.currentPage().getParameters().get('caseRecordTypeId');
		retURL = ApexPages.currentPage().getParameters().get('retURL');
		
		fatalError = false;
		showRecordTypes = false;
		selectedRecordTypeId = null;
		svCon = new Contract();
	}
	
    public PageReference initRecordTypes() {
        PageReference pr = null;
        
        // Verify URL parameters
        if (String.isNotBlank(contractId) && String.isNotBlank(retURL)) {
            
            // Read in our contract record
            svCon = [select Id, ContractNumber, AccountId, ASProject__c, ASProject__r.Name, Branch__c, Contract_Status__c, Type__c from Contract where Id = :contractId];
            
            if (String.isBlank(caseRecordTypeId)) {
                
                if (svCon.Contract_Status__c == 'Active') {
                    
                    // Create map of allowable Case record types
                    Map<String, ContractTypeCaseRecordTypes__c> ctcrtMap = ContractTypeCaseRecordTypes__c.getAll();
                    Map<String, Set<String>> allowedRtMap = new Map<String, Set<String>>();
                    for (String ct :ctcrtMap.keySet()) {
                        allowedRtMap.put(ct, new Set<String>());
                        allowedRtMap.get(ct).addAll(ctcrtMap.get(ct).Case_Record_Types__c.split(';', 0));
                    }
                    
                    // Determine case record type list for user selection
                    Map<Id, Schema.RecordTypeInfo> rtMap = Schema.SObjectType.Case.getRecordTypeInfosById();
                    recordTypeList = new List<SelectOption>();
                    for (Id rt: rtMap.keySet()) {
                        if (rtMap.get(rt).isAvailable() && rtMap.get(rt).getName() != 'Master') {
                            if ( (String.isNotBlank(svCon.Type__c)) && 
                                 (allowedRtMap.containsKey(svCon.Type__c)) && 
                                 (allowedRtMap.get(svCon.Type__c).contains(rtMap.get(rt).getName())) ) {
                                
                                recordTypeList.add(new SelectOption(rt, rtMap.get(rt).getName()));
                                if (rtMap.get(rt).isDefaultRecordTypeMapping()) {
                                    selectedRecordTypeId = rt;
                                }
                            }
                        }
                    }
                    
                    if (!recordTypeList.isEmpty()) {
                        if (selectedRecordTypeId == null) {
                            selectedRecordTypeId = String.valueOf(recordTypeList[0].getValue());
                        }
                        
                        if (recordTypeList.size() > 1) {
                            showRecordTypes = true;
                        } else {
                            
                            // Only one case record type available, take user directly to case new/edit page
                            pr = caseNewEditPage();
                        }
                    } else {
                        fatalError = true;
                        ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Contract Type blank or no Case record types assigned.'));
                    }
                    
                } else {
                    fatalError = true;
                    ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Cases can only be created if Contract Status is Active.'));
                }
                
            } else {
                
                selectedRecordTypeId = caseRecordTypeId;
                pr = caseNewEditPage();
            }
			
		} else {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Bad page parameters.'));
			fatalError = true;
		}
		
		return pr;
	}
	
	// Construct the case new/edit page reference
	private PageReference caseNewEditPage() {
		
		Dynamic_Field_Id_Setting__c fieldIds = Dynamic_Field_Id_Setting__c.getOrgDefaults();
		PageReference pageRef = new PageReference('/500/e');
		
		pageRef.getparameters().put('CF' + fieldIds.Case_ServiceContractCase__c, svCon.ContractNumber);
		pageRef.getparameters().put('CF' + fieldIds.Case_ServiceContractCase__c + '_lkid', contractId);
		
		pageRef.getParameters().put('def_account_id', svCon.AccountId);
		
		pageRef.getparameters().put('CF' + fieldIds.Case_Project__c, svCon.ASProject__r.Name);
		pageRef.getparameters().put('CF' + fieldIds.Case_Project__c + '_lkid', svCon.ASProject__c);
		
		pageRef.getparameters().put(fieldIds.Case_Branch__c, svCon.Branch__c);
		
		pageRef.getparameters().put(fieldIds.Case_ContractType__c, svCon.Type__c);
		
		pageRef.getParameters().put('RecordType', selectedRecordTypeId);
		
		pageRef.getParameters().put('retURL', retURL);
		
		pageRef.setRedirect(true);
		return pageRef;
	}
	
	// Record the case record type selected and take the user to the case new/edit page
    public PageReference saveRecordType() {
		PageReference pr = null;
		
		if (selectedRecordTypeId != null) {
			showRecordTypes = false;
			pr = caseNewEditPage();
		} else {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'You must select a record type.'));
		}
		
		return pr;
    }
}