objects/AcctSeedERP__Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Status__c</fullName>
        <inlineHelpText>Status of PO
Controlled by Procurement and Accounting</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Aaron Approved</fullName>
                </value>
                <value>
                    <fullName>Procurement Approved</fullName>
                </value>
                <value>
                    <fullName>PM Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Vendor</fullName>
                </value>
                <value>
                    <fullName>Vendor Received PO</fullName>
                </value>
                <value>
                    <fullName>Vendor Shipped Material</fullName>
                </value>
                <value>
                    <fullName>Partially Received: Warehouse</fullName>
                </value>
                <value>
                    <fullName>Partially Received: Job Site</fullName>
                </value>
                <value>
                    <fullName>Received In-Full: Warehouse</fullName>
                </value>
                <value>
                    <fullName>Received In-Full: Job Site</fullName>
                </value>
                <value>
                    <fullName>Material Deposit Paid</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Need More Information</fullName>
                </value>
                <value>
                    <fullName>Invoice Processed</fullName>
                </value>
                <value>
                    <fullName>Order on Hold</fullName>
                </value>
                <value>
                    <fullName>Paid out of Branch Account</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Invoice Received</fullName>
                </value>
                <value>
                    <fullName>Pending Retention Billing</fullName>
                </value>
                <value>
                    <fullName>Bill and Hold</fullName>
                </value>
                <value>
                    <fullName>Pending Commissioning</fullName>
                </value>
                <value>
                    <fullName>Pending Next Milestone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PO_Closed_Date__c</fullName>
        <description>Set automatically to today() by workflow rule PO Closed Date whenever the Status field of a Purchase Order is set to &quot;Closed&quot;.</description>
        <inlineHelpText>Set automatically to the date the Status field is set to &quot;Closed&quot;.</inlineHelpText>
        <label>PO Closed Date</label>
        <type>Date</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AcctSeedERP__Purchase_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order__c</fullName>
        <inlineHelpText>Purchase Order the PO Line Is associated with</inlineHelpText>
        <label>Purchase Order</label>
        <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Construction_Req__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Construction Requisition- where the PO Line was generated from
Automatically filled in when the PO Line is created</inlineHelpText>
        <label>Construction Requisition</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Construction Requisition value does not exist or does not match filter criteria.</errorMessage>
            <filterItems>
                <field>$Source.AcctSeedERP__Project__c</field>
                <operation>equals</operation>
                <valueField>AcctSeedERP__Sales_Order_Line__c.AcctSeedERP__Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeedERP__Sales_Order_Line__c</referenceTo>
        <relationshipLabel>Purchase Order Lines</relationshipLabel>
        <relationshipName>Purchase_Order_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roll_Up_All_Account_Payable_Lines__c</fullName>
        <inlineHelpText>Sum of related AP lines (Invoices) that are related to the PO Line</inlineHelpText>
        <label>AP Lines Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AcctSeedERP__Sales_Order_Line__c.object
<CustomObject>
    <fields>
        <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>PO Line created from the req
This is filled in when the req is converted to a PO</inlineHelpText>
        <label>Purchase Order Line</label>
        <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
        <relationshipLabel>Sales Order Line</relationshipLabel>
        <relationshipName>Sales_Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Construction_Req__c</fullName>
        <inlineHelpText>SOL# for Service Requisitions
Will be filled out upon Approval of the Requisition</inlineHelpText>
        <label>Construction Req Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Visit</label>
        <referenceTo>SV__c</referenceTo>
        <relationshipLabel>Construction Requisitions</relationshipLabel>
        <relationshipName>Construction_Requisitions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Reporting for Service Reqs- notes what type of cost the req should be categorized under</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Billable</fullName>
                </value>
                <value>
                    <fullName>Charge Back</fullName>
                </value>
                <value>
                    <fullName>Warranty- Resi</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <description>For Service Construction Requisitions</description>
        <label>Service</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Service_Costs_this_year__c</fullName>
        <inlineHelpText>The total amount of money spent on service cost for the current year.</inlineHelpText>
        <label>Service Costs (this year)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Paid</fullName>
        <active>true</active>
        <description>Paid O&amp;M Service Contracts</description>
        <label>Paid</label>
    </recordTypes>
    <recordTypes>
        <fullName>Warranty</fullName>
        <active>true</active>
        <description>Used to track warranty claims for all projects</description>
        <label>Warranty</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ServiceCostsThisYearRollUpUtility.cls
public class ServiceCostsThisYearRollUpUtility {
	
	/***********************************************
	Calculates the "Service Costs (this year)" field of Service Contracts.
	
	Input:  list of Service Contract Ids
	
	Output: Calculates the "Service Costs (this year)" field on each Service Contract in the following way:
		- Calculate the sum of field "AP Lines Total" on all related Purchase Order Lines that are associated
		with a Purchase Order with "Status" field = "Closed" and "PO Closed Date" field = this year that are
		associated with Construction Requisitions of recordtype = "Service" and "Type" field = "Paid", "Warranty",
		or "Warranty Resi".
	
	************************************************/
	/*
	public static void rollUpServiceCosts(List<Id> conIds) {
		
		List<Id> poIds = new List<Id>();
		List<AcctSeedERP__Purchase_Order_Line__c> poLines = new List<AcctSeedERP__Purchase_Order_Line__c>();
		List<Id> poLineIds = new List<Id>();
		RecordType rtService = new RecordType();
		List<AcctSeedERP__Sales_Order_Line__c> conReq = new List<AcctSeedERP__Sales_Order_Line__c>();
		List<SV__c> serviceVisits = new List<SV__c>();
		List<Contract> con = new List<Contract>();
		Map<Id, Contract> conMap = new Map<Id, Contract>();
		Map<Id, SV__c> svMap = new Map<Id, SV__c>();
		Map<Id, AcctSeedERP__Sales_Order_Line__c> conReqMap = new Map<Id, AcctSeedERP__Sales_Order_Line__c>();
		Map<Id, AcctSeedERP__Sales_Order_Line__c> crPolMap = new Map<Id, AcctSeedERP__Sales_Order_Line__c>();
		List<AcctSeedERP__Purchase_Order__c> poList = new List<AcctSeedERP__Purchase_Order__c>();
		List<AcctSeedERP__Purchase_Order_Line__c> poLineSum = new List<AcctSeedERP__Purchase_Order_Line__c>();
		Map<Id, AcctSeedERP__Purchase_Order__c> poMap = new Map<Id, AcctSeedERP__Purchase_Order__c>();

		if (conIds.size() > 0) {
		
			// Get list of Service Contracts that need to have "Service Costs (this year)" calculated
			con = [SELECT Id, Service_Costs_this_year__c FROM Contract WHERE Id IN: conIds];
			//con = [SELECT Id, Service_Costs_Sum_this_year__c FROM Contract WHERE Id IN: conIds];
	
			// Find all Purchase Order Lines ultimately associated with the Service Contracts and calculate "Service Costs (this year)" for each Service Contract
			if (con.size() > 0) {
				rtService = [SELECT Id, Name FROM RecordType WHERE Name = 'Service' and SobjectType = 'AcctSeedERP__Sales_Order_Line__c'];
				for (Contract c : con) {
					c.Service_Costs_this_year__c = 0;
					//c.Service_Costs_Sum_this_year__c = 0;
					conMap.put(c.Id, c);
				}
				
				system.debug('*****Size of conMap = ' + conMap.size());
		
				// Get all the Service Visits associated with the Service Contracts
				serviceVisits = [SELECT Id, Contract__c FROM SV__c WHERE Contract__c IN: conMap.keySet()];
				
				if (serviceVisits.size() > 0) {
					for (SV__c sv: serviceVisits) {
						svMap.put(sv.Id, sv);
					}
		
					// Get all the Construction Requisition of recordtype "Service" with Type field set appropriately that are associated with the Service Visits
					conReq = [SELECT Id, RecordTypeId, Service_Visit__c, AcctSeedERP__Purchase_Order_Line__c, Type__c FROM AcctSeedERP__Sales_Order_Line__c 
							WHERE RecordTypeId =: rtService.Id AND Service_Visit__c IN: svMap.keySet() AND (Type__c =: 'Paid' OR Type__c =: 'Warranty' OR Type__c =: 'Warranty- Resi')];
					
					if (conReq.size() > 0) {
						for (AcctSeedERP__Sales_Order_Line__c cr : conReq) {
							conReqMap.put(cr.Id, cr);
							poLineIds.add(cr.AcctSeedERP__Purchase_Order_Line__c);
							if (!crPolMap.containsKey(cr.AcctSeedERP__Purchase_Order_Line__c)) {
								crPolMap.put(cr.AcctSeedERP__Purchase_Order_Line__c, cr);
							}
						}
		
						// Get all the Purchase Order Lines associated with the Construction Requisitions
						poLines = [SELECT Id, AcctSeedERP__Purchase_Order__c, Roll_Up_All_Account_Payable_Lines__c, Construction_Req__c FROM AcctSeedERP__Purchase_Order_Line__c 
								WHERE Id IN: poLineIds OR Construction_Req__c IN: conReqMap.keySet()];
						
						if (poLines.size() > 0) {
							for (AcctSeedERP__Purchase_Order_Line__c pol : poLines) {
								poIds.add(pol.AcctSeedERP__Purchase_Order__c);
			
								// Sometimes the Construction Requisition field on a Purchase Order Line is blank, if so fill it in so that we can use it in a map below
								if (pol.Construction_Req__c == NULL) {
									pol.Construction_Req__c = crPolMap.get(pol.Id).Id;
								}
							}
		
							// Get all the Purchase Orders associated with the Purchase Order Lines
							poList = [SELECT Id, AcctSeedERP__Status__c, PO_Closed_Date__c FROM AcctSeedERP__Purchase_Order__c WHERE Id IN: poIds];
							for (AcctSeedERP__Purchase_Order__c po : poList) {
								poMap.put(po.Id, po);
							}
		
							system.debug('***** Number of poList = ' + poList.size() + ', first Id = ' + poList[0].Id);
		
							// Identify all the Purchase Order Lines that are associated with a Purchase Order with Status = "Closed" and PO Closed Date = to this year
							for (AcctSeedERP__Purchase_Order_Line__c pol : poLines) {
								if (poMap.get(pol.AcctSeedERP__Purchase_Order__c).PO_Closed_Date__c != NULL) {
									if (poMap.get(pol.AcctSeedERP__Purchase_Order__c).AcctSeedERP__Status__c == 'Closed' && poMap.get(pol.AcctSeedERP__Purchase_Order__c).PO_Closed_Date__c.year() == system.today().year()) {
										poLineSum.add(pol);
									}
								}
							}
		
							if (poLineSum.size() > 0) {
								system.debug('***** Number of poLineSum = ' + poLineSum.size() + ', first Id = ' + poLineSum[0].Id);
							}
		
							// Iterate through the Purchase Order Lines to calculate the new value of the "Service Costs (this year)" field of the related Service Contract
							for (AcctSeedERP__Purchase_Order_Line__c pol : poLineSum) {
								if (pol.Roll_Up_All_Account_Payable_Lines__c != NULL) {
									conMap.get(svMap.get(conReqMap.get(pol.Construction_Req__c).Service_Visit__c).Contract__c).Service_Costs_this_year__c += pol.Roll_Up_All_Account_Payable_Lines__c;
									//conMap.get(svMap.get(conReqMap.get(pol.Construction_Req__c).Service_Visit__c).Contract__c).Service_Costs_Sum_this_year__c += pol.Roll_Up_All_Account_Payable_Lines__c;
								}
							}
						}
					}
				}
				update conMap.values();
			}
		}
	}
	*/
}