objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Host_Offtaker_Owner_Notes__c</fullName>
        <inlineHelpText>Changes, if any to owners &amp; host customer information.</inlineHelpText>
        <label>Host, Offtaker, Owner Notes</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Host__c</fullName>
        <inlineHelpText>The customer that receives the net metering credits.</inlineHelpText>
        <label>OffTaker/Host</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interconnection_Application__c</fullName>
        <inlineHelpText>The name of the related Interconnection application.</inlineHelpText>
        <label>Interconnection Application</label>
        <referenceTo>Interconnection_Application__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Offtaker__c</fullName>
        <label>Offtaker</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <inlineHelpText>PV system owner.</inlineHelpText>
        <label>Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Size_AC_watts__c</fullName>
        <inlineHelpText>Inverter rating of system.</inlineHelpText>
        <label>System Size AC (watts</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Size_DC_watts__c</fullName>
        <inlineHelpText>Module rating of system.</inlineHelpText>
        <label>System Size DC (watts)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Project_ID_Notes__c</fullName>
        <label>Utility Project ID Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WO_Notes__c</fullName>
        <inlineHelpText>Communication from utility on progress of their construction schedule.</inlineHelpText>
        <label>WO # Notes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WO__c</fullName>
        <inlineHelpText>Utility issued WO# specific to each project.</inlineHelpText>
        <label>WO #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Utility Project ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Interconnection_Application__c.object
<CustomObject>
    <fields>
        <fullName>System_Size_AC_watts__c</fullName>
        <label>System Size AC (watts)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Size_DC_watts__c</fullName>
        <formula>ASProject__r.AcctSeed__Opportunity__r.Original_Contract_System_Size__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>brought over from related opportunity field project system size</inlineHelpText>
        <label>System Size DC (watts)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Interconnection Application</label>
    <nameField>
        <label>Interconnection Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interconnection Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AllApplicationUpdateController.cls
public class AllApplicationUpdateController {
    
    Application__c Application;
    
    public AllApplicationUpdateController(ApexPages.StandardController controller) {
            Application=[Select id,
                            Host__c,
                            Host_Offtaker_Owner_Notes__c,
                            Interconnection_Application__c,
                            Offtaker__c,
                            Owner__c,
                            System_Size_AC_watts__c,
                            System_Size_DC_watts__c,
                            Utility_Project_ID_Notes__c,
                            WO__c,
                            WO_Notes__c
                        From Application__c
                        Where id=:controller.getrecord().id];
        }
    
    public pageReference UpdateAll(){
        List<Application__C> ListOfApplication=[Select id,
                            Host__c,
                            Host_Offtaker_Owner_Notes__c,
                            Interconnection_Application__c,
                            Offtaker__c,
                            Owner__c,
                            System_Size_AC_watts__c,
                            System_Size_DC_watts__c,
                            Utility_Project_ID_Notes__c,
                            WO__c,
                            WO_Notes__c
                        From Application__c
                        Where Interconnection_Application__c=:Application.Interconnection_Application__c
                        and Id!=:Application.ID];
        
        If(ListOfApplication==null || ListOfApplication.size()<=0)
            return ReturnBack();
        
        For(Application__C App:ListOfApplication){
            App.Host__c=Application.Host__c;
            App.Host_Offtaker_Owner_Notes__c=Application.Host_Offtaker_Owner_Notes__c;
            App.Offtaker__c=Application.Offtaker__c;
            App.Owner__c=Application.Owner__c;
            //App.System_Size_AC_watts__c=Application.System_Size_AC_watts__c;
            //App.System_Size_DC_watts__c=Application.System_Size_DC_watts__c;
            App.Utility_Project_ID_Notes__c=Application.Utility_Project_ID_Notes__c;
            //App.WO__c=Application.WO__c;
            App.WO_Notes__c=Application.WO_Notes__c;

        }
                
        Update ListOfApplication;
                
        return ReturnBack();
   }
   
   private Pagereference ReturnBack(){
       PageReference PR=new PageReference('/'+Application.id);
        PR.SetRedirect(true);
        return PR;
   }

}