objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Asset_Status__c</fullName>
        <defaultValue>&quot;Active&quot;</defaultValue>
        <inlineHelpText>Inactive Asset = Asset is on site but not being utilized
Active = Asset is on site and being utilized
Archived = Asset is not on site or being used. Used to indicate a mistake in entry or bad data but kept due to historical relationship that may exist</inlineHelpText>
        <label>Asset Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>RMA</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>Choose what type of asset.
Note: need to edit validation rule &quot;Storage Project Battery Only&quot; any time a new picklist value is added</description>
        <inlineHelpText>Choose what type of asset</inlineHelpText>
        <label>Asset Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Asset_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The service contract associated with the Asset</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the case to a Project
Used in Diaspark Integration</description>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related account for the Service Contract.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AssetFault__c</fullName>
        <description>Select the failure description which best describes what occurred to the asset. Add additional comments to the SV if needed.</description>
        <inlineHelpText>Select the failure description which best describes what occurred to the asset. Add additional comments to the SV if needed.</inlineHelpText>
        <label>Asset Fault</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AssetType__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Blown GFCI Fuse</fullName>
                </value>
                <value>
                    <fullName>DAS Failure (hardware)</fullName>
                </value>
                <value>
                    <fullName>DAS Failure (software)</fullName>
                </value>
                <value>
                    <fullName>External Damage</fullName>
                </value>
                <value>
                    <fullName>Facility Network Issue</fullName>
                </value>
                <value>
                    <fullName>Facility Outage/Issue</fullName>
                </value>
                <value>
                    <fullName>Failed AFCI Controller</fullName>
                </value>
                <value>
                    <fullName>Failed Anemometer</fullName>
                </value>
                <value>
                    <fullName>Failed Breaker</fullName>
                </value>
                <value>
                    <fullName>Failed Communication</fullName>
                </value>
                <value>
                    <fullName>Failed DC Connector</fullName>
                </value>
                <value>
                    <fullName>Failed DC Wire</fullName>
                </value>
                <value>
                    <fullName>Failed Fan</fullName>
                </value>
                <value>
                    <fullName>Failed Fuse</fullName>
                </value>
                <value>
                    <fullName>Failed Inline Fuse</fullName>
                </value>
                <value>
                    <fullName>Failed Inverter (Full Replacement)</fullName>
                </value>
                <value>
                    <fullName>Failed Main Breaker</fullName>
                </value>
                <value>
                    <fullName>Failed Modem</fullName>
                </value>
                <value>
                    <fullName>Failed Module (Failed Bypass Diode)</fullName>
                </value>
                <value>
                    <fullName>Failed Module (internal short)</fullName>
                </value>
                <value>
                    <fullName>Failed Other Internal Component</fullName>
                </value>
                <value>
                    <fullName>Failed Power Supply</fullName>
                </value>
                <value>
                    <fullName>Failed Pyrometer</fullName>
                </value>
                <value>
                    <fullName>Failed Racking</fullName>
                </value>
                <value>
                    <fullName>Failed Switch</fullName>
                </value>
                <value>
                    <fullName>Failed Temp Sensor</fullName>
                </value>
                <value>
                    <fullName>Failed Termination</fullName>
                </value>
                <value>
                    <fullName>Failed Wind vane</fullName>
                </value>
                <value>
                    <fullName>Failure Capacitor</fullName>
                </value>
                <value>
                    <fullName>Failure Contactor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AssetType__c</fullName>
        <description>picklist of values updated once asset selection is made/saved, no need to be on layout, field dependency with Asset Fault.</description>
        <inlineHelpText>picklist of values updated once asset selection is made/saved, no need to be on layout, field dependency with Asset Fault.</inlineHelpText>
        <label>Asset Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Asset_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Asset_Offline__c</fullName>
        <description>exact date/time asset when offline</description>
        <inlineHelpText>exact date/time asset when offline</inlineHelpText>
        <label>Asset Offline</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Asset_Online__c</fullName>
        <description>exact date/time asset when back online</description>
        <inlineHelpText>exact date/time asset when back online</inlineHelpText>
        <label>Asset Online</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Service Visits (Asset)</relationshipLabel>
        <relationshipName>Service_Visits2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Resolved__c</fullName>
        <description>Is the issue entirely resolved, no other visits are needed and case can be closed? - Being used to flag the O&amp;M Manager (Owner of Case) that issue that caused case to be open is fully resolved, updated via a Roll Up or Trigger.</description>
        <inlineHelpText>Is the issue entirely resolved, no other visits are needed and case can be closed?</inlineHelpText>
        <label>Asset Issue Resolved?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The case on which the service visit was scheduled.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>shows type of asset from related Asset record</description>
        <formula>TEXT(Asset__r.Component_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>shows type of asset from related Asset record</inlineHelpText>
        <label>Asset Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>used to bring over value from related Contract from field Type. should auto pop upon creation of the Visit via Code in the New SV button.</description>
        <inlineHelpText>used to bring over value from related Contract from field Type.</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Borrego Warranty</fullName>
                </value>
                <value>
                    <fullName>O&amp;M and Warranty</fullName>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>T&amp;M and Warranty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Was_Asset_Offline__c</fullName>
        <description>Clarifies how much time Asset spend off line: Yes indicates 1 day or less; No indicates it was not offline at all; Multiple indicates it will be offline for multiple days</description>
        <inlineHelpText>Clarifies how much time Asset spend off line: Yes indicates 1 day or less; No indicates it was not offline at all; Multiple indicates it will be offline for multiple days</inlineHelpText>
        <label>Was Asset Offline?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Multiple</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Asset_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AC Panel Cabinet</fullName>
    </customValue>
    <customValue>
        <fullName>Battery Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Battery Enclosure</fullName>
    </customValue>
    <customValue>
        <fullName>BOP</fullName>
    </customValue>
    <customValue>
        <fullName>Central Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Combiner</fullName>
        <label>Combiner Box</label>
    </customValue>
    <customValue>
        <fullName>Communication Cabinet</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Module</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Racking</fullName>
    </customValue>
    <customValue>
        <fullName>Roof</fullName>
    </customValue>
    <customValue>
        <fullName>Solar Array</fullName>
    </customValue>
    <customValue>
        <fullName>String Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Switch Gear</fullName>
    </customValue>
    <customValue>
        <fullName>Tracker</fullName>
    </customValue>
    <customValue>
        <fullName>Transformer</fullName>
    </customValue>
    <customValue>
        <fullName>Weather Station</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Inverter</fullName>
        <isActive>false</isActive>
        <label>Inverter</label>
    </customValue>
    <masterLabel>Asset Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/ServiceVisit_AssetCtlExt.cls
public with sharing class ServiceVisit_AssetCtlExt {
    
    /*
     *  Service Visit controller extension - allows user to select an asset for the service visit
     *  from a filtered list of assets related to the project referenced on the service visit record.
     *
     */
    
    ApexPages.StandardController stdController;
    
    public SV__c serviceVisit {get; set;}
    public Boolean isAdmin {get; set;}
    
    String assetName;
    String selectedAsset;
    
    public ServiceVisit_AssetCtlExt(ApexPages.StandardController stdController) {
        
        this.serviceVisit = (SV__c)stdController.getRecord();
        this.serviceVisit = readServiceVisit(this.serviceVisit.Id);
        
        if (this.serviceVisit.Id == null) {
            this.serviceVisit.RecordTypeId = ApexPages.currentPage().getParameters().get('RecordType');
            this.serviceVisit.Account__c = ApexPages.currentPage().getParameters().get('accountId');
            this.serviceVisit.Case__c = ApexPages.currentPage().getParameters().get('caseId');
            this.serviceVisit.Contract__c = ApexPages.currentPage().getParameters().get('contractId');
            this.serviceVisit.Project__c = ApexPages.currentPage().getParameters().get('projectId');
            this.serviceVisit.Contract_Type__c = ApexPages.currentPage().getParameters().get('contractType');
            this.serviceVisit.Asset__c = ApexPages.currentPage().getParameters().get('assetId');
            
            if (this.serviceVisit.Asset__c != null) {
                Asset tempAsset = [select Id, Name, Component_Type__c from Asset where Id = :this.serviceVisit.Asset__c];
                assetName = tempAsset.Name;
                this.serviceVisit.AssetType__c = tempAsset.Component_Type__c;
            }
        } else {
            assetName = (serviceVisit.Asset__c != null) ? serviceVisit.Asset__r.Name : '';
        }
        
        Profile prf = [select Id, Name from Profile where Id = :UserInfo.getProfileId()];
        isAdmin = (prf.Name == 'Sys Admin w/o HR') ? true : false;
    }
    
    // Read in all the fields of the Service Visit object
    private static SV__c readServiceVisit(Id svId) {
        String selects;
        SV__c sv = new SV__c();
        
        if (svId != null) {
            Map<String, Schema.SObjectField> fMap = Schema.getGlobalDescribe().get('SV__c').getDescribe().Fields.getMap();
            List<string> selectFields = new List<string>();
            
            if (fMap != null) {
                for (Schema.SObjectField ft : fMap.values()) {
                    Schema.DescribeFieldResult fd = ft.getDescribe();
                    selectFields.add(fd.getName());
                }
            }
            selects = '';
            if (!selectFields.isEmpty()) {
                for (string s:selectFields) {
                    selects += s + ',';
                }
                selects += 'Asset__r.Name';
            }
            
            sv = (SV__c)Database.query('SELECT ' + selects + ' FROM SV__c WHERE Id = \'' + svId + '\'');
        }
        
        return sv;
    }
    
    public List<SelectOption> getassets() {
        List<SelectOption> assetOptions = new List<SelectOption>();
        List<Asset> assetList = new List<Asset>();
        
        selectedAsset = null;
        assetOptions.add(new SelectOption('--None--','--None--'));
        if (serviceVisit.Project__c != null) {
            Map<String, Schema.RecordTypeInfo> rtAssetMap = Schema.SObjectType.Asset.getRecordTypeInfosByName();
            assetList = [select Id, Name, Project__c from Asset where Project__c = :serviceVisit.Project__c and RecordTypeId =: rtAssetMap.get('Operations Asset').getRecordTypeId() and Asset_Status__c !='InActive' order by Name];  //'and Asset_Status__c ='Active'
            system.debug('look here' + assetList);
            for (Asset a :assetList) {
                assetOptions.add(new SelectOption(a.Id, a.Name));
                if (serviceVisit.Asset__c == a.Id) {
                    selectedAsset = a.Id;
                }
            }
            
            if (selectedAsset == null) {
            system.debug('This is the second Loop');
                if (serviceVisit.Asset__c != null) {
                    assetOptions.add(new SelectOption(serviceVisit.Asset__c, assetName));
                    selectedAsset = serviceVisit.Asset__c;
                } else {
                system.debug('This is the third Loop');
                    selectedAsset = assetOptions[0].getValue();
                }
            }
        }
        
        return assetOptions;
    }
    
    public String getselectedAsset() {
        return selectedAsset;
    }
    
    public void setselectedAsset(String aId) {
        selectedAsset = aId;
    }
    
    public PageReference assetChanged() {
        
        if (selectedAsset == '--None--') {
            serviceVisit.Asset__c = null;
            serviceVisit.AssetType__c = '';
            serviceVisit.AssetFault__c = '';
            serviceVisit.Asset_Offline__c = null;
            serviceVisit.Asset_Online__c = null;
            serviceVisit.Was_Asset_Offline__c = '';
            serviceVisit.Case_Resolved__c = '';
        } else {
            try {
                serviceVisit.Asset__c = selectedAsset;
                Asset newAsset = [select Id, Component_Type__c from Asset where Id = :selectedAsset];
                servicevisit.AssetType__c = newAsset.Component_Type__c;
                serviceVisit.AssetFault__c = '';
                serviceVisit.Asset_Offline__c = null;
                serviceVisit.Asset_Online__c = null;
                serviceVisit.Was_Asset_Offline__c = '';
                serviceVisit.Case_Resolved__c = '';
            } catch(Exception e) {
                ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Asset read exception: ' + e.getMessage()));
            }
        }
        return null;
    }
    
    public PageReference assetOfflineChanged() {
        
        if (serviceVisit.Asset_Offline__c == null) {
            serviceVisit.Was_Asset_Offline__c = '';
        } else {
            if (String.isBlank(serviceVisit.Was_Asset_Offline__c) || serviceVisit.Was_Asset_Offline__c == 'No') {
                serviceVisit.Was_Asset_Offline__c = 'Yes';
            }
        }
        return null;
    }
    
    // Save the changes made to the Asset field and dependent fields
    public PageReference saveAsset() {
        PageReference pr = null;
        
        try {
            upsert serviceVisit;
            pr = new PageReference('/' + serviceVisit.Id);
        } catch(Exception e) {
            String errMsg = 'Service Visit save exception: ' + e.getMessage();
            if (errMsg.contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                errMsg = errMsg.substringBetween('FIELD_CUSTOM_VALIDATION_EXCEPTION, ', ': [');
            }
            if (String.isBlank(errMsg)) {
                errMsg = 'Service Visit save exception: ' + e.getMessage();
            }
            ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, errMsg));
        }
        
        return pr;
    }
}