objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>Choose what type of asset.
Note: need to edit validation rule &quot;Storage Project Battery Only&quot; any time a new picklist value is added</description>
        <inlineHelpText>Choose what type of asset</inlineHelpText>
        <label>Asset Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Asset_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The service contract associated with the Asset</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the case to a Project
Used in Diaspark Integration</description>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Borrego Warranty</fullName>
                </value>
                <value>
                    <fullName>O&amp;M and Warranty</fullName>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>T&amp;M and Warranty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Date__c</fullName>
        <description>Date that the service occured.</description>
        <label>Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <description>Name of person who went to service the system.</description>
        <inlineHelpText>Personnel who worked on the problem on site. If no one goes to site</inlineHelpText>
        <label>Technician</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Service Case</businessProcess>
        <description>used to log all reactive service cases and is default case type for email to case settings</description>
        <label>Reactive</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PM_Notes__c</fullName>
        <label>PM Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MaintenanceCaseServiceVisits__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Information about the Service Visit records that are automatically created when a Maintenance Case is created.</description>
    <fields>
        <fullName>Default_Technician_Id__c</fullName>
        <inlineHelpText>Id of the Contact record to be used for the Technician__c field on the new Service Visit record.</inlineHelpText>
        <label>Default Technician Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Visit_Record_Type__c</fullName>
        <label>Service Visit Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MaintenanceCaseServiceVisits</label>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related account for the Service Contract.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Service Visits (Asset)</relationshipLabel>
        <relationshipName>Service_Visits2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The case on which the service visit was scheduled.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Component_Type__c</fullName>
        <description>shows type of asset from related Asset record</description>
        <formula>TEXT(Asset__r.Component_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>shows type of asset from related Asset record</inlineHelpText>
        <label>Asset Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <description>used to bring over value from related Contract from field Type. should auto pop upon creation of the Visit via Code in the New SV button.</description>
        <inlineHelpText>used to bring over value from related Contract from field Type.</inlineHelpText>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Borrego Warranty</fullName>
                </value>
                <value>
                    <fullName>O&amp;M and Warranty</fullName>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>T&amp;M and Warranty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>Used for any notes regarding the service visit that you want to appear on the work order form</inlineHelpText>
        <label>Service Visit Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to specific Borrego Solar (O&amp;M) account, where all technicians should be listed as contacts</description>
        <inlineHelpText>individual who did the work, if unable to find, add the contact to the Borrego Solar (O&amp;M) account.</inlineHelpText>
        <label>Technician</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <value>00180000010MDi3</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Visits (Technician)</relationshipLabel>
        <relationshipName>Service_Visits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <inlineHelpText>The date on which the service visit is scheduled to occur/start.</inlineHelpText>
        <label>Visit Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Asset_Type.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AC Panel Cabinet</fullName>
    </customValue>
    <customValue>
        <fullName>Battery Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Battery Enclosure</fullName>
    </customValue>
    <customValue>
        <fullName>BOP</fullName>
    </customValue>
    <customValue>
        <fullName>Central Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Combiner</fullName>
        <label>Combiner Box</label>
    </customValue>
    <customValue>
        <fullName>Communication Cabinet</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Module</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Racking</fullName>
    </customValue>
    <customValue>
        <fullName>Roof</fullName>
    </customValue>
    <customValue>
        <fullName>Solar Array</fullName>
    </customValue>
    <customValue>
        <fullName>String Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Switch Gear</fullName>
    </customValue>
    <customValue>
        <fullName>Tracker</fullName>
    </customValue>
    <customValue>
        <fullName>Transformer</fullName>
    </customValue>
    <customValue>
        <fullName>Weather Station</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Inverter</fullName>
        <isActive>false</isActive>
        <label>Inverter</label>
    </customValue>
    <masterLabel>Asset Type</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/CreateMaintCaseServiceVisits.cls
public class CreateMaintCaseServiceVisits implements Queueable {
    
    private Id caseId;
    private Id contractId;
    
    public CreateMaintCaseServiceVisits(Id csId, Id cnId) {
        this.caseId = csId;
        this.contractId = cnId;
    }
    
    public void execute(QueueableContext context) {
        
        // Determine how many Service Visits need to be created
        Map<String, MaintenanceCaseServiceVisits__c> maintCaseSVs = MaintenanceCaseServiceVisits__c.getAll();
        Map<String, Schema.RecordTypeInfo> rtAssetMap = Schema.SObjectType.Asset.getRecordTypeInfosByName();
        Map<Id, Asset> assetMap = new Map<Id, Asset>([select Id, Name, Component_Type__c, Contract__c from Asset where Contract__c = :contractId and RecordTypeId = :rtAssetMap.get('Operations Asset').getRecordTypeId() and Component_Type__c in :maintCaseSVs.keySet()]);
        Contract svContract = [select Id, Type__c, PM_Notes__c from Contract where Id = :contractId];
        List<SV__c> svList = new List<SV__c>();
        svList = [select Id, Name, Asset__c, Case__c, Contract__c from SV__c where Case__c = :caseId and Contract__c = :contractId and Asset__c in :assetMap.keySet()];
        Map<Id, SV__c> assetSVMap = new Map<Id, SV__c>();
        for (SV__c sv :svList) {
            assetSVMap.put(sv.Asset__c, sv);
        }
        
        system.debug('***** CreateMaintCaseServiceVisits assetSVMap.size = ' + assetSVMap.size() + ' assetMap.size = ' + assetMap.size());
        
        // Create a set of Service Visit records - the number in each set is small to avoid system limits
        if (assetSVMap.size() < assetMap.size()) {
            Map<String, Schema.RecordTypeInfo> rtSVMap = Schema.SObjectType.SV__c.getRecordTypeInfosByName();
            List<SV__c> svNewList = new List<SV__c>();
            Case svCase = [select Id, AccountId, Project__c, Service_Date__c from Case where Id = :caseId];
            String Notes;
            Integer numSV = 0;
            for (Asset a :assetMap.values()) {
                if (!assetSVMap.containsKey(a.Id)) {
                    Notes = (maintCaseSVs.get(a.Component_Type__c).Service_Visit_Record_Type__c == 'PM-Site Grounds') ? Notes = svContract.PM_Notes__c : '';
                    
                    svNewList.add(new SV__c(
                        Account__c = svCase.AccountId,
                        Asset__c = a.Id,
                        Case__c = svCase.Id,
                        Contract__c = svContract.Id,
                        Notes__c = Notes,
                        Contract_Type__c = svContract.Type__c,
                        Project__c = svCase.Project__c,
                        RecordTypeId = rtSVMap.get(maintCaseSVs.get(a.Component_Type__c).Service_Visit_Record_Type__c).getRecordTypeId(),
                        Technician__c = maintCaseSVs.get(a.Component_Type__c).Default_Technician_Id__c,
                        Visit_Date__c = svCase.Service_Date__c)
                    );
                    
                    numSV++;
                    if (numSV >= 50) {
                        break;
                    }
                }
            }
            
            // Write out the new Service Visit records and queue the job to create the next set of Service Visit records
            Id jobId = null;
            if (!svNewList.isEmpty()) {
                insert svNewList;
                if (!Test.isRunningTest()) {
                    CreateMaintCaseServiceVisits createSVJob = new CreateMaintCaseServiceVisits(caseId, contractId);
                    jobId = System.enqueueJob(createSVJob);
                }
            }
            
            system.debug('***** CreateMaintCaseServiceVisits svNewList.size = ' + svNewList.size() + ' next jobId = ' + jobId);
        }
    }
}