objects/Case.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Service Case</businessProcess>
        <description>used to log all reactive service cases and is default case type for email to case settings</description>
        <label>Reactive</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pending_Work__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Value does not exist or does not match filter criteria. The Project on the Asset must match the Project on the Pending Work.</errorMessage>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Asset.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Associated_Case_to_Close__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Case in which the pending work item was addressed</inlineHelpText>
        <label>Associated Case to Close</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Pending Work (Associated Case to Close)</relationshipLabel>
        <relationshipName>Pending_Work1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Associated_Service_Visit_to_Close__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Service Visit in which the Pending work item was addressed</inlineHelpText>
        <label>Associated Service Visit to Close</label>
        <referenceTo>SV__c</referenceTo>
        <relationshipLabel>Pending Work (Associated Service Visit to Close)</relationshipLabel>
        <relationshipName>Pending_Work1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Contract must be associated with the same Project as the Pending Work</errorMessage>
            <filterItems>
                <field>Contract.ASProject__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description_of_Pending_Work__c</fullName>
        <label>Description of Pending Work</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Pending Work</relationshipLabel>
        <relationshipName>Pending_Work</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Display the Status of the Pending Work</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pending Work</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Pending Work Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pending Work</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related account for the Service Contract.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Service Visits (Asset)</relationshipLabel>
        <relationshipName>Service_Visits2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The case on which the service visit was scheduled.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CasePendingWork.cls
public class CasePendingWork {

  public  Id ProjectID;  
  private final Case rcdCase;
  Public List<PendingWorkWrapper> lstPendingWork {get; set;} 
    public String redirectUrl {public get; private set;}
    public Boolean shouldRedirect {public get; private set;}
    private ApexPages.StandardController stdController;
    
    
     public CasePendingWork(ApexPages.StandardController stdController) {
         this.stdController = stdController;
         shouldRedirect = false;
         this.rcdCase = [select id, Project__c, AccountId from case where id = : stdController.getId() limit 1 ];//(Case)stdController.getRecord();  
         lstPendingWork= new List<PendingWorkWrapper>();
         
         for(Pending_Work__c pw: [Select Id, Name, Asset__c, Project__c, Case__c, Contract__c,
                                  		Description_of_Pending_Work__c
                                                   From Pending_Work__c 
                                  					where 
                                  					Project__c =: rcdCase.Project__c
                                                    and
                                                    status__c = 'Open'
                                  					order by Name Asc
                                 					])
           {
               lstPendingWork.add(new PendingWorkWrapper(pw));               
           }         
    }
    
    
    public void  CreateReactiveService()
    {
        Savepoint sp = Database.setSavepoint();
        try{
        	List<SV__c> lstService = new List<SV__c>();
            map<id,SV__c> svByPwId = new map<id,SV__c>();
            
            for(PendingWorkWrapper pw: lstPendingWork){
                 if( pw.selected ){
                     SV__c rcdSV = new SV__c();                 
                     rcdSV.Asset__c = pw.pwrk.Asset__c ;
                     rcdSV.Project__c = pw.pwrk.Project__c ;
                     rcdSV.Case__c = rcdCase.id ; //pw.pwrk.Case__c ;  -- 15-08-2018 Updated as per email from Kumar           
                     rcdSV.Contract__c = pw.pwrk.Contract__c; 
                     rcdSV.Account__c = rcdCase.AccountId ; // -- 17-08-2018 Updated as per email from Kumar        
                     svByPwId.put( pw.pwrk.id , rcdSV );
                     lstService.add(rcdSV);
                 }       
              }
            if(lstService.size()>0)
            {
                insert lstService;  
                list<Pending_Work__c> lstPWtoUpdate = new list<Pending_Work__c>();
                for(id key: svByPwId.keyset()){
                    Pending_Work__c rcdPW = new Pending_Work__c(id = key);	
                    rcdPW.Associated_Case_to_Close__c = rcdCase.id ;
                    if( svByPwId.keyset().contains(key) ){
                    	rcdPW.Associated_Service_Visit_to_Close__c = svByPwId.get(key).id ;    
                    }
                    rcdPW.Status__c = 'Assigned';
                    lstPWtoUpdate.add(rcdPW);
                }
                if( lstPWtoUpdate.size() > 0 ){
                    update lstPWtoUpdate ;	    
                }
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM, 'Service Visit Created Successfully.' ));
                shouldRedirect = true;
                redirectUrl = stdController.view().getUrl();
            }
            else{
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info, label.Case_Pending_Work_Not_Selected ));
            }    
        }
        catch(exception ex){
        	Database.rollback(sp);   
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, ex.getMessage() ));
        }
    }
    
    public class PendingWorkWrapper
    {
        public Pending_Work__c pwrk{get; set;}
        public Boolean selected {get; set;}
      
        public PendingWorkWrapper(Pending_Work__c pwrk)
        {
            this.pwrk = pwrk;
            this.selected = false;
        } 
    } 
}