objects/Case.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ServiceContract_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related service contract # for account which this case was opened.</inlineHelpText>
        <label>Service Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related account for the Service Contract.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The case on which the service visit was scheduled.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related Service Contract.</inlineHelpText>
        <label>Contract</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Approximate Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>Used for any notes regarding the service visit that you want to appear on the work order form</inlineHelpText>
        <label>Service Visit Instructions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>User.Username</field>
                <operation>equals</operation>
                <value>dmarks@borregosolar.com</value>
            </filterItems>
            <filterItems>
                <field>User.Username</field>
                <operation>equals</operation>
                <value>gbuchanan@borregosolar.com</value>
            </filterItems>
            <filterItems>
                <field>User.Username</field>
                <operation>equals</operation>
                <value>mmurphy@borregosolar.com</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <inlineHelpText>The date on which the service visit is scheduled to occur/start.</inlineHelpText>
        <label>Visit Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Visit_Reason__c</fullName>
        <inlineHelpText>The reason or service that is being provided.</inlineHelpText>
        <label>Visit Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Module Wash</fullName>
                </value>
                <value>
                    <fullName>Landscape Maintenance</fullName>
                </value>
                <value>
                    <fullName>Scheduled Service Other</fullName>
                </value>
                <value>
                    <fullName>Reactive Service</fullName>
                </value>
                <value>
                    <fullName>Construction Closeout</fullName>
                </value>
                <value>
                    <fullName>Snow Removal</fullName>
                </value>
                <value>
                    <fullName>Preoperational commissioning</fullName>
                </value>
                <value>
                    <fullName>Operational commissioning</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Primary preventive maintenance</fullName>
                </value>
                <value>
                    <fullName>Secondary preventive maintenance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleServiceVisitsController.cls
public with sharing class ScheduleServiceVisitsController {
    
    private ID ContractId;
    
    public SV__c ServiceVisitObject {get; set;}
    
    public integer VisitDuration {get; set;}
    
    public string FrequencyType {get; set;}
    
    public integer Frequency {get; set;}
    
    public ScheduleServiceVisitsController(ApexPages.StandardSetController controller) {

        ContractId = apexpages.currentpage().getparameters().get('id');
        
        Contract CurrentContract=[Select id, Accountid from Contract where id=:Contractid];
        list<case> ListOfCase=[Select id from Case where ServiceContract_Case__c=:Contractid];
        
        ServiceVisitObject =new SV__c();
        ServiceVisitObject .Contract__c=ContractId ;
        //ServiceVisitObject.Owner__c=UserInfo.GetUserid();
        if(ListOfCase!=null && ListOfCase.size()>0) ServiceVisitObject.Case__c=ListOfCase[0].id;
        ServiceVisitObject .Account__c=CurrentContract.Accountid;
    }
    
    public List<SelectOption> getFrequencyTypeItems() {
            List<SelectOption> options = new List<SelectOption>();
            options.add(new SelectOption('Month','Month'));
            options.add(new SelectOption('Year','Year'));
            options.add(new SelectOption('Week','Week'));
            options.add(new SelectOption('Day','Day'));
            return options;
    }
    
   public pageReference returnBackToContract(){
        pageReference pgRef=new pageReference('/'+ ContractId);
        pgRef.SetRedirect(true);
        return pgRef;   
   }
    
    
    
    Public pageReference ScheduleServiceVisits(){
        try{
    
            list<SV__C> ListOfServiceVisits=new list<sv__C>();
            
            date StartDate=ServiceVisitObject.Visit_Date__c;
            
            date EndDate;//=StartDate.AddMonths(VisitDuration);
            
             if(FrequencyType=='Month')
                    EndDate=StartDate.addMonths(VisitDuration*Frequency);
                else if(FrequencyType=='Year')
                    EndDate=StartDate.addYears(VisitDuration*Frequency);
                else if(FrequencyType=='Week')
                    EndDate=StartDate.addDays(7*VisitDuration*Frequency);
                else if(FrequencyType=='Day')
                    EndDate=StartDate.addDays(VisitDuration*Frequency);
               
            
            while(StartDate<EndDate){
            
                sv__C ServiceVisit=new SV__c();
                
                ServiceVisit.Visit_Date__c=startDate;
                ServiceVisit.Owner__C=ServiceVisitObject.Owner__C;
                ServiceVisit.Cost__c=0;
                ServiceVisit.Visit_Reason__c=ServiceVisitObject.Visit_Reason__c;
                ServiceVisit.Account__c=ServiceVisitObject.Account__c;
                ServiceVisit.Case__c=ServiceVisitObject.Case__c;
                ServiceVisit.Contract__c=ContractId ;
                ServiceVisit.status__c='Scheduled';
                ServiceVisit.Notes__C=ServiceVisitObject.Notes__C;
            
                ListOfServiceVisits.add(ServiceVisit);
            
                if(FrequencyType=='Month')
                    StartDate=StartDate.addMonths(Frequency);
                else if(FrequencyType=='Year')
                    StartDate=StartDate.addYears(Frequency );
                else if(FrequencyType=='Week')
                    StartDate=StartDate.addDays(7*Frequency);
                else if(FrequencyType=='Day')
                    StartDate=StartDate.addDays(Frequency );
            }                            
            
            
            Insert ListOfServiceVisits;
            
            return returnBackToContract();
         }
         catch(exception e){
             ApexPages.addMessages(e);
         }
         return null;
    }
    
    Public pageReference Cancel(){
        return returnBackToContract();
    }

}