objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>The manual field the manager enters to reflect the case start date</inlineHelpText>
        <label>Case Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Con_Req_Group__c.object
<CustomObject>
    <fields>
        <fullName>External_Recipients_and_Order__c</fullName>
        <inlineHelpText>Enter the recipient&apos;s name(s) and email and order of signature.</inlineHelpText>
        <label>External Recipients and Order</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Pages_Where_Signature_is_Required__c</fullName>
        <inlineHelpText>Specify which pages a signature or initials are required.</inlineHelpText>
        <label>Pages Where Signature is Required</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Con Req Groups</relationshipLabel>
        <relationshipName>Con_Req_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_Delivery_Date__c</fullName>
        <label>Requested Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
        <relationshipLabel>Con Req Groups</relationshipLabel>
        <relationshipName>Con_Req_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_To_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Site__c.Project__c</valueField>
            </filterItems>
            <infoMessage>Site must be related to Project of Con Req Group.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Con Req Groups</relationshipLabel>
        <relationshipName>Con_Req_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use Customer, Subcontractor, or Branch Account to indicate where you would like this order shipped to.</inlineHelpText>
        <label>Ship to Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Con Req Groups</relationshipLabel>
        <relationshipName>Con_Req_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Vendor__c</field>
                <operation>equals</operation>
                <valueField>Contact.Account.Id</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Con Req Groups</relationshipLabel>
        <relationshipName>Con_Req_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.AcctSeed__Accounting_Type__c</field>
                <operation>equals</operation>
                <value>Vendor, Vendor, Customer and Vendor</value>
            </filterItems>
            <infoMessage>Accounting Type field must be &quot;Vendor&quot;.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Con Req Groups (Vendor)</relationshipLabel>
        <relationshipName>Con_Req_Groups1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Con Req Group</label>
    <nameField>
        <displayFormat>CRG-{000000}</displayFormat>
        <label>Con Req Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Con Req Groups</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Purchase_Requisition__c.object
<CustomObject>
    <description>Purchase Requisitions empower end users to request new items, and tracks the status of their requests.</description>
    <fields>
        <fullName>BriefDescriptionofDocument__c</fullName>
        <inlineHelpText>Brief description of the document to be signed (ie: Contract for XX Project or Agreement for XX)</inlineHelpText>
        <label>Brief Description of Document</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Needed__c</fullName>
        <inlineHelpText>Date the request is needed by</inlineHelpText>
        <label>Date Needed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Recipients_and_Order__c</fullName>
        <inlineHelpText>Enter the recipient&apos;s name(s) and email and order of signature</inlineHelpText>
        <label>External Recipients and Order</label>
        <length>7000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InternalRecipientsandOrder__c</fullName>
        <inlineHelpText>Enter the Borrego signatories’ names in order of signature</inlineHelpText>
        <label>Internal Signatories and Order</label>
        <length>7000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pages_where_signature_is_required__c</fullName>
        <inlineHelpText>Specify which pages a signature or initials are required</inlineHelpText>
        <label>Pages where signature is required</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ProjectAS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the Project associated with the request</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Requisition Forms</relationshipLabel>
        <relationshipName>Requisition_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project-OLD</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Requisition Forms</relationshipLabel>
        <relationshipName>Requisition_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requisition Form</label>
    <nameField>
        <displayFormat>REQ{0000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requisition Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ContentLinkConreqgroup1test.cls
@isTest
Public class ContentLinkConreqgroup1test {

  @isTest static void testMethod1()
  
   {

   Con_Req_Group__c crgList = new Con_Req_Group__c();
     
        crgList.Project__c  = 'a1t34000002v45k';
        crgList.Sales_Order__c = 'a2C340000002yu9';
        crgList.Vendor__c = '0018000000xpgUZ';
        crgList.Vendor_Contact__c ='00334000022UtU4';
        crgList.Ship_to_Account__c = '0018000000xpgUZ';
        crgList.Ship_To_Site__c = 'a6934000000ND94';
        crgList.Requested_Delivery_Date__c = system.today();

 insert crglist;
 
 RecordType ContentRT = [select Id FROM RecordType WHERE name='Standard Work/SOP'];
    
    ContentVersion ContentDoc = new ContentVersion();
       ContentDoc.Title = 'My Doc';
       ContentDoc.Description ='test';
       ContentDoc.RecordTypeId = ContentRT.Id; //'01234000000GGcgAAG';
       ContentDoc.ContentUrl= 'test.com';
        Insert ContentDoc;
      
         List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        //create ContentDocumentLink  record 

        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = crglist.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        delete cdl;
  
  
  }
   @isTest static void testMethod2()
   {
    SFDC_Purchase_Requisition__c reqlist = new SFDC_Purchase_Requisition__c();
       //  reqlist.RecordTypeId = [select Id FROM RecordType WHERE name='DocuSign Request']; 
         reqlist.ProjectAS__c = 'a1t34000002v45k';
         reqlist.Date_Needed__c = system.today();
         reqlist.BriefDescriptionofDocument__c = 'test';
         reqlist.External_Recipients_and_Order__c = 'test';
         reqlist.Pages_where_signature_is_required__c = 'test';
         reqlist.InternalRecipientsandOrder__c = 'test';
         
         insert reqlist;
         
         RecordType ContentRT = [select Id FROM RecordType WHERE name='Standard Work/SOP'];
    
    ContentVersion ContentDoc = new ContentVersion();
       ContentDoc.Title = 'My Doc';
       ContentDoc.Description ='test';
       ContentDoc.RecordTypeId = ContentRT.Id; //'01234000000GGcgAAG';
       ContentDoc.ContentUrl= 'test.com';
        Insert ContentDoc;
      
         List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        //create ContentDocumentLink  record 

        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = reqlist.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        delete cdl;
  
   }
   
   @isTest static void testMethod3()
   {
    
    Case caselist= new Case();
    caselist.AccountId='0018000000xpgUZ';
    caselist.Project__c='a1t340000034Qdj';
    caselist.Status='Active';  
    caselist.Priority='Medium';
    caselist.Origin='Email';
    caselist.Case_Start_Date__c=date.newInstance(2018, 07, 01);
    caselist.Reason='System Down';
    
    insert caselist;
    
     RecordType ContentRT = [select Id FROM RecordType WHERE name='Standard Work/SOP'];
    
       ContentVersion ContentDoc = new ContentVersion();
       ContentDoc.Title = 'My Doc';
       ContentDoc.Description ='test';
       ContentDoc.RecordTypeId = ContentRT.Id; //'01234000000GGcgAAG';
       ContentDoc.ContentUrl= 'test.com';
        Insert ContentDoc;
      
         List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        //create ContentDocumentLink  record 

        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = caselist.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        //delete cdl;
  
}
}