objects/Case.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Project</description>
        <inlineHelpText>Lookup to Project associated with Account</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ServiceContract_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related service contract # for account which this case was opened.</inlineHelpText>
        <label>Service Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/closecaselightning.cls
public class closecaselightning {
   

    @AuraEnabled
     public  static List<Case> getcase(Id caseid) 
    {
     List<Case>  caserecord = new Case[]{};
        
       
       caserecord = [select id,RecordType.Name,RecordTypeId from Case where id= :caseid];
   
         return caserecord;
      }
    
    @AuraEnabled
     public  static List<Case> getquotefields(Id caseid1) 
    {
     List<Case>  casequoterec = new Case[]{};
        
       
       casequoterec = [select Project__c,ServiceContract_Case__c from Case where id= :caseid1];
   
         return casequoterec;
      }


}