objects/Case.object
<CustomObject>
    <fields>
        <fullName>Contract_Type__c</fullName>
        <label>Contract Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Borrego Warranty</fullName>
                </value>
                <value>
                    <fullName>O&amp;M and Warranty</fullName>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>T&amp;M and Warranty</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceContract_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related service contract # for account which this case was opened.</inlineHelpText>
        <label>Service Contract</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Service</fullName>
        <active>true</active>
        <businessProcess>Service Case</businessProcess>
        <description>used to log all reactive service cases and is default case type for email to case settings</description>
        <label>Reactive</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ContractService.cls
public with sharing class ContractService {
	
	/*
	 *	Service methods for ContractTrigger.
	 */
	
	// Copy various fields from a contract to related case records.
	// - after update
	public static void contractToCase(Map<Id, Contract> newMap, Map<Id, Contract> oldMap) {
		Set<Id> cntrctIds = new Set<Id>();
		
		for (Contract cntrct :newMap.values()) {
			if (cntrct.Type__c != oldMap.get(cntrct.Id).Type__c) {
				cntrctIds.add(cntrct.Id);
			}
		}
		
		if (!cntrctIds.isEmpty()) {
			List<Case> caseList = new List<Case>();
			caseList = [select Id, CaseNumber, Contract_Type__c, ServiceContract_Case__c 
				from Case where ServiceContract_Case__c in :cntrctIds and IsClosed = false];
			
			for (Case c :caseList) {
				if (newMap.containsKey(c.ServiceContract_Case__c)) {
					c.Contract_Type__c = newMap.get(c.ServiceContract_Case__c).Type__c;
				}
			}
			
			if (!caseList.isEmpty()) {
				update caseList;
			}
		}
	}
}