objects/Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Checklists</relationshipLabel>
        <relationshipName>Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DCconnectgoodcondnodamage__c</fullName>
        <description>DC connectors in good condition and free of signs of heat or damage.</description>
        <inlineHelpText>DC connectors in good condition and free of signs of heat or damage.</inlineHelpText>
        <label>DC connect good cond no damage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checklist_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DCwiringisproperlyroutedandsecured__c</fullName>
        <description>DC wiring is properly routed and secured. (add a minimum of 25 zip ties and attach pictures)</description>
        <inlineHelpText>DC wiring is properly routed and secured. (add a minimum of 25 zip ties and attach pictures)</inlineHelpText>
        <label>DC wiring is properly routed and secured</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>Corrected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Docmanufacturerserial__c</fullName>
        <inlineHelpText>Document the Module nameplate w/ manufacturer and serial number. (attach 1 picture per Module type)</inlineHelpText>
        <label>Doc manufacturer &amp; serial #</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>File_Image_URL__c</fullName>
        <formula>LEFT( $Api.Enterprise_Server_URL_100, FIND( &quot;.com&quot;, $Api.Enterprise_Server_URL_100 ) + 4)&amp; &quot;sfc/servlet.shepherd/version/renditionDownload?rendition=THUMB720BY480&amp;versionId=&quot; &amp; Id &amp; &quot;&amp;operationContext=CHATTER&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>File Image URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nodamageetctomodules__c</fullName>
        <inlineHelpText>Modules are free of damage to the frame, cracked front glass, cracked backsheet, signs of delamination, signs of water egress or damage termination box. (attach pictures)</inlineHelpText>
        <label>No damage, etc to modules</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checklist_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nopaintcorrodamage__c</fullName>
        <description>Switchgear/ Recloser is free of paint damage, corrosion, or any other physical damage.</description>
        <inlineHelpText>Switchgear/ Recloser is free of paint damage, corrosion, or any other physical damage.</inlineHelpText>
        <label>No paint, corro, damage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checklist_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Thermalinspectnoanomallies__c</fullName>
        <description>Thermal inspection of the modules are free of anomalies. (attach pictures)</description>
        <inlineHelpText>Thermal inspection of the modules are free of anomalies. (attach pictures)</inlineHelpText>
        <label>Thermal inspect no anomallies</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Checklist_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Order_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order Line Item</label>
        <referenceTo>WorkOrderLineItem</referenceTo>
        <relationshipLabel>Checklists</relationshipLabel>
        <relationshipName>Checklists_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Checklist</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Checklist</label>
        <referenceTo>Checklist__c</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Checklist_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Pass</fullName>
    </customValue>
    <customValue>
        <fullName>Fail</fullName>
    </customValue>
    <customValue>
        <fullName>Corrected</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>Checklist Values</masterLabel>
</GlobalValueSet>

classes/WOChecklistController.cls
public class WOChecklistController {
    
    public List<Checklist__c> ChkLstWO {get;set;}

    public workorderlineitem WOChklist {get;set;} 

    public workorderlineitem WO {get;set;} 
    
    public List<ContentDocumentLink> files = new List<ContentDocumentLink>();
    
    public WOChecklistController(ApexPages.StandardController controller) { 
        
        WO = (workorderlineitem)controller.getRecord();
        
        
        WOChklist = [select id , Checklist__c from workorderlineitem where id =:WO.id ];
        
        ChkLstWO = [select id,Name,RecordType.Name,Owner.Name,Thermalinspectnoanomallies__c,Asset__c,Work_Order_Line_Item__c,File_Image_URL__c,Comments__c ,Docmanufacturerserial__c,Nodamageetctomodules__c,Nopaintcorrodamage__c,DCwiringisproperlyroutedandsecured__c,DCconnectgoodcondnodamage__c from Checklist__c where id= :WOChklist.Checklist__c];
        if(ChkLstWO.size()>0)
        {
        Checklist__c checklist=new Checklist__c ();
        checklist=ChkLstWO.get(0);
        system.debug('CheckList Id' +ChkLstWO);
    }
        
        
        

    }
    
 /*   public List<ContentDocumentLink> getFiles() {
    Checklist__c checklist=new Checklist__c ();
        checklist=ChkLstWO.get(0);
    
     files  = [select ContentDocumentID, LinkedEntityId,ContentDocument.title,ContentDocument.OwnerId,ContentDocument.CreatedDate from ContentDocumentLink where LinkedEntityId = :checklist.id];
     if(files.size()>0)
     { 
     return files;
     } 
     else
     {
     return null;
     }
     } */
     
     Public PageReference redirectToNewPage()
     {
     String hostname = ApexPages.currentPage().getHeaders().get('Host');
       //String  instance = URL.getSalesforceBaseUrl().getHost().substringBefore('.');
     // system.debug('look' +instance);
         system.debug('look here' +hostname);
         
    //  String URL2  ='https://'+hostname+'/'+'/00Q/e?nooverride=1';
       Checklist__c checklist=new Checklist__c ();
        checklist=ChkLstWO.get(0);


     //String URL2 = 'https://bssitraining--training.cs90.my.salesforce.com/'+checklist.id+'?isdtp=vw';
        String URL2='https://' +hostname +'/' +checklist.id+'?isdtp=vw';
      pagereference pageref = new pagereference(URL2);
      pageref.setredirect(true);
      return pageref;
     
        }
    
 
    
}