objects/Checklist__c.object
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkOrderLineItem.object
<CustomObject>
    <fields>
        <fullName>Asset_Fault__c</fullName>
        <label>Asset Fault</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Asset_Fault_Picklist__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Blown GFCI Fuse</fullName>
                </value>
                <value>
                    <fullName>DAS Failure (hardware)</fullName>
                </value>
                <value>
                    <fullName>DAS Failure (software)</fullName>
                </value>
                <value>
                    <fullName>External Damage</fullName>
                </value>
                <value>
                    <fullName>Facility Network Issue</fullName>
                </value>
                <value>
                    <fullName>Facility Outage/Issue</fullName>
                </value>
                <value>
                    <fullName>Failed AFCI Controller</fullName>
                </value>
                <value>
                    <fullName>Failed Anemometer</fullName>
                </value>
                <value>
                    <fullName>Failed Breaker</fullName>
                </value>
                <value>
                    <fullName>Failed Communication</fullName>
                </value>
                <value>
                    <fullName>Failed DC Connector</fullName>
                </value>
                <value>
                    <fullName>Failed DC Wire</fullName>
                </value>
                <value>
                    <fullName>Failed Fan</fullName>
                </value>
                <value>
                    <fullName>Failed Fuse</fullName>
                </value>
                <value>
                    <fullName>Failed Inline Fuse</fullName>
                </value>
                <value>
                    <fullName>Failed Inverter (Full Replacement)</fullName>
                </value>
                <value>
                    <fullName>Failed Main Breaker</fullName>
                </value>
                <value>
                    <fullName>Failed Modem</fullName>
                </value>
                <value>
                    <fullName>Failed Module (Failed Bypass Diode)</fullName>
                </value>
                <value>
                    <fullName>Failed Module (internal short)</fullName>
                </value>
                <value>
                    <fullName>Failed Other Internal Component</fullName>
                </value>
                <value>
                    <fullName>Failed Power Supply</fullName>
                </value>
                <value>
                    <fullName>Failed Pyrometer</fullName>
                </value>
                <value>
                    <fullName>Failed Racking</fullName>
                </value>
                <value>
                    <fullName>Failed Switch</fullName>
                </value>
                <value>
                    <fullName>Failed Temp Sensor</fullName>
                </value>
                <value>
                    <fullName>Failed Termination</fullName>
                </value>
                <value>
                    <fullName>Failed Wind vane</fullName>
                </value>
                <value>
                    <fullName>Failure Capacitor</fullName>
                </value>
                <value>
                    <fullName>Failure Contactor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Asset_Type__c</fullName>
        <formula>TEXT(Asset.Component_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checklist_Record_Type_Name__c</fullName>
        <formula>Checklist__r.RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Checklist Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checklist_Record_Type__c</fullName>
        <formula>Checklist__r.RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Checklist Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Checklist</label>
        <referenceTo>Checklist__c</referenceTo>
        <relationshipLabel>Work Order Line Items</relationshipLabel>
        <relationshipName>Work_Order_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/createfollowupbatchclass.cls
global class createfollowupbatchclass implements Database.Batchable<sObject>  {
    global Id currentId ;
    global Id workrecordid;

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
         return Database.getQueryLocator('select id,Checklist__c,WorkOrderId,AssetId from workorderlineitem where WorkOrderId  =:workrecordid and Status!= \'Completed\' ');
       
    }
    global Void execute(Database.BatchableContext BC, List<workorderlineitem> workorderlinelist)
    {
        
         List<workorderlineitem>wolinelist=new List<workorderlineitem>();
        
        List<workorderlineitem> newrec = new List<workorderlineitem>();
        //wolinelist = [select id,Checklist__c,WorkOrderId,AssetId from workorderlineitem where WorkOrderId  =:currentId and status!='Completed'];
        Integer listsize=workorderlinelist.size();
         try 
        {
            
             for(integer i=0;i<listsize;i++)
        {
              workorderlineitem WOlinerec=new workorderlineitem ();
              workorderlineitem newWOline = new workorderlineitem();
            wolinerec.clear();
            WOlinerec=workorderlinelist.get(i);
            system.debug('WO LIST' +WOlinerec);
           newwoline.WorkOrderId = currentId;
            newwoline.Status ='New';
            newwoline.Checklist__c = wolinerec.Checklist__c;
            //newwoline.Checklist_Record_Type__c = wolinerec.Checklist_Record_Type__c;
            // newwoline.Checklist_Record_Type_Name__c = wolinerec.Checklist_Record_Type_Name__c;
            // newwoline.Asset_Type__c = wolinerec.Asset_Type__c;   
            //newwoline.Asset_Fault__c = wolinerec.Asset_Fault__c;
            newwoline.assetId = wolinerec.AssetId;
            newrec.add(newwoline);
           
        }
        system.debug('this is before');
        insert newrec;
         system.debug('WOL Records'  +newrec);
             
        /*List<serviceappointment>sapptlist=new List<serviceappointment>();
        serviceappointment sapprec=new serviceappointment ();
        serviceappointment getsrapp  = new serviceappointment();
        sapptlist=[select parentrecordId,EarliestStartTime,duedate,SchedEndTime,AssignedResource__c,SchedStartTime from serviceappointment where ParentRecordId=:currentId and parentRecordtype='WorkOrder'];
        ID   getid = currentId;
        if (sapptlist.size() >0){
             getsrapp = sapptlist.get(0);
       
       
        sapprec.ParentRecordId = getid;
        sapprec.EarliestStartTime = getsrapp.EarliestStartTime;
        sapprec.DueDate = getsrapp.duedate;
       // sapprec.AssignedResource__c = getsrapp.AssignedResource__c;
        sapprec.SchedStartTime = getsrapp.SchedStartTime;
        sapprec.SchedEndTime = getsrapp.SchedEndTime;
        sapprec.Status = 'None';
        insert sapprec;
        }
         system.debug('SA Records'  +sapprec);*/
             
             
        }  
         catch(Exception e) {
            System.debug('Error occured during execution.'+e);
        }

}
     global void finish(Database.BatchableContext BC) 
    {
        // execute any post-processing operations
    }
}