objects/Con_PO__c.object
<CustomObject>
    <fields>
        <fullName>Change_Order_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of the Amount Requested field of all Construction Requisitions that are of type Subcontractor Change Order associated with this Construction Purchase Order.  This field is calculated by the trigger ChangeOrderTotal.</description>
        <label>Change Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Retention_Held__c</fullName>
        <description>This field is a pull through from the Retention Held field of the Construction Requisition record of type Subcontractor Requisition associated with this Construction Purchase Order.</description>
        <label>Retention Held</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Retention_Percent__c</fullName>
        <description>This field is a pull through from the Retention Percent field of the Construction Requisition record of type Subcontractor PO associated with this Construction Purchase Order.</description>
        <label>Retention Percent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5%</fullName>
                </value>
                <value>
                    <fullName>10%</fullName>
                </value>
                <value>
                    <fullName>15%</fullName>
                </value>
                <value>
                    <fullName>20%</fullName>
                </value>
                <value>
                    <fullName>other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Approved by Aaron</fullName>
                </value>
                <value>
                    <fullName>PM Approved</fullName>
                </value>
                <value>
                    <fullName>Mary Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted to Vendor</fullName>
                </value>
                <value>
                    <fullName>Vendor Received PO</fullName>
                </value>
                <value>
                    <fullName>Material Deposit Paid</fullName>
                </value>
                <value>
                    <fullName>Vendor Shipped Material</fullName>
                </value>
                <value>
                    <fullName>Material Received</fullName>
                </value>
                <value>
                    <fullName>Work Complete</fullName>
                </value>
                <value>
                    <fullName>Notify AP- Invoice Attached</fullName>
                </value>
                <value>
                    <fullName>Invoice Received</fullName>
                </value>
                <value>
                    <fullName>Invoice Approved</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Construction Purchase Order</label>
    <nameField>
        <displayFormat>SF-PO-{000000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Construction Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Con_Req__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Requested_Change__c</fullName>
        <defaultValue>0</defaultValue>
        <description>For Construction Requisition record updates.  Tracks the change in the Amount Requested field.  Set by trigger ConReqToconPO.</description>
        <label>Amount Requested Change</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Requested__c</fullName>
        <inlineHelpText>Amount of CO
Sub and Material CO only</inlineHelpText>
        <label>Amount Requested</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>Con_PO__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Subcontractor PO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Con_PO__c</referenceTo>
        <relationshipName>R00N80000002kftHEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retention_Held__c</fullName>
        <label>Retention Held</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Retention_Percent__c</fullName>
        <label>Retention Percent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5%</fullName>
                </value>
                <value>
                    <fullName>10%</fullName>
                </value>
                <value>
                    <fullName>15%</fullName>
                </value>
                <value>
                    <fullName>20%</fullName>
                </value>
                <value>
                    <fullName>other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status of the CO
Controlled by the approval process and recall button</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Sent for Signature</fullName>
                </value>
                <value>
                    <fullName>Signed by Customer</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Borrego Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>X - Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved By Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Change Order</label>
    <nameField>
        <displayFormat>SF-CR-{000000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Orders</pluralLabel>
    <recordTypes>
        <fullName>Subcontractor</fullName>
        <active>false</active>
        <description>For requesting subcontractors</description>
        <label>Subcontractor Requisition</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/conReqToconPO.cls
public with sharing class conReqToconPO {

    /*
     * toConPO
     * Pull over the Construction Requisition record type Subcontractor fields
     * Retention Held and Retention Percent to the associated Construction
     * Purchase Order record.
     *
     * Add up the Amount Requested field from each Construction Requisition
     * record of type Subcontractor Change Order associated with a Construction
     * Purchase Order record and put it in the Change Order Total field.
     *
     */
   /*  public static void toConPO(Con_Req__c[] cr, Integer act) {
        
        // Get the Construction Purchase Order Ids.
        List<Id> cpoId = new List<Id>();
        for (Integer i=0; i<cr.size(); i++) {
            cpoId.add(cr[i].Purchase_Order__c);
        }
        
        // Get all the Construction Purchase Order records that may need to
        // be updated.
        Map<Id, Con_PO__c> conPO = new Map<Id, Con_PO__c>();
        Con_PO__c[] cpo = [select Change_Order_Total__c, Retention_Held__c, Retention_Percent__c
                from Con_PO__c where Id in :cpoId];
        for (Integer i=0; i<cpo.size(); i++) {
            conPO.put(cpo[i].Id, cpo[i]);
        }
        
        Map<Id, Con_PO__c> upconPO = new Map<Id, Con_PO__c>();
        
        If(conPO!=null)
            for (Integer i=0; i<cr.size(); i++) {
                
                if (cr[i].Record_Type_Name__c == 'Subcontractor Requisition') {
                    // Pull over Retention Held and Retention Percent fields from the
                    // Construction Requisition to the Construction Purchase Order.
                    if (act == 2 || cr[i].Status__c == 'Recalled') {
                        // Reset Construction Purchase Order fields to null because
                        // of recalled approval or because Construction Requisition is
                        // about to be deleted.
                        if(conPO.ContainsKey(cr[i].Purchase_Order__c)){
                            conPO.get(cr[i].Purchase_Order__c).Retention_Held__c = null;
                            conPO.get(cr[i].Purchase_Order__c).Retention_Percent__c = null;
                        }
                    } else {
                        // Trigger is after insert or after update.
                        if(conPO.ContainsKey(cr[i].Purchase_Order__c)){
                            conPO.get(cr[i].Purchase_Order__c).Retention_Held__c = cr[i].Retention_Held__c;
                            conPO.get(cr[i].Purchase_Order__c).Retention_Percent__c = cr[i].Retention_Percent__c;
                         }
                    }
                     if(conPO.ContainsKey(cr[i].Purchase_Order__c)){
                        upconPO.put(conPO.get(cr[i].Purchase_Order__c).Id, conPO.get(cr[i].Purchase_Order__c));
                      }
                } 
            
            // Add in the new or changed Amount Requested to the Change Order Total field of 
            // the Construction Purchase Order field
            if (cr[i].Record_Type_Name__c == 'Subcontractor Change Order') {
                Decimal coTotal = 0;
                if (act == 0) {
                    coTotal = cr[i].Amount_Requested__c;
                }
                if (act == 1) {
                    coTotal = cr[i].Amount_Requested_Change__c;
                }
                if (act == 2) {
                    coTotal = 0 - cr[i].Amount_Requested__c;
                }
                if (coTotal != 0) {
                    if (conPO.get(cr[i].Purchase_Order__c).Change_Order_Total__c == null) {
                        conPO.get(cr[i].Purchase_Order__c).Change_Order_Total__c = 0;
                    }
                    conPO.get(cr[i].Purchase_Order__c).Change_Order_Total__c += coTotal;
                    upconPO.put(conPO.get(cr[i].Purchase_Order__c).Id, conPO.get(cr[i].Purchase_Order__c));
                }
            }
        }
        
        // Update changed Construction Purchase Order records
        if (upconPO.size() > 0) {
            update upconPO.values();
        }*/
     } 
     
    /* @isTest
     static void runTest() {
        ProjectTest.FieldUpdate();  
     } 
} */