objects/Con_PO__c.object
<CustomObject>
    <label>Construction Purchase Order</label>
    <nameField>
        <displayFormat>SF-PO-{000000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Construction Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice_Distribution_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Pre-Tax Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Construction_Purchase_Order1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Construction Purchase Order</label>
        <referenceTo>Con_PO__c</referenceTo>
        <relationshipLabel>Invoice Distribution Lines</relationshipLabel>
        <relationshipName>Invoice_Distribution_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POInvoice__c</fullName>
        <label>PO Invoice</label>
        <referenceTo>PO_Invoice__c</referenceTo>
        <relationshipLabel>Invoice Distribution Lines</relationshipLabel>
        <relationshipName>Invoice_Distribution_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Retention__c</fullName>
        <label>Retention</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tax Group</label>
        <referenceTo>Tax_Group__c</referenceTo>
        <relationshipLabel>Invoice Distribution Lines</relationshipLabel>
        <relationshipName>Invoice_Distribution_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Liability__c</fullName>
        <label>Tax Liability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Distribution Line</label>
    <nameField>
        <displayFormat>DL#{00000000}</displayFormat>
        <label>Distribution Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Distribution Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PO_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount 1</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>PO Invoice</label>
    <nameField>
        <displayFormat>INV#{000000}</displayFormat>
        <label>PO Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PO Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Retention__c.object
<CustomObject>
    <label>Retention</label>
    <nameField>
        <displayFormat>Retention-{00000000}</displayFormat>
        <label>Retention Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retentions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_Group__c.object
<CustomObject>
    <label>Tax Group</label>
    <nameField>
        <label>Tax Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_trgInvoiceDistributionLineItems.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_trgInvoiceDistributionLineItems {

    static testMethod void TestDMLOperationOnInvoiceDistributionLineItems() {
        
        PO_Invoice__C POInvoice=[select id from PO_Invoice__C limit 1];
        Tax_Group__C TaxGroup =[Select id from Tax_Group__c limit 1];
        Con_po__c ConstructionPO=[Select id from Con_po__c limit 1] ;
        
        Invoice_Distribution_Line__C InvoiceDistributionLine=new Invoice_Distribution_Line__C();
        
        InvoiceDistributionLine.Construction_Purchase_Order1__c=ConstructionPO.id;
        InvoiceDistributionLine.POInvoice__c=POInvoice.id;
        InvoiceDistributionLine.Tax_Group__c=TaxGroup.id;
        InvoiceDistributionLine.Amount__c=3;
        InvoiceDistributionLine.Retention__c=5;
        InvoiceDistributionLine.Tax__c=6;
        InvoiceDistributionLine.Tax_Liability__c=5;
        
        insert InvoiceDistributionLine;
        
         Invoice_Distribution_Line__C InvoiceDistributionLine2=new Invoice_Distribution_Line__C();
        
        InvoiceDistributionLine2.Construction_Purchase_Order1__c=ConstructionPO.id;
        InvoiceDistributionLine2.POInvoice__c=POInvoice.id;
        InvoiceDistributionLine2.Tax_Group__c=TaxGroup.id;
        InvoiceDistributionLine2.Amount__c=3;
        InvoiceDistributionLine2.Retention__c=5;
        InvoiceDistributionLine2.Tax__c=6;
        InvoiceDistributionLine2.Tax_Liability__c=5;
        
        insert InvoiceDistributionLine2;
        
    }
}