objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Prevailing_Wage__c</fullName>
        <description>NO LONGER IN USE replaced by field Prevailing Wage Included.</description>
        <formula>TEXT(ASProject__r.AcctSeed__Opportunity__r.Prevailing_Wage__c)</formula>
        <inlineHelpText>pulls value from prevailing wage field on the opportunity</inlineHelpText>
        <label>Prevailing Wage DO NOT USE</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approximate_Install_Date__c</fullName>
        <description>This is the approximate date that customer expects that installation will begin.</description>
        <inlineHelpText>Required at Project Awarded- This is the approximate date that customer expects that installation will begin.</inlineHelpText>
        <label>Approximate Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <inlineHelpText>Denotes the Financing that was selected when the contract was signed.</inlineHelpText>
        <label>Final Financing Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PPA – Borrego</fullName>
                </value>
                <value>
                    <fullName>PPA - 3rd Party</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>HELOC</fullName>
                </value>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PPA</fullName>
                </value>
                <value>
                    <fullName>PACE</fullName>
                </value>
                <value>
                    <fullName>TEML (tax-exempt municipal lease)</fullName>
                </value>
                <value>
                    <fullName>GO Bond</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prevailing_Wage__c</fullName>
        <inlineHelpText>Does the contract include Prevailing Wage? Required at Contract Signing</inlineHelpText>
        <label>Prevailing Wage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tax_Exemption__c</fullName>
        <inlineHelpText>Will the contract be Tax Exempt? For use by Accounting when purchasing materials</inlineHelpText>
        <label>Tax Exemption Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Exempt</fullName>
                </value>
                <value>
                    <fullName>Non-Exempt</fullName>
                </value>
                <value>
                    <fullName>Varies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <label>Opportunity Utility Company</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PG&amp;E</fullName>
                </value>
                <value>
                    <fullName>SCE</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E</fullName>
                </value>
                <value>
                    <fullName>NSTAR</fullName>
                </value>
                <value>
                    <fullName>National Grid</fullName>
                </value>
                <value>
                    <fullName>TMLP</fullName>
                </value>
                <value>
                    <fullName>WMECO</fullName>
                </value>
                <value>
                    <fullName>Unitil</fullName>
                </value>
                <value>
                    <fullName>CPAU</fullName>
                </value>
                <value>
                    <fullName>SVP</fullName>
                </value>
                <value>
                    <fullName>Healdsburg</fullName>
                </value>
                <value>
                    <fullName>SMUD</fullName>
                </value>
                <value>
                    <fullName>AP+T</fullName>
                </value>
                <value>
                    <fullName>PSNH</fullName>
                </value>
                <value>
                    <fullName>IID</fullName>
                </value>
                <value>
                    <fullName>LADWP</fullName>
                </value>
                <value>
                    <fullName>Bear Valley Electric</fullName>
                </value>
                <value>
                    <fullName>GWP</fullName>
                </value>
                <value>
                    <fullName>Roseville Electric</fullName>
                </value>
                <value>
                    <fullName>Other - Northern CA</fullName>
                </value>
                <value>
                    <fullName>Other - Southern CA</fullName>
                </value>
                <value>
                    <fullName>Other - East Coast</fullName>
                </value>
                <value>
                    <fullName>APS</fullName>
                </value>
                <value>
                    <fullName>Fitchburg Gas and Electric/Unitil</fullName>
                </value>
                <value>
                    <fullName>MetED</fullName>
                </value>
                <value>
                    <fullName>PNM</fullName>
                </value>
                <value>
                    <fullName>El Paso Electric</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>Indianapolis Power &amp; Light (IPL)</fullName>
                </value>
                <value>
                    <fullName>PREPA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Won_Loss_Explanation__c</fullName>
        <inlineHelpText>Why did we win or lose the Opportunity? Required when Stage = Closed Lost or Contract Signed</inlineHelpText>
        <label>Won/Loss Explanation</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Projectbookedcontroller.cls
public with sharing class Projectbookedcontroller {
     @AuraEnabled
 /*  public static Opportunity getOpportuniy(Id OppId){
    return [SELECT Name, Id,StageName,Type FROM Opportunity  WHERE Id = :OppId ];
    
    }
} */
    
     public  static string OppUpdate(Id OppId) 
    {
       String resultMap; 
       String rtId;
       String rtCaptiveOnSite;
       Integer errnum=0;
       String errmsg ='';
            
    Opportunity oppvalues=new Opportunity ();
    List<Opportunity> opp = [Select Id, Approximate_Install_Date__c,Won_Loss_Explanation__c,Type,Utility_Company__c,Prevailing_Wage__c,Tax_Exemption__c,Financing__c,Amount,RecordTypeId,StageName FROM Opportunity Where Id =: OppId ];
 
           oppvalues=opp.get(0);
           Date apprxdate=oppvalues.Approximate_Install_Date__c;
           String TYPE=oppvalues.Type;
           String UTIL=oppvalues.Utility_Company__c;
           String PREVWAGE=oppvalues.Prevailing_Wage__c;
           String EXEMPT=oppvalues.Tax_Exemption__c;
           Decimal TOTALPRICE=oppvalues.Amount;
           rtId=oppvalues.RecordTypeId; 
           rtCaptiveOnSite='012340000007kaK';
           String WONLOSS = oppvalues.Won_Loss_Explanation__c;
           String FINSOURCE=oppvalues.Financing__c;

          
           if(TYPE != 'Service') {
            errmsg='Please Enter the Value For \n'; 
           if (TOTALPRICE == null)
           {     
               apprxdate = null;
               errnum++ ; 
               errmsg += 'Amount\n';
               } 
            if (TYPE == null){errnum++; errmsg += 'Type\n';} 
      if (WONLOSS== null){errnum++; errmsg += 'Won/Loss Explanation\n';} 
      if (EXEMPT == null){errnum++; errmsg += 'Tax Exemption Status';}    
               
           }   
   
                   system.debug('ERNUM VALUE' +errnum);
                   if (errnum==0) {
                       
                       
                    system.debug('record ID' +rtId.substring(0,15));
                    system.debug('FinSource' +FINSOURCE);
                    if (rtId.substring(0,15) == rtCaptiveOnSite) {                        
          if( FINSOURCE == 'PPA'|| FINSOURCE == 'PPA – Borrego' || FINSOURCE == 'PPA - 3rd Party')  {                           
            oppvalues.StageName = 'Project Booked'; 
          } else { 
            oppvalues.StageName = 'Contract Signed'; 
            } 
          } else { 
          oppvalues.StageName = 'Project Booked'; 
              }  
                          
            
                       try {
                           update oppvalues;
                           errmsg= ('Opportunity Updated to ' +oppvalues.StageName);
                           resultMap=errmsg;
                       }
                       catch(Exception e) {
                           resultMap=  e.getMessage(); 
                       }
                 
               } 
           
            else {
                
                    resultMap= errmsg ;
                                   
                      
                  }    
        
      
                  system.debug('LOOK HERE'  +resultMap);
                  return resultMap;   
    
           }
           }