objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Area_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to user record to identify Area Supervisor on a contract</description>
        <inlineHelpText>Area Supervisor on the contract</inlineHelpText>
        <label>Area Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Amount__c</fullName>
        <inlineHelpText>Total yearly amount of the service contract.</inlineHelpText>
        <label>Contract Amount (yearly)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Does_Contract_Auto_Renew__c</fullName>
        <description>indicate whether contract will auto-renew</description>
        <inlineHelpText>indicate whether contract will auto-renew</inlineHelpText>
        <label>Does Contract Auto Renew?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalator__c</fullName>
        <label>Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Labor_Escalator__c</fullName>
        <description>Labor rate escalator for this contract</description>
        <inlineHelpText>Labor rate escalator for this contract</inlineHelpText>
        <label>Labor Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MinimumBillableTravelTime__c</fullName>
        <description>Minimum number of hours billable per service visit. If 0, all travel time is billable</description>
        <inlineHelpText>Minimum number of hours billable per service visit. If 0, all travel time is billable</inlineHelpText>
        <label>Minimum Billable Travel Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_M_Package__c</fullName>
        <label>O&amp;M Package</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Preventative</fullName>
                </value>
                <value>
                    <fullName>Comprehensive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regional_Manager_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to user record to identify Regional Manager on a contract</description>
        <inlineHelpText>Regional manager on the contract</inlineHelpText>
        <label>Regional Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Manager__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes.</description>
        <inlineHelpText>Hourly rate stated in contract</inlineHelpText>
        <label>Regional Manager Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Contract_Start_Date__c</fullName>
        <inlineHelpText>The date that the service contract starts.</inlineHelpText>
        <label>Service Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_1_OT__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes</description>
        <inlineHelpText>Hourly(OT) rate stated in contract</inlineHelpText>
        <label>Solar Electrician 1 - OT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_1__c</fullName>
        <defaultValue>105</defaultValue>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes.</description>
        <inlineHelpText>Hourly rate stated in contract</inlineHelpText>
        <label>Solar Electrician 1 Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_2_OT__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes</description>
        <inlineHelpText>Hourly(OT) rate stated in contract</inlineHelpText>
        <label>Solar Electrician 2 - OT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_2__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes.</description>
        <inlineHelpText>Hourly rate stated in contract</inlineHelpText>
        <label>Solar Electrician 2 Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Engineer_OT__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes</description>
        <inlineHelpText>Hourly(OT) rate stated in contract</inlineHelpText>
        <label>Solar Engineer - OT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Engineer__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes</description>
        <inlineHelpText>Hourly rate stated in contract</inlineHelpText>
        <label>Solar Engineer Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Service_Contract_Escalator__c.object
<CustomObject>
    <description>stores escalator values for each year of service contract</description>
    <fields>
        <fullName>CurrentYearContractValue__c</fullName>
        <description>shows value of contract in current year with escalators applied - updated via trigger or WF</description>
        <inlineHelpText>shows value of contract in current year with escalators applied</inlineHelpText>
        <label>Current Year Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Escalator__c</fullName>
        <description>displays escalator % from the field Escalator from related contract</description>
        <formula>Service_Contract__r.Escalator__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>displays escalator % from the field Escalator from related contract</inlineHelpText>
        <label>Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Labor_Escalator__c</fullName>
        <description>Used to bring over Labor rate escalator from contract.</description>
        <inlineHelpText>Used to bring over Labor rate escalator from contract.</inlineHelpText>
        <label>Labor Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Service_Contract_Start_Date__c</fullName>
        <description>displays Service Contract Start Date from related Contract</description>
        <formula>Service_Contract__r.Service_Contract_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>displays Service Contract Start Date from related Contract</inlineHelpText>
        <label>Service Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <description>displays the related contract</description>
        <inlineHelpText>displays the related contract</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Contract Escalators</relationshipLabel>
        <relationshipName>Service_Contract_Escalators</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>enter in 4 digit year</description>
        <inlineHelpText>enter in 4 digit year</inlineHelpText>
        <label>Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Contract Escalator</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Contract Escalator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Escalators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CreateEscalatorTestClass.cls
@isTest(seealldata=true) 
public class CreateEscalatorTestClass 
{
    static testMethod void testMethod1() 
 {
 
      user userid = [select id from user where isactive=true  and department ='o&m' and title like '%Manager%' limit 1];
     
  Contract testcontract= new Contract();
      testcontract.AccountId='0013000000LBRIs';
      testcontract.Description='test';
      testcontract.Contract_Status__c='Active';
      testcontract.Branch__c='New England';
      testcontract.O_M_Package__c='Reactive';
      testcontract.Does_Contract_Auto_Renew__c='Yes';
      testcontract.Service_Contract_Start_Date__c= Date.newinstance(2016, 11, 01);
      testcontract.ContractTerm=24;
      testcontract.EndDate= Date.newinstance(2018, 11, 02);
      testcontract.Contract_Amount__c=314.58; 
      testcontract.MinimumBillableTravelTime__c=0;
      testcontract.Status=' NullVoid';
      testcontract.Escalator__c=2;
      testcontract.Solar_Electrician_1_OT__c=100;
      testcontract.Labor_Escalator__c=2;
      testcontract.Solar_Electrician_1__c=100;
      testcontract.Solar_Electrician_2__c=200; 
      testcontract.Solar_Electrician_2_OT__c=100; 
      testcontract.Regional_Manager__c=100;
      testcontract.Solar_Engineer__c=100;
      testcontract.Solar_Engineer_OT__c=200;   
      testcontract.Area_Supervisor__c =userid.id;
      testcontract.Regional_Manager_User__c = userid.id;
      insert testcontract;
     
      Service_Contract_Escalator__c testescalator=new Service_Contract_Escalator__c();
      testescalator.Service_Contract__c=testcontract.id;
      testescalator.Year__c=1;
      testescalator.CurrentYearContractValue__c=314.58;
      testescalator.Current_Year1__c=100;
      testescalator.Current_Year_Solar_Electrician_1_Rate__c=100;
      testescalator.Current_Year_Solar_Electrician_1_OT_Ra__c=100;
      testescalator.Current_Year_Solar_Electrician_2_OT_Ra__c=100;
      testescalator.Current_Year12__c=200;
      testescalator.Current_Year_Solar_Engineer_OT_Rate__c=100;
      testescalator.Current_Year__c=100;
      insert testescalator;
    
       testcontract.EndDate=Date.newinstance(2020,11, 02);
      Update testcontract;
     
      
      
 
        }
}