objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Engineer_Rate_OT__c</fullName>
        <label>Current Solar Engineer Rate OT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Engineer_Rate__c</fullName>
        <label>Current Solar Engineer Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Regional_Manager_Rate__c</fullName>
        <label>Current Regional Manager Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Solar_Electrician_1_Rate_OT__c</fullName>
        <label>Current Solar Electrician 1 Rate OT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Solar_Electrician_1_Rate__c</fullName>
        <label>Current Solar Electrician 1 Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Solar_Electrician_2_Rate_OT__c</fullName>
        <label>Current Solar Electrician 2 Rate OT</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Solar_Electrician_2_Rate__c</fullName>
        <label>Current Solar Electrician 2 Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Year_Contract_Value__c</fullName>
        <description>This Field is used to capture the current year contract value from the escalator.  Updated nightly via a Batch Class</description>
        <inlineHelpText>This Field is used to capture the current year contract value from the escalator.</inlineHelpText>
        <label>Current Year Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_of_Contract__c</fullName>
        <description>displays Year of contract we are in, 1st year, 2nd year, 3rd year...etc, based on Service Contract Start Date.</description>
        <formula>YEAR(TODAY()) - YEAR(  Service_Contract_Start_Date__c ) + 
IF( 
OR( 
MONTH(TODAY()) &gt; MONTH(Service_Contract_Start_Date__c), 
AND( 
MONTH(TODAY()) = MONTH(Service_Contract_Start_Date__c), 
DAY(TODAY()) &gt;= DAY(Service_Contract_Start_Date__c) 
) 
), 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>displays Year of contract we are in, 1st year, 2nd year, 3rd year...etc, based on Service Contract Start Date.</inlineHelpText>
        <label>Year of Contract</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Paid</fullName>
        <active>true</active>
        <description>Paid O&amp;M Service Contracts</description>
        <label>Paid</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Service_Contract_Escalator__c.object
<CustomObject>
    <description>stores escalator values for each year of service contract</description>
    <fields>
        <fullName>CurrentYearContractValue__c</fullName>
        <description>shows value of contract in current year with escalators applied - updated via trigger or WF</description>
        <inlineHelpText>shows value of contract in current year with escalators applied</inlineHelpText>
        <label>Current Year Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Year12__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</description>
        <inlineHelpText>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</inlineHelpText>
        <label>Current Solar Engineer Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Year1__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</description>
        <inlineHelpText>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</inlineHelpText>
        <label>Current  Regional Manager Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Year_Solar_Electrician_1_OT_Ra__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</description>
        <inlineHelpText>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</inlineHelpText>
        <label>Current  Solar Electrician 1 - OT Ra</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Year_Solar_Electrician_1_Rate__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the Escalator for billing purposes for current year.</description>
        <inlineHelpText>Hourly rate stated in contract, will be carried over to the Escalator for billing purposes for current year.</inlineHelpText>
        <label>Current  Solar Electrician 1 Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Year_Solar_Electrician_2_OT_Ra__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</description>
        <inlineHelpText>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</inlineHelpText>
        <label>Current  Solar Electrician 2 - OT Ra</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Year_Solar_Engineer_OT_Rate__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</description>
        <inlineHelpText>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</inlineHelpText>
        <label>Current  Solar Engineer - OT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Year__c</fullName>
        <description>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</description>
        <inlineHelpText>Hourly rate stated in contract, will be carried over to the SV for billing purposes for current year.</inlineHelpText>
        <label>Current Solar Electrician 2 Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <description>displays the related contract</description>
        <inlineHelpText>displays the related contract</inlineHelpText>
        <label>Service Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Service Contract Escalators</relationshipLabel>
        <relationshipName>Service_Contract_Escalators</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>enter in 4 digit year</description>
        <inlineHelpText>enter in 4 digit year</inlineHelpText>
        <label>Year</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Service Contract Escalator</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Service Contract Escalator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Contract Escalators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateContractfieldBatch.cls
global class UpdateContractfieldBatch implements Database.Batchable<sObject>
{

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        
       
        
        String query = 'SELECT Id,  EndDate,Year_of_Contract__c FROM Contract WHERE Contract_Status__c= \'ACTIVE\' AND RecordType.Name=\'Paid\'';
         system.debug('Query Size' +query);         
        return Database.getQueryLocator(query);
              
    } 
    global void execute(Database.BatchableContext BC, List<Contract> Contracts)
    {
        system.debug('No of contracts fetched for renewal = '+Contracts.size());
        try 
        {
            for(Contract c :Contracts)
            {
           List< Service_Contract_Escalator__c> currentyear= new  List<Service_Contract_Escalator__c>();
           
             Service_Contract_Escalator__c currentyear1=new Service_Contract_Escalator__c ();
             currentyear=[select CurrentYearContractValue__c,Current_Year_Solar_Electrician_1_Rate__c,Current_Year_Solar_Electrician_1_OT_Ra__c	,Current_Year__c,Current_Year_Solar_Electrician_2_OT_Ra__c,Current_Year12__c,Current_Year_Solar_Engineer_OT_Rate__c,Current_Year1__c from Service_Contract_Escalator__c where Year__c=:c.Year_of_Contract__c and Service_Contract__c=:c.id];
          system.debug('this is 2nd year--->' +currentyear.size());
             if(currentyear.size()>0)
             { 
             currentyear1=currentyear.get(0);
                 
             
             c.Current_Year_Contract_Value__c=currentyear1.CurrentYearContractValue__c;    // ;//updatedcurrentyear;
             
             c.Current_Solar_Electrician_1_Rate__c = currentyear1.Current_Year_Solar_Electrician_1_Rate__c;
             c.Current_Solar_Electrician_1_Rate_OT__c = currentyear1.Current_Year_Solar_Electrician_1_OT_Ra__c;
             c.Current_Solar_Electrician_2_Rate__c = currentyear1.Current_Year__c;
             c.Current_Solar_Electrician_2_Rate_OT__c = currentyear1.Current_Year_Solar_Electrician_2_OT_Ra__c;
             c.Current_Engineer_Rate__c = currentyear1.Current_Year12__c;
             c.Current_Engineer_Rate_OT__c = currentyear1.Current_Year_Solar_Engineer_OT_Rate__c	 ;     
             c.Current_Regional_Manager_Rate__c = currentyear1.Current_Year1__c ;
                     
             Update c; 
              }
              }
              } catch(Exception e) {
            System.debug('Error occured during execution.'+e);
        
    }
    }
    global void finish(Database.BatchableContext BC) 
    {
        // execute any post-processing operations
    }
}