objects/Contract_Committee_Submittal__c.object
<CustomObject>
    <fields>
        <fullName>Date_PB3_Team_Notified__c</fullName>
        <description>uses java button to record time stamp</description>
        <label>Date PB3 Team Notified</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Execution_Version_of_Lease__c</fullName>
        <description>The box link to the Microsoft Word version of the final copy of the lease that has been circulated for execution.</description>
        <inlineHelpText>Paste the box link to the Microsoft Word version of the final copy of the lease that has been circulated for execution.</inlineHelpText>
        <label>Execution Version of Lease</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>GIS_LIDAR_survey__c</fullName>
        <description>Box link for folder containing GIS LIDAR information</description>
        <inlineHelpText>Paste box link for folder containing GIS LIDAR information</inlineHelpText>
        <label>GIS LIDAR survey</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Lease_Extraction_Form__c</fullName>
        <description>Paste box link to completed lease extraction form</description>
        <inlineHelpText>Paste box link to completed lease extraction form</inlineHelpText>
        <label>Lease Extraction Form</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Notify_PB3_Approval_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Sends alert to PB3 Approval Team via workflow</description>
        <inlineHelpText>Sends alert to PB3 Approval Team</inlineHelpText>
        <label>Notify PB3 Approval Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Skeletal_survey__c</fullName>
        <description>Box link for folder containing Skeletal survey files</description>
        <inlineHelpText>Paste box link for folder containing Skeletal survey files</inlineHelpText>
        <label>Skeletal survey</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Title_Report_its_Legal_Review__c</fullName>
        <description>Box link for folder containing title report and legal review of the title report</description>
        <inlineHelpText>Paste box link for folder containing title report and legal review of the title report</inlineHelpText>
        <label>Title Report &amp; its Legal Review</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Wetlands_Delineation__c</fullName>
        <description>box link for folder containing wetland delineation files</description>
        <inlineHelpText>Paste box link for folder containing wetland delineation files</inlineHelpText>
        <label>Wetlands Delineation</label>
        <type>Url</type>
    </fields>
    <label>Contract and Development Approval</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Contract and Development Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract and Development Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NotifyPB3.cls
public class NotifyPB3 {
	
     @AuraEnabled
    
 public  static string ConComitteeUpdate(Id ccsId) 
 {
     string resultmap;
     Contract_Committee_Submittal__c Concommit = new Contract_Committee_Submittal__c();
     List<Contract_Committee_Submittal__c> conlist = [select ID,Date_PB3_Team_Notified__c,Notify_PB3_Approval_Team__c ,Execution_Version_of_Lease__c,Lease_Extraction_Form__c,Wetlands_Delineation__c,GIS_LIDAR_survey__c,Skeletal_survey__c,Title_Report_its_Legal_Review__c from Contract_Committee_Submittal__c where Id =:ccsId] ;
     //
     Concommit = conlist.get(0);
     
if(Concommit.Execution_Version_of_Lease__c == null || Concommit.Lease_Extraction_Form__c == null || Concommit.Wetlands_Delineation__c == null || Concommit.GIS_LIDAR_survey__c == null || Concommit.Skeletal_survey__c == null || Concommit.Title_Report_its_Legal_Review__c == null ) 
{
    resultmap = ('Before notifying PB3 Approval Team, Execution version of Lease, Lease Extraction Form, and all Initial Site Discovery Items (except NHESP Letter) must be filled out');
    
    
}else{
    
    		try {
                
                          
                           Date d = system.Today() ;
                           String mydate =  d.format() ;
                         //  string mydate = string.valueof(date.today(),'MM/DD/YYYY');
                        Concommit.Date_PB3_Team_Notified__c = mydate;
                        Concommit.Notify_PB3_Approval_Team__c = true;
              				//  system.debug(system.Today());
                              system.debug(d);
                			  system.debug(concommit);
                           update Concommit;
                          // errmsg= ('Opportunity Updated to ' +oppvalues.StageName);
                           resultmap = 'Notified Pb3 Team';
                       }
                       catch(Exception e) {
                           resultMap=  e.getMessage(); 
                       }
    
}
     return resultmap;
 }   
   
    
}