objects/Contract.object
<CustomObject>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The related project that the service contract was created for.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nor Cal</fullName>
                </value>
                <value>
                    <fullName>So Cal</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Amount__c</fullName>
        <inlineHelpText>Total yearly amount of the service contract.</inlineHelpText>
        <label>Contract Amount (yearly)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Status__c</fullName>
        <inlineHelpText>The status of the service contract.</inlineHelpText>
        <label>Contract Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Paid Contract Complete</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Erroneous</fullName>
                </value>
                <value>
                    <fullName>Customer Terminated</fullName>
                </value>
                <value>
                    <fullName>Borrego Terminated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_First_Escalator_to_be_Applied__c</fullName>
        <label>Date of First Escalator to be Applied</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Does_Contract_Auto_Renew__c</fullName>
        <description>indicate whether contract will auto-renew</description>
        <inlineHelpText>indicate whether contract will auto-renew</inlineHelpText>
        <label>Does Contract Auto Renew?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalator_Details__c</fullName>
        <label>Escalator Details</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Escalator_Details</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalator__c</fullName>
        <label>Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>MinimumBillableTravelTime__c</fullName>
        <description>Minimum number of hours billable per service visit. If 0, all travel time is billable</description>
        <inlineHelpText>Minimum number of hours billable per service visit. If 0, all travel time is billable</inlineHelpText>
        <label>Minimum Billable Travel Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>O_M_Package__c</fullName>
        <label>O&amp;M Package</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Hourly</fullName>
                </value>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Preventative</fullName>
                </value>
                <value>
                    <fullName>Comprehensive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Options__c</fullName>
        <description>payment options will eventually auto-populate value on Billings and set off automated process, please make sure its accurate before activating contract.     SHOULD MATCH Billing Frequency field on RECURRING BILLING OBJECT and PAYMENT OPTIONS on Opportunity.</description>
        <inlineHelpText>payment options will eventually auto-populate value on Billings and set off automated process, please make sure its accurate before activating contract.</inlineHelpText>
        <label>Payment Options</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Lump Sum</fullName>
                    <label>Anniversary in Advance</label>
                </value>
                <value>
                    <fullName>Anniversary Semi-Annual in Arrears</fullName>
                </value>
                <value>
                    <fullName>Annual - Jan to Dec in Advance</fullName>
                    <label>Annual in Advance - Jan to Dec</label>
                </value>
                <value>
                    <fullName>Arrears Per % of visits completed</fullName>
                </value>
                <value>
                    <fullName>Long-Term Multiple Years in Advance</fullName>
                    <label>Long-Term in Advance</label>
                </value>
                <value>
                    <fullName>Mid Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Monthly in Advance</fullName>
                </value>
                <value>
                    <fullName>Monthly in Arrears</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Advance</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Advance Equal Installments</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Arrears</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Arrears Equal Installments</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual in Advance</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual in Arrears</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recurring_Billing_Name__c</fullName>
        <description>Formula Field to concatenate the project name and account name used in the recurring billing record to populate the recurring billing name</description>
        <formula>Account__c&amp;&quot;-&quot;&amp;SUBSTITUTE(ASProject__r.Name,&quot;O&amp;M.-&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula Field to concatenate the project name and account name used in the recurring billing record to populate the recurring billing name</inlineHelpText>
        <label>Recurring Billing Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Contract_Start_Date__c</fullName>
        <inlineHelpText>The date that the service contract starts.</inlineHelpText>
        <label>Service Contract Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Contract_Tier__c</fullName>
        <description>describes levels of performance guarantee coverage on O&amp;M contracts</description>
        <inlineHelpText>Tier 1 = Borrego has a performance or availability guarantee in place 
Tier 2 = Reactive package 
Tier 3 = Basic package 
Tier 4 = Less than Basic package
Tier 10 = Not Currently Contracted or Warranty</inlineHelpText>
        <label>Service Contract Tier</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 0</fullName>
                </value>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4</fullName>
                </value>
                <value>
                    <fullName>Tier 10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>O&amp;MWarranty:  Borrego built, under EPCWrnty &amp; contract
O&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract
O&amp;M T&amp;M: Borrego didn&apos;t build; EPC expired &amp; contract,  billed T&amp;M 
Borrego Warranty: Borrego built, under EPCWrnty; no contract
Project: one-offs</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Warranty/Construction</fullName>
                    <default>true</default>
                    <label>Warranty/Construction</label>
                </value>
                <value>
                    <fullName>O&amp;M</fullName>
                </value>
                <value>
                    <fullName>O&amp;M T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Special Projects</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Escalator_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Increases per calendar year</fullName>
    </customValue>
    <customValue>
        <fullName>Increases on anniversary date of contract</fullName>
    </customValue>
    <masterLabel>Escalator Details</masterLabel>
</GlobalValueSet>

classes/CreateRecurringBillingTestClass.cls
@isTest(seealldata=true)
public class CreateRecurringBillingTestClass 
{
    static testMethod void testMethod1() 
 {
      
      Test.startTest();
      //ASeedAccountingSettingsSetupTest.testDataSetup(); 
      //
      user userid = [select id from user where isactive=true  and department ='o&m' and title like '%Manager%' limit 1];
      
      Contract testcontract= new Contract();
      testcontract.AccountId='0013000000LBRIs';
      
      testcontract.Description='test';
      testcontract.Contract_Status__c='Pending';
      testcontract.Branch__c='New England';
      testcontract.O_M_Package__c='Reactive';
      testcontract.ASProject__c='a1t340000047bVz';
      testcontract.Does_Contract_Auto_Renew__c='Yes';
      testcontract.Service_Contract_Start_Date__c= Date.newinstance(2010, 11, 01);
      testcontract.ContractTerm=84;
      testcontract.EndDate= Date.newinstance(2018, 12, 13);
      testcontract.Contract_Amount__c=314.58; 
      testcontract.MinimumBillableTravelTime__c=0;
      testcontract.Status=' NullVoid';
      testcontract.Escalator__c=2;
      testcontract.Type__c='O&M';
      //testcontract.Recurring_Billing_Name__c=
      testcontract.Payment_Options__c='Anniversary in Advance';
      testcontract.Escalator_Details__c='Increases on anniversary date of contract';
      testcontract.Date_of_First_Escalator_to_be_Applied__c=Date.newinstance(2011, 3, 11);  
      insert testcontract;
      testcontract.Contract_Status__c='Active';
      testcontract.Service_Contract_Tier__c='Tier 0';
      testcontract.Monitoring_Required__c ='No';  
     testcontract.Area_Supervisor__c=userid.id;
     testcontract.Regional_Manager_User__c=userid.id;
      update testcontract;
      
      
           /*AcctSeed__Recurring_Billing__c testrecurringbilling= new AcctSeed__Recurring_Billing__c();
           testrecurringbilling.Name='AES Distributed Energy - Information Technology (DOIT) - O&M';
           testrecurringbilling.AcctSeed__Customer__c='0013400001KBNN4';
           testrecurringbilling.AcctSeed__Status__c='Active';
           testrecurringbilling.AcctSeed__Billing_Frequency__c='Anniversary in Advance';
           testrecurringbilling.AcctSeed__Next_Billing_Date__c=Date.newinstance(2018, 12, 31);
           testrecurringbilling.Service_Contract__c='80034000001FX4m';
           insert testrecurringbilling;*/
           Test.stopTest();
      
      
      
 
        }
}