objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <description>pulls over Active user checkbox from SF user record</description>
        <formula>SF_User_Record__r.IsActive</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>pulls over Active user checkbox from SF user record</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MWA1_Answer__c.object
<CustomObject>
    <description>An answer is specific to a question (entry) or a given submission.</description>
    <fields>
        <fullName>Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MWAQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>MWA1_Entry__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>R00N30000001ldyyEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NR__c</fullName>
        <label>Numeric Response</label>
        <precision>14</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SVR__c</fullName>
        <label>Text Response</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>MWA1_Submission__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>R00N30000001ldyvEAA</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Answer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MWA1_Entry__c.object
<CustomObject>
    <description>Each record is an individual line item on a survey, which may include (i) divider text, (ii) a rating scale, or (iii) a question.</description>
    <fields>
        <fullName>EType__c</fullName>
        <label>Entry Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DIVIDER TEXT</fullName>
                </value>
                <value>
                    <fullName>RATING SCALE LABELS</fullName>
                </value>
                <value>
                    <fullName>VERTICAL SPACER</fullName>
                </value>
                <value>
                    <fullName>Single-select (Vertical)</fullName>
                </value>
                <value>
                    <fullName>Single-select (Horizontal)</fullName>
                </value>
                <value>
                    <fullName>Multi-select (Vertical)</fullName>
                </value>
                <value>
                    <fullName>Multi-select (Horizontal)</fullName>
                </value>
                <value>
                    <fullName>Number (ranged)</fullName>
                </value>
                <value>
                    <fullName>Number (unranged)</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Short Answer (255)</fullName>
                </value>
                <value>
                    <fullName>Long Answer (32000)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entry_Text__c</fullName>
        <label>Entry Text</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MWASurvey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>MWA1_Survey__c</referenceTo>
        <relationshipLabel>Entries</relationshipLabel>
        <relationshipName>R00N30000001ldz5EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Entry</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MWA1_Submission__c.object
<CustomObject>
    <description>A Submission record represents the header data for a reponse.  Answers are the child records to a submission.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>R00N30000001ldz3EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MWASurvey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>MWA1_Survey__c</referenceTo>
        <relationshipLabel>Survey Submission</relationshipLabel>
        <relationshipName>R00N30000001ldyqEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>S{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MWA1_Survey__c.object
<CustomObject>
    <description>Used to store the macro survey information</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyResult.cls
public class SurveyResult {
    public static void ratingNumber(MWA1_Answer__c[] ans) {
        for (MWA1_Answer__c a:ans) {
            MWA1_Entry__c question = [select Id, Position__c from MWA1_Entry__c where Id = :a.MWAQuestion__c];
            if (question.Position__c == 1.00) {
                try {
                a.NR__c = Double.valueOf(a.SVR__c);
                }
                catch(System.TypeException e){
                    System.assert(e.getMessage().contains('Invalid double:'), 
                     e.getMessage());
                     a.Failed__c = true;
                }   
            }
        }
    }
    public static testMethod void SurveyTest(){
        Contact Contact=new contact(FirstName='System', LastName='User'); Insert Contact;
        //Contact contact = [select Id from Contact where Name = 'System User'];
        MWA1_Survey__c survey = new MWA1_Survey__c(Active__c = true); insert survey;
        MWA1_Entry__c question = new MWA1_Entry__c(MWASurvey__c = survey.Id, Position__c = 1.00, EType__c = 'Satisfaction Survey', Entry_Text__c = 'Je mange de fromage'); insert question;
        MWA1_Submission__c submission = new MWA1_Submission__c(MWASurvey__c = survey.Id, Contact__c = contact.Id); insert submission;   
        MWA1_Answer__c answer = new MWA1_Answer__c(Submission__c = submission.Id, MWAQuestion__c = question.Id, SVR__c = '9'); insert answer;
        
        answer.SVR__c = '10';
        update answer;
        answer.SVR__c = 'Ten';
        update answer;
    }
}