objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Opportunity</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date_Updated__c</fullName>
        <label>Delivery Date Updated</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inverter_Delivery_Date_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to tell if the Inverter Delivery Date field has been updated since the last automated reset of the Delivery Date Updated field.</description>
        <label>Inverter Delivery Date Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module_Delivery_Date_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to tell if the Module Delivery Date field has been updated since the last automated reset of the Delivery Date Updated field.</description>
        <label>Module Delivery Date Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Racking_Delivery_Date_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to tell if the Racking Delivery Date field has been updated since the last automated reset of the Delivery Date Updated field.</description>
        <label>Racking Delivery Date Updated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_Project__c.object
<CustomObject>
    <description>Project Management</description>
    <fields>
        <fullName>Inverter_Status__c</fullName>
        <label>Inverter Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Defined</fullName>
                </value>
                <value>
                    <fullName>PO Placed</fullName>
                </value>
                <value>
                    <fullName>Borrego Received</fullName>
                </value>
                <value>
                    <fullName>Subcon. Received</fullName>
                </value>
                <value>
                    <fullName>Product On Site</fullName>
                </value>
                <value>
                    <fullName>Install In Progress</fullName>
                </value>
                <value>
                    <fullName>Install Complete</fullName>
                </value>
                <value>
                    <fullName>Need to Order</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>In Stock</fullName>
                </value>
                <value>
                    <fullName>Kit Issued</fullName>
                </value>
                <value>
                    <fullName>Partial Delivered</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Modules_Status__c</fullName>
        <label>Modules Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Defined</fullName>
                </value>
                <value>
                    <fullName>PO Placed</fullName>
                </value>
                <value>
                    <fullName>Borrego Received</fullName>
                </value>
                <value>
                    <fullName>Subcon. Received</fullName>
                </value>
                <value>
                    <fullName>Product On Site</fullName>
                </value>
                <value>
                    <fullName>Install In Progress</fullName>
                </value>
                <value>
                    <fullName>Install Complete</fullName>
                </value>
                <value>
                    <fullName>Need to Order</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>In Stock</fullName>
                </value>
                <value>
                    <fullName>Kit Issued</fullName>
                </value>
                <value>
                    <fullName>Partial Delivered</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N300000021XqLEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consulting Services</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>Sub-Contract Install</fullName>
                </value>
                <value>
                    <fullName>Turnkey System</fullName>
                    <default>true</default>
                    <label>Turnkey System</label>
                </value>
                <value>
                    <fullName>Upgrades</fullName>
                </value>
                <value>
                    <fullName>PV Direct</fullName>
                </value>
                <value>
                    <fullName>Design Only</fullName>
                </value>
                <value>
                    <fullName>Direct Sales</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Racking_Status__c</fullName>
        <label>Racking Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Defined</fullName>
                </value>
                <value>
                    <fullName>PO Placed</fullName>
                </value>
                <value>
                    <fullName>Borrego Received</fullName>
                </value>
                <value>
                    <fullName>Subcon. Received</fullName>
                </value>
                <value>
                    <fullName>Product On Site</fullName>
                </value>
                <value>
                    <fullName>Install In Progress</fullName>
                </value>
                <value>
                    <fullName>Install Complete</fullName>
                </value>
                <value>
                    <fullName>Need to Order</fullName>
                </value>
                <value>
                    <fullName>Ordered</fullName>
                </value>
                <value>
                    <fullName>In Stock</fullName>
                </value>
                <value>
                    <fullName>Partial Delivered</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC_Project_Stage__c</fullName>
        <label>Construction Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Budget Locked</fullName>
                </value>
                <value>
                    <fullName>Subcontractors Selected</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Work 90% Completed</fullName>
                </value>
                <value>
                    <fullName>Inspections Complete</fullName>
                </value>
                <value>
                    <fullName>Cust. Accept. Complete</fullName>
                </value>
                <value>
                    <fullName>Post Mortem Completed</fullName>
                </value>
                <value>
                    <fullName>Roof Mounts/Rough In</fullName>
                </value>
                <value>
                    <fullName>Racking In</fullName>
                </value>
                <value>
                    <fullName>Modules In</fullName>
                </value>
                <value>
                    <fullName>Elec. Inspec. Pending</fullName>
                </value>
                <value>
                    <fullName>Inspection Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC_Project_Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Contract</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Ready to Handoff</fullName>
                </value>
                <value>
                    <fullName>Plans Ready</fullName>
                </value>
                <value>
                    <fullName>Permitted</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Sales Complete</fullName>
                </value>
                <value>
                    <fullName>Construction Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SFDCProject</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFDCProjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DeliveryDate.cls
public with sharing class DeliveryDate {
	
	public static void resetDeliveryDateReminder() {
		
		//Reset the Opportunity drop down that reminds the owner to
		//update the delivery dates for Racking, Module, and Inverters.
		//We only do this for Opportunity records that have associated Project records.
		
		//Get all the Opportunity and Project records we are interested in
		SFDC_Project__c[] pro = [select Id, Opportunity__c from SFDC_Project__c
				where Opportunity__c !=:null and Project_Type__c =:'Turnkey System' and
				(SFDC_Project_Status__c =:'Pre-Contract' or SFDC_Project_Status__c =:'New' or
				SFDC_Project_Status__c =:'Design' or SFDC_Project_Status__c =:'Construction') and
				(SFDC_Project_Stage__c =:null or SFDC_Project_Stage__c =:'Budget Locked' or
				SFDC_Project_Stage__c =:'Subcontractors Selected' or SFDC_Project_Stage__c =:'In Progress') and
				(Racking_Status__c =:'Product Defined' or Modules_Status__c =:'Product Defined' or Inverter_Status__c =:'Product Defined')];
		
		List<Id> oppId = new List<Id>();
		for (Integer i=0; i<pro.size(); i++) {
			oppId.add(pro[i].Opportunity__c);
		}
		
		Opportunity[] o = [select Id, Delivery_Date_Updated__c, Module_Delivery_Date_Updated__c,
				Inverter_Delivery_Date_Updated__c, Racking_Delivery_Date_Updated__c
				from Opportunity where Id in :oppId and Type =:'Turnkey System' and
				(StageName =:'Contract Negotiations' or StageName =:'Contract Signed')];
		
		List<Opportunity> upOpp = new List<Opportunity>();
		for (Integer i=0; i<o.size(); i++) {				
			if ( (o[i].Module_Delivery_Date_Updated__c == false) ||
				 (o[i].Inverter_Delivery_Date_Updated__c == false) ||
				 (o[i].Racking_Delivery_Date_Updated__c == false) ) {
				o[i].Delivery_Date_Updated__c = 'No';
			}
			o[i].Module_Delivery_Date_Updated__c = false;
			o[i].Inverter_Delivery_Date_Updated__c = false;
			o[i].Racking_Delivery_Date_Updated__c = false;
			upOpp.add(o[i]);
		}
		
		if (upOpp.size() > 0) {
			update upOpp;
		}
	}
	
	static testMethod void testDeliveryDate() {
		resetDeliveryDateReminder();
	}
}