objects/Contract_Committee_Submittal__c.object
<CustomObject>
    <fields>
        <fullName>Date_PB3_Complete__c</fullName>
        <description>uses Java button to record timestamp</description>
        <label>TEXT Date PB3 Complete</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Execution_Version_of_Lease__c</fullName>
        <description>The box link to the Microsoft Word version of the final copy of the lease that has been circulated for execution.</description>
        <inlineHelpText>Paste the box link to the Microsoft Word version of the final copy of the lease that has been circulated for execution.</inlineHelpText>
        <label>Execution Version of Lease</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>PB3_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Should not be on layout. Controlled by button and WF. When it is checked off it sends an email alert out</description>
        <inlineHelpText>Sends email alert out to PB3 Team.</inlineHelpText>
        <label>PB3 Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pricing_Request_Approved__c</fullName>
        <description>Displays whether or not the selected Pricing Request for the PB3 has been approved.</description>
        <formula>IF(Pricing_Tool_Approval__r.Approval_Status__c   = &quot;Approved&quot;, &quot;Yes&quot;,
IF(Pricing_Tool_Approval__r.Approval_Status__c   = &quot;Preliminary Approval&quot;, &quot;Yes&quot;,
IF(Pricing_Tool_Approval__r.Approval_Status__c   = &quot;Final Approval&quot;, &quot;Yes&quot;, 
&quot;No&quot;
)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Pricing Request must be approved (&quot;Preliminary Approved&quot;, &quot;Approved&quot;, or &quot;Final Approved&quot;) to click PB3 Complete button.</inlineHelpText>
        <label>Pricing Request Approved?</label>
        <type>Text</type>
    </fields>
    <label>Contract and Development Approval</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Contract and Development Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract and Development Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Pb3Complete.cls
public class Pb3Complete {

      @AuraEnabled
    
 public  static string ConComitteeUpdate(Id ccsId) 
 {
     string resultmap;
     Contract_Committee_Submittal__c Concommit = new Contract_Committee_Submittal__c();
     List<Contract_Committee_Submittal__c> conlist = [select ID,Date_PB3_Complete__c ,PB3_Complete__c  ,Execution_Version_of_Lease__c,Pricing_Request_Approved__c from Contract_Committee_Submittal__c where Id =:ccsId] ;
     
     Concommit = conlist.get(0);
     
if(Concommit.Execution_Version_of_Lease__c == null  || Concommit.Pricing_Request_Approved__c =='No' ) 
{
    resultmap = ('Before marking PB3 Complete, Executed Lease must be filled out and the Pricing Request must be approved');
    
    
}else{
    
    		try {
                
                          
                           Date d = Date.Today() ;
                           String mydate =  d.format() ;
                           Concommit.Date_PB3_Complete__c  = mydate;
                           Concommit.PB3_Complete__c  = true;
                           update Concommit;
                           resultmap = 'Pb3 Complete';
                       }
                       catch(Exception e) {
                           resultMap=  e.getMessage(); 
                       }
    
}
     return resultmap;
    
}
      
    
}