objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract_Committee_Submittal__c.object
<CustomObject>
    <fields>
        <fullName>Are_the_Products_accurate__c</fullName>
        <label>Are the Products accurate?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the Project associated with the CC Submittal- A project must be created prior to a development spending or contract execution request is submitted.</inlineHelpText>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>AcctSeed__Project__c.AcctSeed__Opportunity__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Opportunity__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Contract and Development Approvals</relationshipLabel>
        <relationshipName>Contract_Committee_Submittals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract and Development Approval</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Contract and Development Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract and Development Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Project_Products__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Product2.Status__c</field>
                <operation>equals</operation>
                <value>1- Standard, 2- CC Approved for Sale, 3- Project Specific Approved</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Project Products</relationshipLabel>
        <relationshipName>Project_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Products</relationshipLabel>
        <relationshipName>Project_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Enter the quantity of the product on this project</inlineHelpText>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup the site the product is related to</inlineHelpText>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Site__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Project Products</relationshipLabel>
        <relationshipName>Project_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Product</label>
    <nameField>
        <displayFormat>PP-{000000000}</displayFormat>
        <label>Project Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/clsCCSubProducts.cls
public with sharing class clsCCSubProducts {
	
	// Controller extension for vfCCSubProducts.page.  Provides mechanism to display Opportunity Products
	// on the Contract Committee Submittal detail page.
	
	List<Project_Products__c> productList = new List<Project_Products__c>();
	public Id ccSubId {get; set;}
	public Contract_Committee_Submittal__c ccSub {get; set;}
    
    public clsCCSubProducts(ApexPages.StandardController controller) {
        
		ccSubId = controller.getrecord().Id;
		ccSub = new Contract_Committee_Submittal__c();
		ccSub = [select Id, Project__c, Are_the_Products_accurate__c from Contract_Committee_Submittal__c where Id = :ccSubId limit 1];
		if (ccSub.Project__c != null) {
			productList = [select Id, Project__c, Product__r.Name, Quantity__c, Site__c, Site__r.Name, Product__r.Family from Project_Products__c where Project__c = :ccSub.Project__c];
		}
    }
    
    public List<Project_Products__c> getProducts() {
		return productList;
	}
	
	/*
	public Boolean accurateProducts {get; set;}
	
	public PageReference verifyProducts() {
		
		if (accurateProducts) {
			ccSub.Are_the_Products_accurate__c = 'Yes';
		} else {
			ccSub.Are_the_Products_accurate__c = 'No';
		}
		
		try {
			update ccSub;
		} catch(Exception e) {
			system.debug('*****Unable to update Contract Committee Submittal, error = ' + e.getMessage());
		}
		
		return null;
	}
	*/
}