objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Inverter_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Date of Inverter Delivery</inlineHelpText>
        <label>Inverter Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Module_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Module Delivery Date</inlineHelpText>
        <label>Module Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Racking_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Racking Delivery Date</inlineHelpText>
        <label>Racking Delivery Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ProjectDeadline__c.object
<CustomObject>
    <fields>
        <fullName>AssociatedMilestone__c</fullName>
        <inlineHelpText>Milestone that the deadline is associated with.</inlineHelpText>
        <label>Associated Milestone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Intx App Submitted</fullName>
                </value>
                <value>
                    <fullName>Interconnection Study Received Date</fullName>
                </value>
                <value>
                    <fullName>ISA Date</fullName>
                </value>
                <value>
                    <fullName>25% Payment Date</fullName>
                </value>
                <value>
                    <fullName>75% Payment Date</fullName>
                </value>
                <value>
                    <fullName>Utility Design Completion</fullName>
                </value>
                <value>
                    <fullName>Utility Construction Completion</fullName>
                </value>
                <value>
                    <fullName>PB9 CC Approval Date</fullName>
                </value>
                <value>
                    <fullName>Handoff Date</fullName>
                </value>
                <value>
                    <fullName>EPC Signed</fullName>
                </value>
                <value>
                    <fullName>FNTP Date</fullName>
                </value>
                <value>
                    <fullName>50% Set Completed</fullName>
                </value>
                <value>
                    <fullName>EPC- LOI</fullName>
                </value>
                <value>
                    <fullName>CD IFR</fullName>
                </value>
                <value>
                    <fullName>CD IFP</fullName>
                </value>
                <value>
                    <fullName>CD IFC</fullName>
                </value>
                <value>
                    <fullName>Building Permit</fullName>
                </value>
                <value>
                    <fullName>Module Delivery Date</fullName>
                </value>
                <value>
                    <fullName>Inverter Delivery Date</fullName>
                </value>
                <value>
                    <fullName>Transformer/SWGear Delivery Date</fullName>
                </value>
                <value>
                    <fullName>Delivery of LLTI MV/AC Equip</fullName>
                </value>
                <value>
                    <fullName>Racking Delivery Date</fullName>
                </value>
                <value>
                    <fullName>Energy Storage Unit Delivery Date</fullName>
                </value>
                <value>
                    <fullName>Mobilization Date</fullName>
                </value>
                <value>
                    <fullName>Mechanical Completion</fullName>
                </value>
                <value>
                    <fullName>PTO Date</fullName>
                </value>
                <value>
                    <fullName>Substantial Completion</fullName>
                </value>
                <value>
                    <fullName>Final Completion</fullName>
                </value>
                <value>
                    <fullName>CUSTOM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DeadlineDate__c</fullName>
        <inlineHelpText>Date of the Project Deadline</inlineHelpText>
        <label>Deadline Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DeadlineDescription__c</fullName>
        <label>Deadline Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Site__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Project Deadlines</relationshipLabel>
        <relationshipName>Project_Deadlines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Deadline</label>
    <nameField>
        <displayFormat>PD-{0000000}</displayFormat>
        <label>Project Deadline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Deadlines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>BuildingPermitObtainedDate__c</fullName>
        <inlineHelpText>Date Building Permit Obtained</inlineHelpText>
        <label>Building Permit Obtained Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CD_Forecast_Release_Date__c</fullName>
        <inlineHelpText>Forecasted Date of Construction Set Release- ISSUED FOR REVIEW</inlineHelpText>
        <label>CD IFR Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CD_IFC_Release_Date__c</fullName>
        <inlineHelpText>Construction Set Release Date - ISSUED FOR CONSTRUCTION</inlineHelpText>
        <label>CD IFC Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CD_IFP_Date__c</fullName>
        <description>Release date of CD Issued For Permit Set.</description>
        <inlineHelpText>Release date of CD Issued For Permit Set.</inlineHelpText>
        <label>CD IFP Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deadline_Date__c</fullName>
        <inlineHelpText>Are there any deadlines in the contract? Specify any deadline dates here.</inlineHelpText>
        <label>Deadline Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deadline_Description__c</fullName>
        <inlineHelpText>Description of the deadline date: What entity is the deadline for and what happens after that date?
Required when there is a deadline date filled in.</inlineHelpText>
        <label>Deadline Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EPC_Signed_Date__c</fullName>
        <label>EPC Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Energy_Storage_Unit_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or Actual delivery date of the Energy Storage Unit</inlineHelpText>
        <label>Energy Storage Unit Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FNTP_Date__c</fullName>
        <label>FNTP Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Final_Completion__c</fullName>
        <description>date field used by OPS</description>
        <label>Final Completion</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Handoff_Date__c</fullName>
        <inlineHelpText>Date Site was handed off to Operations</inlineHelpText>
        <label>Handoff Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ISA_Received_Date__c</fullName>
        <label>ISA Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interconnection_App_Submitted_Date__c</fullName>
        <label>Interconnection App Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inverter_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Inverter delivery</inlineHelpText>
        <label>Inverter Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LNTP_Date__c</fullName>
        <inlineHelpText>Only required for non-Cash or 3rd Party Financed projects</inlineHelpText>
        <label>LNTP Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MarkettoOwnerDate__c</fullName>
        <inlineHelpText>Date that 7C has been submitted, and project is ready to market to Owner</inlineHelpText>
        <label>7C Submittal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mobilization_Date__c</fullName>
        <label>Mobilization Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Module_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Module delivery.</inlineHelpText>
        <label>Module Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Comments_on_Schedule__c</fullName>
        <inlineHelpText>Explanation as to why key milestone date has changed (Project Kickoff, Handoff, Mobilization, Mechanical Completion, PTO, Substantial Completion, 50% Set, CD IFR, CD IFC) . Required when changing any of these dates.</inlineHelpText>
        <label>New Comments on Schedule</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_Record_Type__c</fullName>
        <description>pulls over the name of the related opportunity record type, used mostly for reporting not on layouts.</description>
        <formula>Opportunity__r.Record_Type_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>pulls over the name of the related opportunity record type, used mostly for reporting not on layouts.</inlineHelpText>
        <label>Opportunity Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PB9CCApprovalDate__c</fullName>
        <description>Development Only</description>
        <inlineHelpText>Date Contracts Committee approved project at PB 9</inlineHelpText>
        <label>PB9 CC Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PTO_Date__c</fullName>
        <inlineHelpText>Permission to Operate, A letter from the Utility defines this date. usually means Placed in Service.</inlineHelpText>
        <label>PTO Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductDeliveryDateUpdated__c</fullName>
        <inlineHelpText>Date any Milestone Date is Updated- If no update is needed, enter today&apos;s date so the Project Team knows you looked at the field.</inlineHelpText>
        <label>Milestone Dates Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Kickoff_Date_editable__c</fullName>
        <description>Uses a field update to pull the project kickoff date instead of a formula field. Allows it to be edited by engineer managers in special cases.</description>
        <inlineHelpText>Pull the Kickoff date from the Project. May be edited by Engineer Managers</inlineHelpText>
        <label>Project Kickoff Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Racking_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Racking delivery.</inlineHelpText>
        <label>Racking Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Substantial_Completion_Date__c</fullName>
        <inlineHelpText>Date where all components of the generation system are installed and connected. Electrical completion, or a COC from the AHJ, usually means &quot;ready for intended use&quot;.</inlineHelpText>
        <label>Mechanical Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Substantial_Completion_NEW__c</fullName>
        <inlineHelpText>Contractually issued after the performance testing is successful.</inlineHelpText>
        <label>Substantial Completion</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Switchboard_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Switchboard delivery.</inlineHelpText>
        <label>Switchboard Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Switchgear_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Switchgear delivery.</inlineHelpText>
        <label>Switchgear Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transformer_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or actual date of Transformer delivery.</inlineHelpText>
        <label>Transformer Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UtilityConstructionCompletionDate__c</fullName>
        <inlineHelpText>Date Utility Construction is Complete</inlineHelpText>
        <label>Utility Construction Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UtilityDesignCompletionDate__c</fullName>
        <inlineHelpText>Date Utility Design will be complete</inlineHelpText>
        <label>Utility Design Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X25PaymentDate__c</fullName>
        <inlineHelpText>Date 25% payment was made to the utility</inlineHelpText>
        <label>25% Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X50_Forecast_Release_Date__c</fullName>
        <description>Formerly Development Plan Set Complete/50% Set Date, changed 5/20/20</description>
        <inlineHelpText>Forecasted Date of 50% Set Release until the actual date of release</inlineHelpText>
        <label>Bid Set Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X50_Set_Completed__c</fullName>
        <inlineHelpText>Actual Date of 50% Set Release.</inlineHelpText>
        <label>50% Set Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X75PaymentDate__c</fullName>
        <inlineHelpText>Date 75% payment was made to the utility</inlineHelpText>
        <label>75% Payment Date</label>
        <type>Date</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateMilestoneDates1.cls
public with sharing class UpdateMilestoneDates1
{

    //public String objectsList { get; set; }
    
    public UpdateMilestoneDates1() {

    }
    public ApexPages.StandardSetController stdSetmilestone;
    public List<Site__c> selectedSites;
    private String listViewFilterId1;
    public String selectedsiteid {get;set;}
    public Boolean showonsiterecordtype {get; set;}
    public Boolean showsite {get; set;}

           
    private String siteId;
    public List<Site__c> lstsiteQuery{get;set;}
    public List<ProjectDeadline__c> lstprojdeadlineQuery{get;set;}
    public List<Site__c> lstsiteQuery1{get;set;}
    public List<ProjectDeadline__c> lstprojdeadlineQuery1{get;set;}
    public List<wrapperSite> siteList {get; set;}
    public List<wrapperSite> projdeadList {get; set;}
    public class wrapperSite
      {
        public Site__c site {get; set;}
        public ProjectDeadline__c projdead {get; set;}
        public List<ProjectDeadline__c> projdeadList {get; set;}
        public Boolean selected {get; set;}        
        public wrapperSite(Site__c b,ProjectDeadline__c  bl) 
            {
                site= b;
                projdead=bl;
                selected = false;
            }
      } 
      
     /** public PageReference siteSelected() 
      {
        List<Site__c> selectedSites= new List<Site__c>();
        system.debug('the selected rows'+sitelist);
        for(wrapperSite csite: siteList) 
        
          {
          system.debug('the selected rows'+csite);
                if(csite.selected == true) 
                { 
                    selectedSites.add(csite.site);
                    system.debug('Select billing - '+csite.site.id);
                }
          }
         return null;
      }**/
     public UpdateMilestoneDates1(ApexPages.StandardSetController stdSetmilestone)
     {
        this.stdSetmilestone= stdSetmilestone;
        showsite=false;
        showonsiterecordtype =false;
        system.debug('UpdateMilestoneDates method');
        List<Site__c>selectedSites= stdSetmilestone.getSelected();
        system.debug('List'+stdSetmilestone.getSelected());
        system.debug('List size'+selectedSites.size());
        siteList= new List<wrapperSite> ();
        projdeadList = new List<wrapperSite> ();
        lstsiteQuery=new List<Site__c>();
        lstprojdeadlineQuery=new List<ProjectDeadline__c>();
        Site__c theSite = new Site__c();
        ProjectDeadline__c theProjectDeadline = new ProjectDeadline__c();
        /**lstsiteQuery=[select Name,MarkettoOwnerDate__c,PB9CCApprovalDate__c,Switchgear_Delivery_Date__c ,Handoff_Date__c,ISA_Received_Date__c,X25PaymentDate__c,id,X75PaymentDate__c,UtilityDesignCompletionDate__c,CD_Forecast_Release_Date__c,CD_IFC_Release_Date__c,EPC_Signed_Date__c,FNTP_Date__c,ProductDeliveryDateUpdated__c ,BuildingPermitObtainedDate__c,Mobilization_Date__c,Energy_Storage_Unit_Delivery_Date__c,Racking_Delivery_Date__c,Module_Delivery_Date__c,Inverter_Delivery_Date__c,Switchboard_Delivery_Date__c,Substantial_Completion_Date__c,PTO_Date__c,Substantial_Completion_NEW__c,Final_Completion__c,Deadline_Date__c,Deadline_Description__c from Site__c where id=:selectedsiteid]; 
        lstprojdeadlineQuery=[select AssociatedMilestone__c,DeadlineDate__c,DeadlineDescription__c,id,Site__c,Name from ProjectDeadline__c where Site__c =:selectedsiteid];     
        for(integer i=0;i<lstsiteQuery.size();i++) 
        {        
            theSite = lstsiteQuery[i];
            if(lstprojdeadlineQuery.size()>0){
                for(integer j=0;j<lstprojdeadlineQuery.size();j++)
                {
                    theProjectDeadline = lstprojdeadlineQuery[j];
                    if(theSite.id==theProjectDeadline.Site__c)
                    {
                        siteList.add(new wrapperSite(theSite ,theProjectDeadline));
                    }
                }
                
            }
            else{                
                siteList.add(new wrapperSite(theSite ,new ProjectDeadline__c()));
            }  
        }*/  
    }       
  
  public List<Site__c> SiteTemp = new List<Site__c>(); 
   
  public List<SelectOption> Sitelist1 
   
    {
        get
        {
            List<Site__c> SiteTemp = [select id,Name from Site__c where id IN : (List<Site__c>) stdSetmilestone.getSelected()];
            if(SiteTemp.Size()>0)
            {
                Sitelist1 = new List<SelectOption>();
                Sitelist1.add(new SelectOption('---','Pick a record'));
                for(Site__c site : SiteTemp)
                {
                    Sitelist1.add(new SelectOption(site.id,site.Name));
                }
            }
            return Sitelist1;
        }
        set;
    }
   public void getsiterecords()
   {
       Site__c theSite = new Site__c();
       ProjectDeadline__c theProjectDeadline = new ProjectDeadline__c();
       lstsiteQuery1=new List<Site__c>();
       lstprojdeadlineQuery1=new List<ProjectDeadline__c>();
       system.debug('selectedsite  is ' +selectedsiteid);
       
       lstsiteQuery=[select Name,MarkettoOwnerDate__c,Project_Kickoff_Date_editable__c,X50_Forecast_Release_Date__c ,New_Comments_on_Schedule__c,Interconnection_App_Submitted_Date__c,LNTP_Date__c,X50_Set_Completed__c,Opportunity_Record_Type__c,CD_IFP_Date__c,PB9CCApprovalDate__c,Switchgear_Delivery_Date__c ,UtilityConstructionCompletionDate__c,Handoff_Date__c,ISA_Received_Date__c,X25PaymentDate__c,id,X75PaymentDate__c,UtilityDesignCompletionDate__c,Transformer_Delivery_Date__c ,CD_Forecast_Release_Date__c,CD_IFC_Release_Date__c,EPC_Signed_Date__c,FNTP_Date__c,ProductDeliveryDateUpdated__c ,BuildingPermitObtainedDate__c,Mobilization_Date__c,Energy_Storage_Unit_Delivery_Date__c,Racking_Delivery_Date__c,Module_Delivery_Date__c,Inverter_Delivery_Date__c,Switchboard_Delivery_Date__c,Substantial_Completion_Date__c,PTO_Date__c,Substantial_Completion_NEW__c,Final_Completion__c,Deadline_Date__c,Deadline_Description__c from Site__c where id=:selectedsiteid]; 
       lstprojdeadlineQuery=[select AssociatedMilestone__c,DeadlineDate__c,DeadlineDescription__c,id,Site__c,Name,RelatedMilestoneDate__c,Mitigation_Plan__c from ProjectDeadline__c where Site__c =:selectedsiteid];
       if(lstsiteQuery.Size()>0)
       {
           theSite=lstsiteQuery[0];
           
           
           system.debug('Thesite  is ' +theSite);
           system.debug('Thesite opportunity recordtype  is ' +theSite.Opportunity_Record_Type__c);
           if(theSite.Opportunity_Record_Type__c=='captive/onsite')
           {
                 showsite=true;
                 showonsiterecordtype=false;
                 system.debug('showsite Value'+showsite+' record type'+showonsiterecordtype);
             
                   if(lstprojdeadlineQuery.size()>0)
                   {
                   projdeadList.clear();
                   for(integer j=0;j<lstprojdeadlineQuery.size();j++)
                        {
                            theProjectDeadline = lstprojdeadlineQuery[j];
                            if(theSite.id==theProjectDeadline.Site__c)
                            {
                                siteList.clear();
                                siteList.add(new wrapperSite(theSite ,theProjectDeadline));
                                projdeadList.add(new wrapperSite(theSite ,theProjectDeadline));
                                
                            }
                        }
                        
                    }
                    else{
                        projdeadList.clear();
                        siteList.clear();
                        siteList.add(new wrapperSite(theSite ,new ProjectDeadline__c()));
                        projdeadList.add(new wrapperSite(theSite ,new ProjectDeadline__c()));
                        system.debug('List' +siteList);
                    }
            } 
            else
            {
               
              showsite=false;
              showonsiterecordtype=true;
              system.debug('showsite Value'+showsite+' record type'+showonsiterecordtype);
               theSite=lstsiteQuery[0];
               system.debug('Thesite  is ' +theSite);
               if(lstprojdeadlineQuery.size()>0)
                   {
                       projdeadList.clear();
                       for(integer j=0;j<lstprojdeadlineQuery.size();j++)
                            {
                                theProjectDeadline = lstprojdeadlineQuery[j];
                                if(theSite.id==theProjectDeadline.Site__c)
                                    {
                                        siteList.clear();
                                        siteList.add(new wrapperSite(theSite ,theProjectDeadline));
                                        projdeadList.add(new wrapperSite(theSite ,theProjectDeadline));
                        
                                    }
                            }
                
                }
               else{
                    projdeadList.clear();
                    siteList.clear();
                    siteList.add(new wrapperSite(theSite ,new ProjectDeadline__c()));
                    projdeadList.add(new wrapperSite(theSite ,new ProjectDeadline__c()));
                    system.debug('List' +siteList);   
                   }
            }
        
        }
    }
        
       
       
            
       
    Public pagereference Save() 
    {       
        System.debug('Site List' +siteList);
        System.debug('Site List' +siteList.size());
        if(siteList.size()>0)
        {
            update lstsiteQuery;
            update lstprojdeadlineQuery;                          
        }
         ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Record has been saved successfully'));
    
        return null;
    }
}