objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Development_Only__c</fullName>
        <label>Non Revenue Generating Project</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_Bid_Date__c</fullName>
        <label>Expected Bid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Government - Small</fullName>
                </value>
                <value>
                    <fullName>Utility Scale</fullName>
                </value>
                <value>
                    <fullName>ES Ground</fullName>
                </value>
                <value>
                    <fullName>Non ES Ground</fullName>
                </value>
                <value>
                    <fullName>ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Non ES Built Environment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>DG Solar</fullName>
                </value>
                <value>
                    <fullName>DG Wind</fullName>
                </value>
                <value>
                    <fullName>DG SAS</fullName>
                </value>
                <value>
                    <fullName>LSR PV</fullName>
                </value>
                <value>
                    <fullName>Bulk ES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PSD__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <label>Revision Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Building_Owner__c</fullName>
        <defaultValue>&apos;N/A&apos;</defaultValue>
        <inlineHelpText>Input N/A if Building Owner should not be in title block</inlineHelpText>
        <label>Building Owner</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_Type__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Existing Rooftop</fullName>
                </value>
                <value>
                    <fullName>New Construction</fullName>
                </value>
                <value>
                    <fullName>Ground</fullName>
                </value>
                <value>
                    <fullName>Carport</fullName>
                </value>
                <value>
                    <fullName>Landfill</fullName>
                </value>
                <value>
                    <fullName>Variable Solution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <formula>IF(ISPICKVAL( Designer__c  , &apos;Internal&apos;), 50 *  Hours__c , IF(ISPICKVAL(Designer__c , &apos;Outsource&apos;),  Design_Partner__r.Hourly_Rate__c *Hours__c, 0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <inlineHelpText>Name to be displayed in the title block</inlineHelpText>
        <label>Project Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_Since_Status_Change__c</fullName>
        <formula>TODAY() -  Status_Change__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Since Status Change</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Design_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Design Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Pre-Sales Designs</relationshipLabel>
        <relationshipName>Pre_Sales_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Designer__c</fullName>
        <label>Designer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Outsource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Drawings_Already_Exist__c</fullName>
        <label>Drawings Already Exist</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>No - Aerial Sufficient</fullName>
                </value>
                <value>
                    <fullName>Yes - Attached</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <defaultValue>TODAY()+2</defaultValue>
        <inlineHelpText>L1 - Minimum 2 Days
L2 - Minimum 5 Days
L3 - Minimum 14-21 Days</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Electrical_Sizing_Strategy__c</fullName>
        <inlineHelpText>Describe existing electrical equipment on site including possible interconnection locations.</inlineHelpText>
        <label>Existing Electrical Info and Location</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inverters__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inverter Type 1</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Pre-Sales Designs (Inverters)</relationshipLabel>
        <relationshipName>Pre_Sales_Designs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <formula>TEXT( Opportunity__r.Account.Job_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Job Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Module_Location_Description__c</fullName>
        <label>Module Location Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Modules__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module Type 1</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Pre-Sales Designs</relationshipLabel>
        <relationshipName>Pre_Sales_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Buildings__c</fullName>
        <label>Number of Buildings</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Hold_Notes__c</fullName>
        <label>On Hold Notes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>The opportunity that the Pre-Sales Design is related too.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Sales Designs</relationshipLabel>
        <relationshipName>Pre_Sales_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_Level_Needed__c</fullName>
        <label>Proposal Level Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>L0</fullName>
                </value>
                <value>
                    <fullName>L1</fullName>
                </value>
                <value>
                    <fullName>L2</fullName>
                </value>
                <value>
                    <fullName>L3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposed_System_Tilt_Angle__c</fullName>
        <label>Proposed System Tilt Angle</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Racking_System__c</fullName>
        <label>Racking System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Carport</fullName>
                </value>
                <value>
                    <fullName>Flat Roof Tilt-Up</fullName>
                </value>
                <value>
                    <fullName>Flush Mount</fullName>
                </value>
                <value>
                    <fullName>Ground Tilt-Up</fullName>
                </value>
                <value>
                    <fullName>On-Energy</fullName>
                </value>
                <value>
                    <fullName>SunLink</fullName>
                </value>
                <value>
                    <fullName>Tracker</fullName>
                </value>
                <value>
                    <fullName>Sunlink Ground</fullName>
                </value>
                <value>
                    <fullName>SolarFlex Ground</fullName>
                </value>
                <value>
                    <fullName>ULA Ground</fullName>
                </value>
                <value>
                    <fullName>Other Ground</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Roof_Space_Off_Limits__c</fullName>
        <inlineHelpText>Describe any roof space that will be off limits due to shade, vents, etc.</inlineHelpText>
        <label>Roof Space Off Limits</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Roof_Type__c</fullName>
        <label>Roof Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shading_Notes__c</fullName>
        <label>General Design Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Site_Address2__c</fullName>
        <inlineHelpText>When multiple sites add include a name of the site which will help to designate which PSD belongs to which site. 
When single site just use main site addresses.</inlineHelpText>
        <label>Site Name/Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status_Change__c</fullName>
        <label>Status Change</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Design</fullName>
                </value>
                <value>
                    <fullName>Draft Layout</fullName>
                </value>
                <value>
                    <fullName>Approved Pending Investigation</fullName>
                </value>
                <value>
                    <fullName>Design Approved for Sale</fullName>
                </value>
                <value>
                    <fullName>Revisions Needed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Orientation_Azimuth__c</fullName>
        <label>System Orientation/Azimuth</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>System_Sizing_Strategy__c</fullName>
        <inlineHelpText>Maximum modules possible or notate a specific system size.</inlineHelpText>
        <label>System Sizing Strategy</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Today__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Today</label>
        <type>Date</type>
    </fields>
    <label>Pre-Sales Design</label>
    <nameField>
        <displayFormat>P-SD-{000000}</displayFormat>
        <label>Pre-Sales Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Sales Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Project__c.object
<CustomObject>
    <description>Project Management</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Rebate section - due date.</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Buildings__c</fullName>
        <label>Number of Buildings</label>
        <summaryForeignKey>Building__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N300000021XqLEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SFDCProject</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFDCProjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/printDesign.cls
public class printDesign {

    ApexPages.StandardController stdController;
    private final SFDC_Project__c p;  
    
  public printDesign(ApexPages.StandardController stdController) {
    this.p = (SFDC_Project__c)stdController.getRecord(); 
    this.stdController = stdController;
    }
    private PSD__c[] psds;
  public PSD__c getPSD(){
    psds = [select p.Today__c, p.System_Sizing_Strategy__c, p.System_Orientation_Azimuth__c, p.SystemModstamp, 
        p.Status__c, p.Status_Change__c, p.Site_Address2__c, p.Shading_Notes__c, p.Roof_Type__c, 
        p.Roof_Space_Off_Limits__c, p.Racking_System__c, p.Proposed_System_Tilt_Angle__c, 
        p.Proposal_Level_Needed__c, p.Opportunity__c, p.On_Hold_Notes__c, p.Number_of_Buildings__c, 
        p.Name, p.Modules__c, p.Module_Location_Description__c, p.Job_Type__c, p.Inverters__c, 
        p.Id, p.Hours__c, p.Electrical_Sizing_Strategy__c, p.Due_Date__c, p.Drawings_Already_Exist__c, 
        p.Designer__c, p.Design_Partner__c, p.Days_Since_Status_Change__c, p.Customer_Name__c, p.CreatedDate, 
        p.Cost__c, p.Building_Type__c, p.Building_Owner__c, p.Additional_Notes__c from PSD__c p 
        where Opportunity__c = :p.Opportunity__c ORDER BY CreatedDate DESC LIMIT 1];    
    if(psds.size() > 0){
      return psds[0];
    } else {
      return null;
    }    
  }
  public static testmethod void invoiceTest() {       
        SFDC_Project__c p = ProjectTestOld.setupTestProj();
        RecordType ContentRT = [select Id FROM RecordType WHERE name='O&M Opportunity'];
        Opportunity opp = [select Id, StageName from Opportunity where Id = :p.Opportunity__c ];
       opp.StageName = 'Qualified';
      //  opp.Development_Only__c = 'No';
      //  opp.Expected_Bid_Date__c = system.today();
      //  opp.of_Sites__c = 1;
        
        update opp;
        PSD__c psd = new PSD__c(Opportunity__c = p.Opportunity__c,
                    Customer_Name__c = 'Test',
                    Proposal_Level_Needed__c = 'L1',
                    Due_Date__c = System.today()+20
                    );

        PageReference pageRef = Page.printDesign;
        Test.setCurrentPage(pageRef);
               
        //Set Page Parameters
        ApexPages.StandardController con = new ApexPages.StandardController(new SFDC_Project__c());
    ApexPages.StandardController con2 = new ApexPages.StandardController(p);
    
        ApexPages.currentPage().getParameters().put('id', p.Id); 
        printDesign ext = new printDesign(con);
        //Call all methods on New page 
      ext.getPSD();
      
    insert psd;
    printDesign ext2 = new printDesign(con2);  
      ext2.getPSD();                 
    } 
}