objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Approximate_Install_Date__c</fullName>
        <description>This is the approximate date that customer expects that installation will begin.</description>
        <inlineHelpText>Required at Project Awarded- This is the approximate date that customer expects that installation will begin.</inlineHelpText>
        <label>Approximate Install Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Rebate__c</fullName>
        <description>This is the dollar value of the rebate we expect project to be eligable for.</description>
        <inlineHelpText>Expected Rebate Amount- required at Project Awarded. Enter $0 if rebate is not applicable</inlineHelpText>
        <label>Expected Rebate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <inlineHelpText>Denotes the Financing that was selected when the contract was signed.</inlineHelpText>
        <label>Final Financing Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PPA – Borrego</fullName>
                </value>
                <value>
                    <fullName>PPA - 3rd Party</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Lease</fullName>
                </value>
                <value>
                    <fullName>HELOC</fullName>
                </value>
                <value>
                    <fullName>Bond</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PPA</fullName>
                </value>
                <value>
                    <fullName>PACE</fullName>
                </value>
                <value>
                    <fullName>TEML (tax-exempt municipal lease)</fullName>
                </value>
                <value>
                    <fullName>GO Bond</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inverter_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Date of Inverter Delivery</inlineHelpText>
        <label>Inverter Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Module_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Module Delivery Date</inlineHelpText>
        <label>Module Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Contract_System_Size__c</fullName>
        <inlineHelpText>Original Contract System Size in watts- Proposed or executed Contract System Size</inlineHelpText>
        <label>PV System Size - DC (W)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prevailing_Wage__c</fullName>
        <inlineHelpText>Does the contract include Prevailing Wage? Required at Contract Signing</inlineHelpText>
        <label>Prevailing Wage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal_Submitted_Date__c</fullName>
        <label>First Proposal Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Proposed_System_Size__c</fullName>
        <inlineHelpText>Current proposed system size in watts</inlineHelpText>
        <label>Proposed System Size (watts)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Racking_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated Racking Delivery Date</inlineHelpText>
        <label>Racking Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>System_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The individual or entity that will own the system.</inlineHelpText>
        <label>System Owner-Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (System Owner)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Exemption__c</fullName>
        <inlineHelpText>Will the contract be Tax Exempt? For use by Accounting when purchasing materials</inlineHelpText>
        <label>Tax Exemption Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Exempt</fullName>
                </value>
                <value>
                    <fullName>Non-Exempt</fullName>
                </value>
                <value>
                    <fullName>Varies</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Utility_Rate__c</fullName>
        <inlineHelpText>What is the host customer&apos;s or offtaker&apos;s current utility rate? You can find this on their bill.</inlineHelpText>
        <label>Current Utility Rate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E A</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E AL-TOU</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E AL-TOU DGR</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E PA</fullName>
                </value>
                <value>
                    <fullName>SDG&amp;E PA-T-1</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A6</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A-10</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E A-10 TOU</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E E-19</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E E-20</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-1</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-4</fullName>
                </value>
                <value>
                    <fullName>PG&amp;E AG-5</fullName>
                </value>
                <value>
                    <fullName>SCE GS-1</fullName>
                </value>
                <value>
                    <fullName>SCE GS-2</fullName>
                </value>
                <value>
                    <fullName>SCE GS-2 TOU</fullName>
                </value>
                <value>
                    <fullName>SCE GS-3-A</fullName>
                </value>
                <value>
                    <fullName>SCE-GS-3-B</fullName>
                </value>
                <value>
                    <fullName>SCE-GS-3-R</fullName>
                </value>
                <value>
                    <fullName>SCE TOU-8-A</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-B</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-CPP</fullName>
                </value>
                <value>
                    <fullName>SCE-TOU-8-R</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-1</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-2</fullName>
                </value>
                <value>
                    <fullName>SMUD GS-TOU-3</fullName>
                </value>
                <value>
                    <fullName>LADWP A1A</fullName>
                </value>
                <value>
                    <fullName>LADWP A2A</fullName>
                </value>
                <value>
                    <fullName>NSTAR B7-TOU</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Won_Loss_Explanation__c</fullName>
        <inlineHelpText>Why did we win or lose the Opportunity? Required when Stage = Closed Lost or Contract Signed</inlineHelpText>
        <label>Won/Loss Explanation</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Production_Modeling__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Production Models</relationshipLabel>
        <relationshipName>Production_Models</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person_Responsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enter the person you would like to perform the modeling</inlineHelpText>
        <label>Person Responsible</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Resources Group, Engineer, CTO</value>
            </filterItems>
            <filterItems>
                <field>User.Title</field>
                <operation>contains</operation>
                <value>Pre-Con</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Production_Modeling_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production_Modeling_Stage__c</fullName>
        <inlineHelpText>Enter the production modeling stage.</inlineHelpText>
        <label>Production Modeling Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>50% Design</fullName>
                </value>
                <value>
                    <fullName>CD IFR</fullName>
                </value>
                <value>
                    <fullName>Record Drawing</fullName>
                </value>
                <value>
                    <fullName>Performance Test</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Guarantee model</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>shows status of the request itself not the actual completed production model</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Standards__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Buyer/Owner&apos;s Account for which the model is to be run. If the Buyer/Owner is not yet identified, select the Borrego Solar account.</inlineHelpText>
        <label>Standards</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Production Modeling</relationshipLabel>
        <relationshipName>Production_Modeling</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Production Modeling</label>
    <nameField>
        <label>Production Modeling Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Modeling</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PMsubmitandcancelrequesttestclass.cls
@isTest
public class PMsubmitandcancelrequesttestclass {
    
    //Test class for ProdModellightningcontroller apex class
    
    static testMethod void testMethod1() 
    {
        ASeedAccountingSettingsSetupTest.testDataSetup();
        
         Account acc = new Account(Name = 'nsvAccount');
          insert acc;
      
        
        
         Contact con = new Contact(FirstName = 'Generic', LastName = 'Technician', Title = 'Solar Tech', AccountId = acc.Id);
        insert con;
        
        
         Opportunity testOpportunity = new Opportunity(Name = 'Test test', AccountId = acc.Id, CloseDate = System.today(), Module_Delivery_Date__c =system.now().Date(),         
                Inverter_Delivery_Date__c =system.now().Date(), Racking_Delivery_Date__c =system.now().Date(), StageName = 'Prospecting', Amount = 500000, Proposed_System_Size__c = 10000,
                System_Owner__c = con.Id, Expected_Rebate__c = 0,Utility_Rate__c = 'N/A', Prevailing_Wage__c = 'No', Original_Contract_System_Size__c = 1000, 
                Type = 'Turnkey System', Approximate_Install_Date__c = System.today(),Won_Loss_Explanation__c='test',Tax_Exemption__c='Exempt', Proposal_Submitted_Date__c = System.today(), Financing__c = 'PPA', 
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Captive/OnSite').getRecordTypeId());
        insert testOpportunity;
        
        user ur = [select id from user limit 1];
        
         Production_Modeling__c PMtest = new Production_Modeling__c(Name = 'test test',Opportunity__c=testOpportunity.id,Person_Responsible__c=ur.Id,Production_Modeling_Stage__c='Other',Standards__c=acc.Id);
         insert PMtest;
        
         String result = ProdModellightningcontroller.PrdModSubmit(PMtest.id);
        
        
        
      
        
        
    }
    
    static testMethod void testMethod2() 
    {
        ASeedAccountingSettingsSetupTest.testDataSetup();
        
         Account acc = new Account(Name = 'nsvAccount');
          insert acc;
      
        
        
         Contact con = new Contact(FirstName = 'Generic', LastName = 'Technician', Title = 'Solar Tech', AccountId = acc.Id);
        insert con;
        
        
         Opportunity testOpportunity = new Opportunity(Name = 'Test test', AccountId = acc.Id, CloseDate = System.today(), Module_Delivery_Date__c =system.now().Date(),         
                Inverter_Delivery_Date__c =system.now().Date(), Racking_Delivery_Date__c =system.now().Date(), StageName = 'Prospecting', Amount = 500000, Proposed_System_Size__c = 10000,
                System_Owner__c = con.Id, Expected_Rebate__c = 0,Utility_Rate__c = 'N/A', Prevailing_Wage__c = 'No', Original_Contract_System_Size__c = 1000, 
                Type = 'Turnkey System', Approximate_Install_Date__c = System.today(),Won_Loss_Explanation__c='test',Tax_Exemption__c='Exempt', Proposal_Submitted_Date__c = System.today(), Financing__c = 'PPA', 
                RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Captive/OnSite').getRecordTypeId());
        insert testOpportunity;
        
        user ur = [select id from user limit 1];
        
         Production_Modeling__c PMtest = new Production_Modeling__c(Name = 'test test',Opportunity__c=testOpportunity.id,Person_Responsible__c=ur.Id,Production_Modeling_Stage__c='Other',Standards__c=acc.Id,Request_Status__c='Submitted');
         insert PMtest;
        
         String result1 = ProdModellightningcontroller.PrdModCancel(PMtest.id);
        
    
        
      
        
        
    }
    
    
    

}