objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Amount_yearly__c</fullName>
        <inlineHelpText>Total Yearly Amount of the Service Contract</inlineHelpText>
        <label>Contract Amount (yearly)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_for_Added_Landscaping_per_Visit__c</fullName>
        <label>Cost for Added Landscaping per Visit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_for_Added_Module_Washing_per_Wash__c</fullName>
        <label>Cost for Added Module Washing per Wash</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_for_Added_Snow_Removal_per_Visit__c</fullName>
        <label>Cost for Added Snow Removal per Visit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Equipment_Rental_Included1__c</fullName>
        <description>Uses Global Value Set - shared with Service Contract</description>
        <inlineHelpText>Determines whether equipment rentals are included as part of the contract or if they will be billable to the customer.</inlineHelpText>
        <label>Equipment Rental Included</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Equipment_Rental_Included</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalator_Details1__c</fullName>
        <description>uses Global Value set - shared with Service Contract</description>
        <label>Escalator Details</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Escalator_Details</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Escalator__c</fullName>
        <inlineHelpText>%/year</inlineHelpText>
        <label>Lease Escalator</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Guarantee_Start_Date__c</fullName>
        <label>Guarantee Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantee_Status__c</fullName>
        <label>Guarantee Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Active</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Internal_Prevailing_Wage__c</fullName>
        <description>Prevailing wage that is required to be paid to internal solar electricians</description>
        <inlineHelpText>Prevailing wage that is required to be paid to internal solar electricians</inlineHelpText>
        <label>Internal Prevailing Wage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Landscaping_Visits_per_Year__c</fullName>
        <label>Landscaping Visits per Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 Prepaid If Required</fullName>
                </value>
                <value>
                    <fullName>2 Prepaid If Required</fullName>
                </value>
                <value>
                    <fullName>3 Prepaid If Required</fullName>
                </value>
                <value>
                    <fullName>4 Prepaid If Required</fullName>
                </value>
                <value>
                    <fullName>1 Required</fullName>
                </value>
                <value>
                    <fullName>2 Required</fullName>
                </value>
                <value>
                    <fullName>3 Required</fullName>
                </value>
                <value>
                    <fullName>4 Required</fullName>
                </value>
                <value>
                    <fullName>Unlimited Prepaid</fullName>
                </value>
                <value>
                    <fullName>OnCall Billable</fullName>
                </value>
                <value>
                    <fullName>1 Required Billable</fullName>
                </value>
                <value>
                    <fullName>2 Required Billable</fullName>
                </value>
                <value>
                    <fullName>3 Required Billable</fullName>
                </value>
                <value>
                    <fullName>4 Required Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Link_to_Performance_Model__c</fullName>
        <label>Link to Performance Model</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Modules_Washings_per_Year__c</fullName>
        <label>Modules Washings per Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 Prepaid If Required</fullName>
                </value>
                <value>
                    <fullName>2 Prepaid If Required</fullName>
                </value>
                <value>
                    <fullName>3 Prepaid If Required</fullName>
                </value>
                <value>
                    <fullName>4 Prepaid If Required</fullName>
                </value>
                <value>
                    <fullName>1 Required</fullName>
                </value>
                <value>
                    <fullName>2 Required</fullName>
                </value>
                <value>
                    <fullName>3 Required</fullName>
                </value>
                <value>
                    <fullName>4 Required</fullName>
                </value>
                <value>
                    <fullName>Unlimited Prepaid</fullName>
                </value>
                <value>
                    <fullName>OnCall Billable</fullName>
                </value>
                <value>
                    <fullName>1 Required Billable</fullName>
                </value>
                <value>
                    <fullName>2 Required Billable</fullName>
                </value>
                <value>
                    <fullName>3 Required Billable</fullName>
                </value>
                <value>
                    <fullName>4 Required Billable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>O_M_Package__c</fullName>
        <label>O&amp;M Package</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reactive</fullName>
                </value>
                <value>
                    <fullName>T&amp;M</fullName>
                </value>
                <value>
                    <fullName>Preventative</fullName>
                </value>
                <value>
                    <fullName>Comprehensive</fullName>
                </value>
                <value>
                    <fullName>Basic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Options__c</fullName>
        <label>Payment Options</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Lump Sum</fullName>
                    <label>Anniversary in Advance</label>
                </value>
                <value>
                    <fullName>Anniversary Semi-Annual in Arrears</fullName>
                </value>
                <value>
                    <fullName>Annual in Advance - Jan to Dec</fullName>
                </value>
                <value>
                    <fullName>Arrears Per % of visits completed</fullName>
                </value>
                <value>
                    <fullName>Long-Term in Advance</fullName>
                </value>
                <value>
                    <fullName>Mid Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Monthly in Advance</fullName>
                </value>
                <value>
                    <fullName>Monthly in Arrears</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Advance</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Advance Equal Installments</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Arrears</fullName>
                </value>
                <value>
                    <fullName>Quarterly in Arrears Equal Installments</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual in Advance</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual in Arrears</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Penalty_Rate_kWh__c</fullName>
        <label>Penalty Rate ($/kWh)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_PM_Visits__c</fullName>
        <label>Primary PM Visits</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regional_Manager_Rate__c</fullName>
        <inlineHelpText>Hourly rate stated in contract</inlineHelpText>
        <label>Regional Manager Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reporting_Requirements__c</fullName>
        <label>Reporting Requirements</label>
        <length>131000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Secondary_PM_Visits__c</fullName>
        <label>Secondary PM Visits</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Snow_Removal_Included__c</fullName>
        <label>Snow Removal Included?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Yes_No</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solar_Electrician_1_OT_Rate__c</fullName>
        <inlineHelpText>Hourly OT rate stated in the Contract</inlineHelpText>
        <label>Solar Electrician 1 - OT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_1_Rate__c</fullName>
        <inlineHelpText>Hourly rate stated in the Contract</inlineHelpText>
        <label>Solar Electrician 1 Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_2_OT_Rate__c</fullName>
        <inlineHelpText>Hourly OT rate stated in the Contract</inlineHelpText>
        <label>Solar Electrician 2 - OT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Electrician_2_Rate__c</fullName>
        <inlineHelpText>Hourly rate stated in the Contract</inlineHelpText>
        <label>Solar Electrician 2 Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Engineer_Rate_OT_Rate__c</fullName>
        <inlineHelpText>Hourly OT rate stated in the Contract</inlineHelpText>
        <label>Solar Engineer Rate - OT Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solar_Engineer_Rate__c</fullName>
        <inlineHelpText>Hourly rate stated in the Contract</inlineHelpText>
        <label>Solar Engineer Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tariff__c</fullName>
        <label>Tariff</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Billable__c</fullName>
        <description>Designates If travel billable per the service contract, and how it should be billed if it is.</description>
        <inlineHelpText>Designates If travel billable per the service contract, and how it should be billed if it is.</inlineHelpText>
        <label>Travel Billable ?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1-way</fullName>
                </value>
                <value>
                    <fullName>2-way</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Travel_Billing_Cap_Hours__c</fullName>
        <description>maximum hours that can be billed for travel per contract</description>
        <inlineHelpText>maximum hours that can be billed for travel per contract</inlineHelpText>
        <label>Travel Billing Cap (Hours)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

globalValueSets/Equipment_Rental_Included.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>PM Only</fullName>
    </customValue>
    <masterLabel>Equipment Rental Included</masterLabel>
</GlobalValueSet>

globalValueSets/Escalator_Details.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Increases per calendar year</fullName>
    </customValue>
    <customValue>
        <fullName>Increases on anniversary date of contract</fullName>
    </customValue>
    <masterLabel>Escalator Details</masterLabel>
</GlobalValueSet>

globalValueSets/Yes_No.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>PM Only</fullName>
        <isActive>false</isActive>
        <label>PM Only</label>
    </customValue>
    <masterLabel>Yes/No</masterLabel>
</GlobalValueSet>

classes/createcontractfromopp.cls
public class createcontractfromopp {
      @Auraenabled
    public static List<Opportunity> createcontract(Id Oppid){
        
        List<Opportunity>  newlist = new List<Opportunity>();
            
            newlist=[select Id, Amount,AccountId,Payment_Options__c,O_M_Package__c,Escalator_Details1__c,Solar_Electrician_1_Rate__c,Solar_Electrician_1_OT_Rate__c,Solar_Electrician_2_Rate__c,Solar_Electrician_2_OT_Rate__c,Solar_Engineer_Rate__c,
            Solar_Engineer_Rate_OT_Rate__c,Internal_Prevailing_Wage__c,Travel_Billable__c,Travel_Billing_Cap_Hours__c,Equipment_Rental_Included1__c,Cost_for_Added_Landscaping_per_Visit__c,Cost_for_Added_Module_Washing_per_Wash__c,Cost_for_Added_Snow_Removal_per_Visit__c,
           Primary_PM_Visits__c,Secondary_PM_Visits__c,Modules_Washings_per_Year__c,Landscaping_Visits_per_Year__c,Snow_Removal_Included__c,Contract_Amount_yearly__c,Name,
           Guarantee_Start_Date__c,Guarantee_Status__c,Link_to_Performance_Model__c,Penalty_Rate_kWh__c,Escalator__c,Regional_Manager_Rate__c,Reporting_Requirements__c,
           Tariff__c,Preapproval_Level__c,HVAC_Included__c,Fire_Suppression_Included__c,X24_Hour_Response_kW__c,X48_Hour_Response_kW__c,X72_Hour_Response_kW__c,
           Thermal__c,VOC_IMP__c,IV_Curve__c,Transformer_DGA__c,Torque_Structural__c,Tier__c,Monitoring__c,Aerial_Thermal_Inspection__c,Material_and_Equipment_Mark_Up__c from opportunity where id=:Oppid];
        
         return newlist;

}
}