objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Development_Only__c</fullName>
        <label>Non Revenue Generating Project</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Expected_Bid_Date__c</fullName>
        <label>Expected Bid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>of_Sites__c</fullName>
        <description>used with roll up helper</description>
        <inlineHelpText>Manually entered # of Sites created in SF related to this opportunity</inlineHelpText>
        <label># of Sites</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PSD__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Notes__c</fullName>
        <label>Revision Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Pre-Sales Designs</relationshipLabel>
        <relationshipName>Pre_Sales_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <inlineHelpText>Name to be displayed in the title block</inlineHelpText>
        <label>Project Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Designer__c</fullName>
        <label>Designer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Outsource</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <defaultValue>TODAY()+2</defaultValue>
        <inlineHelpText>L1 - Minimum 2 Days
L2 - Minimum 5 Days
L3 - Minimum 14-21 Days</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>The opportunity that the Pre-Sales Design is related too.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Sales Designs</relationshipLabel>
        <relationshipName>Pre_Sales_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposal_Level_Needed__c</fullName>
        <label>Proposal Level Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>L0</fullName>
                </value>
                <value>
                    <fullName>L1</fullName>
                </value>
                <value>
                    <fullName>L2</fullName>
                </value>
                <value>
                    <fullName>L3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Change__c</fullName>
        <label>Status Change</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Design</fullName>
                </value>
                <value>
                    <fullName>Draft Layout</fullName>
                </value>
                <value>
                    <fullName>Approved Pending Investigation</fullName>
                </value>
                <value>
                    <fullName>Design Approved for Sale</fullName>
                </value>
                <value>
                    <fullName>Revisions Needed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Sales Design</label>
    <nameField>
        <displayFormat>P-SD-{000000}</displayFormat>
        <label>Pre-Sales Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Sales Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Pre_Sales_Design_Request_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this box is checked and the user has the Role of Applications Engineer, the user will be copied on all level L1 Pre Sales Design Request emails for their region.</description>
        <inlineHelpText>If the Role field is set to Applications Engineer, check this box to have this user copied on all level L1 Pre Sales Design Request emails for their region.</inlineHelpText>
        <label>Pre Sales Design Request Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Northern CA</fullName>
                </value>
                <value>
                    <fullName>Southern CA</fullName>
                </value>
                <value>
                    <fullName>New England</fullName>
                </value>
                <value>
                    <fullName>Mid Atlantic</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>MidWest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/psdUpdate.cls
public class psdUpdate {
   /* public static void addStatusDate(PSD__c[] psds) {
        for (PSD__c p:psds) {
            p.Status_Change__c = System.today();
        }
    }
    
    public static void emailPreSalesDesign(PSD__c[] psd) {
        
        //Send a design email request to the Design Partner for each PSD
        String emailBody;
        List<Id> conId = new List<Id>();
        for (Integer i=0; i<psd.size(); i++) {
            conId.add(psd[i].Contact__c);
        }
        Contact[] con = [select Id, Email from Contact where Id in:conId];
        Map<Id, Contact> conMap = new Map<Id, Contact>();
        for (Integer i=0; i<con.size(); i++) {
            conMap.put(con[i].Id, con[i]);
        }
        
        UserRole appRole = [select Id from UserRole where Name =:'Applications Engineer'];
        Id cuId = UserInfo.getUserId();
        User[] users = [select Id, UserRoleId, Email, Region__c, Pre_Sales_Design_Request_Email__c from User where Id =:cuId or UserRoleId =:appRole.Id];
        User cUser;
        List<User> appUser = new List<User>();
        for (Integer i=0; i<users.size(); i++) {
            if (users[i].Id == cuId) {
                cUser = users[i];
            }
            if (users[i].UserRoleId == appRole.Id) {
                appUser.add(users[i]);
            }
        }
        
        List<String> ccaddr = new List<String>();
        for (Integer i=0; i<appUser.size(); i++) {
            if ( (appUser[i].Region__c == cUser.Region__c) && (appUser[i].Pre_Sales_Design_Request_Email__c) ) {
                ccaddr.add(appUser[i].Email);
            }
        }
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        for (Integer i=0; i<psd.size(); i++) {
            emailBody = '\nBorrego Solar Systems has requested a layout.\n\n';
            emailBody += 'Project:  ' + psd[i].Customer_Name__c + '\n';
            emailBody += 'Due Date:  ' + psd[i].Due_Date__c.format() + '\n';
            emailBody += 'Notes:  ' + psd[i].Additional_Notes__c + '\n\n';
            emailBody += 'Access the design information here:\n';
            emailBody += 'https://na6.salesforce.com/' + psd[i].Id + '\n\n';
            mail.setSubject(psd[i].Customer_Name__c + ': Borrego Solar Systems has requested a layout');
            mail.setPlainTextBody(emailBody);
            mail.setTargetObjectId(psd[i].Contact__c);
            mail.setCcAddresses(ccaddr);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
        }
    }
    
    public static testMethod void psdTest(){
        User other = [select Id from User where Name = 'Michael Hall'];
        Account AccMake = new Account(Name = 'Knight - 2456', ShippingCity = 'Park City'); insert AccMake;
        Contact ConMake = new Contact(FirstName = 'Tom', LastName = 'Tuttle', AccountId = AccMake.Id, Email = 'tt@borregosolar.com.training');
        insert ConMake;
        RecordType ContentRT = [select Id FROM RecordType WHERE name='O&M Opportunity'];
        Opportunity OppMake = new Opportunity(OwnerId = other.Id, Name = 'Knight - 2456',AccountId = AccMake.Id,Type = 'Turnkey System',
                                                CloseDate = System.today(),StageName = 'Prospecting', of_Sites__c = 1,RecordTypeId = ContentRT.Id); insert OppMake;
        OppMake.StageName = 'Qualified'; update OppMake; //OppMake.Development_Only__c = 'No'; OppMake.Expected_Bid_Date__c = system.today(); 
        PSD__c psd = new PSD__c(Opportunity__c = OppMake.Id, Contact__c = ConMake.Id);
        insert psd;
        psd.Status__c = 'Submitted';
        psd.Proposal_Level_Needed__c = 'L1';
        psd.Designer__c = 'Outsource';
        update psd;
    }*/
}