objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Project_System_Size__c</fullName>
        <label>Current Project System Size (w)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offtaker_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Opportunity must have a Record Type of Offtaker.</inlineHelpText>
        <label>Offtaker Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Opportunity.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Offtaker</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Related Opportunities</relationshipLabel>
        <relationshipName>Child_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Contract_System_Size__c</fullName>
        <inlineHelpText>Original Contract System Size in watts- Proposed or executed Contract System Size</inlineHelpText>
        <label>PV System Size - DC (W)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vertical__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>What is the Vertical the Opportunity is in? Will determine the cost assumptions</inlineHelpText>
        <label>Vertical</label>
        <referenceTo>CostAssumption__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>DevelopmentSite</fullName>
        <active>true</active>
        <businessProcess>Development</businessProcess>
        <description>Use when developing land that will have an Offtaker</description>
        <label>Development</label>
    </recordTypes>
    <recordTypes>
        <fullName>Offtaker</fullName>
        <active>true</active>
        <businessProcess>Offtaker</businessProcess>
        <description>Use for Offtaker Opportunities</description>
        <label>Offtaker</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_Opportunity_SiteControllerExt.cls
@isTest
private class Test_Opportunity_SiteControllerExt {

	static testMethod void testOpp_SiteControllerExt() {
		
		List<RecordType> rtList = new List<RecordType>();
		rtList = [select Id, DeveloperName from RecordType where SobjectType = 'Opportunity' and (DeveloperName = 'Offtaker' or DeveloperName = 'DevelopmentSite')];
		Id rtOffId;
		Id rtDevId;
		for (RecordType rt :rtList) {
			if (rt.DeveloperName == 'OffTaker') {
				rtOffId = rt.Id;
			}
			if (rt.DeveloperName == 'DevelopmentSite') {
				rtDevId = rt.Id;
			}
		}
		
		List<Opportunity> opp = new List<Opportunity>();
		opp.add(new Opportunity(OwnerId = TestMethods.getUserList()[0].Id, Name = 'Knight - 2456',AccountId = TestMethods.getAccount().Id,Type = 'Turnkey System', CloseDate = System.today(),StageName = 'Prospecting', RecordTypeId = rtOffId, Current_Project_System_Size__c = 1000));
		opp.add(new Opportunity(OwnerId = TestMethods.getUserList()[0].Id, Name = 'Knight - 2457',AccountId = TestMethods.getAccount().Id,Type = 'Turnkey System', CloseDate = System.today(),StageName = 'Prospecting', RecordTypeId = rtDevId, Current_Project_System_Size__c = 1000,Vertical__c ='a382H000001u77B',Original_Contract_System_Size__c=100));
		insert opp;
		
		opp[1].Offtaker_Opportunity__c = opp[0].Id;
		update opp[1];
		
		List<Site__c> sList = new List<Site__c>();
		sList.add(new Site__c(
			Name = '123 Main Street',
			Opportunity__c = opp[1].Id)
		);
		sList.add(new Site__c(
			Name = '456 Main Street',
			Opportunity__c = opp[1].Id)
		);
		insert sList;
		
		//Instantiate a new controller
		ApexPages.StandardController std = new ApexPages.StandardController(opp[0]);
		Opportunity_SiteControllerExt ctl = new Opportunity_SiteControllerExt(std);
	}
}