objects/PreSaleDesignAttchment__c.object
<CustomObject>
    <description>This object is used to add one checkbox in Attachment window for Presale design object</description>
    <fields>
        <fullName>AttachmentID__c</fullName>
        <description>This id points to related attachment</description>
        <label>Attachment ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WorkDesign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This points to work design field</description>
        <label>Working Design</label>
        <type>Checkbox</type>
    </fields>
    <label>PreSale Design Attchment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreSale Design Attchments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PSD__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>The opportunity that the Pre-Sales Design is related too.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Sales Designs</relationshipLabel>
        <relationshipName>Pre_Sales_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Pre-Sales Design</label>
    <nameField>
        <displayFormat>P-SD-{000000}</displayFormat>
        <label>Pre-Sales Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Sales Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/clsPSDAttachments.cls
public with sharing class clsPSDAttachments {

    Public PSD__c CurrentPSD{get; set;}
    
   Public string AttachmentID{get; set;}
    
    public clsPSDAttachments(ApexPages.StandardController controller) {

        CurrentPSD=[Select c.Id
                    from PSD__C c where c.id=:controller.getrecord().id];
        
    
    }
    
    Public Void DeleteAttachment(){
    
                        
            Map<ID,Attachment> MapOfAttachments=new Map<ID,Attachment>([Select  BODY, BodyLength, ContentType, CreatedById
                            , CreatedDate, Id, IsDeleted, IsPrivate, LastModifiedById, LastModifiedDate
                            , Name, OwnerId, ParentId, SystemModstamp From Attachment where id=:AttachmentID]);
            
            
           
            
             List<PreSaleDesignAttchment__c > ListOfFileAttachment=[Select s.Id, s.AttachmentID__c
                            , s.WorkDesign__c from PreSaleDesignAttchment__c s
                              Where s.AttachmentID__c in :MapOfAttachments.KeySet()];
             
                  
             Delete ListOfFileAttachment;
             
             Delete MapOfAttachments.values();               
                   
    
    }
    
    Public list<CustomAttachment> GetAttachments(){
    
            List<CustomAttachment> ListOfCustomAttachment= new List<CustomAttachment>();
            
            Map<ID,Attachment> MapOfAttachments=new Map<ID,Attachment>([Select  BODY, BodyLength, ContentType, CreatedById
                            , CreatedDate, Id, IsDeleted, IsPrivate, LastModifiedById, LastModifiedDate
                            , Name, OwnerId, ParentId, SystemModstamp From Attachment where ParentID=:CurrentPSD.ID]);
            
            
            Map<ID,PreSaleDesignAttchment__c  > MapOfFileAttachments=new Map<ID,PreSaleDesignAttchment__c  >();
            
            for(PreSaleDesignAttchment__c  FileAttachment:[Select s.Id, s.AttachmentID__c
                            , s.WorkDesign__c from PreSaleDesignAttchment__c s 
                            Where s.AttachmentID__c in :MapOfAttachments.KeySet()]){
             
                 MapOfFileAttachments.Put(FileAttachment.AttachmentID__c,FileAttachment);
                            
            }                
            
            for(Attachment Att:MapOfAttachments.VALUES()){
             
                 CustomAttachment CA=NEW CustomAttachment();
                 
                 CA.Attachment=Att;
                 
                 CA.FileAttachment=MapOfFileAttachments.Get(Att.ID);
             
                 ListOfCustomAttachment.Add(CA);
                            
            }   
            
        return ListOfCustomAttachment;
    }

    Public PageReference AttachNewFile(){
    
        PageReference PR=new PageReference('/apex/vfNewAttachment' );
        
        PR.getParameters().Put('id',CurrentPSD.id);
        PR.setRedirect(true);
        return PR;
    
    }

    Public Class CustomAttachment{

        Public Attachment Attachment{get; Set;}
        
        Public PreSaleDesignAttchment__c  FileAttachment{ Get; Set;}
        
        Public CustomAttachment(){ }
        
        Public CustomAttachment(Attachment Att,PreSaleDesignAttchment__c  FileAtt){ 
            
               Attachment=Att;
               FileAttachment=FileAtt;
            
        }
                
    }
    
    static testMethod void Test_clsPSDAttachments  () {
    
         PSD__c PSD ;

          PSD=[Select ID, Opportunity__C
                , (Select  CreatedById, CreatedDate, Field, Id, IsDeleted, NewValue, OldValue, ParentId From Histories) 
                FROM PSD__C Limit 1];
    
        ApexPages.StandardController Controller=new ApexPages.StandardController(PSD );

        clsPSDAttachments CPA=NEW clsPSDAttachments(Controller);
        
        CPA.DeleteAttachment();
        CPA.GetAttachments();
        CPA.AttachNewFile();       
    
    }
}