objects/Pricing_Tool_Approval__c.object
<CustomObject>
    <fields>
        <fullName>Request_Status__c</fullName>
        <inlineHelpText>Shows the current status of the request for pricing.</inlineHelpText>
        <label>Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Approval status of the current pricing tool approval record</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Preliminary Approval</fullName>
                </value>
                <value>
                    <fullName>Final Approval</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Previously Approved</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <label>Pricing Request</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/submitrequestcontroller.cls
public with sharing class submitrequestcontroller {
    @AuraEnabled
    public  static string PricepUpdate(Id PriceId) 
    {
        String resultMap;
        String errmsg;
        Pricing_Tool_Approval__c Pricevalues=new Pricing_Tool_Approval__c ();
        List<Pricing_Tool_Approval__c> Price = [Select Id, Request_Status__c FROM Pricing_Tool_Approval__c Where Id =: PriceId];
        Pricevalues=Price.get(0);
        Pricevalues.Request_Status__c='Submitted';
        try {
            update Pricevalues;
            errmsg= ('Pricing Request Updated to ' +Pricevalues.Request_Status__c);
            resultMap=errmsg;
            
        }
        catch(Exception e) {
            resultMap=  e.getMessage(); 
        }
        return resultMap;
    }
    
    
    @AuraEnabled
    public  static string CancelPR(Id PriceId1) 
    {
        string result; 
        Pricing_Tool_Approval__c Pricevalues=new Pricing_Tool_Approval__c ();
        List<Pricing_Tool_Approval__c> Price = [Select Id, Request_Status__c,Status__c FROM Pricing_Tool_Approval__c Where Id =: PriceId1];
        Pricevalues=Price.get(0);
        system.debug('Look here'+Pricevalues.Request_Status__c);
        system.debug('Look here'+Pricevalues.Status__c);
        if((Pricevalues.Request_Status__c == 'New' || Pricevalues.Request_Status__c == 'Submitted' || Pricevalues.Request_Status__c == 'In Progress') && (Pricevalues.Status__c != 'Approval Pending')){
            system.debug('this is if');
            try {
                system.debug('lll-->');
                 system.debug('this is try');
                Pricevalues.Request_Status__c ='Cancelled' ;  
                pricevalues.Status__c ='Cancelled';
                 system.debug('this is update' +Pricevalues);
                update Pricevalues;
               
                
            }
            catch(Exception e) {
                system.debug('this is catch');
                result=  e.getMessage(); 
            }
        }
        else{
            system.debug('else condition-->' +Pricevalues.Request_Status__c);
            if((Pricevalues.Request_Status__c != 'New' || Pricevalues.Request_Status__c != 'Submitted' ) ){
            result ='A request cannot be cancelled if it is Completed, Cancelled, or pending approval.';
                //'"Pricing Tool \"Request Status\" must be "New" or "Submitted" and not presently in an Approval Process in order to be Cancelled.testing';
            }
        }
        
        system.debug('this is result-->' +result);
        return result;
    }
}