objects/Product_Quotes__c.object
<CustomObject>
    <description>used in conjunction with Issue Tracker to track engineering requests</description>
    <fields>
        <fullName>Issue_Tracker__c</fullName>
        <description>Issue Tracker number associated with this product quote</description>
        <inlineHelpText>Issue Tracker number associated with this product quote</inlineHelpText>
        <label>Issue Tracker</label>
        <referenceTo>Request_for_Information_RFI__c</referenceTo>
        <relationshipLabel>Product Quotes</relationshipLabel>
        <relationshipName>Product_Quotes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link filled in by trigger?</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Product Quotes</relationshipLabel>
        <relationshipName>Product_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Quotes</label>
    <nameField>
        <label>Product Quotes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Request_for_Information_RFI__c.object
<CustomObject>
    <description>Facilitates the communications between Borrego and its subcontractors regarding Requests for Information, otherwise known as RFIs.</description>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A lookup to the related project.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Issue Tracker</relationshipLabel>
        <relationshipName>Issue_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the name of the Borrego project to which this RFI is related.</description>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Issue Tracker</relationshipLabel>
        <relationshipName>Requests_for_Information_RFIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Issue Tracker</label>
    <nameField>
        <displayFormat>ISS-{000000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProductQuotesService.cls
public class ProductQuotesService {
	
	/*
	 *	Service methods for ProductQuotesTrigger.trigger
	 *
	 */
	
	// Set various fields on Product Quotes records upon insert
	// - before insert
	public static void setFieldsOnCreate(List<Product_Quotes__c> newList) {
		Set<Id> itIds = new Set<Id>();
		
		for (Product_Quotes__c pq :newList) {
			if (pq.Issue_Tracker__c != null) {
				itIds.add(pq.Issue_Tracker__c);
			}
		}
		
		if (!itIds.isEmpty()) {
			Map<Id, Request_for_Information_RFI__c> itMap = new Map<Id, Request_for_Information_RFI__c>([select Id, Name, ASProject__c 
					from Request_for_Information_RFI__c where Id in :itIds]);
			
			for (Product_Quotes__c pq :newList) {
				if (itMap.containsKey(pq.Issue_Tracker__c)) {
					pq.Project__c = itMap.get(pq.Issue_Tracker__c).ASProject__c;
				}
			}
		}
	}
}