objects/ProjectDeadline__c.object
<CustomObject>
    <fields>
        <fullName>AssociatedMilestone__c</fullName>
        <inlineHelpText>Milestone that the deadline is associated with.</inlineHelpText>
        <label>Associated Milestone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Intx App Submitted</fullName>
                </value>
                <value>
                    <fullName>Interconnection Study Received Date</fullName>
                </value>
                <value>
                    <fullName>ISA Date</fullName>
                </value>
                <value>
                    <fullName>25% Payment Date</fullName>
                </value>
                <value>
                    <fullName>75% Payment Date</fullName>
                </value>
                <value>
                    <fullName>Utility Design Completion</fullName>
                </value>
                <value>
                    <fullName>Utility Construction Completion</fullName>
                </value>
                <value>
                    <fullName>PB9 CC Approval Date</fullName>
                </value>
                <value>
                    <fullName>Handoff Date</fullName>
                </value>
                <value>
                    <fullName>EPC Signed</fullName>
                </value>
                <value>
                    <fullName>FNTP Date</fullName>
                </value>
                <value>
                    <fullName>50% Set Completed</fullName>
                </value>
                <value>
                    <fullName>EPC- LOI</fullName>
                </value>
                <value>
                    <fullName>CD IFR</fullName>
                </value>
                <value>
                    <fullName>CD IFP</fullName>
                </value>
                <value>
                    <fullName>CD IFC</fullName>
                </value>
                <value>
                    <fullName>Building Permit</fullName>
                </value>
                <value>
                    <fullName>Module Delivery Date</fullName>
                </value>
                <value>
                    <fullName>Inverter Delivery Date</fullName>
                </value>
                <value>
                    <fullName>Transformer/SWGear Delivery Date</fullName>
                </value>
                <value>
                    <fullName>Delivery of LLTI MV/AC Equip</fullName>
                </value>
                <value>
                    <fullName>Racking Delivery Date</fullName>
                </value>
                <value>
                    <fullName>Energy Storage Unit Delivery Date</fullName>
                </value>
                <value>
                    <fullName>Mobilization Date</fullName>
                </value>
                <value>
                    <fullName>Mechanical Completion</fullName>
                </value>
                <value>
                    <fullName>PTO Date</fullName>
                </value>
                <value>
                    <fullName>Substantial Completion</fullName>
                </value>
                <value>
                    <fullName>Final Completion</fullName>
                </value>
                <value>
                    <fullName>CUSTOM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DeadlineDate__c</fullName>
        <inlineHelpText>Date of the Project Deadline</inlineHelpText>
        <label>Deadline Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Project Deadlines</relationshipLabel>
        <relationshipName>Project_Deadliens</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Site__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Project Deadlines</relationshipLabel>
        <relationshipName>Project_Deadlines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Deadline</label>
    <nameField>
        <displayFormat>PD-{0000000}</displayFormat>
        <label>Project Deadline Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Deadlines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>BuildingPermitObtainedDate__c</fullName>
        <inlineHelpText>Date Building Permit Obtained</inlineHelpText>
        <label>Building Permit Obtained Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Energy_Storage_Unit_Delivery_Date__c</fullName>
        <inlineHelpText>Estimated or Actual delivery date of the Energy Storage Unit</inlineHelpText>
        <label>Energy Storage Unit Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Handoff_Date__c</fullName>
        <inlineHelpText>Date Site was handed off to Operations</inlineHelpText>
        <label>Handoff Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ISA_Received_Date__c</fullName>
        <label>ISA Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MarkettoOwnerDate__c</fullName>
        <inlineHelpText>Date that 7C has been submitted, and project is ready to market to Owner</inlineHelpText>
        <label>7C Submittal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mobilization_Date__c</fullName>
        <label>Mobilization Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PB9CCApprovalDate__c</fullName>
        <description>Development Only</description>
        <inlineHelpText>Date Contracts Committee approved project at PB 9</inlineHelpText>
        <label>PB9 CC Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductDeliveryDateUpdated__c</fullName>
        <inlineHelpText>Date any Milestone Date is Updated- If no update is needed, enter today&apos;s date so the Project Team knows you looked at the field.</inlineHelpText>
        <label>Milestone Dates Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Address__c</fullName>
        <label>Site Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_City__c</fullName>
        <label>Site City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_State__c</fullName>
        <label>Site State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Zip__c</fullName>
        <label>Site Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Product Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Tilt Ground</fullName>
                </value>
                <value>
                    <fullName>Single Axis Tracker</fullName>
                </value>
                <value>
                    <fullName>Standalone Storage</fullName>
                </value>
                <value>
                    <fullName>Floating Solar</fullName>
                </value>
                <value>
                    <fullName>Landfill</fullName>
                </value>
                <value>
                    <fullName>Dual Use/Ag Canopy</fullName>
                </value>
                <value>
                    <fullName>Multiple</fullName>
                </value>
                <value>
                    <fullName>Wind</fullName>
                </value>
                <value>
                    <fullName>SSS</fullName>
                </value>
                <value>
                    <fullName>Roof</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>X25PaymentDate__c</fullName>
        <inlineHelpText>Date 25% payment was made to the utility</inlineHelpText>
        <label>25% Payment Date</label>
        <type>Date</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUpdateMilestoneDates1.cls
@isTest(seealldata=TRUE) 
public class TestUpdateMilestoneDates1 
{
 static testMethod void testMethod1() 
 {
 List <Site__c> lstsite = new List<Site__c>();
 
 Site__c testsite = new Site__c();
 testsite.Name='12 River Street - Palmer' ;
 testsite.Opportunity__c='00634000015Qmk9';
 testsite.Site_Address__c='12 River Street';
 testsite.Site_City__c='Palmer';
 testsite.Site_State__c='Massachusetts';
 testsite.Site_Zip__c='01069';
 testsite.Type__c='Fixed Ground';
 testsite.MarkettoOwnerDate__c= Date.newinstance(2018, 10, 21);
 //testsite.ProductDeliveryDateUpdated__c= Date.newinstance(2018, 06, 26);
 testsite.PB9CCApprovalDate__c= Date.newinstance(2018, 10, 21);
 testsite.BuildingPermitObtainedDate__c= Date.newinstance(2018, 06, 20);
 testsite.Handoff_Date__c= Date.newinstance(2018, 10, 21);
 testsite.Mobilization_Date__c= Date.newinstance(2018, 07, 02);
 testsite.ISA_Received_Date__c= Date.newinstance(2018, 10, 22);
 testsite.Energy_Storage_Unit_Delivery_Date__c= Date.newinstance(2018, 09, 24);
 testsite.X25PaymentDate__c= Date.newinstance(2018, 08, 21);
 
 lstsite.add(testsite);
 Site__c testsite1 = new Site__c();
 testsite1.Name='1718 County Route 1- SOUTH' ;
 testsite1.Opportunity__c='0068000000tUDvH';
 testsite1.Site_Address__c='1718 County Route 1- SOUTH';
 testsite1.Site_City__c='Westtown';
 testsite1.Site_State__c='New York';
 testsite1.Site_Zip__c='10998';
 testsite1.Type__c='Fixed Ground';
 testsite1.MarkettoOwnerDate__c= Date.newinstance(2018, 10, 21);
 //testsite1.ProductDeliveryDateUpdated__c= Date.newinstance(2018, 06, 26);
 testsite1.PB9CCApprovalDate__c= Date.newinstance(2018, 10, 21);
 testsite1.BuildingPermitObtainedDate__c= Date.newinstance(2018, 06, 20);
 testsite1.Handoff_Date__c= Date.newinstance(2018, 10, 21);
 testsite1.Mobilization_Date__c= Date.newinstance(2018, 07, 02);
 testsite1.ISA_Received_Date__c= Date.newinstance(2018, 10, 22);
 testsite1.Energy_Storage_Unit_Delivery_Date__c= Date.newinstance(2018, 09, 24);
 testsite1.X25PaymentDate__c= Date.newinstance(2018, 08, 21);
 
 Site__c testsite2 = new Site__c();
 testsite2.Name='3 Perkins Way - Newburyport - Site 1' ;
 testsite2.Opportunity__c='00634000015Nz1Y';
 testsite2.Site_Address__c='3 Perkins Way';
 testsite2.Site_City__c='Newburyport';
 testsite2.Site_State__c='Massachusetts';
 testsite2.Site_Zip__c='01950';
 testsite2.Type__c='Fixed Ground';
 testsite2.MarkettoOwnerDate__c= Date.newinstance(2018, 10, 21);
 //testsite1.ProductDeliveryDateUpdated__c= Date.newinstance(2018, 06, 26);
 testsite2.PB9CCApprovalDate__c= Date.newinstance(2018, 10, 21);
 testsite2.BuildingPermitObtainedDate__c= Date.newinstance(2018, 06, 20);
 testsite2.Handoff_Date__c= Date.newinstance(2018, 10, 21);
 testsite2.Mobilization_Date__c= Date.newinstance(2018, 07, 02);
 testsite2.ISA_Received_Date__c= Date.newinstance(2018, 10, 22);
 testsite2.Energy_Storage_Unit_Delivery_Date__c= Date.newinstance(2018, 09, 24);
 testsite2.X25PaymentDate__c= Date.newinstance(2018, 08, 21);
 
 lstsite.add(testsite2);
 insert  lstsite;
 
 List <ProjectDeadline__c> lstprojectdeadline = new List<ProjectDeadline__c>();
 ProjectDeadline__c testprojectdeadline = new ProjectDeadline__c();
 testprojectdeadline.Project__c='a1t340000034GBh';
 testprojectdeadline.Site__c='a6934000000Bie8';
 testprojectdeadline.DeadlineDate__c=Date.newinstance(2018, 10, 12);
 testprojectdeadline.AssociatedMilestone__c='Building Permit';
 lstprojectdeadline.add(testprojectdeadline );
 //insert lstprojectdeadline;
 
 
 ProjectDeadline__c testprojectdeadline1 = new ProjectDeadline__c();
 testprojectdeadline1.Project__c='a1t340000037Rm3';
 testprojectdeadline1.Site__c='a6934000001gRgz';
 testprojectdeadline1.DeadlineDate__c=Date.newinstance(2018, 10, 12);
 testprojectdeadline1.AssociatedMilestone__c='Building Permit';
 lstprojectdeadline.add(testprojectdeadline1 );
 insert lstprojectdeadline;
 
 
 Test.startTest();
  Test.setCurrentPage(Page.UpdateMilestondDates);
  ApexPages.StandardSetController stdSetController= new ApexPages.StandardSetController(lstsite);
  stdSetController.setSelected(lstsite);
  
  UpdateMilestoneDates1 ext = new UpdateMilestoneDates1(stdSetController);
  //ext.selectedsiteid=lstsite[0].id;
  ext.selectedsiteid='a6934000001gRgz';
  List<SelectOption> lst = ext.Sitelist1;
  
  //ext.siteSelected();
  
  ext.getsiterecords();
  //System.assertEquals(0, ext.SiteList.size());
  
  ext.Save();
 Test.stopTest();
 }
}