objects/PSD__c.object
<CustomObject>
    <fields>
        <fullName>Application_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Pick the AE that will be working with you on the design.</inlineHelpText>
        <label>Application Engineer</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>contains</operation>
                <value>Applications Engineer, Application Engineer, Industrial Engineer, Development Engineer,Sr Pre-Construction Manager</value>
            </filterItems>
            <filterItems>
                <field>User.Alias</field>
                <operation>equals</operation>
                <value>so&apos;le</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Pre_Sales_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <defaultValue>TODAY()+2</defaultValue>
        <inlineHelpText>L1 - Minimum 2 Days
L2 - Minimum 5 Days
L3 - Minimum 14-21 Days</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <inlineHelpText>The opportunity that the Pre-Sales Design is related too.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Sales Designs</relationshipLabel>
        <relationshipName>Pre_Sales_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Quick Revision</fullName>
                </value>
                <value>
                    <fullName>Top</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal_Level_Needed__c</fullName>
        <label>Proposal Level Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>L0</fullName>
                </value>
                <value>
                    <fullName>L1</fullName>
                </value>
                <value>
                    <fullName>L2</fullName>
                </value>
                <value>
                    <fullName>L3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Address2__c</fullName>
        <inlineHelpText>When multiple sites add include a name of the site which will help to designate which PSD belongs to which site. 
When single site just use main site addresses.</inlineHelpText>
        <label>Site Name/Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Which_AC_Rating_is_Required__c</fullName>
        <label>Which AC Rating is Required?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AC</fullName>
                </value>
                <value>
                    <fullName>AC-CEC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pre-Sales Design</label>
    <nameField>
        <displayFormat>P-SD-{000000}</displayFormat>
        <label>Pre-Sales Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Sales Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PSD_Revision__c.object
<CustomObject>
    <description>This object will contain all of the Pre-Sales Design revision requests.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <formula>Pre_Sales_Design__r.Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Sales_Design__c</fullName>
        <label>Pre-Sales Design</label>
        <referenceTo>PSD__c</referenceTo>
        <relationshipLabel>PSD Revisions</relationshipLabel>
        <relationshipName>PSD_Revisions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>TOP - Should only be used when it absolutely has to be completed by tomorrow.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Normal</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Quick Revision</fullName>
                </value>
                <value>
                    <fullName>Top</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposal_Level_Needed__c</fullName>
        <inlineHelpText>L0 = Almost always used on 1st Rev, Basic Layout, System Size and limited add&apos;l info 
L1 = More Details, Full System specs 
L2 = L1 + Simple Single Line 
L3 = L1 + Inconnection App level &amp; simple single line</inlineHelpText>
        <label>Proposal Level Needed</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>L0</fullName>
                </value>
                <value>
                    <fullName>L1</fullName>
                </value>
                <value>
                    <fullName>L2</fullName>
                </value>
                <value>
                    <fullName>L3</fullName>
                </value>
                <value>
                    <fullName>Intx Layout</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_for_modifiction__c</fullName>
        <label>Reason for Modification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>First Draft</fullName>
                </value>
                <value>
                    <fullName>Design Change</fullName>
                </value>
                <value>
                    <fullName>Upgrade Proposal Level</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Correct Mistakes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PSD Revision</label>
    <nameField>
        <label>PSD Revision Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PSD Revisions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestPSDdetailslightning.cls
@isTest(seealldata=true)
public class TestPSDdetailslightning {
    
     static testMethod void testMethod1() 
    {
        
         
        
          Account acc = new Account(Name = 'nsvAccount');
          insert acc;
      
        
        Contact con = new Contact(FirstName = 'Generic', LastName = 'Technician', Title = 'Solar Tech', AccountId = acc.Id);
        insert con;
       
      
        opportunity testOpportunity=[select id from opportunity where StageName='Qualified' limit 1];
        
        user userid = [select id from user where isactive=true limit 1];
        
        PSD__c testpsd=new PSD__c(Opportunity__c=testOpportunity.id,Site_Address2__c='test',Which_AC_Rating_is_Required__c='AC',Application_Engineer__c=userid.Id);
        insert testpsd;
        
        PSD_Revision__c testpsr=new PSD_Revision__c(Name='test revision',Pre_Sales_Design__c=testpsd.id,Proposal_Level_Needed__c='L1',Reason_for_modifiction__c='First Draft',Due_Date__c=System.today(),Priority__c='Normal');
        insert testpsr;
        
        List<PSD_Revision__c> result = PSDdetailslightning.Oppdisplay(testOpportunity.id);
        
        
        
        


}
}