objects/Request_for_Information_RFI__c.object
<CustomObject>
    <description>Facilitates the communications between Borrego and its subcontractors regarding Requests for Information, otherwise known as RFIs.</description>
    <fields>
        <fullName>ASProject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>A lookup to the related project.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Issue Tracker</relationshipLabel>
        <relationshipName>Issue_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the name of the Borrego project to which this RFI is related.</description>
        <label>SFDCProject</label>
        <referenceTo>SFDC_Project__c</referenceTo>
        <relationshipLabel>Issue Tracker</relationshipLabel>
        <relationshipName>Requests_for_Information_RFIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Issue Tracker</label>
    <nameField>
        <displayFormat>ISS-{000000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Report__c.object
<CustomObject>
    <fields>
        <fullName>Issue_Tracker__c</fullName>
        <inlineHelpText>Issue Tracker number associated this Test Report</inlineHelpText>
        <label>Issue Tracker</label>
        <referenceTo>Request_for_Information_RFI__c</referenceTo>
        <relationshipLabel>Test Reports</relationshipLabel>
        <relationshipName>Test_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>updated by trigger to match project on related Issue tracker, hidden field no need to be on layout.</description>
        <inlineHelpText>updated by trigger to match project on related Issue tracker, hidden field no need to be on layout.</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Test Reports</relationshipLabel>
        <relationshipName>Test_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Report</label>
    <nameField>
        <label>Test Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestReportService.cls
public class TestReportService {
	
	/*
	 *	Service methods for TestReportTrigger.trigger
	 *
	 */
	
	// Set various fields on Test Report records upon insert
	// - before insert
	public static void setFieldsOnCreate(List<Test_Report__c> newList) {
		Set<Id> itIds = new Set<Id>();
		
		for (Test_Report__c tr :newList) {
			if (tr.Issue_Tracker__c != null) {
				itIds.add(tr.Issue_Tracker__c);
			}
		}
		
		if (!itIds.isEmpty()) {
			Map<Id, Request_for_Information_RFI__c> itMap = new Map<Id, Request_for_Information_RFI__c>([select Id, Name, ASProject__c 
					from Request_for_Information_RFI__c where Id in :itIds]);
			
			for (Test_Report__c tr :newList) {
				if (itMap.containsKey(tr.Issue_Tracker__c)) {
					tr.Project__c = itMap.get(tr.Issue_Tracker__c).ASProject__c;
				}
			}
		}
	}
}