objects/Request_for_Information_RFI__c.object
<CustomObject>
    <description>Facilitates the communications between Borrego and its subcontractors regarding Requests for Information, otherwise known as RFIs.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to track and manage the status of the RFI.</description>
        <inlineHelpText>Used to track and manage the status of the RFI.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Submitted/Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
                <value>
                    <fullName>Clarification Needed</fullName>
                </value>
                <value>
                    <fullName>Resubmitted</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Re-assigned</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Issue Tracker</label>
    <nameField>
        <displayFormat>ISS-{000000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Submittal_1__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Used to track and manage the status of the submittal.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Revise and Resubmit</fullName>
                </value>
                <value>
                    <fullName>Approved as Corrected</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Submittal</label>
    <nameField>
        <label>Submittal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submittals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestSubmittalApphistorybuttons.cls
@isTest(seealldata=true)

public class TestSubmittalApphistorybuttons {
    
    
     static testMethod void testMethod1() 
    {
        

        
        Request_for_Information_RFI__c testissue=[select id from Request_for_Information_RFI__c where Status__c='Submitted/Pending'limit 1 ];
        ProcessInstanceWorkitem testprocessInstanceworkitem=[select id from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId=:testissue.id];
      
         Submittal_1__c testsubmittal=[select id from Submittal_1__c where Status__c='Approval Pending'limit 1];
        submittal_1__c testbutton = [select id from submittal_1__c where status__c='Approval Pending' order by id desc limit 1];
        ProcessInstanceWorkitem testbuttonpi = [select id from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId=:testbutton.id];
   
        system.debug('this is id-->' +testsubmittal.id);
        ProcessInstanceWorkitem testprocessInstanceworkitem1=[select id from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId=:testsubmittal.id];
        system.debug('this is submittal id' +testprocessInstanceworkitem1.Id);
        
        String resut1=SubmittalApphistorybuttons.Buttonshowhide(testbuttonpi.id);
        String result = SubmittalApphistorybuttons.Issueresolved(testprocessInstanceworkitem.id);
      
        String resut2=SubmittalApphistorybuttons.Apphistoryrecallid(testprocessInstanceworkitem1.id);
      
        
        

}
    
     static testMethod void testMethod2() 
    {
        
        Submittal_1__c testsubmittal=[select id from Submittal_1__c where Status__c='Approval Pending'limit 1];
        submittal_1__c testbutton = [select id from submittal_1__c where status__c='Approval Pending' order by id desc limit 1];
        ProcessInstanceWorkitem testbuttonpi = [select id from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId=:testbutton.id];
   
        ProcessInstanceWorkitem testprocessInstanceworkitem1=[select id from ProcessInstanceWorkitem where ProcessInstance.TargetObjectId=:testsubmittal.id];
        
        
        String resut1=SubmittalApphistorybuttons.Buttonshowhide(testbuttonpi.id);
        String resut3=SubmittalApphistorybuttons.Apphistoryid(testprocessInstanceworkitem1.id);
        
    }
    
}