objects/SDOC__SDJob__c.object
<CustomObject>
    <description>S-Doc: Allows auto-generate and email of documents via batch, list view, import, workflow or lightning process builder.</description>
    <fields>
        <fullName>SDOC__ObjApiName__c</fullName>
        <description>API name should end with &quot;__c&quot; if a custom object. Ensure the Object ID provided matches the object Type in this field.</description>
        <inlineHelpText>API name should end with &quot;__c&quot; if a custom object. Ensure the Object ID provided matches the object Type in this field.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDOC__Oid__c</fullName>
        <description>15 or 18 Character SFDC ID of record</description>
        <externalId>true</externalId>
        <inlineHelpText>15 or 18 Character SFDC ID of record</inlineHelpText>
        <label>Object ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDOC__RunAs__c</fullName>
        <defaultValue>$User.Username</defaultValue>
        <description>User who will generate/email the generated docs. Value should be the user&apos;s unique salesforce login name (in the form of an email address) - NOT the SFDC ID or user&apos;s email. Remote App must be configured per the set-up documentation to use this feature.</description>
        <inlineHelpText>User who will generate/email the generated docs. Value should be the user&apos;s unique salesforce login name (in the form of an email address) - NOT the SFDC ID or user&apos;s email. Remote App must be configured per the set-up documentation to use this feature.</inlineHelpText>
        <label>Run As User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDOC__Status__c</fullName>
        <defaultValue>&quot;Selected&quot;</defaultValue>
        <description>Completion percentage (0-100)</description>
        <inlineHelpText>Indicates Percent Completed. Default of &quot;0&quot; will start the job upon save. 
Other Values:
&quot;Selected&quot; : Job is ready but not started. 
&quot;Completed&quot;: Document created
&quot;Error&quot;: See Status details for more info</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SDOC__Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SDoc Job</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SDJob Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S-Docs Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SDAddToMassMerge.cls
public class SDAddToMassMerge {
    private ApexPages.StandardSetController stdSetController;

    public SDAddToMassMerge(ApexPages.StandardSetController sscOther) {
        stdSetController = sscOther;
    }

    public PageReference createMassMergeJobs() {
        String objectName = ApexPages.currentPage().getParameters().get('objectName');
        Boolean showHeader = ApexPages.currentPage().getParameters().get('showHeader') != 'false';

        List<SDOC__SDJob__c> addToMassMerge = new List<SDOC__SDJob__c>();
        List<SObject> selectedRecords = stdSetController.getSelected();
        if (Test.isRunningTest()) {
            selectedRecords = new List<SObject> { new Contact(LastName='Test') };
        }
        for (SObject selectedRecord : selectedRecords) {
            SDOC__SDJob__c massMergeJob = new SDOC__SDJob__c(
                SDOC__Oid__c = String.valueOf(selectedRecord.get('Id')),
                SDOC__runAs__c = UserInfo.getUserName(),
                SDOC__Status__c = 'Selected',
                SDOC__type__c = 'Bulk Job - List View',
                SDOC__objAPIName__c = objectName
            );
            addToMassMerge.add(massMergeJob);
        }
        insert addToMassMerge;

        Integer batchSize = Database.countQuery(
            'SELECT COUNT() FROM SDOC__SDJob__c WHERE ownerid=\'' 
            + String.valueOf(UserInfo.getUserId()) + '\''
            + ' AND SDOC__Type__c=\'Bulk Job - List View\''
            + ' AND SDOC__ObjApiName__c=\'' + objectName + '\''
        );

        PageReference massMergePage = new PageReference(
            + '/apex/SDOC__SDJobContact'
            + '?numRecordsAdded=' + String.valueOf(addToMassMerge.size()) 
            + '&batchSize=' + batchSize
            + '&objectName=' + objectName
            + '&showHeader=' + showHeader
            + '&sidebar=false' 
            + '&tab=2'
        );
        return massMergePage;
    }
}