objects/SDOC__SDJob__c.object
<CustomObject>
    <description>S-Doc: Allows auto-generate and email of documents via batch, list view, import, workflow or lightning process builder.</description>
    <fields>
        <fullName>SDOC__ObjApiName__c</fullName>
        <description>API name should end with &quot;__c&quot; if a custom object. Ensure the Object ID provided matches the object Type in this field.</description>
        <inlineHelpText>API name should end with &quot;__c&quot; if a custom object. Ensure the Object ID provided matches the object Type in this field.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SDoc Job</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>SDJob Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S-Docs Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SDAddToMassMergeTest.cls
@isTest
private class SDAddToMassMergeTest {
    @isTest
    private static void SDAddToMassMergeTest() {
        Integer numJobsToCreate = 20;
        List<Opportunity> selectedOpportunities = [
            SELECT Id, Name
            FROM Opportunity
            LIMIT :numJobsToCreate
        ];
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(selectedOpportunities);
        ssc.setSelected(selectedOpportunities);                                                                 
        SDAddToMassMerge sdatmm = new SDAddToMassMerge(ssc);
        String objectNameTest = '[SDAddToMassMerge Test]';
        sdatmm.createMassMergeJobs();
        Integer numJobsCreated = Database.countQuery(
            'SELECT COUNT() '
            + 'FROM SDOC__SDJob__c '
            + 'WHERE SDOC__ObjApiName__c=\'' + objectNameTest + '\''
        );
        // System.assert(numJobsCreated == numJobsToCreate);
    }
}