objects/SFDC_Purchase_Requisition__c.object
<CustomObject>
    <description>Purchase Requisitions empower end users to request new items, and tracks the status of their requests.</description>
    <fields>
        <fullName>BriefDescriptionofDocument__c</fullName>
        <inlineHelpText>Brief description of the document to be signed (ie: Contract for XX Project or Agreement for XX)</inlineHelpText>
        <label>Brief Description of Document</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Needed__c</fullName>
        <inlineHelpText>Date the request is needed by</inlineHelpText>
        <label>Date Needed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Recipients_and_Order__c</fullName>
        <inlineHelpText>Enter the recipient&apos;s name(s) and email and order of signature</inlineHelpText>
        <label>External Recipients and Order</label>
        <length>7000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>InternalRecipientsandOrder__c</fullName>
        <inlineHelpText>Enter the Borrego signatories’ names in order of signature</inlineHelpText>
        <label>Internal Signatories and Order</label>
        <length>7000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pages_where_signature_is_required__c</fullName>
        <inlineHelpText>Specify which pages a signature or initials are required</inlineHelpText>
        <label>Pages where signature is required</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ProjectAS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the Project associated with the request</inlineHelpText>
        <label>Project</label>
        <referenceTo>AcctSeed__Project__c</referenceTo>
        <relationshipLabel>Requisition Forms</relationshipLabel>
        <relationshipName>Requisition_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requisition Form</label>
    <nameField>
        <displayFormat>REQ{0000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requisition Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/contentdocumenttrigger1testclass.cls
@isTest
public class contentdocumenttrigger1testclass {
    @isTest static void testMethod1()
  
   {
       //Profile p = [SELECT Id FROM Profile WHERE Name='O&M Manager'];
       User U = [select id from User where profile.Name='O&M Manager' and IsActive=true limit 1];
       system.debug('User' +U);
       System.runAs(U)
       {

        SFDC_Purchase_Requisition__c reqlist = new SFDC_Purchase_Requisition__c();
       //  reqlist.RecordTypeId = [select Id FROM RecordType WHERE name='DocuSign Request']; 
         reqlist.ProjectAS__c = 'a1t34000002v45k';
         reqlist.Date_Needed__c = system.today();
         reqlist.BriefDescriptionofDocument__c = 'test';
         reqlist.External_Recipients_and_Order__c = 'test';
         reqlist.Pages_where_signature_is_required__c = 'test';
         reqlist.InternalRecipientsandOrder__c = 'test';
         
         insert reqlist;
         
         RecordType ContentRT = [select Id FROM RecordType WHERE name='Standard Work/SOP'];
    
    ContentVersion ContentDoc = new ContentVersion();
       ContentDoc.Title = 'My Doc';
       ContentDoc.Description ='test';
       ContentDoc.RecordTypeId = ContentRT.Id; //'01234000000GGcgAAG';
       ContentDoc.ContentUrl= 'test.com';
        Insert ContentDoc;
      
         List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        //create ContentDocumentLink  record 

        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = reqlist.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
       }

}
}