objects/SFDC_Purchase_Order__c.object
<CustomObject>
    <description>The Purchase Order is an order to a vendor comprised of Line Items all going to one shipping location.</description>
    <label>Purchase Order-OLD</label>
    <nameField>
        <displayFormat>SF{00000}</displayFormat>
        <label>Purchase Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders-OLD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Purchase_Requisition__c.object
<CustomObject>
    <description>Purchase Requisitions empower end users to request new items, and tracks the status of their requests.</description>
    <fields>
        <fullName>Purchase_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Order-OLD</label>
        <referenceTo>SFDC_Purchase_Order__c</referenceTo>
        <relationshipLabel>Requisition Forms</relationshipLabel>
        <relationshipName>R00N300000025IStEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Requisition Form</label>
    <nameField>
        <displayFormat>REQ{0000}</displayFormat>
        <label>Requisition Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requisition Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/POButton.cls
global class POButton {
    Webservice static String createPO(Id[] reqIds) {

        SFDC_Purchase_Order__c pOrder = new SFDC_Purchase_Order__c();
        insert pOrder;
        
        SFDC_Purchase_Requisition__c[] req = ([select Id, Purchase_Order__c from SFDC_Purchase_Requisition__c where Id in :reqIds]);
        for (Integer i = 0; i <req.size(); i++) {
            req[i].Purchase_Order__c = pOrder.Id;
        }
        update req;
        return pOrder.Id;
    }
}