objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The case on which the service visit was scheduled.</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Visits</relationshipLabel>
        <relationshipName>Service_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technician__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to specific Borrego Solar (O&amp;M) account, where all technicians should be listed as contacts</description>
        <inlineHelpText>individual who did the work, if unable to find, add the contact to the Borrego Solar (O&amp;M) account.</inlineHelpText>
        <label>Technician</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <value>00180000010MDi3</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Visits (Technician)</relationshipLabel>
        <relationshipName>Service_Visits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Case_SVTechnicianCtlExt.cls
public with sharing class Case_SVTechnicianCtlExt {
	
	/*
	 *	Controller extension methods to allow setting the Technician field on a set of Service Visit records.
	 */
	
	private ApexPages.StandardSetController stdSetCon;
	
	public List<SV__c> selectedServiceVisits;
	
	public List<SV__c> svList {get; set;}
	public Boolean isError {get; set;}
	
	public Case_SVTechnicianCtlExt(ApexPages.StandardSetController stdSetCon){
		this.stdSetCon = stdSetCon;
		selectedServiceVisits = stdSetCon.getSelected();
		isError = false;
		svList = new List<SV__c>();
		
		Set<Id> svIds = new Set<Id>();
    	for (SV__c sv :selectedServiceVisits) {
    		svIds.add(sv.Id);
    	}
		
		if (!svIds.isEmpty()) {
			svList = [select Id, Case__c, Technician__c from SV__c where Id in :svIds];
		} else {
			ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'You must select at least one Service Visit.'));
    		isError = true;
		}
    }
    
    public PageReference saveServiceVisits() {
    	PageReference pr = null;
    	
    	for (Integer i=1; i<svList.size(); i++) {
    		svList[i].Technician__c = svList[0].Technician__c;
    	}
    	
    	try {
    		update svList;
    		pr = new PageReference('/' + svList[0].Case__c);
    		pr.setRedirect(true);
    	} catch(Exception e) {
    		ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Service Visit exception: ' + e.getMessage()));
    		isError = true;
    	}
    	
    	return pr;
    }
}