objects/SV__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Service Visit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CloseServiceVisitsController.cls
public class CloseServiceVisitsController {

    private ID ContractId;
    private list<SV__C> ListOfServiceVisits;
    public CloseServiceVisitsController(ApexPages.StandardSetController controller) {
    
         ContractId = apexpages.currentpage().getparameters().get('id');
         ListOfServiceVisits=new List<SV__c>();
         
         for(sObject SOBJ:controller.getSelected()){
             ListOfServiceVisits.add((sv__C) SOBJ);
         }
    }

   Public pageReference CloseServiceVisits(){
   
       for(sv__C ServiceVisit:ListOfServiceVisits){
             ServiceVisit.Status__c='Closed';
         }
   
       Update ListOfServiceVisits;
   
        pageReference pgRef=new pageReference('/'+ ContractId);
        pgRef.SetRedirect(true);
        return pgRef;   
   }

}