objects/Team_Member__c.object
<CustomObject>
    <description>Team Members for PV Direct Jobs</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Force_Recalc__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to force a recalculation of the rate and total cost fields.  This is set and unset via apex code.</description>
        <label>Force Recalc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoices__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>ONLY FOR CONSULTING SERVICES</inlineHelpText>
        <label>Team Member</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Team_Member__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Team_Member__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Time Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/recalcTE.cls
global class recalcTE {
/*
	webService static void recalcTimeEntries(Id[] tmId) {
		
        // Get the set of Time Entry records associated with these Team Member records
        Time_Entry__c[] te = [select Force_Recalc__c, Invoice__c from Time_Entry__c where Team_Member__c in :tmId];
        
        // Set the force recalculation flag to true for each Time Entry record that is not
        // already on an invoice
        List<Time_Entry__c> newTE = new List<Time_Entry__c>();
        for (Integer i=0; i<te.size(); i++) {
        	if (te[i].Invoice__c == null) {
        		te[i].Force_Recalc__c = true;
        		newTE.add(te[i]);
        	}
        }
        
        // Write the Time Entry records - this will cause the rates to be recalculated
        if (newTE.size() > 0) {
        	update te;
        }
	}
*/	
	public static void recalcProjectRates(Team_Member__c[] tm) {
		
		// Force the recalculation of the Rate (Project), Total Cost (Project),
		// Rate (Internal), and Total Cost (Internal) fields for all Time Entry
		// records associated with these Team Member records that are not already
		// on an invoice.
		//
		// Create a list of Team Member record Ids and get the associated Time Entry records
		List<Id> tmId = new List<Id>();
        for (Integer i = 0; i <tm.size(); i++) {
            tmId.add(tm[i].Id); 
        }
        Time_Entry__c[] te = [select Force_Recalc__c, Invoice__c from Time_Entry__c where Team_Member__c in :tmId];
        
        // Set the force recalculation flag to true for each Time Entry record that is not
        // already on an invoice
        List<Time_Entry__c> newTE = new List<Time_Entry__c>();
        for (Integer i=0; i<te.size(); i++) {
        	if (te[i].Invoice__c == null) {
        		te[i].Force_Recalc__c = true;
        		newTE.add(te[i]);
        	}
        }
        
        // Write the Time Entry records - this will cause the Project rates to be recalculated
        if (newTE.size() > 0) {
        	update newTE;
        }
	}
	
	public static void recalcInternalRates(User[] u) {
		
		// Get the Team Member record Ids associated with these user records and
		// call recalcProjectRates to recaluculate the project and internal rates
		// for all Time Entry records associated with those Team Member records.
		List<Id> uId = new List<Id>();
        for (Integer i = 0; i <u.size(); i++) {
            uId.add(u[i].Id); 
        }
        Team_Member__c[] tm = [select Id from Team_Member__c where User__c in :uId];
        recalcProjectRates(tm); 
	}
}